# Pandas

In [1]:
import pandas as pd

In [4]:
#dictionary of list
data={
    "date":["1/1/2025","1/2/2025","1/3/2026","1/4/2026","1/5/2026"],
    "city":["pune","nagpur","mumbai","bangalore","chennai"],
    "temp":[30,32,37,40,45],
    "windspeed":[10,11,12,13,14]
}
df=pd.DataFrame(data)
df

       date       city  temp  windspeed
0  1/1/2025       pune    30         10
1  1/2/2025     nagpur    32         11
2  1/3/2026     mumbai    37         12
3  1/4/2026  bangalore    40         13
4  1/5/2026    chennai    45         14

In [5]:
#access column
df["date"]

0    1/1/2025
1    1/2/2025
2    1/3/2026
3    1/4/2026
4    1/5/2026
Name: date, dtype: object

In [6]:
df.date

0    1/1/2025
1    1/2/2025
2    1/3/2026
3    1/4/2026
4    1/5/2026
Name: date, dtype: object

In [8]:
#acess multiple column
df[["date","city"]]

       date       city
0  1/1/2025       pune
1  1/2/2025     nagpur
2  1/3/2026     mumbai
3  1/4/2026  bangalore
4  1/5/2026    chennai

In [9]:
df[["date","city","temp"]]

       date       city  temp
0  1/1/2025       pune    30
1  1/2/2025     nagpur    32
2  1/3/2026     mumbai    37
3  1/4/2026  bangalore    40
4  1/5/2026    chennai    45

In [12]:
#ndim-dimension of a data frame
df.ndim

2

In [17]:
#df.shape-number of rows and number of columns
df.shape

(5, 4)

In [15]:
df.shape[0] #rows

5

In [16]:
df.shape[1] #columns

4

In [20]:
df.columns #columns names

Index(['date', 'city', 'temp', 'windspeed'], dtype='object')

In [33]:
#head()- gives first 5 rows-if we didnt specify
df.head()

       date       city  temp  windspeed
0  1/1/2025       pune    30         10
1  1/2/2025     nagpur    32         11
2  1/3/2026     mumbai    37         12
3  1/4/2026  bangalore    40         13
4  1/5/2026    chennai    45         14

In [29]:
df.head(2) #gives first 2 rows

       date    city  temp  windspeed
0  1/1/2025    pune    30         10
1  1/2/2025  nagpur    32         11

In [30]:
#tail()- gives last 5 rows
df.tail()

       date       city  temp  windspeed
0  1/1/2025       pune    30         10
1  1/2/2025     nagpur    32         11
2  1/3/2026     mumbai    37         12
3  1/4/2026  bangalore    40         13
4  1/5/2026    chennai    45         14

In [34]:
df.tail(2) #gives last 2 rows

       date       city  temp  windspeed
3  1/4/2026  bangalore    40         13
4  1/5/2026    chennai    45         14

In [38]:
#sample()- gives a single random row
df.sample()

       date    city  temp  windspeed
1  1/2/2025  nagpur    32         11

In [39]:
df.sample(2) #gives any random 2 rows

       date       city  temp  windspeed
3  1/4/2026  bangalore    40         13
2  1/3/2026     mumbai    37         12

In [40]:
#info()- information about each and every column present in the data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       5 non-null      object
 1   city       5 non-null      object
 2   temp       5 non-null      int64
 3   windspeed  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [63]:
#get the maximum temperature record in the data frame
df[df["temp"]==df["temp"].max()]


#df["temp"]==df["temp"].max()---> condition.
#df[condition] based on this condition the rows are getting retrieved.

       date     city  temp  windspeed
4  1/5/2026  chennai    45         14

In [45]:
df["temp"].max()

45

In [64]:
# Get the minimum temperature record
df[df["temp"]==df["temp"].min()]

       date  city  temp  windspeed
0  1/1/2025  pune    30         10

In [51]:
#Get all the rows where the temperature is greater than 30
df[df["temp"]>30]

       date       city  temp  windspeed
1  1/2/2025     nagpur    32         11
2  1/3/2026     mumbai    37         12
3  1/4/2026  bangalore    40         13
4  1/5/2026    chennai    45         14

In [60]:
#Get a record where the temperature greater than 30 and windspeed is greater than 10
df[(df["temp"]>30) & (df["windspeed"]>10)]

       date       city  temp  windspeed
1  1/2/2025     nagpur    32         11
2  1/3/2026     mumbai    37         12
3  1/4/2026  bangalore    40         13
4  1/5/2026    chennai    45         14

In [61]:
#Get the average temperature
df["temp"].mean()

np.float64(36.8)

In [62]:
#Get all the records where the temp is greater than the avg temperature
df[df["temp"]>df["temp"].mean()]

       date       city  temp  windspeed
2  1/3/2026     mumbai    37         12
3  1/4/2026  bangalore    40         13
4  1/5/2026    chennai    45         14

In [66]:
#Get the records where the temp is greater than average temp and windspeed is greater than average speed.
df[(df["temp"]>df["temp"].mean()) & (df["windspeed"]>df["windspeed"].mean())]

       date       city  temp  windspeed
3  1/4/2026  bangalore    40         13
4  1/5/2026    chennai    45         14

dataset---> iris.csv file.
    CSV- Comma seperated value

In [67]:
df1=pd.read_csv("iris.csv")

In [68]:
df1

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [69]:
df1.ndim

2

In [70]:
df1.shape

(150, 5)

In [71]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [72]:
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [73]:
df.tail()

       date       city  temp  windspeed
0  1/1/2025       pune    30         10
1  1/2/2025     nagpur    32         11
2  1/3/2026     mumbai    37         12
3  1/4/2026  bangalore    40         13
4  1/5/2026    chennai    45         14

In [6]:
df=pd.read_csv("matches.csv")
df

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [6]:
df.shape

(1095, 20)

In [7]:
df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [9]:
#get all the matches played in mumbai
df["city"].unique() #gives all unique names

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah', 'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'],
      dtype=object)

In [11]:
df[df["city"]=="Mumbai"]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
12,335994,2007/08,Mumbai,2008-04-27,League,AC Gilchrist,Dr DY Patil Sports Academy,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,10.0,155.0,20.0,N,NaN,Asad Rauf,SL Shastri
22,336004,2007/08,Mumbai,2008-05-04,League,SM Pollock,Dr DY Patil Sports Academy,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,Mumbai Indians,runs,29.0,163.0,20.0,N,NaN,IL Howell,RE Koertzen
26,336008,2007/08,Mumbai,2008-05-07,League,A Nehra,Dr DY Patil Sports Academy,Mumbai Indians,Rajasthan Royals,Mumbai Indians,field,Mumbai Indians,wickets,7.0,104.0,20.0,N,NaN,DJ Harper,RE Koertzen
35,336018,2007/08,Mumbai,2008-05-14,League,ST Jayasuriya,Wankhede Stadium,Mumbai Indians,Chennai Super Kings,Mumbai Indians,field,Mumbai Indians,wickets,9.0,157.0,20.0,N,NaN,BR Doctrove,AM Saheba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048,1426263,2024,Mumbai,2024-04-11,League,JJ Bumrah,"Wankhede Stadium, Mumbai",Royal Challengers Bengaluru,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,7.0,197.0,20.0,N,NaN,Nitin Menon,VA Kulkarni
1052,1426267,2024,Mumbai,2024-04-14,League,M Pathirana,"Wankhede Stadium, Mumbai",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,20.0,207.0,20.0,N,NaN,Nitin Menon,HAS Khalid
1074,1426289,2024,Mumbai,2024-05-03,League,VR Iyer,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Kolkata Knight Riders,runs,24.0,170.0,20.0,N,NaN,J Madanagopal,Tapan Sharma
1078,1426293,2024,Mumbai,2024-05-06,League,SA Yadav,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,7.0,174.0,20.0,N,NaN,Navdeep Singh,Tapan Sharma
1088,1426305,2024,Mumbai,2024-05-17,League,N Pooran,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Mumbai Indians,Mumbai Indians,field,Lucknow Super Giants,runs,18.0,215.0,20.0,N,NaN,Navdeep Singh,R Pandit

In [12]:
#total number of matches played in mumbai
df[df["city"]=="Mumbai"].shape[0]

173

In [16]:
#write a function which returns total number of matches played in city
def total_matches_per_city(city):
    return df[df["city"]==city].shape[0]
total_matches_per_city("Kolkata")

93

In [22]:
#get all the matches won by mumbai indians
def matches_won_per_team(team):
    return df[df["winner"]==team].shape[0]
matches_won_per_team("Mumbai Indians")

144

In [30]:
#get a winning percentage of mumbai indians
total_matches_played=df[(df["team1"]=="Mumbai Indians") | (df["team2"]=="Mumbai Indians")].shape[0]
matches_won_by_mi=df[df["winner"]=="Mumbai Indians"].shape[0]
winning_percentage=(matches_won_by_mi/total_matches_played)*100
winning_percentage

55.172413793103445

In [32]:
#get all the matches where mi won the toss as well as match
df[(df["toss_winner"]=="Mumbai Indians") & (df["winner"]=="Mumbai Indians")].shape[0]

78

In [35]:
#get the total number of matches played in mumbai and won by mi
df[(df["city"]=="Mumbai") & (df["winner"]=="Mumbai Indians")].shape[0]

64

In [40]:
df["match_type"].unique()

array(['League', 'Semi Final', 'Final', '3rd Place Play-Off',
       'Qualifier 1', 'Elimination Final', 'Qualifier 2', 'Eliminator'],
      dtype=object)

In [42]:
#get the total number of finals won by mi
df[(df["match_type"]=="Final") & (df["winner"]=="Mumbai Indians")].shape[0]

5

In [43]:
#get all the matches where MI won a toss but lost a matchd
df[(df["toss_winner"]=="Mumbai Indians") & (df["winner"]!="Mumbai Indians")].shape[0]

65

In [44]:
df["method"].unique()

array([nan, 'D/L'], dtype=object)

In [45]:
#get all the matches where the result will be decided by DL method
df[df["method"]=="D/L"].shape[0]

21

In [47]:
#get all the player of matches
df["player_of_match"].value_counts() #couting the categorical count

player_of_match
AB de Villiers       25
CH Gayle             22
RG Sharma            19
DA Warner            18
V Kohli              18
                     ..
NV Ojha               1
KV Sharma             1
Washington Sundar     1
PD Collingwood        1
Shahbaz Ahmed         1
Name: count, Length: 291, dtype: int64

In [50]:
#which player got the maximum player of the match award
df["player_of_match"].value_counts().idxmax() #returns the maximum value

'AB de Villiers'

In [51]:
#get all the matches where result_margin is greater than 100
df[df["result_margin"]>100].shape[0]

11

In [52]:
#get all the matches where the target >200
df[df["target_runs"]>200].shape[0]

145

In [7]:
#get the winning percent of mi in season 2016
matches_season = df[df["season"] == "2016"]

matches_played = matches_season[
    (matches_season["team1"] == "Mumbai Indians") |
    (matches_season["team2"] == "Mumbai Indians")
]

total_matches = matches_played.shape[0]

matches_won = matches_played[
    matches_played["winner"] == "Mumbai Indians"
].shape[0]

winning_percentage = (matches_won / total_matches) * 100

winning_percentage

50.0

In [69]:
#in which season, the winning percentage of MI is more.
mi = df[
    (df["team1"] == "Mumbai Indians") |
    (df["team2"] == "Mumbai Indians")
]

total_matches = mi["season"].value_counts()

matches_won = mi[mi["winner"] == "Mumbai Indians"]["season"].value_counts()

winning_percentage =(matches_won / total_matches) * 100

winning_percentage.idxmax()

'2017'

In [59]:
df["super_over"].unique()

array(['N', 'Y'], dtype=object)

In [60]:
#get all the matches where the matches decided by super over.
df[df["super_over"]=="Y"].shape[0]

14

In [70]:
#get the winning percentage at home of mi.
home = df[
    ((df["team1"] == "Mumbai Indians") |
     (df["team2"] == "Mumbai Indians")) &
    (df["city"] == "Mumbai")
]
total_matches=home.shape[0]
matches_won = home[
    home["winner"] == "Mumbai Indians"
].shape[0]

winning_percentage = (matches_won / total_matches) * 100

winning_percentage

61.53846153846154

In [73]:
#get the winning percentage in the leaggue matches of mi
type_match=df[df["match_type"]=="League"]
MI_leage=type_match[(type_match["team1"]=="Mumbai Indians") | (type_match["team2"]=="Mumbai Indians")]
winners=MI_leage[MI_leage["winner"]=="Mumbai Indians"].shape[0]
total_matches=MI_leage.shape[0]
winning_percentage = (winners / total_matches) * 100
winning_percentage

54.356846473029044

In [74]:
#get the total number of league matches in 2016 season for all team.
type_match = df[df["match_type"] == "League"]

season2016 = type_match[
    type_match["season"] == "2016"
].shape[0]

season2016

56

In [75]:
#get the winning percentage of matches of MI where MI loss the toss but won the match
MI_matches = df[
    (df["team1"] == "Mumbai Indians") |
    (df["team2"] == "Mumbai Indians")
]

toss_loss = MI_matches[
    MI_matches["toss_winner"] != "Mumbai Indians"
]

won_match_loss_toss = toss_loss[
    toss_loss["winner"] == "Mumbai Indians"
]

total_matches = toss_loss.shape[0]

matches_won = won_match_loss_toss.shape[0]

winning_percentage = (matches_won / total_matches) * 100

winning_percentage

55.932203389830505

In [91]:
df1=pd.read_csv("matches.csv")
df1

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [90]:
df2=pd.read_csv("deliveries.csv")
df2

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [16]:
df1.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [17]:
df2.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

Merging of data frame:
Join--->A join is used to combine two DataFrames based on a common column.
pd.merge(df1,df2,left_on="common column",right_on="common column",how="inner")

In [21]:
df_merge=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")
df_merge.shape

(260920, 37)

In [19]:
df1.shape

(1095, 20)

In [20]:
df2.shape

(260920, 17)

In [22]:
#verify whether every record in deliveries.csv has a matching match_id in matches.csv
set(df1["id"])-set(df2["match_id"])

set()

In [25]:
set(df2["match_id"])-set(df1["id"])

set()

In [27]:
#extract all deliveries for the 2016 IPL season using merged data.
new=df1[["id","season"]]
ans=pd.merge(new,df2,left_on="id",right_on="match_id",how="inner")
del_2016=ans[ans["season"]=="2016"]
del_2016

,id,season,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
122502,980901,2016,980901,1,Mumbai Indians,Rising Pune Supergiants,0,1,LMP Simmons,RP Singh,RG Sharma,1,0,1,NaN,0,NaN,NaN,NaN
122503,980901,2016,980901,1,Mumbai Indians,Rising Pune Supergiants,0,2,RG Sharma,RP Singh,LMP Simmons,0,0,0,NaN,0,NaN,NaN,NaN
122504,980901,2016,980901,1,Mumbai Indians,Rising Pune Supergiants,0,3,RG Sharma,RP Singh,LMP Simmons,2,0,2,NaN,0,NaN,NaN,NaN
122505,980901,2016,980901,1,Mumbai Indians,Rising Pune Supergiants,0,4,RG Sharma,RP Singh,LMP Simmons,4,0,4,NaN,0,NaN,NaN,NaN
122506,980901,2016,980901,1,Mumbai Indians,Rising Pune Supergiants,0,5,RG Sharma,RP Singh,LMP Simmons,1,0,1,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136593,981019,2016,981019,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,2,Sachin Baby,B Kumar,CJ Jordan,2,0,2,NaN,0,NaN,NaN,NaN
136594,981019,2016,981019,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,3,Sachin Baby,B Kumar,CJ Jordan,0,0,0,NaN,1,CJ Jordan,run out,NV Ojha
136595,981019,2016,981019,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,4,Iqbal Abdulla,B Kumar,Sachin Baby,0,1,1,legbyes,0,NaN,NaN,NaN
136596,981019,2016,981019,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,5,Sachin Baby,B Kumar,Iqbal Abdulla,1,0,1,NaN,0,NaN,NaN,NaN
136597,981019,2016,981019,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Iqbal Abdulla,B Kumar,Sachin Baby,4,0,4,NaN,0,NaN,NaN,NaN

In [31]:
#find all deliveries  from matches where the city  was "Mumbai"
cities=df1[["id","city"]]
ans=pd.merge(cities,df2,left_on="id",right_on="match_id",how="inner")
mumbai_deli=ans[ans["city"]=="Mumbai"]
mumbai_deli

,id,city,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
692,335985,Mumbai,335985,1,Mumbai Indians,Royal Challengers Bangalore,0,1,L Ronchi,P Kumar,ST Jayasuriya,0,0,0,NaN,0,NaN,NaN,NaN
693,335985,Mumbai,335985,1,Mumbai Indians,Royal Challengers Bangalore,0,2,L Ronchi,P Kumar,ST Jayasuriya,4,0,4,NaN,0,NaN,NaN,NaN
694,335985,Mumbai,335985,1,Mumbai Indians,Royal Challengers Bangalore,0,3,L Ronchi,P Kumar,ST Jayasuriya,0,0,0,NaN,0,NaN,NaN,NaN
695,335985,Mumbai,335985,1,Mumbai Indians,Royal Challengers Bangalore,0,4,L Ronchi,P Kumar,ST Jayasuriya,0,0,0,NaN,0,NaN,NaN,NaN
696,335985,Mumbai,335985,1,Mumbai Indians,Royal Challengers Bangalore,0,5,L Ronchi,P Kumar,ST Jayasuriya,4,0,4,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259531,1426305,Mumbai,1426305,2,Mumbai Indians,Lucknow Super Giants,19,3,Ishan Kishan,Naveen-ul-Haq,Naman Dhir,0,0,0,NaN,1,Ishan Kishan,bowled,NaN
259532,1426305,Mumbai,1426305,2,Mumbai Indians,Lucknow Super Giants,19,4,R Shepherd,Naveen-ul-Haq,Naman Dhir,0,1,1,wides,0,NaN,NaN,NaN
259533,1426305,Mumbai,1426305,2,Mumbai Indians,Lucknow Super Giants,19,5,R Shepherd,Naveen-ul-Haq,Naman Dhir,1,0,1,NaN,0,NaN,NaN,NaN
259534,1426305,Mumbai,1426305,2,Mumbai Indians,Lucknow Super Giants,19,6,Naman Dhir,Naveen-ul-Haq,R Shepherd,0,0,0,NaN,0,NaN,NaN,NaN
259535,1426305,Mumbai,1426305,2,Mumbai Indians,Lucknow Super Giants,19,7,Naman Dhir,Naveen-ul-Haq,R Shepherd,6,0,6,NaN,0,NaN,NaN,NaN

In [33]:
#list all deliveries bowled in matches won by "Mumbai indians".
new=df1[["id","winner"]]
ans=pd.merge(new,df2,left_on="id",right_on="match_id",how="inner")
won_by_mi=ans[ans["winner"]=="Mumbai Indians"]
won_by_mi

,id,winner,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
3536,335997,Mumbai Indians,335997,1,Kolkata Knight Riders,Mumbai Indians,0,1,BB McCullum,SM Pollock,SC Ganguly,1,0,1,NaN,0,NaN,NaN,NaN
3537,335997,Mumbai Indians,335997,1,Kolkata Knight Riders,Mumbai Indians,0,2,SC Ganguly,SM Pollock,BB McCullum,4,0,4,NaN,0,NaN,NaN,NaN
3538,335997,Mumbai Indians,335997,1,Kolkata Knight Riders,Mumbai Indians,0,3,SC Ganguly,SM Pollock,BB McCullum,0,0,0,NaN,1,SC Ganguly,caught,ST Jayasuriya
3539,335997,Mumbai Indians,335997,1,Kolkata Knight Riders,Mumbai Indians,0,4,RT Ponting,SM Pollock,BB McCullum,1,0,1,NaN,0,NaN,NaN,NaN
3540,335997,Mumbai Indians,335997,1,Kolkata Knight Riders,Mumbai Indians,0,5,BB McCullum,SM Pollock,RT Ponting,0,0,0,NaN,1,BB McCullum,lbw,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257181,1426293,Mumbai Indians,1426293,2,Mumbai Indians,Sunrisers Hyderabad,16,5,SA Yadav,PJ Cummins,Tilak Varma,4,0,4,NaN,0,NaN,NaN,NaN
257182,1426293,Mumbai Indians,1426293,2,Mumbai Indians,Sunrisers Hyderabad,16,6,SA Yadav,PJ Cummins,Tilak Varma,4,0,4,NaN,0,NaN,NaN,NaN
257183,1426293,Mumbai Indians,1426293,2,Mumbai Indians,Sunrisers Hyderabad,16,7,SA Yadav,PJ Cummins,Tilak Varma,6,0,6,NaN,0,NaN,NaN,NaN
257184,1426293,Mumbai Indians,1426293,2,Mumbai Indians,Sunrisers Hyderabad,17,1,Tilak Varma,T Natarajan,SA Yadav,1,0,1,NaN,0,NaN,NaN,NaN
257185,1426293,Mumbai Indians,1426293,2,Mumbai Indians,Sunrisers Hyderabad,17,2,SA Yadav,T Natarajan,Tilak Varma,6,0,6,NaN,0,NaN,NaN,NaN

In [77]:
#find the total runs scored in finals across all seasons
finals=df1[["id","match_type"]]
runs=df2[["match_id","total_runs"]]
ans=pd.merge(finals,runs,left_on="id",right_on="match_id",how="inner")
final_runs=ans[ans["match_type"]=="Final"]
final_matches=final_runs["total_runs"].sum()
final_matches

np.int64(5556)

In [40]:
#Filter all balls from matches decided by duckworth-lewis method(dl_applied==1)
new1=df1[["id","method"]]
ans=pd.merge(new1,df2,left_on="id",right_on="match_id",how="inner")
dl_deli=ans[ans["method"]=="D/L"]
dl_deli

,id,method,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
8852,336022,D/L,336022,1,Delhi Daredevils,Kings XI Punjab,0,1,G Gambhir,S Sreesanth,V Sehwag,0,0,0,NaN,0,NaN,NaN,NaN
8853,336022,D/L,336022,1,Delhi Daredevils,Kings XI Punjab,0,2,G Gambhir,S Sreesanth,V Sehwag,0,1,1,wides,0,NaN,NaN,NaN
8854,336022,D/L,336022,1,Delhi Daredevils,Kings XI Punjab,0,3,G Gambhir,S Sreesanth,V Sehwag,0,2,2,wides,0,NaN,NaN,NaN
8855,336022,D/L,336022,1,Delhi Daredevils,Kings XI Punjab,0,4,V Sehwag,S Sreesanth,G Gambhir,0,0,0,NaN,0,NaN,NaN,NaN
8856,336022,D/L,336022,1,Delhi Daredevils,Kings XI Punjab,0,5,V Sehwag,S Sreesanth,G Gambhir,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,1370353,D/L,1370353,2,Chennai Super Kings,Gujarat Titans,14,2,S Dube,MM Sharma,RA Jadeja,1,0,1,NaN,0,NaN,NaN,NaN
243813,1370353,D/L,1370353,2,Chennai Super Kings,Gujarat Titans,14,3,RA Jadeja,MM Sharma,S Dube,1,0,1,NaN,0,NaN,NaN,NaN
243814,1370353,D/L,1370353,2,Chennai Super Kings,Gujarat Titans,14,4,S Dube,MM Sharma,RA Jadeja,1,0,1,NaN,0,NaN,NaN,NaN
243815,1370353,D/L,1370353,2,Chennai Super Kings,Gujarat Titans,14,5,RA Jadeja,MM Sharma,S Dube,6,0,6,NaN,0,NaN,NaN,NaN
243816,1370353,D/L,1370353,2,Chennai Super Kings,Gujarat Titans,14,6,RA Jadeja,MM Sharma,S Dube,4,0,4,NaN,0,NaN,NaN,NaN

In [42]:
#find deliveries where the toss winner also won the match
new=df1[["id","toss_winner","winner"]]
res=pd.merge(new,df2,left_on="id",right_on="match_id",how="inner")
ans=res[res["toss_winner"]==res["winner"]]
ans

,id,toss_winner,winner,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
225,335983,Chennai Super Kings,Chennai Super Kings,335983,1,Chennai Super Kings,Kings XI Punjab,0,1,PA Patel,B Lee,ML Hayden,0,0,0,NaN,0,NaN,NaN,NaN
226,335983,Chennai Super Kings,Chennai Super Kings,335983,1,Chennai Super Kings,Kings XI Punjab,0,2,PA Patel,B Lee,ML Hayden,0,0,0,NaN,0,NaN,NaN,NaN
227,335983,Chennai Super Kings,Chennai Super Kings,335983,1,Chennai Super Kings,Kings XI Punjab,0,3,PA Patel,B Lee,ML Hayden,1,0,1,NaN,0,NaN,NaN,NaN
228,335983,Chennai Super Kings,Chennai Super Kings,335983,1,Chennai Super Kings,Kings XI Punjab,0,4,ML Hayden,B Lee,PA Patel,0,0,0,NaN,0,NaN,NaN,NaN
229,335983,Chennai Super Kings,Chennai Super Kings,335983,1,Chennai Super Kings,Kings XI Punjab,0,5,ML Hayden,B Lee,PA Patel,4,0,4,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260480,1426310,Rajasthan Royals,Rajasthan Royals,1426310,2,Rajasthan Royals,Royal Challengers Bengaluru,18,2,R Powell,LH Ferguson,R Ashwin,4,0,4,NaN,0,NaN,NaN,NaN
260481,1426310,Rajasthan Royals,Rajasthan Royals,1426310,2,Rajasthan Royals,Royal Challengers Bengaluru,18,3,R Powell,LH Ferguson,R Ashwin,0,0,0,NaN,0,NaN,NaN,NaN
260482,1426310,Rajasthan Royals,Rajasthan Royals,1426310,2,Rajasthan Royals,Royal Challengers Bengaluru,18,4,R Powell,LH Ferguson,R Ashwin,0,0,0,NaN,0,NaN,NaN,NaN
260483,1426310,Rajasthan Royals,Rajasthan Royals,1426310,2,Rajasthan Royals,Royal Challengers Bengaluru,18,5,R Powell,LH Ferguson,R Ashwin,0,0,0,NaN,0,NaN,NaN,NaN
260484,1426310,Rajasthan Royals,Rajasthan Royals,1426310,2,Rajasthan Royals,Royal Challengers Bengaluru,18,6,R Powell,LH Ferguson,R Ashwin,6,0,6,NaN,0,NaN,NaN,NaN

In [46]:
#extract all wickets taken in matches played at "eden gardens"
new1=df1[["id","venue"]]
ans=pd.merge(new1,df2,left_on="id",right_on="match_id",how="inner")
res=ans[ans["venue"]=="Eden Gardens"]["is_wicket"]
res

938       0
939       0
940       0
941       0
942       0
         ..
176130    0
176131    0
176132    1
176133    0
176134    0
Name: is_wicket, Length: 17988, dtype: int64

In [49]:
#Get all deliveries of Super Overs using merged data
new=df1[["id","super_over"]]
ans=pd.merge(new,df2,left_on="id",right_on="match_id",how="inner")
res=ans[ans["super_over"]=="Y"]
res

,id,super_over,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
15161,392190,Y,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,1,GC Smith,I Sharma,PC Valthaty,0,0,0,NaN,0,NaN,NaN,NaN
15162,392190,Y,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,2,GC Smith,I Sharma,PC Valthaty,0,1,1,legbyes,0,NaN,NaN,NaN
15163,392190,Y,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,3,PC Valthaty,I Sharma,GC Smith,1,0,1,NaN,0,NaN,NaN,NaN
15164,392190,Y,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,4,GC Smith,I Sharma,PC Valthaty,0,0,0,NaN,0,NaN,NaN,NaN
15165,392190,Y,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,5,GC Smith,I Sharma,PC Valthaty,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198500,1254077,Y,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,2,S Dhawan,Rashid Khan,RR Pant,0,1,1,legbyes,0,NaN,NaN,NaN
198501,1254077,Y,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,3,RR Pant,Rashid Khan,S Dhawan,4,0,4,NaN,0,NaN,NaN,NaN
198502,1254077,Y,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,4,RR Pant,Rashid Khan,S Dhawan,0,0,0,NaN,0,NaN,NaN,NaN
198503,1254077,Y,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,5,RR Pant,Rashid Khan,S Dhawan,0,1,1,legbyes,0,NaN,NaN,NaN
198504,1254077,Y,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,6,S Dhawan,Rashid Khan,RR Pant,0,1,1,legbyes,0,NaN,NaN,NaN

In [76]:
#Filter matches where the toss decision was "field" and list first 10 deliveries.
new=df1[["id","toss_decision"]]
ans=pd.merge(new,df2,left_on="id",right_on="match_id",how="inner")
res=ans[ans["toss_decision"]=="field"]
res.head(10)

,id,toss_decision,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,...,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,matchup,run_type
0,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,...,0,1,1,legbyes,0,NaN,NaN,NaN,"SC Ganguly, P Kumar",other
1,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,...,0,0,0,NaN,0,NaN,NaN,NaN,"BB McCullum, P Kumar",dot
2,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,...,0,1,1,wides,0,NaN,NaN,NaN,"BB McCullum, P Kumar",other
3,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,...,0,0,0,NaN,0,NaN,NaN,NaN,"BB McCullum, P Kumar",dot
4,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,...,0,0,0,NaN,0,NaN,NaN,NaN,"BB McCullum, P Kumar",dot
5,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,...,0,0,0,NaN,0,NaN,NaN,NaN,"BB McCullum, P Kumar",dot
6,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,...,0,1,1,legbyes,0,NaN,NaN,NaN,"BB McCullum, P Kumar",other
7,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,...,0,0,0,NaN,0,NaN,NaN,NaN,"BB McCullum, Z Khan",dot
8,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,...,4,0,4,NaN,0,NaN,NaN,NaN,"BB McCullum, Z Khan",boundary
9,335982,field,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,...,4,0,4,NaN,0,NaN,NaN,NaN,"BB McCullum, Z Khan",boundary

In [51]:
#show all balls bowled in matchs that had a tie result
new=df1[["id","result"]]
ans=pd.merge(new,df2,left_on="id",right_on="match_id",how="inner")
res=ans[ans["result"]=="tie"]
res

,id,result,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
15161,392190,tie,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,1,GC Smith,I Sharma,PC Valthaty,0,0,0,NaN,0,NaN,NaN,NaN
15162,392190,tie,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,2,GC Smith,I Sharma,PC Valthaty,0,1,1,legbyes,0,NaN,NaN,NaN
15163,392190,tie,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,3,PC Valthaty,I Sharma,GC Smith,1,0,1,NaN,0,NaN,NaN,NaN
15164,392190,tie,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,4,GC Smith,I Sharma,PC Valthaty,0,0,0,NaN,0,NaN,NaN,NaN
15165,392190,tie,392190,1,Rajasthan Royals,Kolkata Knight Riders,0,5,GC Smith,I Sharma,PC Valthaty,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198500,1254077,tie,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,2,S Dhawan,Rashid Khan,RR Pant,0,1,1,legbyes,0,NaN,NaN,NaN
198501,1254077,tie,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,3,RR Pant,Rashid Khan,S Dhawan,4,0,4,NaN,0,NaN,NaN,NaN
198502,1254077,tie,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,4,RR Pant,Rashid Khan,S Dhawan,0,0,0,NaN,0,NaN,NaN,NaN
198503,1254077,tie,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,5,RR Pant,Rashid Khan,S Dhawan,0,1,1,legbyes,0,NaN,NaN,NaN
198504,1254077,tie,1254077,4,Delhi Capitals,Sunrisers Hyderabad,0,6,S Dhawan,Rashid Khan,RR Pant,0,1,1,legbyes,0,NaN,NaN,NaN

In [52]:
#find all deliveries bowled by "Bumrah" in matches where his team lost.
new=df1[["id","winner"]]
res=pd.merge(new,df2,left_on="id",right_on="match_id",how="inner")
matches_lost_mi=res[res["winner"]!="Mumbai Indians"]
bumrah_del=matches_lost_mi[matches_lost_mi["bowler"]=="JJ Bumrah"]
bumrah_del

,id,winner,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
76637,597999,Royal Challengers Bangalore,597999,1,Royal Challengers Bangalore,Mumbai Indians,4,1,V Kohli,JJ Bumrah,CH Gayle,4,0,4,NaN,0,NaN,NaN,NaN
76638,597999,Royal Challengers Bangalore,597999,1,Royal Challengers Bangalore,Mumbai Indians,4,2,V Kohli,JJ Bumrah,CH Gayle,4,0,4,NaN,0,NaN,NaN,NaN
76639,597999,Royal Challengers Bangalore,597999,1,Royal Challengers Bangalore,Mumbai Indians,4,3,V Kohli,JJ Bumrah,CH Gayle,0,0,0,NaN,0,NaN,NaN,NaN
76640,597999,Royal Challengers Bangalore,597999,1,Royal Challengers Bangalore,Mumbai Indians,4,4,V Kohli,JJ Bumrah,CH Gayle,4,0,4,NaN,0,NaN,NaN,NaN
76641,597999,Royal Challengers Bangalore,597999,1,Royal Challengers Bangalore,Mumbai Indians,4,5,V Kohli,JJ Bumrah,CH Gayle,0,0,0,NaN,1,V Kohli,lbw,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258196,1426298,Kolkata Knight Riders,1426298,1,Kolkata Knight Riders,Mumbai Indians,15,2,RK Singh,JJ Bumrah,Ramandeep Singh,0,0,0,NaN,1,RK Singh,caught,Ishan Kishan
258197,1426298,Kolkata Knight Riders,1426298,1,Kolkata Knight Riders,Mumbai Indians,15,3,MA Starc,JJ Bumrah,Ramandeep Singh,1,0,1,NaN,0,NaN,NaN,NaN
258198,1426298,Kolkata Knight Riders,1426298,1,Kolkata Knight Riders,Mumbai Indians,15,4,Ramandeep Singh,JJ Bumrah,MA Starc,1,0,1,NaN,0,NaN,NaN,NaN
258199,1426298,Kolkata Knight Riders,1426298,1,Kolkata Knight Riders,Mumbai Indians,15,5,MA Starc,JJ Bumrah,Ramandeep Singh,1,0,1,NaN,0,NaN,NaN,NaN
258200,1426298,Kolkata Knight Riders,1426298,1,Kolkata Knight Riders,Mumbai Indians,15,6,Ramandeep Singh,JJ Bumrah,MA Starc,6,0,6,NaN,0,NaN,NaN,NaN

In [53]:
#Add a column is_final which marks 1 if the match was a final
#(based on match_id of last match in each season).
df1["is_final"]=df1["match_type"].apply(lambda x:1 if x=="Final" else 0)
df1["is_final"].value_counts()

is_final
0    1078
1      17
Name: count, dtype: int64

In [59]:
#add a new coloumn combining batsman and bowler as a single string "matchup"
df2["matchup"]=df2["batter"] + ", "+df2["bowler"]
df2["matchup"]

0            SC Ganguly, P Kumar
1           BB McCullum, P Kumar
2           BB McCullum, P Kumar
3           BB McCullum, P Kumar
4           BB McCullum, P Kumar
                   ...
260915       SS Iyer, AK Markram
260916       VR Iyer, AK Markram
260917    VR Iyer, Shahbaz Ahmed
260918    SS Iyer, Shahbaz Ahmed
260919    VR Iyer, Shahbaz Ahmed
Name: matchup, Length: 260920, dtype: object

In [60]:
#Create a new column run_type that classifies each ball as "boundary","dot", or "other".
def convert(x):
    if x in [4,5,6,7]:
        return "boundary"
    elif x==0:
        return "dot"
    else:
        return "other"
df2["run_type"]=df2["total_runs"].apply(convert)
df2["run_type"]

0         other
1           dot
2         other
3           dot
4           dot
          ...
260915    other
260916    other
260917    other
260918    other
260919    other
Name: run_type, Length: 260920, dtype: object

Groupby-
It will group the records based on the similar values.
We will apply aggregation with groupby.
Aggregation func- giving multiple rows as ip----> single value as a output

In [3]:
data={
    "department":["IT","CS","IT","CS","ECE","ECE"],
    "ename":["abc","pqr","xyz","uvw","mnp","mpk"],
    "salary":[10000,10000,20000,15000,20000,10000],
    "gender":["male","female","female","male","male","female"]
}
df=pd.DataFrame(data)
df

  department ename  salary  gender
0         IT   abc   10000    male
1         CS   pqr   10000  female
2         IT   xyz   20000  female
3         CS   uvw   15000    male
4        ECE   mnp   20000    male
5        ECE   mpk   10000  female

In [5]:
#get department wise average salary
df.groupby("department")["salary"].mean()

department
CS     12500.0
ECE    15000.0
IT     15000.0
Name: salary, dtype: float64

In [6]:
#get average salary based on department as well as gender.
df.groupby(["department","gender"])["salary"].mean()

department  gender
CS          female    10000.0
            male      15000.0
ECE         female    10000.0
            male      20000.0
IT          female    20000.0
            male      10000.0
Name: salary, dtype: float64

In [7]:
df1=pd.read_csv("matches.csv")
df1

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [8]:
df2=pd.read_csv("deliveries.csv")
df2

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [9]:
#add a new boolean column powerplay_ball for overs <=6
df2["powerplay_ball"]=df2["over"].apply(lambda x: 1 if x<=5 else 0)
df2["powerplay_ball"]

0         1
1         1
2         1
3         1
4         1
         ..
260915    0
260916    0
260917    0
260918    0
260919    0
Name: powerplay_ball, Length: 260920, dtype: int64

In [13]:
#add a column showing cumulative wickets lost by each batting team in a match
#is_wicket,batting_team
df2.groupby(["match_id","batting_team"])["is_wicket"].cumsum()

0         0
1         0
2         0
3         0
4         0
         ..
260915    2
260916    2
260917    2
260918    2
260919    2
Name: is_wicket, Length: 260920, dtype: int64

In [16]:
#replace dismissal_kind NAN values with "not out".
#dismissal_kind	
df2["dismissal_kind"]=df2["dismissal_kind"].fillna("not out") #fillna is used to replace a value with another.
df2["dismissal_kind"].unique()

array(['not out', 'caught', 'bowled', 'run out', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field', 'retired out'], dtype=object)

In [24]:
#add column inning_type with values "first innings" or "second innings".
def innings(x):
    if x in [1,3,5]:
        return "first innings"
    else:
        return "second innings"
df2["inning_type"]=df2["inning"].apply(innings)

In [26]:
df2["inning_type"].unique()

array(['first innings', 'second innings'], dtype=object)

In [29]:
#Add column match_label combining season and city name
df1["match_label"]=df1["season"]+" , "+df1["city"]
df1["match_label"]

0        2007/08 , Bangalore
1       2007/08 , Chandigarh
2            2007/08 , Delhi
3           2007/08 , Mumbai
4          2007/08 , Kolkata
                ...
1090        2024 , Hyderabad
1091        2024 , Ahmedabad
1092        2024 , Ahmedabad
1093          2024 , Chennai
1094          2024 , Chennai
Name: match_label, Length: 1095, dtype: object

In [35]:
#compute total runs scored by each team in each season
new1=df1[["id","season"]]
new2=df2[["match_id","total_runs","batting_team"]]
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")

res.groupby(["season","batting_team"])["total_runs"].sum()

season   batting_team
2007/08  Chennai Super Kings            2520
         Deccan Chargers                2229
         Delhi Daredevils               2118
         Kings XI Punjab                2464
         Kolkata Knight Riders          1942
                                        ...
2024     Mumbai Indians                 2568
         Punjab Kings                   2487
         Rajasthan Royals               2647
         Royal Challengers Bengaluru    2930
         Sunrisers Hyderabad            3052
Name: total_runs, Length: 146, dtype: int64

In [34]:
res.groupby(["season","batting_team"])["total_runs"].sum().reset_index() #gives in data frame form

      season                 batting_team  total_runs
0    2007/08          Chennai Super Kings        2520
1    2007/08              Deccan Chargers        2229
2    2007/08             Delhi Daredevils        2118
3    2007/08              Kings XI Punjab        2464
4    2007/08        Kolkata Knight Riders        1942
..       ...                          ...         ...
141     2024               Mumbai Indians        2568
142     2024                 Punjab Kings        2487
143     2024             Rajasthan Royals        2647
144     2024  Royal Challengers Bengaluru        2930
145     2024          Sunrisers Hyderabad        3052

[146 rows x 3 columns]

In [38]:
#calculate total wickets taken by each bowler across all seasons
new1=df1[["id","season"]]
new2=df2[["match_id","is_wicket","bowler"]]
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")

res.groupby(["season","bowler"])["is_wicket"].sum()

season   bowler
2007/08  A Kumble              8
         A Mishra             11
         A Nehra              14
         A Nel                 1
         A Symonds             0
                              ..
2024     Washington Sundar     1
         YS Chahal            19
         Yash Dayal           16
         Yash Thakur          12
         Yudhvir Singh         1
Name: is_wicket, Length: 1948, dtype: int64

In [40]:
#find total number of matches played per city 
df1["city"].value_counts()

city
Mumbai            173
Kolkata            93
Delhi              90
Chennai            85
Hyderabad          77
Bangalore          65
Chandigarh         61
Jaipur             57
Pune               51
Abu Dhabi          37
Ahmedabad          36
Bengaluru          29
Durban             15
Visakhapatnam      15
Lucknow            14
Dubai              13
Dharamsala         13
Centurion          12
Rajkot             10
Sharjah            10
Indore              9
Navi Mumbai         9
Johannesburg        8
Cuttack             7
Port Elizabeth      7
Ranchi              7
Cape Town           7
Raipur              6
Mohali              5
Kochi               5
Kanpur              4
Kimberley           3
East London         3
Guwahati            3
Nagpur              3
Bloemfontein        2
Name: count, dtype: int64

In [42]:
#get the average runs per over for each team in the 2017 season.
#season, over, batting_team,total_runs
new1=df1[["id","season"]]
new2=df2[["match_id","batting_team","over","total_runs"]]
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")

season_2017=res[res["season"]=="2017"]

season_2017.groupby(["batting_team","over"])["total_runs"].mean()

batting_team         over
Delhi Daredevils     0       0.873563
                     1       1.270588
                     2       1.505882
                     3       1.425287
                     4       1.616279
                               ...
Sunrisers Hyderabad  15      1.313953
                     16      1.419753
                     17      1.737500
                     18      1.788732
                     19      1.823529
Name: total_runs, Length: 160, dtype: float64

In [43]:
season_2017.groupby(["batting_team","over"])["total_runs"].mean().reset_index()

            batting_team  over  total_runs
0       Delhi Daredevils     0    0.873563
1       Delhi Daredevils     1    1.270588
2       Delhi Daredevils     2    1.505882
3       Delhi Daredevils     3    1.425287
4       Delhi Daredevils     4    1.616279
..                   ...   ...         ...
155  Sunrisers Hyderabad    15    1.313953
156  Sunrisers Hyderabad    16    1.419753
157  Sunrisers Hyderabad    17    1.737500
158  Sunrisers Hyderabad    18    1.788732
159  Sunrisers Hyderabad    19    1.823529

[160 rows x 3 columns]

In [58]:
#find the top 5 batsmen with highest total runs in finals
#	batsman_runs,match_type,batter
new1=df1[["id","match_type"]]
new2=df2[["match_id","batter","batsman_runs"]]
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")

final_matches=res[res["match_type"]=="Final"]

final_matches.groupby("batter")["batsman_runs"].sum().sort_values(ascending=False).head(5)

batter
SK Raina      249
SR Watson     236
RG Sharma     183
M Vijay       181
KA Pollard    180
Name: batsman_runs, dtype: int64

In [59]:
final_matches.groupby("batter")["batsman_runs"].sum().sort_values().tail(5)

batter
KA Pollard    180
M Vijay       181
RG Sharma     183
SR Watson     236
SK Raina      249
Name: batsman_runs, dtype: int64

In [69]:
#find the bowler with the best economy rate in each season.
new1=df1[["id","season"]]
new2=df2[["match_id","bowler","total_runs"]]
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")

res.groupby(["season","bowler"])["total_runs"].mean().sort_values(ascending=False)

season   bowler
2022     YBK Jaiswal         6.000000
2024     VR Iyer             4.666667
2011     S Sriram            4.166667
2024     Atharva Taide       4.000000
         Mukesh Choudhary    3.857143
                               ...
2016     N Rana              0.500000
2007/08  TM Dilshan          0.500000
2013     BJ Hodge            0.500000
         AC Gilchrist        0.000000
2023     A Badoni            0.000000
Name: total_runs, Length: 1948, dtype: float64

In [21]:
customers=pd.read_csv("customers.csv")
order_items=pd.read_csv("order_items.csv")
orders=pd.read_csv("orders.csv")
payments=pd.read_csv("payments.csv")
reviews=pd.read_csv("reviews.csv")
products=pd.read_csv("products.csv")

In [6]:
#merge customers.csv and orders.csv using customer_id and display customer_id, custimer name,order_id and order_date
merge_res=pd.merge(customers,orders,left_on="customer_id",right_on="customer_id",how="inner")
merge_res

,customer_id,name,email,city,signup_date,order_id,order_date,status
0,C0001,Ananya Sharma,ananya.sharma1@example.com,Kochi,2023-07-18,O00026,2024-04-03,Processing
1,C0002,Sneha Singh,sneha.singh2@example.com,Delhi,2022-07-29,O00037,2024-12-15,Delivered
2,C0003,Nikhil Patel,nikhil.patel3@example.com,Lucknow,2024-05-14,O00351,2024-09-24,Delivered
3,C0004,Aditi Sharma,aditi.sharma4@example.com,Mumbai,2023-03-24,O00145,2025-10-03,Delivered
4,C0004,Aditi Sharma,aditi.sharma4@example.com,Mumbai,2023-03-24,O00249,2025-05-28,Delivered
...,...,...,...,...,...,...,...,...
495,C0497,Sneha Gupta,sneha.gupta497@example.com,Mumbai,2022-04-08,O00063,2024-10-28,Shipped
496,C0497,Sneha Gupta,sneha.gupta497@example.com,Mumbai,2022-04-08,O00267,2025-07-31,Cancelled
497,C0497,Sneha Gupta,sneha.gupta497@example.com,Mumbai,2022-04-08,O00463,2025-12-15,Processing
498,C0498,Sneha Verma,sneha.verma498@example.com,Surat,2025-06-29,O00144,2025-07-04,Processing
499,C0499,Riya Patel,riya.patel499@example.com,Mumbai,2024-10-20,O00246,2024-08-16,Processing

In [10]:
#merge orders.csv  with customers.csv and add the customer name to every order
new1=customers[["customer_id","name"]]
res=pd.merge(orders,new1,left_on="customer_id",right_on="customer_id",how="inner")
res

    order_id customer_id  order_date      status           name
0     O00001       C0007  2025-12-22   Cancelled    Pooja Singh
1     O00002       C0269  2025-08-13   Cancelled    Aditi Mehta
2     O00003       C0290  2024-08-17   Cancelled    Rahul Mehta
3     O00004       C0448  2024-12-12  Processing     Riya Joshi
4     O00005       C0268  2025-12-05   Cancelled       Neha Rao
..       ...         ...         ...         ...            ...
495   O00496       C0078  2024-02-20  Processing  Aditya Sharma
496   O00497       C0012  2024-07-09   Delivered   Ishita Joshi
497   O00498       C0145  2024-10-02   Delivered    Kavya Mehta
498   O00499       C0367  2025-03-24   Cancelled    Aarav Kumar
499   O00500       C0005  2024-08-26   Delivered     Sneha Shah

[500 rows x 5 columns]

In [13]:
#Merge order.csv and payments.csv using order_id and display order details along with payment method, payment amount and payment status
new1=payments[["order_id","payment_method","amount","payment_status"]]
res=pd.merge(orders,new1,left_on="order_id",right_on="order_id",how="inner")
res

,order_id,customer_id,order_date,status,payment_method,amount,payment_status
0,O00001,C0007,2025-12-22,Cancelled,Net Banking,144897.18,Failed
1,O00002,C0269,2025-08-13,Cancelled,Net Banking,322447.60,Failed
2,O00003,C0290,2024-08-17,Cancelled,Cash on Delivery,58851.28,Failed
3,O00004,C0448,2024-12-12,Processing,UPI,134663.12,Pending
4,O00005,C0268,2025-12-05,Cancelled,Cash on Delivery,27229.80,Failed
...,...,...,...,...,...,...,...
495,O00496,C0078,2024-02-20,Processing,UPI,206231.56,Paid
496,O00497,C0012,2024-07-09,Delivered,UPI,123772.40,Paid
497,O00498,C0145,2024-10-02,Delivered,UPI,288362.52,Paid
498,O00499,C0367,2025-03-24,Cancelled,UPI,8525.93,Failed
499,O00500,C0005,2024-08-26,Delivered,Cash on Delivery,115032.56,Paid

In [17]:
#merge customers.csv and payments.csv and display customer name, order_id, payment method and payment amount
new1=customers[["customer_id","name"]]
new2=orders[["customer_id","order_id"]]
new3=payments[["order_id","payment_method","amount"]]
res=pd.merge(new1,new2,left_on="customer_id",right_on="customer_id",how="inner")
result=pd.merge(res,new3,left_on="order_id",right_on="order_id",how="inner")
result

    customer_id           name order_id    payment_method     amount
0         C0001  Ananya Sharma   O00026       Credit Card  226177.22
1         C0002    Sneha Singh   O00037  Cash on Delivery  530484.51
2         C0003   Nikhil Patel   O00351        Debit Card  104727.31
3         C0004   Aditi Sharma   O00145        Debit Card  332840.14
4         C0004   Aditi Sharma   O00249       Net Banking  422249.54
..          ...            ...      ...               ...        ...
495       C0497    Sneha Gupta   O00063        Debit Card  219685.17
496       C0497    Sneha Gupta   O00267       Net Banking  179662.83
497       C0497    Sneha Gupta   O00463               UPI   87192.64
498       C0498    Sneha Verma   O00144       Net Banking  260151.74
499       C0499     Riya Patel   O00246       Net Banking  240586.05

[500 rows x 5 columns]

In [23]:
#merge order_items.csv and products.csv using product id and display order_id, product id, product_name, categort, quamtity and total_price.
new1=order_items[["product_id","order_id","total_price"]]
new2=products[["product_id","product_name","category",	"stock"]]
res=pd.merge(new1,new2,left_on="product_id",right_on="product_id",how="inner")
res

,product_id,order_id,total_price,product_name,category,stock
0,P0008,O00001,63318.90,Novel,Home & Kitchen,415
1,P0253,O00001,81578.28,Backpack,Sports,387
2,P0160,O00002,62438.16,Yoga Mat,Books,288
3,P0403,O00002,111073.48,Kitchen Mixer,Toys,430
4,P0410,O00002,19526.34,Smart Watch,Beauty,203
...,...,...,...,...,...,...
1470,P0447,O00498,199491.84,Wireless Headphones,Home & Kitchen,132
1471,P0345,O00498,65441.35,Kitchen Mixer,Clothing,416
1472,P0055,O00498,23429.33,Wireless Mouse,Clothing,136
1473,P0203,O00499,8525.93,Cotton T-Shirt,Grocery,141
1474,P0088,O00500,115032.56,Mechanical Keyboard,Sports,278

In [30]:
#merge order_items.csv with products.csv and find the total revenue generated by each product
new1=order_items[["product_id","total_price"]]
new2=products[["product_id","product_name"]]
res=pd.merge(new1,new2,left_on="product_id",right_on="product_id",how="inner")
res.groupby(["product_name"])["total_price"].sum().reset_index()

           product_name  total_price
0              Backpack   7201976.70
1     Bluetooth Speaker   6134371.00
2          Coffee Maker   4504752.53
3        Cotton T-Shirt   7943980.96
4             Face Wash   3444624.02
5          Fitness Band   3603710.37
6         Kitchen Mixer   6677126.32
7              LED Lamp   4898671.05
8       Laptop Backpack   4009065.00
9   Mechanical Keyboard   4916300.11
10             Notebook   8200047.81
11                Novel   6093498.75
12         Office Chair   5550514.13
13        Running Shoes   4884099.51
14          Smart Watch   5503614.55
15           Sunglasses   2475991.11
16         Water Bottle   6851699.60
17  Wireless Headphones   7267281.77
18       Wireless Mouse   5276890.01
19             Yoga Mat   5891848.12

In [80]:
#merge orders.csv,  order_items.csv and customers.csv and find the total spending of each customer. 
new1=orders[["customer_id", "order_id"]]
new2=order_items[["order_id","total_price"]]
new3=customers[["customer_id","name"]]

res1=pd.merge(orders,order_items,left_on="order_id",right_on="order_id",how="inner")
res2=pd.merge(res1,customers,left_on="customer_id",right_on="customer_id",how="inner")
res2.groupby(["name"])["total_price"].sum().reset_index()

              name  total_price
0      Aarav Gupta    318023.42
1       Aarav Iyer    344700.73
2      Aarav Joshi    586483.62
3      Aarav Kumar   1542807.23
4      Aarav Mehta    309956.40
..             ...          ...
197    Vikram Nair     34390.00
198   Vikram Reddy   2070824.82
199    Vikram Shah    379050.75
200  Vikram Sharma     53118.12
201   Vikram Singh    426257.44

[202 rows x 2 columns]

In [82]:
#using the customer spending data, find the top 10 customers based on total spending
new1=orders[["customer_id", "order_id"]]
new2=order_items[["order_id","total_price"]]
new3=customers[["customer_id","name"]]

res1=pd.merge(orders,order_items,left_on="order_id",right_on="order_id",how="inner")
res2=pd.merge(res1,customers,left_on="customer_id",right_on="customer_id",how="inner")
res2.groupby(["name"])["total_price"].sum().sort_values(ascending=False).head(10)

name
Arjun Iyer      2509015.05
Rohan Rao       2112048.71
Karan Joshi     2091395.37
Vikram Reddy    2070824.82
Vikram Iyer     1881063.15
Aditi Iyer      1795682.50
Meera Rao       1794383.20
Kavya Shah      1656344.24
Aditi Patel     1555394.82
Aarav Kumar     1542807.23
Name: total_price, dtype: float64

In [84]:
#merge order_items.csv with products.csv and find the total revenue generated by each product category
new1=order_items[["product_id","total_price"]]
new2=products[["product_id","category"]]
res=pd.merge(new1,new2,left_on="product_id",right_on="product_id",how="inner")
res.groupby(["category"])["total_price"].sum()

category
Beauty            14498928.57
Books             12617012.96
Clothing          14358933.68
Electronics       10329947.02
Grocery           11969174.23
Home & Kitchen    14195577.32
Sports            16751441.66
Toys              16609047.98
Name: total_price, dtype: float64

In [85]:
#Merge customers.csv, orders.csv, and order_items.csv and 
#find the total revenue generated by each city.
new1=customers[["customer_id","city"]]
new2=orders[["customer_id","order_id"]]
new3=order_items[["order_id","total_price"]]
res1=pd.merge(new1,new2,left_on="customer_id",right_on="customer_id",how="inner")
result=pd.merge(res1,new3,left_on="order_id",right_on="order_id",how="inner")

result.groupby(["city"])["total_price"].sum().reset_index()

         city  total_price
0   Ahmedabad  11198989.65
1   Bangalore  10688336.64
2     Chennai   7668968.70
3       Delhi   8474478.26
4   Hyderabad   7379072.01
5      Jaipur   7042489.21
6       Kochi   8430047.68
7     Kolkata   8708212.47
8     Lucknow   8452349.92
9      Mumbai  11917291.57
10       Pune   8474120.32
11      Surat  12895706.99

In [66]:
#Merge reviews.csv with products.csv and find the average rating for every product
new1=reviews[["product_id","rating"]]
new2=products[["product_id","product_name"]]
res=pd.merge(new1,new2,left_on="product_id",right_on="product_id",how="inner")
res.groupby(["product_name"])["rating"].mean().reset_index()

           product_name    rating
0              Backpack  3.814815
1     Bluetooth Speaker  3.962963
2          Coffee Maker  4.200000
3        Cotton T-Shirt  4.111111
4             Face Wash  4.153846
5          Fitness Band  4.166667
6         Kitchen Mixer  3.806452
7              LED Lamp  3.750000
8       Laptop Backpack  4.333333
9   Mechanical Keyboard  4.153846
10             Notebook  3.947368
11                Novel  3.960000
12         Office Chair  4.111111
13        Running Shoes  4.086957
14          Smart Watch  3.838710
15           Sunglasses  4.000000
16         Water Bottle  3.833333
17  Wireless Headphones  3.964286
18       Wireless Mouse  4.210526
19             Yoga Mat  4.200000

agg(aggregation)-It is used with groupby() to perform multiple calculations at the same time on one or more columns.

df.groupby("column").agg({
    "column1": "sum",
    "column2": "mean"
})

In [88]:
#merge products.csv , order_items.csv and reviews.csv and create a dataframe containing product name, category, total_quantity sold, 
#total revenue, average rating
new1=products[["product_id","product_name","category"]]
new2=order_items[["product_id","quantity","total_price"]]
new3=reviews[["product_id","rating"]]

res1=pd.merge(new1,new2,left_on="product_id",right_on="product_id",how="inner")
res2=pd.merge(res1,new3,left_on="product_id",right_on="product_id",how="inner")

res2.groupby(["product_id","product_name","category"]).agg(total_quantity=("quantity","sum"),
                                                        total_revenue=("total_price","sum"),
                                                        average_rating=("rating","mean")).reset_index()

,product_id,product_name,category,total_quantity,total_revenue,average_rating
0,P0001,Cotton T-Shirt,Books,10,215751.00,4.500000
1,P0003,LED Lamp,Clothing,11,39263.73,4.000000
2,P0004,Face Wash,Electronics,84,198828.84,4.166667
3,P0006,Water Bottle,Beauty,8,308958.16,3.500000
4,P0007,Cotton T-Shirt,Beauty,10,177434.90,5.000000
...,...,...,...,...,...,...
281,P0489,Mechanical Keyboard,Electronics,5,200592.45,5.000000
282,P0490,Running Shoes,Toys,9,383319.45,4.000000
283,P0492,Yoga Mat,Beauty,22,1050773.68,4.000000
284,P0498,Fitness Band,Beauty,5,215776.35,5.000000
285,P0500,Bluetooth Speaker,Grocery,12,158727.84,4.500000