In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("Placement_Data_Full_Class.csv")

In [5]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [9]:
df.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [10]:
#Display all students who got placed.
df[df["status"]=="Placed"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
7,8,M,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.0,Mkt&Fin,62.14,Placed,252000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,M,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0

In [11]:
#Show records of students who were not placed.
df[df["status"]!="Placed"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
3,4,M,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
5,6,M,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,F,46.0,Others,49.2,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
9,10,M,58.0,Central,70.0,Central,Commerce,61.00,Comm&Mgmt,No,54.00,Mkt&Fin,52.21,Not Placed,NaN
12,13,F,47.0,Central,55.0,Others,Science,65.00,Comm&Mgmt,No,62.00,Mkt&HR,65.04,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,199,F,67.0,Central,70.0,Central,Commerce,65.00,Others,No,88.00,Mkt&HR,71.96,Not Placed,NaN
201,202,M,54.2,Central,63.0,Others,Science,58.00,Comm&Mgmt,No,79.00,Mkt&HR,58.44,Not Placed,NaN
206,207,M,41.0,Central,42.0,Central,Science,60.00,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed,NaN
208,209,F,43.0,Central,60.0,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN
214,215,M,62.0,Central,58.0,Others,Science,53.00,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [12]:
#Display students with ssc_p (10th percentage) greater than 80.
df[df["ssc_p"]>80]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
7,8,M,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.00,Mkt&Fin,62.14,Placed,252000.0
33,34,F,87.00,Others,65.00,Others,Science,81.00,Comm&Mgmt,Yes,88.00,Mkt&Fin,72.78,Placed,260000.0
39,40,M,81.00,Others,68.00,Others,Science,64.00,Sci&Tech,No,93.00,Mkt&Fin,62.56,Placed,411000.0
43,44,M,87.00,Others,87.00,Others,Commerce,68.00,Comm&Mgmt,No,95.00,Mkt&HR,62.90,Placed,300000.0
61,62,M,84.20,Central,73.40,Central,Commerce,66.89,Comm&Mgmt,No,61.60,Mkt&Fin,62.48,Placed,300000.0
62,63,F,86.50,Others,64.20,Others,Science,67.40,Sci&Tech,No,59.00,Mkt&Fin,59.69,Placed,240000.0
66,67,M,83.00,Others,74.00,Others,Science,66.00,Comm&Mgmt,No,68.92,Mkt&HR,58.46,Placed,275000.0
67,68,M,80.92,Others,78.50,Others,Commerce,67.00,Comm&Mgmt,No,68.71,Mkt&Fin,60.99,Placed,275000.0
70,71,M,82.00,Others,61.00,Others,Science,62.00,Sci&Tech,No,89.00,Mkt&Fin,65.45,Placed,360000.0
72,73,M,84.86,Others,67.00,Others,Science,78.00,Comm&Mgmt,No,95.50,Mkt&Fin,68.53,Placed,240000.0
78,79,M,84.00,Others,90.90,Others,Science,64.50,Sci&Tech,No,86.04,Mkt&Fin,59.42,Placed,270000.0
81,82,M,81.70,Others,63.00,Others,Science,67.00,Comm&Mgmt,Yes,86.00,Mkt&Fin,70.20,Placed,300000.0
83,84,M,84.00,Others,79.00,Others,Science,68.00,Sci&Tech,Yes,84.00,Mkt&Fin,66.69,Placed,300000.0
85,86,F,83.84,Others,89.83,Others,Commerce,77.20,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
89,90,F,84.00,Others,75.00,Others,Science,69.00,Sci&Tech,Yes,62.00,Mkt&HR,62.36,Placed,210000.0
90,91,F,85.00,Others,90.00,Others,Commerce,82.00,Comm&Mgmt,No,92.00,Mkt&Fin,68.03,Placed,300000.0
107,108,M,82.00,Others,90.00,Others,Commerce,83.00,Comm&Mgmt,No,80.00,Mkt&HR,73.52,Placed,200000.0
125,126,F,84.00,Central,73.00,Central,Commerce,73.00,Comm&Mgmt,No,75.00,Mkt&Fin,73.33,Placed,350000.0
128,129,M,80.40,Central,73.40,Central,Science,77.72,Sci&Tech,Yes,81.20,Mkt&HR,76.26,Placed,400000.0
138,139,F,82.00,Others,64.00,Others,Science,73.00,Sci&Tech,Yes,96.00,Mkt&Fin,71.77,Placed,250000.0
142,143,M,85.00,Central,60.00,Others,Science,73.43,Sci&Tech,Yes,60.00,Mkt&Fin,61.29,Placed,260000.0
145,146,M,89.40,Others,65.66,Others,Science,71.25,Sci&Tech,No,72.00,Mkt&HR,63.23,Placed,400000.0
156,157,M,84.20,Central,69.40,Central,Science,65.00,Sci&Tech,Yes,80.00,Mkt&HR,52.72,Placed,255000.0
160,161,M,87.00,Central,74.00,Central,Science,65.00,Sci&Tech,Yes,75.00,Mkt&HR,72.29,Placed,300000.0
185,186,F,88.00,Central,72.00,Central,Science,78.00,Others,No,82.00,Mkt&HR,71.43,Placed,252000.0
197,198,F,83.96,Others,53.00,Others,Science,91.00,Sci&Tech,No,59.32,Mkt&HR,69.71,Placed,260000.0
207,208,M,83.33,Central,78.00,Others,Commerce,61.00,Comm&Mgmt,Yes,88.56,Mkt&Fin,71.55,Placed,300000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0

In [13]:
#Retrieve all students whose hsc_p (12th percentage) is less than 70.
df[df["hsc_p"]<70]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
2,3,M,65.0,Central,68.0,Central,Arts,64.00,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
5,6,M,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,F,46.0,Others,49.2,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
7,8,M,82.0,Central,64.0,Central,Science,66.00,Sci&Tech,Yes,67.00,Mkt&Fin,62.14,Placed,252000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,209,F,43.0,Central,60.0,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN
211,212,M,58.0,Others,60.0,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.0,Others,67.0,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.0,Others,66.0,Others,Commerce,58.00,Comm&Mgmt,No,70.00,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.0,Central,58.0,Others,Science,53.00,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [14]:
#Select students who have degree_p greater than 75 and mba_p greater than 60.
df[(df["degree_p"]>75) & (df["mba_p"]>60)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
11,12,M,69.60,Central,68.40,Central,Commerce,78.30,Comm&Mgmt,Yes,60.00,Mkt&Fin,63.70,Placed,250000.0
21,22,F,79.00,Others,76.00,Others,Commerce,85.00,Comm&Mgmt,No,95.00,Mkt&Fin,69.06,Placed,393000.0
24,25,M,76.50,Others,97.70,Others,Science,78.86,Sci&Tech,No,97.40,Mkt&Fin,74.01,Placed,360000.0
33,34,F,87.00,Others,65.00,Others,Science,81.00,Comm&Mgmt,Yes,88.00,Mkt&Fin,72.78,Placed,260000.0
40,41,F,78.00,Central,77.00,Others,Commerce,80.00,Comm&Mgmt,No,60.00,Mkt&Fin,66.72,Placed,287000.0
44,45,F,77.00,Others,73.00,Others,Commerce,81.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,69.70,Placed,200000.0
72,73,M,84.86,Others,67.00,Others,Science,78.00,Comm&Mgmt,No,95.50,Mkt&Fin,68.53,Placed,240000.0
75,76,F,59.00,Central,62.00,Others,Commerce,77.50,Comm&Mgmt,No,74.00,Mkt&HR,67.00,Not Placed,NaN
85,86,F,83.84,Others,89.83,Others,Commerce,77.20,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
90,91,F,85.00,Others,90.00,Others,Commerce,82.00,Comm&Mgmt,No,92.00,Mkt&Fin,68.03,Placed,300000.0
96,97,F,76.00,Central,70.00,Central,Science,76.00,Comm&Mgmt,Yes,66.00,Mkt&Fin,64.44,Placed,300000.0
107,108,M,82.00,Others,90.00,Others,Commerce,83.00,Comm&Mgmt,No,80.00,Mkt&HR,73.52,Placed,200000.0
118,119,M,76.00,Central,80.00,Central,Science,78.00,Sci&Tech,Yes,97.00,Mkt&HR,70.48,Placed,276000.0
126,127,F,79.00,Others,61.00,Others,Science,75.50,Sci&Tech,Yes,70.00,Mkt&Fin,68.20,Placed,210000.0
128,129,M,80.40,Central,73.40,Central,Science,77.72,Sci&Tech,Yes,81.20,Mkt&HR,76.26,Placed,400000.0
133,134,M,73.00,Central,64.00,Others,Commerce,77.00,Comm&Mgmt,Yes,65.00,Mkt&HR,60.98,Placed,250000.0
152,153,F,75.40,Others,60.50,Central,Science,84.00,Sci&Tech,No,98.00,Mkt&Fin,65.25,Placed,240000.0
162,163,M,74.20,Central,87.60,Others,Commerce,77.25,Comm&Mgmt,Yes,75.20,Mkt&Fin,66.06,Placed,285000.0
177,178,F,73.00,Central,97.00,Others,Commerce,79.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,70.81,Placed,650000.0
185,186,F,88.00,Central,72.00,Central,Science,78.00,Others,No,82.00,Mkt&HR,71.43,Placed,252000.0
197,198,F,83.96,Others,53.00,Others,Science,91.00,Sci&Tech,No,59.32,Mkt&HR,69.71,Placed,260000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0

In [15]:
#Display all male students with workex equal to “Yes”.
df[(df["gender"]=="M") & (df["workex"]=="Yes")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
5,6,M,55.00,Others,49.80,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
7,8,M,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.00,Mkt&Fin,62.14,Placed,252000.0
10,11,M,58.00,Central,61.00,Central,Commerce,60.00,Comm&Mgmt,Yes,62.00,Mkt&HR,60.85,Placed,260000.0
11,12,M,69.60,Central,68.40,Central,Commerce,78.30,Comm&Mgmt,Yes,60.00,Mkt&Fin,63.70,Placed,250000.0
16,17,M,63.00,Central,66.20,Central,Commerce,65.60,Comm&Mgmt,Yes,60.00,Mkt&Fin,62.54,Placed,300000.0
19,20,M,60.00,Others,67.00,Others,Arts,70.00,Comm&Mgmt,Yes,50.48,Mkt&Fin,77.89,Placed,236000.0
26,27,M,71.00,Others,79.00,Others,Commerce,66.00,Comm&Mgmt,Yes,94.00,Mkt&Fin,57.55,Placed,240000.0
28,29,M,76.76,Others,76.50,Others,Commerce,67.50,Comm&Mgmt,Yes,73.35,Mkt&Fin,64.15,Placed,350000.0
47,48,M,63.00,Central,60.00,Central,Commerce,57.00,Comm&Mgmt,Yes,78.00,Mkt&Fin,54.55,Placed,204000.0
60,61,M,74.00,Central,70.00,Central,Science,72.00,Comm&Mgmt,Yes,60.00,Mkt&Fin,57.24,Placed,260000.0
69,70,M,73.00,Central,73.00,Central,Science,66.00,Sci&Tech,Yes,70.00,Mkt&Fin,68.07,Placed,275000.0
77,78,M,64.00,Others,80.00,Others,Science,65.00,Sci&Tech,Yes,69.00,Mkt&Fin,57.65,Placed,500000.0
81,82,M,81.70,Others,63.00,Others,Science,67.00,Comm&Mgmt,Yes,86.00,Mkt&Fin,70.20,Placed,300000.0
83,84,M,84.00,Others,79.00,Others,Science,68.00,Sci&Tech,Yes,84.00,Mkt&Fin,66.69,Placed,300000.0
84,85,M,70.00,Central,63.00,Others,Science,70.00,Sci&Tech,Yes,55.00,Mkt&Fin,62.00,Placed,300000.0
95,96,M,73.00,Central,78.00,Others,Commerce,65.00,Comm&Mgmt,Yes,95.46,Mkt&Fin,62.16,Placed,420000.0
103,104,M,73.00,Central,78.00,Central,Science,73.00,Sci&Tech,Yes,85.00,Mkt&HR,65.83,Placed,240000.0
104,105,M,69.00,Central,63.00,Others,Science,65.00,Comm&Mgmt,Yes,55.00,Mkt&HR,58.23,Placed,360000.0
109,110,M,52.00,Central,63.00,Others,Science,65.00,Sci&Tech,Yes,86.00,Mkt&HR,56.09,Not Placed,NaN
116,117,M,68.20,Central,72.80,Central,Commerce,66.60,Comm&Mgmt,Yes,96.00,Mkt&Fin,70.85,Placed,300000.0
118,119,M,76.00,Central,80.00,Central,Science,78.00,Sci&Tech,Yes,97.00,Mkt&HR,70.48,Placed,276000.0
119,120,M,60.80,Central,68.40,Central,Commerce,64.60,Comm&Mgmt,Yes,82.66,Mkt&Fin,64.34,Placed,940000.0
123,124,M,74.00,Others,59.00,Others,Commerce,73.00,Comm&Mgmt,Yes,60.00,Mkt&HR,56.70,Placed,240000.0
124,125,M,67.00,Central,71.00,Central,Science,64.33,Others,Yes,64.00,Mkt&HR,61.26,Placed,250000.0
128,129,M,80.40,Central,73.40,Central,Science,77.72,Sci&Tech,Yes,81.20,Mkt&HR,76.26,Placed,400000.0
129,130,M,76.70,Central,89.70,Others,Commerce,66.00,Comm&Mgmt,Yes,90.00,Mkt&Fin,68.55,Placed,250000.0
132,133,M,67.00,Others,68.00,Others,Commerce,64.00,Comm&Mgmt,Yes,74.40,Mkt&HR,53.49,Placed,300000.0
133,134,M,73.00,Central,64.00,Others,Commerce,77.00,Comm&Mgmt,Yes,65.00,Mkt&HR,60.98,Placed,250000.0
139,140,M,77.00,Central,70.00,Central,Commerce,59.00,Comm&Mgmt,Yes,58.00,Mkt&Fin,54.43,Placed,220000.0
140,141,M,65.00,Central,64.80,Others,Commerce,69.50,Comm&Mgmt,Yes,56.00,Mkt&Fin,56.94,Placed,265000.0
142,143,M,85.00,Central,60.00,Others,Science,73.43,Sci&Tech,Yes,60.00,Mkt&Fin,61.29,Placed,260000.0
149,150,M,44.00,Central,58.00,Central,Arts,55.00,Comm&Mgmt,Yes,64.25,Mkt&HR,58.54,Not Placed,NaN
150,151,M,71.00,Central,58.66,Central,Science,58.00,Sci&Tech,Yes,56.00,Mkt&Fin,61.30,Placed,690000.0
153,154,M,49.00,Others,59.00,Others,Science,65.00,Sci&Tech,Yes,86.00,Mkt&Fin,62.48,Placed,340000.0
154,155,M,53.00,Central,63.00,Others,Science,60.00,Comm&Mgmt,Yes,70.00,Mkt&Fin,53.20,Placed,250000.0
155,156,M,51.57,Others,74.66,Others,Commerce,59.90,Comm&Mgmt,Yes,56.15,Mkt&HR,65.99,Not Placed,NaN
156,157,M,84.20,Central,69.40,Central,Science,65.00,Sci&Tech,Yes,80.00,Mkt&HR,52.72,Placed,255000.0
160,161,M,87.00,Central,74.00,Central,Science,65.00,Sci&Tech,Yes,75.00,Mkt&HR,72.29,Placed,300000.0
162,163,M,74.20,Central,87.60,Others,Commerce,77.25,Comm&Mgmt,Yes,75.20,Mkt&Fin,66.06,Placed,285000.0
166,167,M,62.00,Others,62.00,Others,Commerce,60.00,Comm&Mgmt,Yes,63.00,Mkt&HR,52.38,Placed,240000.0
167,168,M,67.90,Others,62.00,Others,Science,67.00,Sci&Tech,Yes,58.10,Mkt&Fin,75.71,Not Placed,NaN
171,172,M,80.00,Others,80.00,Others,Commerce,72.00,Comm&Mgmt,Yes,63.79,Mkt&Fin,66.04,Placed,290000.0
174,175,M,73.24,Others,50.83,Others,Science,64.27,Sci&Tech,Yes,64.00,Mkt&Fin,66.23,Placed,500000.0
180,181,M,65.00,Central,71.50,Others,Commerce,62.80,Comm&Mgmt,Yes,57.00,Mkt&Fin,56.60,Placed,265000.0
182,183,M,52.00,Others,65.00,Others,Arts,57.00,Others,Yes,75.00,Mkt&Fin,59.81,Not Placed,NaN
187,188,M,78.50,Central,65.50,Central,Science,67.00,Sci&Tech,Yes,95.00,Mkt&Fin,64.86,Placed,280000.0
192,193,M,65.20,Central,61.40,Central,Commerce,64.80,Comm&Mgmt,Yes,93.40,Mkt&Fin,57.34,Placed,270000.0
195,196,M,66.00,Central,76.00,Central,Commerce,72.00,Comm&Mgmt,Yes,84.00,Mkt&HR,58.95,Placed,275000.0
196,197,M,72.00,Others,63.00,Others,Science,77.50,Sci&Tech,Yes,78.00,Mkt&Fin,54.48,Placed,250000.0
207,208,M,83.33,Central,78.00,Others,Commerce,61.00,Comm&Mgmt,Yes,88.56,Mkt&Fin,71.55,Placed,300000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0

In [16]:
#Show female students with degree_t as “Sci&amp;Tech”.
df[(df["gender"]=="F") & (df["degree_t"]=="Sci&Tech")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
22,23,F,69.80,Others,60.8,Others,Science,72.23,Sci&Tech,No,55.53,Mkt&HR,68.81,Placed,360000.0
23,24,F,77.40,Others,60.0,Others,Science,64.74,Sci&Tech,Yes,92.00,Mkt&Fin,63.62,Placed,300000.0
31,32,F,67.00,Central,53.0,Central,Science,65.00,Sci&Tech,No,64.00,Mkt&HR,58.32,Not Placed,NaN
37,38,F,79.00,Central,76.0,Central,Science,65.60,Sci&Tech,No,58.00,Mkt&HR,55.47,Placed,320000.0
45,46,F,76.00,Central,64.0,Central,Science,72.00,Sci&Tech,No,58.00,Mkt&HR,66.53,Not Placed,NaN
62,63,F,86.50,Others,64.2,Others,Science,67.40,Sci&Tech,No,59.00,Mkt&Fin,59.69,Placed,240000.0
68,69,F,69.70,Central,47.0,Central,Commerce,72.70,Sci&Tech,No,79.00,Mkt&HR,59.24,Not Placed,NaN
79,80,F,69.00,Central,62.0,Central,Science,66.00,Sci&Tech,No,75.00,Mkt&HR,67.99,Not Placed,NaN
89,90,F,84.00,Others,75.0,Others,Science,69.00,Sci&Tech,Yes,62.00,Mkt&HR,62.36,Placed,210000.0
110,111,F,69.50,Central,70.0,Central,Science,72.00,Sci&Tech,No,57.20,Mkt&HR,54.80,Placed,250000.0
121,122,F,64.00,Central,67.0,Others,Science,69.60,Sci&Tech,Yes,55.67,Mkt&HR,71.49,Placed,250000.0
126,127,F,79.00,Others,61.0,Others,Science,75.50,Sci&Tech,Yes,70.00,Mkt&Fin,68.20,Placed,210000.0
138,139,F,82.00,Others,64.0,Others,Science,73.00,Sci&Tech,Yes,96.00,Mkt&Fin,71.77,Placed,250000.0
152,153,F,75.40,Others,60.5,Central,Science,84.00,Sci&Tech,No,98.00,Mkt&Fin,65.25,Placed,240000.0
173,174,F,52.00,Others,52.0,Others,Science,55.00,Sci&Tech,No,67.00,Mkt&HR,59.32,Not Placed,NaN
179,180,F,77.80,Central,64.0,Central,Science,64.20,Sci&Tech,No,75.50,Mkt&HR,72.14,Not Placed,NaN
197,198,F,83.96,Others,53.0,Others,Science,91.00,Sci&Tech,No,59.32,Mkt&HR,69.71,Placed,260000.0

In [17]:
#Get students whose etest_p is between 70 and 90.
df[(df["etest_p"]>70) & (df["etest_p"]<90)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
6,7,F,46.00,Others,49.20,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
14,15,M,62.00,Central,47.00,Central,Commerce,50.00,Comm&Mgmt,No,76.00,Mkt&HR,54.96,Not Placed,NaN
15,16,F,65.00,Central,75.00,Central,Commerce,69.00,Comm&Mgmt,Yes,72.00,Mkt&Fin,64.66,Placed,200000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,202,M,54.20,Central,63.00,Others,Science,58.00,Comm&Mgmt,No,79.00,Mkt&HR,58.44,Not Placed,NaN
204,205,F,74.00,Others,73.00,Others,Commerce,73.00,Comm&Mgmt,Yes,80.00,Mkt&Fin,67.69,Placed,210000.0
207,208,M,83.33,Central,78.00,Others,Commerce,61.00,Comm&Mgmt,Yes,88.56,Mkt&Fin,71.55,Placed,300000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [18]:
#Display students who have hsc_b (HSC board) as “Central” 
#and ssc_b as “Central”.
df[(df["hsc_b"]=="Central") & (df["ssc_b"]=="Central")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
2,3,M,65.0,Central,68.0,Central,Arts,64.0,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.0,Central,52.0,Central,Science,52.0,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.8,Central,73.6,Central,Commerce,73.3,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
7,8,M,82.0,Central,64.0,Central,Science,66.0,Sci&Tech,Yes,67.00,Mkt&Fin,62.14,Placed,252000.0
8,9,M,73.0,Central,79.0,Central,Commerce,72.0,Comm&Mgmt,No,91.34,Mkt&Fin,61.29,Placed,231000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,M,66.0,Central,76.0,Central,Commerce,72.0,Comm&Mgmt,Yes,84.00,Mkt&HR,58.95,Placed,275000.0
198,199,F,67.0,Central,70.0,Central,Commerce,65.0,Others,No,88.00,Mkt&HR,71.96,Not Placed,NaN
202,203,M,70.0,Central,63.0,Central,Science,66.0,Sci&Tech,No,61.28,Mkt&HR,60.11,Placed,240000.0
206,207,M,41.0,Central,42.0,Central,Science,60.0,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed,NaN
209,210,M,62.0,Central,72.0,Central,Commerce,65.0,Comm&Mgmt,No,67.00,Mkt&Fin,56.49,Placed,216000.0

In [19]:
#Show students with mba_p less than 60 or degree_p less than 60.
df[(df["mba_p"]<60) | (df["degree_p"]<60)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.0,Others,91.0,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
2,3,M,65.0,Central,68.0,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.8,Central,73.6,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
5,6,M,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.0,Mkt&Fin,51.58,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,207,M,41.0,Central,42.0,Central,Science,60.00,Comm&Mgmt,No,97.0,Mkt&Fin,53.39,Not Placed,NaN
209,210,M,62.0,Central,72.0,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
211,212,M,58.0,Others,60.0,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
213,214,F,74.0,Others,66.0,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.0,Central,58.0,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [20]:
#Retrieve all students with status equal to “Placed” and 
#salary greater than 400000.
df[(df["status"]=="Placed") & (df["salary"]>400000)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
39,40,M,81.00,Others,68.00,Others,Science,64.00,Sci&Tech,No,93.00,Mkt&Fin,62.56,Placed,411000.0
53,54,M,80.00,Others,70.00,Others,Science,72.00,Sci&Tech,No,87.00,Mkt&HR,71.04,Placed,450000.0
77,78,M,64.00,Others,80.00,Others,Science,65.00,Sci&Tech,Yes,69.00,Mkt&Fin,57.65,Placed,500000.0
95,96,M,73.00,Central,78.00,Others,Commerce,65.00,Comm&Mgmt,Yes,95.46,Mkt&Fin,62.16,Placed,420000.0
119,120,M,60.80,Central,68.40,Central,Commerce,64.60,Comm&Mgmt,Yes,82.66,Mkt&Fin,64.34,Placed,940000.0
150,151,M,71.00,Central,58.66,Central,Science,58.00,Sci&Tech,Yes,56.00,Mkt&Fin,61.30,Placed,690000.0
163,164,M,63.00,Others,67.00,Others,Science,64.00,Sci&Tech,No,75.00,Mkt&Fin,66.46,Placed,500000.0
174,175,M,73.24,Others,50.83,Others,Science,64.27,Sci&Tech,Yes,64.00,Mkt&Fin,66.23,Placed,500000.0
177,178,F,73.00,Central,97.00,Others,Commerce,79.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,70.81,Placed,650000.0

In [21]:
#Display records where degree_t is “Comm&amp;Mgmt”.
df[df["degree_t"]=="Comm&Mgmt"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
2,3,M,65.0,Central,68.0,Central,Arts,64.0,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
4,5,M,85.8,Central,73.6,Central,Commerce,73.3,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
6,7,F,46.0,Others,49.2,Others,Commerce,79.0,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
8,9,M,73.0,Central,79.0,Central,Commerce,72.0,Comm&Mgmt,No,91.34,Mkt&Fin,61.29,Placed,231000.0
9,10,M,58.0,Central,70.0,Central,Commerce,61.0,Comm&Mgmt,No,54.00,Mkt&Fin,52.21,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,M,62.0,Central,72.0,Central,Commerce,65.0,Comm&Mgmt,No,67.00,Mkt&Fin,56.49,Placed,216000.0
210,211,M,80.6,Others,82.0,Others,Commerce,77.6,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
212,213,M,67.0,Others,67.0,Others,Commerce,73.0,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.0,Others,66.0,Others,Commerce,58.0,Comm&Mgmt,No,70.00,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.0,Central,58.0,Others,Science,53.0,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [22]:
#Select students whose hsc_p ≥ 85 and workex = “Yes”.
df[(df["hsc_p"]>=85) & (df["workex"]=="Yes")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
85,86,F,83.84,Others,89.83,Others,Commerce,77.20,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
129,130,M,76.70,Central,89.70,Others,Commerce,66.00,Comm&Mgmt,Yes,90.00,Mkt&Fin,68.55,Placed,250000.0
134,135,F,77.44,Central,92.00,Others,Commerce,72.00,Comm&Mgmt,Yes,94.00,Mkt&Fin,67.13,Placed,250000.0
162,163,M,74.20,Central,87.60,Others,Commerce,77.25,Comm&Mgmt,Yes,75.20,Mkt&Fin,66.06,Placed,285000.0
177,178,F,73.00,Central,97.00,Others,Commerce,79.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,70.81,Placed,650000.0

In [23]:
#Show all students whose gender is “F” and ssc_p &lt; 70.
df[(df["gender"]=="F") & (df["ssc_p"]<70)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
6,7,F,46.00,Others,49.20,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
12,13,F,47.00,Central,55.00,Others,Science,65.00,Comm&Mgmt,No,62.00,Mkt&HR,65.04,Not Placed,NaN
15,16,F,65.00,Central,75.00,Central,Commerce,69.00,Comm&Mgmt,Yes,72.00,Mkt&Fin,64.66,Placed,200000.0
17,18,F,55.00,Central,67.00,Central,Commerce,64.00,Comm&Mgmt,No,60.00,Mkt&Fin,67.28,Not Placed,NaN
18,19,F,63.00,Central,66.00,Central,Commerce,64.00,Comm&Mgmt,No,68.00,Mkt&HR,64.08,Not Placed,NaN
22,23,F,69.80,Others,60.80,Others,Science,72.23,Sci&Tech,No,55.53,Mkt&HR,68.81,Placed,360000.0
25,26,F,52.58,Others,54.60,Central,Commerce,50.20,Comm&Mgmt,Yes,76.00,Mkt&Fin,65.33,Not Placed,NaN
30,31,F,64.00,Central,73.50,Central,Commerce,73.00,Comm&Mgmt,No,52.00,Mkt&HR,56.70,Placed,250000.0
31,32,F,67.00,Central,53.00,Central,Science,65.00,Sci&Tech,No,64.00,Mkt&HR,58.32,Not Placed,NaN
32,33,F,61.00,Central,81.00,Central,Commerce,66.40,Comm&Mgmt,No,50.89,Mkt&HR,62.21,Placed,278000.0
35,36,F,69.00,Central,78.00,Central,Commerce,72.00,Comm&Mgmt,No,71.00,Mkt&HR,62.74,Placed,300000.0
49,50,F,50.00,Others,37.00,Others,Arts,52.00,Others,No,65.00,Mkt&HR,56.11,Not Placed,NaN
52,53,F,40.89,Others,45.83,Others,Commerce,53.00,Comm&Mgmt,No,71.20,Mkt&HR,65.49,Not Placed,NaN
68,69,F,69.70,Central,47.00,Central,Commerce,72.70,Sci&Tech,No,79.00,Mkt&HR,59.24,Not Placed,NaN
75,76,F,59.00,Central,62.00,Others,Commerce,77.50,Comm&Mgmt,No,74.00,Mkt&HR,67.00,Not Placed,NaN
76,77,F,66.50,Others,70.40,Central,Arts,71.93,Comm&Mgmt,No,61.00,Mkt&Fin,64.27,Placed,230000.0
79,80,F,69.00,Central,62.00,Central,Science,66.00,Sci&Tech,No,75.00,Mkt&HR,67.99,Not Placed,NaN
80,81,F,69.00,Others,62.00,Others,Commerce,69.00,Comm&Mgmt,Yes,67.00,Mkt&HR,62.35,Placed,240000.0
88,89,F,66.00,Central,62.00,Central,Commerce,73.00,Comm&Mgmt,No,58.00,Mkt&HR,64.36,Placed,210000.0
92,93,F,60.23,Central,69.00,Central,Science,66.00,Comm&Mgmt,No,72.00,Mkt&Fin,59.47,Placed,230000.0
98,99,F,69.00,Central,73.00,Central,Commerce,65.00,Comm&Mgmt,No,70.00,Mkt&Fin,57.31,Placed,220000.0
100,101,F,45.00,Others,57.00,Others,Commerce,58.00,Comm&Mgmt,Yes,56.39,Mkt&HR,64.95,Not Placed,NaN
110,111,F,69.50,Central,70.00,Central,Science,72.00,Sci&Tech,No,57.20,Mkt&HR,54.80,Placed,250000.0
121,122,F,64.00,Central,67.00,Others,Science,69.60,Sci&Tech,Yes,55.67,Mkt&HR,71.49,Placed,250000.0
122,123,F,66.50,Central,66.80,Central,Arts,69.30,Comm&Mgmt,Yes,80.40,Mkt&Fin,71.00,Placed,236000.0
136,137,F,47.00,Central,59.00,Central,Arts,64.00,Comm&Mgmt,No,78.00,Mkt&Fin,61.58,Not Placed,NaN
164,165,F,67.16,Central,72.50,Central,Commerce,63.35,Comm&Mgmt,No,53.04,Mkt&Fin,65.52,Placed,250000.0
165,166,F,63.30,Central,78.33,Others,Commerce,74.00,Comm&Mgmt,No,80.00,Mkt&Fin,74.56,Not Placed,NaN
168,169,F,48.00,Central,51.00,Central,Commerce,58.00,Comm&Mgmt,Yes,60.00,Mkt&HR,58.79,Not Placed,NaN
170,171,F,63.40,Others,67.20,Others,Commerce,60.00,Comm&Mgmt,No,58.06,Mkt&HR,69.28,Not Placed,NaN
173,174,F,52.00,Others,52.00,Others,Science,55.00,Sci&Tech,No,67.00,Mkt&HR,59.32,Not Placed,NaN
176,177,F,59.00,Central,60.00,Others,Commerce,56.00,Comm&Mgmt,No,55.00,Mkt&HR,57.90,Placed,220000.0
184,185,F,56.28,Others,62.83,Others,Commerce,59.79,Comm&Mgmt,No,60.00,Mkt&HR,57.29,Not Placed,NaN
186,187,F,52.00,Central,64.00,Central,Commerce,61.00,Comm&Mgmt,No,55.00,Mkt&Fin,62.93,Not Placed,NaN
189,190,F,54.00,Central,77.60,Others,Commerce,69.20,Comm&Mgmt,No,95.65,Mkt&Fin,66.94,Not Placed,NaN
190,191,F,64.00,Others,70.20,Central,Commerce,61.00,Comm&Mgmt,No,50.00,Mkt&Fin,62.50,Not Placed,NaN
193,194,F,60.00,Central,63.00,Central,Arts,56.00,Others,Yes,80.00,Mkt&HR,56.63,Placed,300000.0
198,199,F,67.00,Central,70.00,Central,Commerce,65.00,Others,No,88.00,Mkt&HR,71.96,Not Placed,NaN
208,209,F,43.00,Central,60.00,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN

In [24]:
# Find students whose salary is missing 
df[df["salary"].isnull()]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
3,4,M,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
5,6,M,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,F,46.0,Others,49.2,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
9,10,M,58.0,Central,70.0,Central,Commerce,61.00,Comm&Mgmt,No,54.00,Mkt&Fin,52.21,Not Placed,NaN
12,13,F,47.0,Central,55.0,Others,Science,65.00,Comm&Mgmt,No,62.00,Mkt&HR,65.04,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,199,F,67.0,Central,70.0,Central,Commerce,65.00,Others,No,88.00,Mkt&HR,71.96,Not Placed,NaN
201,202,M,54.2,Central,63.0,Others,Science,58.00,Comm&Mgmt,No,79.00,Mkt&HR,58.44,Not Placed,NaN
206,207,M,41.0,Central,42.0,Central,Science,60.00,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed,NaN
208,209,F,43.0,Central,60.0,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN
214,215,M,62.0,Central,58.0,Others,Science,53.00,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [25]:
#Display top 10 rows where etest_p is highest.
df.sort_values("etest_p", ascending=False).head(10)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
152,153,F,75.40,Others,60.5,Central,Science,84.00,Sci&Tech,No,98.00,Mkt&Fin,65.25,Placed,240000.0
24,25,M,76.50,Others,97.7,Others,Science,78.86,Sci&Tech,No,97.40,Mkt&Fin,74.01,Placed,360000.0
206,207,M,41.00,Central,42.0,Central,Science,60.00,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed,NaN
118,119,M,76.00,Central,80.0,Central,Science,78.00,Sci&Tech,Yes,97.00,Mkt&HR,70.48,Placed,276000.0
4,5,M,85.80,Central,73.6,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
138,139,F,82.00,Others,64.0,Others,Science,73.00,Sci&Tech,Yes,96.00,Mkt&Fin,71.77,Placed,250000.0
116,117,M,68.20,Central,72.8,Central,Commerce,66.60,Comm&Mgmt,Yes,96.00,Mkt&Fin,70.85,Placed,300000.0
189,190,F,54.00,Central,77.6,Others,Commerce,69.20,Comm&Mgmt,No,95.65,Mkt&Fin,66.94,Not Placed,NaN
72,73,M,84.86,Others,67.0,Others,Science,78.00,Comm&Mgmt,No,95.50,Mkt&Fin,68.53,Placed,240000.0
95,96,M,73.00,Central,78.0,Others,Commerce,65.00,Comm&Mgmt,Yes,95.46,Mkt&Fin,62.16,Placed,420000.0

In [26]:
#Show all students who have degree_p between 60 and 80.
df[(df["degree_p"]>60)&(df["degree_p"]<80)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
5,6,M,55.00,Others,49.80,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,F,46.00,Others,49.20,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,209,F,43.00,Central,60.00,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN
209,210,M,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.00,Mkt&Fin,56.49,Placed,216000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0

In [27]:
#Select students whose specialisation is “Mkt&amp;Fin”.
df[df["specialisation"]=="Mkt&Fin"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
5,6,M,55.00,Others,49.80,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,F,46.00,Others,49.20,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,208,M,83.33,Central,78.00,Others,Commerce,61.00,Comm&Mgmt,Yes,88.56,Mkt&Fin,71.55,Placed,300000.0
209,210,M,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.00,Mkt&Fin,56.49,Placed,216000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0

In [28]:
#Retrieve all students with workex = “No” and placed = “No”.
df[(df["workex"]=="No") & (df["status"]!="Placed")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
6,7,F,46.00,Others,49.20,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
9,10,M,58.00,Central,70.00,Central,Commerce,61.00,Comm&Mgmt,No,54.00,Mkt&Fin,52.21,Not Placed,NaN
12,13,F,47.00,Central,55.00,Others,Science,65.00,Comm&Mgmt,No,62.00,Mkt&HR,65.04,Not Placed,NaN
14,15,M,62.00,Central,47.00,Central,Commerce,50.00,Comm&Mgmt,No,76.00,Mkt&HR,54.96,Not Placed,NaN
17,18,F,55.00,Central,67.00,Central,Commerce,64.00,Comm&Mgmt,No,60.00,Mkt&Fin,67.28,Not Placed,NaN
18,19,F,63.00,Central,66.00,Central,Commerce,64.00,Comm&Mgmt,No,68.00,Mkt&HR,64.08,Not Placed,NaN
29,30,M,62.00,Central,67.00,Central,Commerce,58.00,Comm&Mgmt,No,77.00,Mkt&Fin,51.29,Not Placed,NaN
31,32,F,67.00,Central,53.00,Central,Science,65.00,Sci&Tech,No,64.00,Mkt&HR,58.32,Not Placed,NaN
34,35,M,62.00,Others,51.00,Others,Science,52.00,Others,No,68.44,Mkt&HR,62.77,Not Placed,NaN
36,37,M,51.00,Central,44.00,Central,Commerce,57.00,Comm&Mgmt,No,64.00,Mkt&Fin,51.45,Not Placed,NaN
42,43,M,49.00,Others,39.00,Central,Science,65.00,Others,No,63.00,Mkt&Fin,51.21,Not Placed,NaN
45,46,F,76.00,Central,64.00,Central,Science,72.00,Sci&Tech,No,58.00,Mkt&HR,66.53,Not Placed,NaN
46,47,F,70.89,Others,71.98,Others,Science,65.60,Comm&Mgmt,No,68.00,Mkt&HR,71.63,Not Placed,NaN
49,50,F,50.00,Others,37.00,Others,Arts,52.00,Others,No,65.00,Mkt&HR,56.11,Not Placed,NaN
51,52,M,54.40,Central,61.12,Central,Commerce,56.20,Comm&Mgmt,No,67.00,Mkt&HR,62.65,Not Placed,NaN
52,53,F,40.89,Others,45.83,Others,Commerce,53.00,Comm&Mgmt,No,71.20,Mkt&HR,65.49,Not Placed,NaN
63,64,M,61.00,Others,70.00,Others,Commerce,64.00,Comm&Mgmt,No,68.50,Mkt&HR,59.50,Not Placed,NaN
65,66,M,54.00,Others,47.00,Others,Science,57.00,Comm&Mgmt,No,89.69,Mkt&HR,57.10,Not Placed,NaN
68,69,F,69.70,Central,47.00,Central,Commerce,72.70,Sci&Tech,No,79.00,Mkt&HR,59.24,Not Placed,NaN
75,76,F,59.00,Central,62.00,Others,Commerce,77.50,Comm&Mgmt,No,74.00,Mkt&HR,67.00,Not Placed,NaN
79,80,F,69.00,Central,62.00,Central,Science,66.00,Sci&Tech,No,75.00,Mkt&HR,67.99,Not Placed,NaN
82,83,M,63.00,Central,67.00,Central,Commerce,74.00,Comm&Mgmt,No,82.00,Mkt&Fin,60.44,Not Placed,NaN
87,88,M,59.60,Central,51.00,Central,Science,60.00,Others,No,75.00,Mkt&HR,59.08,Not Placed,NaN
91,92,M,52.00,Central,57.00,Central,Commerce,50.80,Comm&Mgmt,No,67.00,Mkt&HR,62.79,Not Placed,NaN
93,94,M,52.00,Central,62.00,Central,Commerce,54.00,Comm&Mgmt,No,72.00,Mkt&HR,55.41,Not Placed,NaN
97,98,F,70.50,Central,62.50,Others,Commerce,61.00,Comm&Mgmt,No,93.91,Mkt&Fin,69.03,Not Placed,NaN
99,100,M,54.00,Central,82.00,Others,Commerce,63.00,Sci&Tech,No,50.00,Mkt&Fin,59.47,Not Placed,NaN
105,106,M,59.00,Central,64.00,Others,Science,58.00,Sci&Tech,No,85.00,Mkt&HR,55.30,Not Placed,NaN
106,107,M,61.08,Others,50.00,Others,Science,54.00,Sci&Tech,No,71.00,Mkt&Fin,65.69,Not Placed,NaN
111,112,M,51.00,Others,54.00,Others,Science,61.00,Sci&Tech,No,60.00,Mkt&HR,60.64,Not Placed,NaN
120,121,M,58.00,Others,40.00,Others,Science,59.00,Comm&Mgmt,No,73.00,Mkt&HR,58.81,Not Placed,NaN
130,131,M,62.00,Central,65.00,Others,Commerce,60.00,Comm&Mgmt,No,84.00,Mkt&Fin,64.15,Not Placed,NaN
136,137,F,47.00,Central,59.00,Central,Arts,64.00,Comm&Mgmt,No,78.00,Mkt&Fin,61.58,Not Placed,NaN
141,142,M,66.00,Central,64.00,Central,Science,60.00,Comm&Mgmt,No,60.00,Mkt&HR,61.90,Not Placed,NaN
144,145,M,52.00,Others,50.00,Others,Arts,61.00,Comm&Mgmt,No,60.00,Mkt&Fin,58.52,Not Placed,NaN
158,159,M,67.00,Others,63.00,Others,Science,64.00,Sci&Tech,No,60.00,Mkt&Fin,61.87,Not Placed,NaN
159,160,M,52.00,Central,49.00,Others,Commerce,58.00,Comm&Mgmt,No,62.00,Mkt&HR,60.59,Not Placed,NaN
161,162,M,55.60,Others,51.00,Others,Commerce,57.50,Comm&Mgmt,No,57.63,Mkt&HR,62.72,Not Placed,NaN
165,166,F,63.30,Central,78.33,Others,Commerce,74.00,Comm&Mgmt,No,80.00,Mkt&Fin,74.56,Not Placed,NaN
169,170,M,59.96,Others,42.16,Others,Science,61.26,Sci&Tech,No,54.48,Mkt&HR,65.48,Not Placed,NaN
170,171,F,63.40,Others,67.20,Others,Commerce,60.00,Comm&Mgmt,No,58.06,Mkt&HR,69.28,Not Placed,NaN
173,174,F,52.00,Others,52.00,Others,Science,55.00,Sci&Tech,No,67.00,Mkt&HR,59.32,Not Placed,NaN
175,176,M,63.00,Others,62.00,Others,Science,65.00,Sci&Tech,No,87.50,Mkt&HR,60.69,Not Placed,NaN
179,180,F,77.80,Central,64.00,Central,Science,64.20,Sci&Tech,No,75.50,Mkt&HR,72.14,Not Placed,NaN
181,182,M,62.00,Central,60.33,Others,Science,64.21,Sci&Tech,No,63.00,Mkt&HR,60.02,Not Placed,NaN
184,185,F,56.28,Others,62.83,Others,Commerce,59.79,Comm&Mgmt,No,60.00,Mkt&HR,57.29,Not Placed,NaN
186,187,F,52.00,Central,64.00,Central,Commerce,61.00,Comm&Mgmt,No,55.00,Mkt&Fin,62.93,Not Placed,NaN
188,189,M,61.80,Others,47.00,Others,Commerce,54.38,Comm&Mgmt,No,57.00,Mkt&Fin,56.13,Not Placed,NaN
189,190,F,54.00,Central,77.60,Others,Commerce,69.20,Comm&Mgmt,No,95.65,Mkt&Fin,66.94,Not Placed,NaN
190,191,F,64.00,Others,70.20,Central,Commerce,61.00,Comm&Mgmt,No,50.00,Mkt&Fin,62.50,Not Placed,NaN
194,195,M,52.00,Others,55.00,Others,Commerce,56.30,Comm&Mgmt,No,59.00,Mkt&Fin,64.74,Not Placed,NaN
198,199,F,67.00,Central,70.00,Central,Commerce,65.00,Others,No,88.00,Mkt&HR,71.96,Not Placed,NaN
201,202,M,54.20,Central,63.00,Others,Science,58.00,Comm&Mgmt,No,79.00,Mkt&HR,58.44,Not Placed,NaN
206,207,M,41.00,Central,42.00,Central,Science,60.00,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed,NaN
208,209,F,43.00,Central,60.00,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [29]:
#Show students who studied in “Others” board in ssc_b.
df[df["ssc_b"]=="Others"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.0,Others,91.0,Others,Commerce,58.00,Sci&Tech,No,55.00,Mkt&HR,58.80,Placed,270000.0
5,6,M,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,F,46.0,Others,49.2,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
19,20,M,60.0,Others,67.0,Others,Arts,70.00,Comm&Mgmt,Yes,50.48,Mkt&Fin,77.89,Placed,236000.0
20,21,M,62.0,Others,65.0,Others,Commerce,66.00,Comm&Mgmt,No,50.00,Mkt&HR,56.70,Placed,265000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,206,M,61.0,Others,62.0,Others,Commerce,65.00,Comm&Mgmt,No,62.00,Mkt&Fin,56.81,Placed,250000.0
210,211,M,80.6,Others,82.0,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.0,Others,60.0,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.0,Others,67.0,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.0,Others,66.0,Others,Commerce,58.00,Comm&Mgmt,No,70.00,Mkt&HR,60.23,Placed,204000.0

In [30]:
#Display students who have exactly 50 in hsc_p.
df[df["hsc_p"]==50]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
106,107,M,61.08,Others,50.0,Others,Science,54.0,Sci&Tech,No,71.0,Mkt&Fin,65.69,Not Placed,NaN
144,145,M,52.00,Others,50.0,Others,Arts,61.0,Comm&Mgmt,No,60.0,Mkt&Fin,58.52,Not Placed,NaN

In [31]:
#Retrieve students whose salary is above average salary.
avg=df["salary"].mean()
df[df["salary"]>avg]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
16,17,M,63.00,Central,66.20,Central,Commerce,65.60,Comm&Mgmt,Yes,60.00,Mkt&Fin,62.54,Placed,300000.0
21,22,F,79.00,Others,76.00,Others,Commerce,85.00,Comm&Mgmt,No,95.00,Mkt&Fin,69.06,Placed,393000.0
22,23,F,69.80,Others,60.80,Others,Science,72.23,Sci&Tech,No,55.53,Mkt&HR,68.81,Placed,360000.0
23,24,F,77.40,Others,60.00,Others,Science,64.74,Sci&Tech,Yes,92.00,Mkt&Fin,63.62,Placed,300000.0
24,25,M,76.50,Others,97.70,Others,Science,78.86,Sci&Tech,No,97.40,Mkt&Fin,74.01,Placed,360000.0
28,29,M,76.76,Others,76.50,Others,Commerce,67.50,Comm&Mgmt,Yes,73.35,Mkt&Fin,64.15,Placed,350000.0
35,36,F,69.00,Central,78.00,Central,Commerce,72.00,Comm&Mgmt,No,71.00,Mkt&HR,62.74,Placed,300000.0
37,38,F,79.00,Central,76.00,Central,Science,65.60,Sci&Tech,No,58.00,Mkt&HR,55.47,Placed,320000.0
39,40,M,81.00,Others,68.00,Others,Science,64.00,Sci&Tech,No,93.00,Mkt&Fin,62.56,Placed,411000.0
43,44,M,87.00,Others,87.00,Others,Commerce,68.00,Comm&Mgmt,No,95.00,Mkt&HR,62.90,Placed,300000.0
53,54,M,80.00,Others,70.00,Others,Science,72.00,Sci&Tech,No,87.00,Mkt&HR,71.04,Placed,450000.0
57,58,M,68.00,Central,76.00,Central,Commerce,74.00,Comm&Mgmt,No,80.00,Mkt&Fin,63.59,Placed,360000.0
61,62,M,84.20,Central,73.40,Central,Commerce,66.89,Comm&Mgmt,No,61.60,Mkt&Fin,62.48,Placed,300000.0
70,71,M,82.00,Others,61.00,Others,Science,62.00,Sci&Tech,No,89.00,Mkt&Fin,65.45,Placed,360000.0
74,75,M,56.60,Central,64.80,Central,Commerce,70.20,Comm&Mgmt,No,84.27,Mkt&Fin,67.20,Placed,336000.0
77,78,M,64.00,Others,80.00,Others,Science,65.00,Sci&Tech,Yes,69.00,Mkt&Fin,57.65,Placed,500000.0
81,82,M,81.70,Others,63.00,Others,Science,67.00,Comm&Mgmt,Yes,86.00,Mkt&Fin,70.20,Placed,300000.0
83,84,M,84.00,Others,79.00,Others,Science,68.00,Sci&Tech,Yes,84.00,Mkt&Fin,66.69,Placed,300000.0
84,85,M,70.00,Central,63.00,Others,Science,70.00,Sci&Tech,Yes,55.00,Mkt&Fin,62.00,Placed,300000.0
85,86,F,83.84,Others,89.83,Others,Commerce,77.20,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
90,91,F,85.00,Others,90.00,Others,Commerce,82.00,Comm&Mgmt,No,92.00,Mkt&Fin,68.03,Placed,300000.0
95,96,M,73.00,Central,78.00,Others,Commerce,65.00,Comm&Mgmt,Yes,95.46,Mkt&Fin,62.16,Placed,420000.0
96,97,F,76.00,Central,70.00,Central,Science,76.00,Comm&Mgmt,Yes,66.00,Mkt&Fin,64.44,Placed,300000.0
101,102,M,63.00,Central,72.00,Central,Commerce,68.00,Comm&Mgmt,No,78.00,Mkt&HR,60.44,Placed,380000.0
102,103,F,77.00,Others,61.00,Others,Commerce,68.00,Comm&Mgmt,Yes,57.50,Mkt&Fin,61.31,Placed,300000.0
104,105,M,69.00,Central,63.00,Others,Science,65.00,Comm&Mgmt,Yes,55.00,Mkt&HR,58.23,Placed,360000.0
108,109,M,61.00,Central,82.00,Central,Commerce,69.00,Comm&Mgmt,No,84.00,Mkt&Fin,58.31,Placed,300000.0
116,117,M,68.20,Central,72.80,Central,Commerce,66.60,Comm&Mgmt,Yes,96.00,Mkt&Fin,70.85,Placed,300000.0
119,120,M,60.80,Central,68.40,Central,Commerce,64.60,Comm&Mgmt,Yes,82.66,Mkt&Fin,64.34,Placed,940000.0
125,126,F,84.00,Central,73.00,Central,Commerce,73.00,Comm&Mgmt,No,75.00,Mkt&Fin,73.33,Placed,350000.0
128,129,M,80.40,Central,73.40,Central,Science,77.72,Sci&Tech,Yes,81.20,Mkt&HR,76.26,Placed,400000.0
131,132,F,74.90,Others,57.00,Others,Science,62.00,Others,Yes,80.00,Mkt&Fin,60.78,Placed,360000.0
132,133,M,67.00,Others,68.00,Others,Commerce,64.00,Comm&Mgmt,Yes,74.40,Mkt&HR,53.49,Placed,300000.0
143,144,M,77.67,Others,64.89,Others,Commerce,70.67,Comm&Mgmt,No,89.00,Mkt&Fin,60.39,Placed,300000.0
145,146,M,89.40,Others,65.66,Others,Science,71.25,Sci&Tech,No,72.00,Mkt&HR,63.23,Placed,400000.0
147,148,M,70.00,Central,74.00,Central,Commerce,65.00,Comm&Mgmt,No,83.00,Mkt&Fin,62.28,Placed,300000.0
150,151,M,71.00,Central,58.66,Central,Science,58.00,Sci&Tech,Yes,56.00,Mkt&Fin,61.30,Placed,690000.0
153,154,M,49.00,Others,59.00,Others,Science,65.00,Sci&Tech,Yes,86.00,Mkt&Fin,62.48,Placed,340000.0
157,158,M,66.50,Central,62.50,Central,Commerce,60.90,Comm&Mgmt,No,93.40,Mkt&Fin,55.03,Placed,300000.0
160,161,M,87.00,Central,74.00,Central,Science,65.00,Sci&Tech,Yes,75.00,Mkt&HR,72.29,Placed,300000.0
163,164,M,63.00,Others,67.00,Others,Science,64.00,Sci&Tech,No,75.00,Mkt&Fin,66.46,Placed,500000.0
171,172,M,80.00,Others,80.00,Others,Commerce,72.00,Comm&Mgmt,Yes,63.79,Mkt&Fin,66.04,Placed,290000.0
172,173,M,73.00,Others,58.00,Others,Commerce,56.00,Comm&Mgmt,No,84.00,Mkt&HR,52.64,Placed,300000.0
174,175,M,73.24,Others,50.83,Others,Science,64.27,Sci&Tech,Yes,64.00,Mkt&Fin,66.23,Placed,500000.0
177,178,F,73.00,Central,97.00,Others,Commerce,79.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,70.81,Placed,650000.0
178,179,M,68.00,Others,56.00,Others,Science,68.00,Sci&Tech,No,73.00,Mkt&HR,68.07,Placed,350000.0
193,194,F,60.00,Central,63.00,Central,Arts,56.00,Others,Yes,80.00,Mkt&HR,56.63,Placed,300000.0
200,201,M,69.00,Others,60.00,Others,Commerce,65.00,Comm&Mgmt,No,87.55,Mkt&Fin,52.81,Placed,300000.0
207,208,M,83.33,Central,78.00,Others,Commerce,61.00,Comm&Mgmt,Yes,88.56,Mkt&Fin,71.55,Placed,300000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0

In [32]:
#Show records where both hsc_p and ssc_p are above 80.
df[(df["hsc_p"]>80) & (df["ssc_p"]>80)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
43,44,M,87.00,Others,87.00,Others,Commerce,68.0,Comm&Mgmt,No,95.00,Mkt&HR,62.90,Placed,300000.0
78,79,M,84.00,Others,90.90,Others,Science,64.5,Sci&Tech,No,86.04,Mkt&Fin,59.42,Placed,270000.0
85,86,F,83.84,Others,89.83,Others,Commerce,77.2,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
90,91,F,85.00,Others,90.00,Others,Commerce,82.0,Comm&Mgmt,No,92.00,Mkt&Fin,68.03,Placed,300000.0
107,108,M,82.00,Others,90.00,Others,Commerce,83.0,Comm&Mgmt,No,80.00,Mkt&HR,73.52,Placed,200000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.6,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0

In [33]:
#Find students with etest_p exactly equal to 100.
df[df["etest_p"]==100]

Empty DataFrame
Columns: [sl_no, gender, ssc_p, ssc_b, hsc_p, hsc_b, hsc_s, degree_p, degree_t, workex, etest_p, specialisation, mba_p, status, salary]
Index: []

In [34]:
#Display students with either hsc_b = “Central” or ssc_b = “Others”.
df[(df["hsc_b"]=="Central") & (df["ssc_b"]=="Others")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
25,26,F,52.58,Others,54.6,Central,Commerce,50.20,Comm&Mgmt,Yes,76.0,Mkt&Fin,65.33,Not Placed,NaN
42,43,M,49.00,Others,39.0,Central,Science,65.00,Others,No,63.0,Mkt&Fin,51.21,Not Placed,NaN
76,77,F,66.50,Others,70.4,Central,Arts,71.93,Comm&Mgmt,No,61.0,Mkt&Fin,64.27,Placed,230000.0
137,138,M,67.00,Others,63.0,Central,Commerce,72.00,Comm&Mgmt,No,56.0,Mkt&HR,60.41,Placed,225000.0
152,153,F,75.40,Others,60.5,Central,Science,84.00,Sci&Tech,No,98.0,Mkt&Fin,65.25,Placed,240000.0
190,191,F,64.00,Others,70.2,Central,Commerce,61.00,Comm&Mgmt,No,50.0,Mkt&Fin,62.50,Not Placed,NaN
191,192,M,67.00,Others,61.0,Central,Science,72.00,Comm&Mgmt,No,72.0,Mkt&Fin,61.01,Placed,264000.0

In [35]:
#Add a new column overall_avg = (ssc_p + hsc_p + degree_p + mba_p) / 4.
df["overall_avg"]=((df["ssc_p"]+df["hsc_p"]+df["degree_p"]+df["mba_p"])/4)

In [36]:
df["overall_avg"]

0      68.7000
1      75.3550
2      63.7000
3      54.8575
4      72.0500
        ...
210    78.6725
211    60.9050
212    69.1800
213    64.5575
214    58.3050
Name: overall_avg, Length: 215, dtype: float64

In [37]:
#Rename the column degree_p to degree_percentage.
df=df.rename(columns={"degree_p":"degree_per"})

In [38]:
#Create a new column placement_status = “Hired” if status = “Placed” else “Not
#Hired”.
df["placement_status"] = df["status"].apply(
    lambda x: "Hired" if x == "Placed" else "Not Hired"
)

In [39]:
df["placement_status"].unique()

array(['Hired', 'Not Hired'], dtype=object)

In [40]:
df["status"].unique()

array(['Placed', 'Not Placed'], dtype=object)

In [41]:
#Drop the column sl_no.
df.drop(columns="sl_no",inplace=True)

In [42]:
#Replace all “Comm&amp;Mgmt” in degree_t with “Commerce”.
df["degree_t"]=df["degree_t"].replace("Comm&Mgmt","Commerce")

In [43]:
df["degree_t"].unique()

array(['Sci&Tech', 'Commerce', 'Others'], dtype=object)

In [44]:
#Convert gender column values “M” → “Male”, “F” → “Female”.
df["gender"]=df["gender"].apply(lambda x: "Male" if x=="M" else "Female")

In [45]:
#Create a new column above_80_ssc = True if ssc_p &gt; 80 else False.
df["above_80_ssc"]=df["ssc_p"].apply(lambda x: "True" if x>80 else "False")

In [46]:
#Round all percentage columns to 1 decimal place.
df["ssc_p"]=df["ssc_p"].round(1)
df["hsc_p"]=df["hsc_p"].round(1)
df["degree_per"]=df["degree_per"].round(1)
df["etest_p"]=df["etest_p"].round(1)
df["mba_p"]=df["mba_p"].round(1)
df["salary"]=df["salary"].round(1)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            215 non-null    object
 1   ssc_p             215 non-null    float64
 2   ssc_b             215 non-null    object
 3   hsc_p             215 non-null    float64
 4   hsc_b             215 non-null    object
 5   hsc_s             215 non-null    object
 6   degree_per        215 non-null    float64
 7   degree_t          215 non-null    object
 8   workex            215 non-null    object
 9   etest_p           215 non-null    float64
 10  specialisation    215 non-null    object
 11  mba_p             215 non-null    float64
 12  status            215 non-null    object
 13  salary            148 non-null    float64
 14  overall_avg       215 non-null    float64
 15  placement_status  215 non-null    object
 16  above_80_ssc      215 non-null    object
dtypes: float64(7), object(10)
memory usage: 28.7+ KB

In [48]:
#Convert all column names to lowercase.
df.columns = df.columns.str.lower()

In [49]:
#Add a new column salary_in_lpa = salary / 100000.
df["salary_in_lpa"]=(df["salary"]/100000)

In [50]:
#Replace NaN values in salary with 0.
df["salary"] = df["salary"].fillna(0)

In [51]:
#Drop all duplicate rows from the dataset.
df.duplicated().sum()

np.int64(0)

In [52]:
#Increase all mba_p scores by 5 points.
df["mba_p"]=(df["mba_p"]+5)

In [53]:
#Convert salary column to integer type.
df["salary"]=df["salary"].astype(int)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            215 non-null    object
 1   ssc_p             215 non-null    float64
 2   ssc_b             215 non-null    object
 3   hsc_p             215 non-null    float64
 4   hsc_b             215 non-null    object
 5   hsc_s             215 non-null    object
 6   degree_per        215 non-null    float64
 7   degree_t          215 non-null    object
 8   workex            215 non-null    object
 9   etest_p           215 non-null    float64
 10  specialisation    215 non-null    object
 11  mba_p             215 non-null    float64
 12  status            215 non-null    object
 13  salary            215 non-null    int64
 14  overall_avg       215 non-null    float64
 15  placement_status  215 non-null    object
 16  above_80_ssc      215 non-null    object
 17  salary_in_lpa     148 non-null    float64
dtypes: float64(7), int64(1), object(10)
memory usage: 30.4+ KB

In [55]:
#Reorder columns to make status the first column.
df = df[["status"] + [col for col in df.columns if col != "status"]]

In [56]:
#Replace all “Yes”/“No” in workex with 1/0.
df["workex"]=df["workex"].apply(lambda x: 1 if x=="Yes" else 0)

In [57]:
df["workex"].unique()

array([0, 1])

In [58]:
#Create a new column performance_tag: “Excellent” if degree_p &gt; 80 else
#“Average”.
df["performance_tag"]=df["degree_per"].apply(lambda x: "Excellent" if x>80 else "Average")

In [59]:
#Standardize all column names to snake_case (e.g., ssc_p → ssc_percentage).
df = df.rename(columns={
    "ssc_p": "ssc_percentage",
    "hsc_p": "hsc_percentage",
    "degree_per": "degree_percentage",
    "etest_p": "etest_percentage",
    "mba_p": "mba_percentage"
})

In [60]:
df.columns

Index(['status', 'gender', 'ssc_percentage', 'ssc_b', 'hsc_percentage',
       'hsc_b', 'hsc_s', 'degree_percentage', 'degree_t', 'workex',
       'etest_percentage', 'specialisation', 'mba_percentage', 'salary',
       'overall_avg', 'placement_status', 'above_80_ssc', 'salary_in_lpa',
       'performance_tag'],
      dtype='object')

In [61]:
#Create a new column combining degree_t and specialisation (e.g.,
#“Sci&amp;Tech_Mkt&amp;HR”).
df["degree_specialisation"] = df["degree_t"] + "_" + df["specialisation"]

In [62]:
#Fill missing etest_p values with mean of that column.
mean=df["etest_percentage"].mean()
df["etest_percentage"]=df["etest_percentage"].fillna(mean)

In [63]:
#Create a new column total_score = ssc_p + hsc_p + degree_p + mba_p.
df["total_score"]=df["ssc_percentage"]+df["hsc_percentage"]+df["degree_percentage"]+df["mba_percentage"]

In [64]:
#Create a boolean column is_placed = True if status = “Placed”.
df["is_placed"]=df["status"].apply(lambda x: True if x=="Placed" else False)

In [65]:
#Add a column mba_grade = “A” if mba_p ≥ 75 else “B”.
df["mba_grade"]=df["mba_percentage"].apply(lambda x: "A" if x>=75 else "B")

In [66]:
#Replace NaN salaries for non-placed students with 0.
df.loc[df["status"] == "Not Placed", "salary"] = 0

In [67]:
#Count how many students are in each gender.
df["gender"].value_counts()

gender
Male      139
Female     76
Name: count, dtype: int64

In [68]:
#Find the average mba_p for each specialisation.
df.groupby(["specialisation"])["mba_percentage"].mean()

specialisation
Mkt&Fin    67.825833
Mkt&HR     66.584211
Name: mba_percentage, dtype: float64

In [69]:
#Get the mean degree_p for placed vs non-placed students.
df.groupby(["status"])["degree_percentage"].mean()

status
Not Placed    61.134328
Placed        68.739865
Name: degree_percentage, dtype: float64

In [70]:
#Find the maximum salary for each specialisation.
df.groupby(["specialisation"])["salary"].max()

specialisation
Mkt&Fin    940000
Mkt&HR     450000
Name: salary, dtype: int64

In [71]:
#Count the number of students with and without workex.
df["workex"].value_counts()

workex
0    141
1     74
Name: count, dtype: int64

In [72]:
#Calculate the average etest_p for each degree_t.
df.groupby(["degree_t"])["etest_percentage"].mean()

degree_t
Commerce    71.986897
Others      72.490909
Sci&Tech    72.310169
Name: etest_percentage, dtype: float64

In [73]:
#Find the total number of placed students per degree_t.
df[df["status"] == "Placed"].groupby("degree_t").size()

degree_t
Commerce    102
Others        5
Sci&Tech     41
dtype: int64

In [74]:
#Get the minimum hsc_p for each hsc_b.
df.groupby(["hsc_b"])["hsc_percentage"].min()

hsc_b
Central    39.0
Others     37.0
Name: hsc_percentage, dtype: float64

In [75]:
#Count of students in each specialisation grouped by gender.
df.groupby(["gender", "specialisation"]).size()

gender  specialisation
Female  Mkt&Fin           37
        Mkt&HR            39
Male    Mkt&Fin           83
        Mkt&HR            56
dtype: int64

In [76]:
#Find the highest mba_p among placed students.
place=df[df["status"]=="Placed"]
place.groupby(["status"])["mba_percentage"].max()

status
Placed    82.9
Name: mba_percentage, dtype: float64

In [77]:
#Calculate mean, min, and max ssc_p for each gender.
df.groupby(["gender"])["ssc_percentage"].mean()

gender
Female    68.311842
Male      66.753237
Name: ssc_percentage, dtype: float64

In [78]:
df.groupby(["gender"])["ssc_percentage"].min()

gender
Female    40.9
Male      41.0
Name: ssc_percentage, dtype: float64

In [79]:
df.groupby(["gender"])["ssc_percentage"].max()

gender
Female    88.0
Male      89.4
Name: ssc_percentage, dtype: float64

In [80]:
# Count how many students have each unique combination of degree_t and workex.
df.groupby(["workex"])["degree_t"].value_counts()

workex  degree_t
0       Commerce    100
        Sci&Tech     34
        Others        7
1       Commerce     45
        Sci&Tech     25
        Others        4
Name: count, dtype: int64

In [81]:
#Find the number of placed students per hsc_b.
df[df["status"]=="Placed"].groupby("hsc_b").size()

hsc_b
Central    57
Others     91
dtype: int64

In [82]:
#Get average salary for each specialisation grouped by workex.
df.groupby(["workex","specialisation"])["salary"].mean()

workex  specialisation
0       Mkt&Fin           197507.246377
        Mkt&HR            134500.000000
1       Mkt&Fin           289470.588235
        Mkt&HR            202000.000000
Name: salary, dtype: float64

In [83]:
#Calculate the average of all numeric columns for each degree_t.
df.groupby("degree_t").mean(numeric_only=True)

,ssc_percentage,hsc_percentage,degree_percentage,workex,etest_percentage,mba_percentage,salary,overall_avg,salary_in_lpa,total_score,is_placed
degree_t,,,,,,,,,,,
Commerce,65.956552,67.184828,66.203448,0.310345,71.986897,66.864138,196000.000000,65.302362,2.786275,266.208966,0.703448
Others,64.227273,60.181818,60.663636,0.363636,72.490909,66.381818,127454.545455,61.612500,2.804000,251.454545,0.454545
Sci&Tech,71.189831,65.386441,67.842373,0.423729,72.310169,68.459322,218627.118644,66.970085,3.146098,272.877966,0.694915

In [84]:
#Find the number of students with etest_p &gt; 80 grouped by workex.
etest=df[df["etest_percentage"]>80]
etest.groupby(["workex"])["etest_percentage"].count()

workex
0    37
1    24
Name: etest_percentage, dtype: int64

In [85]:
#Display count of placed and not placed students per degree_t.
df.groupby(["status"])["degree_t"].count()

status
Not Placed     67
Placed        148
Name: degree_t, dtype: int64

In [86]:
#Show mean mba_p for each specialisation and gender.
df.groupby(["specialisation","gender"])["mba_percentage"].mean()

specialisation  gender
Mkt&Fin         Female    70.902703
                Male      66.454217
Mkt&HR          Female    68.448718
                Male      65.285714
Name: mba_percentage, dtype: float64

In [87]:
#Find how many students from each hsc_b got placed.
df[df["status"]=="Placed"].groupby("hsc_b").size()

hsc_b
Central    57
Others     91
dtype: int64

In [88]:
#Get both min and max salary for each specialisation.
df.groupby(["specialisation"])["salary"].min()

specialisation
Mkt&Fin    0
Mkt&HR     0
Name: salary, dtype: int64

In [89]:
df.groupby(["specialisation"])["salary"].max()

specialisation
Mkt&Fin    940000
Mkt&HR     450000
Name: salary, dtype: int64

In [90]:
#Display number of unique degree_t values for each workex group.
df.groupby(["workex"])["degree_t"].nunique()

workex
0    3
1    3
Name: degree_t, dtype: int64

In [91]:
#Find average degree_p per hsc_b and ssc_b.
df.groupby(["hsc_b","ssc_b"])["degree_percentage"].mean()

hsc_b    ssc_b
Central  Central    65.548052
         Others     68.014286
Others   Central    67.223077
         Others     66.570652
Name: degree_percentage, dtype: float64

In [92]:
#Calculate total number of students grouped by specialisation and status.
df.groupby(["specialisation"])["status"].value_counts()

specialisation  status
Mkt&Fin         Placed        95
                Not Placed    25
Mkt&HR          Placed        53
                Not Placed    42
Name: count, dtype: int64

In [93]:
#Find which degree_t has the highest average placement rate.
df.groupby("degree_t")["status"].apply(lambda x: (x == "Placed").mean() * 100).idxmax()

'Commerce'

In [94]:
#Display how many students scored more than 70 in mba_p for each 
#specialisation.
df[df["mba_percentage"]>70].groupby(["specialisation"]).size()

specialisation
Mkt&Fin    44
Mkt&HR     24
dtype: int64

In [96]:
#Sort dataset by salary in descending order.
df.sort_values(by="salary", ascending=False)

,status,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,...,salary,overall_avg,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_specialisation,total_score,is_placed,mba_grade
119,Placed,Male,60.8,Central,68.4,Central,Commerce,64.6,Commerce,1,...,940000,64.5350,Hired,False,9.4,Average,Commerce_Mkt&Fin,263.1,True,B
150,Placed,Male,71.0,Central,58.7,Central,Science,58.0,Sci&Tech,1,...,690000,62.2400,Hired,False,6.9,Average,Sci&Tech_Mkt&Fin,254.0,True,B
177,Placed,Female,73.0,Central,97.0,Others,Commerce,79.0,Commerce,1,...,650000,79.9525,Hired,False,6.5,Average,Commerce_Mkt&Fin,324.8,True,A
163,Placed,Male,63.0,Others,67.0,Others,Science,64.0,Sci&Tech,0,...,500000,65.1150,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,265.5,True,B
174,Placed,Male,73.2,Others,50.8,Others,Science,64.3,Sci&Tech,1,...,500000,63.6425,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,259.5,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,Not Placed,Female,69.7,Central,47.0,Central,Commerce,72.7,Sci&Tech,0,...,0,62.1600,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,253.6,False,B
175,Not Placed,Male,63.0,Others,62.0,Others,Science,65.0,Sci&Tech,0,...,0,62.6725,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,255.7,False,B
65,Not Placed,Male,54.0,Others,47.0,Others,Science,57.0,Commerce,0,...,0,53.7750,Not Hired,False,NaN,Average,Commerce_Mkt&HR,220.1,False,B
63,Not Placed,Male,61.0,Others,70.0,Others,Commerce,64.0,Commerce,0,...,0,63.6250,Not Hired,False,NaN,Average,Commerce_Mkt&HR,259.5,False,B
214,Not Placed,Male,62.0,Central,58.0,Others,Science,53.0,Commerce,0,...,0,58.3050,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.2,False,B

In [97]:
#Sort by degree_p and then by mba_p.
df.sort_values(by=["degree_percentage", "mba_percentage"])

,status,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,...,salary,overall_avg,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_specialisation,total_score,is_placed,mba_grade
14,Not Placed,Male,62.0,Central,47.0,Central,Commerce,50.0,Commerce,0,...,0,53.4900,Not Hired,False,NaN,Average,Commerce_Mkt&HR,219.0,False,B
25,Not Placed,Female,52.6,Others,54.6,Central,Commerce,50.2,Commerce,1,...,0,55.6775,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,227.7,False,B
91,Not Placed,Male,52.0,Central,57.0,Central,Commerce,50.8,Commerce,0,...,0,55.6475,Not Hired,False,NaN,Average,Commerce_Mkt&HR,227.6,False,B
49,Not Placed,Female,50.0,Others,37.0,Others,Arts,52.0,Others,0,...,0,48.7775,Not Hired,False,NaN,Average,Others_Mkt&HR,200.1,False,B
3,Not Placed,Male,56.0,Central,52.0,Central,Science,52.0,Sci&Tech,0,...,0,54.8575,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.4,False,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Placed,Female,85.0,Others,90.0,Others,Commerce,82.0,Commerce,0,...,300000,81.2575,Hired,True,3.00,Excellent,Commerce_Mkt&Fin,330.0,True,B
107,Placed,Male,82.0,Others,90.0,Others,Commerce,83.0,Commerce,0,...,200000,82.1300,Hired,True,2.00,Excellent,Commerce_Mkt&HR,333.5,True,A
152,Placed,Female,75.4,Others,60.5,Central,Science,84.0,Sci&Tech,0,...,240000,71.2875,Hired,False,2.40,Excellent,Sci&Tech_Mkt&Fin,290.1,True,B
21,Placed,Female,79.0,Others,76.0,Others,Commerce,85.0,Commerce,0,...,393000,77.2650,Hired,False,3.93,Excellent,Commerce_Mkt&Fin,314.1,True,B
197,Placed,Female,84.0,Others,53.0,Others,Science,91.0,Sci&Tech,0,...,260000,74.4175,Hired,True,2.60,Excellent,Sci&Tech_Mkt&HR,302.7,True,B

In [98]:
#Sort all placed students by salary.
df[df["status"]=="Placed"].sort_values(by=["salary"])

,status,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,...,salary,overall_avg,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_specialisation,total_score,is_placed,mba_grade
107,Placed,Male,82.0,Others,90.0,Others,Commerce,83.0,Commerce,0,...,200000,82.1300,Hired,True,2.0,Excellent,Commerce_Mkt&HR,333.5,True,A
1,Placed,Male,79.3,Central,78.3,Others,Science,77.5,Sci&Tech,1,...,200000,75.3550,Hired,False,2.0,Average,Sci&Tech_Mkt&Fin,306.4,True,B
135,Placed,Female,72.0,Central,56.0,Others,Science,69.0,Commerce,0,...,200000,65.6575,Hired,False,2.0,Average,Commerce_Mkt&HR,267.6,True,B
50,Placed,Female,75.2,Central,73.2,Central,Science,68.4,Commerce,0,...,200000,69.9450,Hired,False,2.0,Average,Commerce_Mkt&HR,284.8,True,B
44,Placed,Female,77.0,Others,73.0,Others,Commerce,81.0,Commerce,1,...,200000,75.1750,Hired,False,2.0,Excellent,Commerce_Mkt&Fin,305.7,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,Placed,Male,63.0,Others,67.0,Others,Science,64.0,Sci&Tech,0,...,500000,65.1150,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,265.5,True,B
77,Placed,Male,64.0,Others,80.0,Others,Science,65.0,Sci&Tech,1,...,500000,66.6625,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,271.6,True,B
177,Placed,Female,73.0,Central,97.0,Others,Commerce,79.0,Commerce,1,...,650000,79.9525,Hired,False,6.5,Average,Commerce_Mkt&Fin,324.8,True,A
150,Placed,Male,71.0,Central,58.7,Central,Science,58.0,Sci&Tech,1,...,690000,62.2400,Hired,False,6.9,Average,Sci&Tech_Mkt&Fin,254.0,True,B
119,Placed,Male,60.8,Central,68.4,Central,Commerce,64.6,Commerce,1,...,940000,64.5350,Hired,False,9.4,Average,Commerce_Mkt&Fin,263.1,True,B

In [101]:
#Sort the entire dataset by ssc_p ascending.
df.sort_values(by=["ssc_percentage"])

,status,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,...,salary,overall_avg,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_specialisation,total_score,is_placed,mba_grade
52,Not Placed,Female,40.9,Others,45.8,Others,Commerce,53.0,Commerce,0,...,0,51.3025,Not Hired,False,NaN,Average,Commerce_Mkt&HR,210.2,False,B
206,Not Placed,Male,41.0,Central,42.0,Central,Science,60.0,Commerce,0,...,0,49.0975,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,201.4,False,B
208,Not Placed,Female,43.0,Central,60.0,Others,Science,65.0,Commerce,0,...,0,57.7300,Not Hired,False,NaN,Average,Commerce_Mkt&HR,235.9,False,B
149,Not Placed,Male,44.0,Central,58.0,Central,Arts,55.0,Commerce,1,...,0,53.8850,Not Hired,False,NaN,Average,Commerce_Mkt&HR,220.5,False,B
100,Not Placed,Female,45.0,Others,57.0,Others,Commerce,58.0,Commerce,1,...,0,56.2375,Not Hired,False,NaN,Average,Commerce_Mkt&HR,230.0,False,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,Placed,Male,87.0,Others,87.0,Others,Commerce,68.0,Commerce,0,...,300000,76.2250,Hired,True,3.00,Average,Commerce_Mkt&HR,309.9,True,B
160,Placed,Male,87.0,Central,74.0,Central,Science,65.0,Sci&Tech,1,...,300000,74.5725,Hired,True,3.00,Average,Sci&Tech_Mkt&HR,303.3,True,A
33,Placed,Female,87.0,Others,65.0,Others,Science,81.0,Commerce,1,...,260000,76.4450,Hired,True,2.60,Excellent,Commerce_Mkt&Fin,310.8,True,A
185,Placed,Female,88.0,Central,72.0,Central,Science,78.0,Others,0,...,252000,77.3575,Hired,True,2.52,Average,Others_Mkt&HR,314.4,True,A
145,Placed,Male,89.4,Others,65.7,Others,Science,71.2,Sci&Tech,0,...,400000,72.3850,Hired,True,4.00,Average,Sci&Tech_Mkt&HR,294.5,True,B

In [111]:
#Sort students first by status, then by salary (descending).
df.sort_values(by=["status","salary"],ascending=[True,False])

,status,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,...,salary,overall_avg,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_specialisation,total_score,is_placed,mba_grade
3,Not Placed,Male,56.0,Central,52.0,Central,Science,52.0,Sci&Tech,0,...,0,54.8575,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.4,False,B
5,Not Placed,Male,55.0,Others,49.8,Others,Science,67.2,Sci&Tech,1,...,0,55.9075,Not Hired,False,NaN,Average,Sci&Tech_Mkt&Fin,228.6,False,B
6,Not Placed,Female,46.0,Others,49.2,Others,Commerce,79.0,Commerce,0,...,0,56.8725,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,232.5,False,B
9,Not Placed,Male,58.0,Central,70.0,Central,Commerce,61.0,Commerce,0,...,0,60.3025,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,246.2,False,B
12,Not Placed,Female,47.0,Central,55.0,Others,Science,65.0,Commerce,0,...,0,58.0100,Not Hired,False,NaN,Average,Commerce_Mkt&HR,237.0,False,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,Placed,Female,65.0,Central,75.0,Central,Commerce,69.0,Commerce,1,...,200000,68.4150,Hired,False,2.0,Average,Commerce_Mkt&Fin,278.7,True,B
44,Placed,Female,77.0,Others,73.0,Others,Commerce,81.0,Commerce,1,...,200000,75.1750,Hired,False,2.0,Excellent,Commerce_Mkt&Fin,305.7,True,B
50,Placed,Female,75.2,Central,73.2,Central,Science,68.4,Commerce,0,...,200000,69.9450,Hired,False,2.0,Average,Commerce_Mkt&HR,284.8,True,B
107,Placed,Male,82.0,Others,90.0,Others,Commerce,83.0,Commerce,0,...,200000,82.1300,Hired,True,2.0,Excellent,Commerce_Mkt&HR,333.5,True,A
135,Placed,Female,72.0,Central,56.0,Others,Science,69.0,Commerce,0,...,200000,65.6575,Hired,False,2.0,Average,Commerce_Mkt&HR,267.6,True,B

In [115]:
#Retrieve top 5 students with highest mba_p.
df["mba_percentage"].sort_values(ascending=False).head(5)

19     82.9
128    81.3
85     81.2
167    80.7
165    79.6
Name: mba_percentage, dtype: float64

In [114]:
#Retrieve bottom 10 students with lowest degree_p.
df["degree_percentage"].sort_values().head(10)

14     50.0
25     50.2
91     50.8
34     52.0
49     52.0
3      52.0
52     53.0
214    53.0
106    54.0
93     54.0
Name: degree_percentage, dtype: float64

In [106]:
#Use .nlargest() to get top 5 salaries.
df["salary"].nlargest(5)

119    940000
150    690000
177    650000
77     500000
163    500000
Name: salary, dtype: int64

In [107]:
#Use .nsmallest() to get 3 lowest etest_p values.
df["etest_percentage"].nsmallest(3)

20     50.0
99     50.0
190    50.0
Name: etest_percentage, dtype: float64

In [116]:
#Select rows using .loc[] for index 10 to 20.
df.iloc[10:20]

,status,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,...,salary,overall_avg,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_specialisation,total_score,is_placed,mba_grade
10,Placed,Male,58.0,Central,61.0,Central,Commerce,60.0,Commerce,1,...,260000,59.9625,Hired,False,2.60,Average,Commerce_Mkt&HR,244.8,True,B
11,Placed,Male,69.6,Central,68.4,Central,Commerce,78.3,Commerce,1,...,250000,70.0000,Hired,False,2.50,Average,Commerce_Mkt&Fin,285.0,True,B
12,Not Placed,Female,47.0,Central,55.0,Others,Science,65.0,Commerce,0,...,0,58.0100,Not Hired,False,NaN,Average,Commerce_Mkt&HR,237.0,False,B
13,Placed,Female,77.0,Central,87.0,Central,Commerce,59.0,Commerce,0,...,218000,72.9075,Hired,False,2.18,Average,Commerce_Mkt&Fin,296.6,True,B
14,Not Placed,Male,62.0,Central,47.0,Central,Commerce,50.0,Commerce,0,...,0,53.4900,Not Hired,False,NaN,Average,Commerce_Mkt&HR,219.0,False,B
15,Placed,Female,65.0,Central,75.0,Central,Commerce,69.0,Commerce,1,...,200000,68.4150,Hired,False,2.00,Average,Commerce_Mkt&Fin,278.7,True,B
16,Placed,Male,63.0,Central,66.2,Central,Commerce,65.6,Commerce,1,...,300000,64.3350,Hired,False,3.00,Average,Commerce_Mkt&Fin,262.3,True,B
17,Not Placed,Female,55.0,Central,67.0,Central,Commerce,64.0,Commerce,0,...,0,63.3200,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,258.3,False,B
18,Not Placed,Female,63.0,Central,66.0,Central,Commerce,64.0,Commerce,0,...,0,64.2700,Not Hired,False,NaN,Average,Commerce_Mkt&HR,262.1,False,B
19,Placed,Male,60.0,Others,67.0,Others,Arts,70.0,Commerce,1,...,236000,68.7225,Hired,False,2.36,Average,Commerce_Mkt&Fin,279.9,True,A

In [117]:
#Use .iloc[] to get first 3 columns and first 10 rows.
df.iloc[:10,:3]

       status  gender  ssc_percentage
0      Placed    Male            67.0
1      Placed    Male            79.3
2      Placed    Male            65.0
3  Not Placed    Male            56.0
4      Placed    Male            85.8
5  Not Placed    Male            55.0
6  Not Placed  Female            46.0
7      Placed    Male            82.0
8      Placed    Male            73.0
9  Not Placed    Male            58.0

In [118]:
#Sort dataset alphabetically by degree_t.
df.sort_values(by="degree_t")

,status,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,...,salary,overall_avg,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_specialisation,total_score,is_placed,mba_grade
107,Placed,Male,82.0,Others,90.0,Others,Commerce,83.0,Commerce,0,...,200000,82.1300,Hired,True,2.00,Excellent,Commerce_Mkt&HR,333.5,True,A
120,Not Placed,Male,58.0,Others,40.0,Others,Science,59.0,Commerce,0,...,0,53.9525,Not Hired,False,NaN,Average,Commerce_Mkt&HR,220.8,False,B
122,Placed,Female,66.5,Central,66.8,Central,Arts,69.3,Commerce,1,...,236000,68.4000,Hired,False,2.36,Average,Commerce_Mkt&Fin,278.6,True,A
123,Placed,Male,74.0,Others,59.0,Others,Commerce,73.0,Commerce,1,...,240000,65.6750,Hired,False,2.40,Average,Commerce_Mkt&HR,267.7,True,B
125,Placed,Female,84.0,Central,73.0,Central,Commerce,73.0,Commerce,0,...,350000,75.8325,Hired,True,3.50,Average,Commerce_Mkt&Fin,308.3,True,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,Placed,Female,82.0,Others,64.0,Others,Science,73.0,Sci&Tech,1,...,250000,72.6925,Hired,True,2.50,Average,Sci&Tech_Mkt&Fin,295.8,True,A
53,Placed,Male,80.0,Others,70.0,Others,Science,72.0,Sci&Tech,0,...,450000,73.2600,Hired,False,4.50,Average,Sci&Tech_Mkt&HR,298.0,True,A
128,Placed,Male,80.4,Central,73.4,Central,Science,77.7,Sci&Tech,1,...,400000,76.9450,Hired,True,4.00,Average,Sci&Tech_Mkt&HR,312.8,True,A
173,Not Placed,Female,52.0,Others,52.0,Others,Science,55.0,Sci&Tech,0,...,0,54.5800,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,223.3,False,B
0,Placed,Male,67.0,Others,91.0,Others,Commerce,58.0,Sci&Tech,0,...,270000,68.7000,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.8,True,B

In [120]:
#Display all columns except sl_no and salary.
df.drop(columns=["salary"])

,status,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,...,mba_percentage,overall_avg,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_specialisation,total_score,is_placed,mba_grade
0,Placed,Male,67.0,Others,91.0,Others,Commerce,58.0,Sci&Tech,0,...,63.8,68.7000,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.8,True,B
1,Placed,Male,79.3,Central,78.3,Others,Science,77.5,Sci&Tech,1,...,71.3,75.3550,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.4,True,B
2,Placed,Male,65.0,Central,68.0,Central,Arts,64.0,Commerce,0,...,62.8,63.7000,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.8,True,B
3,Not Placed,Male,56.0,Central,52.0,Central,Science,52.0,Sci&Tech,0,...,64.4,54.8575,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.4,False,B
4,Placed,Male,85.8,Central,73.6,Central,Commerce,73.3,Commerce,0,...,60.5,72.0500,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.2,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,Male,80.6,Others,82.0,Others,Commerce,77.6,Commerce,0,...,79.5,78.6725,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.7,True,A
211,Placed,Male,58.0,Others,60.0,Others,Science,72.0,Sci&Tech,0,...,58.6,60.9050,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.6,True,B
212,Placed,Male,67.0,Others,67.0,Others,Commerce,73.0,Commerce,1,...,74.7,69.1800,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.7,True,B
213,Placed,Female,74.0,Others,66.0,Others,Commerce,58.0,Commerce,0,...,65.2,64.5575,Hired,False,2.04,Average,Commerce_Mkt&HR,263.2,True,B
214,Not Placed,Male,62.0,Central,58.0,Others,Science,53.0,Commerce,0,...,65.2,58.3050,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.2,False,B

In [121]:
#Select only gender, status, salary, and specialisation columns.
df[["gender", "status", "salary", "specialisation"]]

     gender      status  salary specialisation
0      Male      Placed  270000         Mkt&HR
1      Male      Placed  200000        Mkt&Fin
2      Male      Placed  250000        Mkt&Fin
3      Male  Not Placed       0         Mkt&HR
4      Male      Placed  425000        Mkt&Fin
..      ...         ...     ...            ...
210    Male      Placed  400000        Mkt&Fin
211    Male      Placed  275000        Mkt&Fin
212    Male      Placed  295000        Mkt&Fin
213  Female      Placed  204000         Mkt&HR
214    Male  Not Placed       0         Mkt&HR

[215 rows x 4 columns]

In [122]:
#Filter dataset for first and last 5 rows together.
pd.concat([df.head(5), df.tail(5)])

,status,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,...,salary,overall_avg,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_specialisation,total_score,is_placed,mba_grade
0,Placed,Male,67.0,Others,91.0,Others,Commerce,58.0,Sci&Tech,0,...,270000,68.7000,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.8,True,B
1,Placed,Male,79.3,Central,78.3,Others,Science,77.5,Sci&Tech,1,...,200000,75.3550,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.4,True,B
2,Placed,Male,65.0,Central,68.0,Central,Arts,64.0,Commerce,0,...,250000,63.7000,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.8,True,B
3,Not Placed,Male,56.0,Central,52.0,Central,Science,52.0,Sci&Tech,0,...,0,54.8575,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.4,False,B
4,Placed,Male,85.8,Central,73.6,Central,Commerce,73.3,Commerce,0,...,425000,72.0500,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.2,True,B
210,Placed,Male,80.6,Others,82.0,Others,Commerce,77.6,Commerce,0,...,400000,78.6725,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.7,True,A
211,Placed,Male,58.0,Others,60.0,Others,Science,72.0,Sci&Tech,0,...,275000,60.9050,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.6,True,B
212,Placed,Male,67.0,Others,67.0,Others,Commerce,73.0,Commerce,1,...,295000,69.1800,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.7,True,B
213,Placed,Female,74.0,Others,66.0,Others,Commerce,58.0,Commerce,0,...,204000,64.5575,Hired,False,2.04,Average,Commerce_Mkt&HR,263.2,True,B
214,Not Placed,Male,62.0,Central,58.0,Others,Science,53.0,Commerce,0,...,0,58.3050,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.2,False,B

In [123]:
df = df[sorted(df.columns)]

In [125]:
#Sort dataset based on the rounded value of etest_p.
df.sort_values(by="etest_percentage", key=round)

,above_80_ssc,degree_percentage,degree_specialisation,degree_t,etest_percentage,gender,hsc_b,hsc_percentage,hsc_s,is_placed,...,performance_tag,placement_status,salary,salary_in_lpa,specialisation,ssc_b,ssc_percentage,status,total_score,workex
99,False,63.0,Sci&Tech_Mkt&Fin,Sci&Tech,50.0,Male,Others,82.0,Commerce,False,...,Average,Not Hired,0,NaN,Mkt&Fin,Central,54.0,Not Placed,263.5,0
20,False,66.0,Commerce_Mkt&HR,Commerce,50.0,Male,Others,65.0,Commerce,True,...,Average,Hired,265000,2.65,Mkt&HR,Others,62.0,Placed,254.7,0
190,False,61.0,Commerce_Mkt&Fin,Commerce,50.0,Female,Central,70.2,Commerce,False,...,Average,Not Hired,0,NaN,Mkt&Fin,Others,64.0,Not Placed,262.7,0
19,False,70.0,Commerce_Mkt&Fin,Commerce,50.5,Male,Others,67.0,Arts,True,...,Average,Hired,236000,2.36,Mkt&Fin,Others,60.0,Placed,279.9,1
32,False,66.4,Commerce_Mkt&HR,Commerce,50.9,Female,Central,81.0,Commerce,True,...,Average,Hired,278000,2.78,Mkt&HR,Central,61.0,Placed,275.6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,False,78.0,Sci&Tech_Mkt&HR,Sci&Tech,97.0,Male,Central,80.0,Science,True,...,Average,Hired,276000,2.76,Mkt&HR,Central,76.0,Placed,309.5,1
24,False,78.9,Sci&Tech_Mkt&Fin,Sci&Tech,97.4,Male,Others,97.7,Science,True,...,Average,Hired,360000,3.60,Mkt&Fin,Others,76.5,Placed,332.1,0
206,False,60.0,Commerce_Mkt&Fin,Commerce,97.0,Male,Central,42.0,Science,False,...,Average,Not Hired,0,NaN,Mkt&Fin,Central,41.0,Not Placed,201.4,0
4,True,73.3,Commerce_Mkt&Fin,Commerce,96.8,Male,Central,73.6,Commerce,True,...,Average,Hired,425000,4.25,Mkt&Fin,Central,85.8,Placed,293.2,0
152,False,84.0,Sci&Tech_Mkt&Fin,Sci&Tech,98.0,Female,Central,60.5,Science,True,...,Excellent,Hired,240000,2.40,Mkt&Fin,Others,75.4,Placed,290.1,0

In [127]:
#Extract all rows with even index numbers only.
df[df.index % 2 == 0]

,above_80_ssc,degree_percentage,degree_specialisation,degree_t,etest_percentage,gender,hsc_b,hsc_percentage,hsc_s,is_placed,...,performance_tag,placement_status,salary,salary_in_lpa,specialisation,ssc_b,ssc_percentage,status,total_score,workex
False,False,77.5,Sci&Tech_Mkt&Fin,Sci&Tech,86.5,Male,Others,78.3,Science,True,...,Average,Hired,200000,2.00,Mkt&Fin,Central,79.3,Placed,306.4,1
False,False,52.0,Sci&Tech_Mkt&HR,Sci&Tech,66.0,Male,Central,52.0,Science,False,...,Average,Not Hired,0,NaN,Mkt&HR,Central,56.0,Not Placed,224.4,0
False,False,67.2,Sci&Tech_Mkt&Fin,Sci&Tech,55.0,Male,Others,49.8,Science,False,...,Average,Not Hired,0,NaN,Mkt&Fin,Others,55.0,Not Placed,228.6,1
False,True,66.0,Sci&Tech_Mkt&Fin,Sci&Tech,67.0,Male,Central,64.0,Science,True,...,Average,Hired,252000,2.52,Mkt&Fin,Central,82.0,Placed,279.1,1
False,False,61.0,Commerce_Mkt&Fin,Commerce,54.0,Male,Central,70.0,Commerce,False,...,Average,Not Hired,0,NaN,Mkt&Fin,Central,58.0,Not Placed,246.2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
False,False,65.0,Commerce_Mkt&Fin,Commerce,62.0,Male,Others,62.0,Commerce,True,...,Average,Hired,250000,2.50,Mkt&Fin,Others,61.0,Placed,249.8,0
False,True,61.0,Commerce_Mkt&Fin,Commerce,88.6,Male,Others,78.0,Commerce,True,...,Average,Hired,300000,3.00,Mkt&Fin,Central,83.3,Placed,298.9,1
False,False,65.0,Commerce_Mkt&Fin,Commerce,67.0,Male,Central,72.0,Commerce,True,...,Average,Hired,216000,2.16,Mkt&Fin,Central,62.0,Placed,260.5,0
False,False,72.0,Sci&Tech_Mkt&Fin,Sci&Tech,74.0,Male,Others,60.0,Science,True,...,Average,Hired,275000,2.75,Mkt&Fin,Others,58.0,Placed,248.6,0
False,False,58.0,Commerce_Mkt&HR,Commerce,70.0,Female,Others,66.0,Commerce,True,...,Average,Hired,204000,2.04,Mkt&HR,Others,74.0,Placed,263.2,0

In [128]:
#Concatenate two subsets: one for Placed and one for Not Placed.
placed = df[df["status"] == "Placed"]
not_placed = df[df["status"] == "Not Placed"]

pd.concat([placed, not_placed])

,above_80_ssc,degree_percentage,degree_specialisation,degree_t,etest_percentage,gender,hsc_b,hsc_percentage,hsc_s,is_placed,...,performance_tag,placement_status,salary,salary_in_lpa,specialisation,ssc_b,ssc_percentage,status,total_score,workex
True,False,58.0,Sci&Tech_Mkt&HR,Sci&Tech,55.0,Male,Others,91.0,Commerce,True,...,Average,Hired,270000,2.70,Mkt&HR,Others,67.0,Placed,279.8,0
False,False,77.5,Sci&Tech_Mkt&Fin,Sci&Tech,86.5,Male,Others,78.3,Science,True,...,Average,Hired,200000,2.00,Mkt&Fin,Central,79.3,Placed,306.4,1
True,False,64.0,Commerce_Mkt&Fin,Commerce,75.0,Male,Central,68.0,Arts,True,...,Average,Hired,250000,2.50,Mkt&Fin,Central,65.0,Placed,259.8,0
True,True,73.3,Commerce_Mkt&Fin,Commerce,96.8,Male,Central,73.6,Commerce,True,...,Average,Hired,425000,4.25,Mkt&Fin,Central,85.8,Placed,293.2,0
False,True,66.0,Sci&Tech_Mkt&Fin,Sci&Tech,67.0,Male,Central,64.0,Science,True,...,Average,Hired,252000,2.52,Mkt&Fin,Central,82.0,Placed,279.1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
True,False,65.0,Others_Mkt&HR,Others,88.0,Female,Central,70.0,Commerce,False,...,Average,Not Hired,0,NaN,Mkt&HR,Central,67.0,Not Placed,279.0,0
False,False,58.0,Commerce_Mkt&HR,Commerce,79.0,Male,Others,63.0,Science,False,...,Average,Not Hired,0,NaN,Mkt&HR,Central,54.2,Not Placed,238.6,0
True,False,60.0,Commerce_Mkt&Fin,Commerce,97.0,Male,Central,42.0,Science,False,...,Average,Not Hired,0,NaN,Mkt&Fin,Central,41.0,Not Placed,201.4,0
True,False,65.0,Commerce_Mkt&HR,Commerce,92.7,Female,Others,60.0,Science,False,...,Average,Not Hired,0,NaN,Mkt&HR,Central,43.0,Not Placed,235.9,0
True,False,53.0,Commerce_Mkt&HR,Commerce,89.0,Male,Others,58.0,Science,False,...,Average,Not Hired,0,NaN,Mkt&HR,Central,62.0,Not Placed,238.2,0

In [129]:
df1 = df[["gender", "salary"]]
df2 = df[["gender", "mba_percentage"]]

pd.merge(df1, df2, on="gender")

      gender  salary  mba_percentage
0       Male  270000            63.8
1       Male  270000            71.3
2       Male  270000            62.8
3       Male  270000            64.4
4       Male  270000            60.5
...      ...     ...             ...
25092   Male       0            61.5
25093   Male       0            79.5
25094   Male       0            58.6
25095   Male       0            74.7
25096   Male       0            65.2

[25097 rows x 3 columns]

In [130]:
#Sort records by specialisation and then by descending degree_p.
df.sort_values(by=["specialisation","degree_percentage"],ascending=[True,False])

,above_80_ssc,degree_percentage,degree_specialisation,degree_t,etest_percentage,gender,hsc_b,hsc_percentage,hsc_s,is_placed,...,performance_tag,placement_status,salary,salary_in_lpa,specialisation,ssc_b,ssc_percentage,status,total_score,workex
False,False,85.0,Commerce_Mkt&Fin,Commerce,95.0,Female,Others,76.0,Commerce,True,...,Excellent,Hired,393000,3.93,Mkt&Fin,Others,79.0,Placed,314.1,0
True,False,84.0,Sci&Tech_Mkt&Fin,Sci&Tech,98.0,Female,Central,60.5,Science,True,...,Excellent,Hired,240000,2.40,Mkt&Fin,Others,75.4,Placed,290.1,0
True,True,82.0,Commerce_Mkt&Fin,Commerce,92.0,Female,Others,90.0,Commerce,True,...,Excellent,Hired,300000,3.00,Mkt&Fin,Others,85.0,Placed,330.0,0
False,True,81.0,Commerce_Mkt&Fin,Commerce,88.0,Female,Others,65.0,Science,True,...,Excellent,Hired,260000,2.60,Mkt&Fin,Others,87.0,Placed,310.8,1
True,False,81.0,Commerce_Mkt&Fin,Commerce,89.0,Female,Others,73.0,Commerce,True,...,Excellent,Hired,200000,2.00,Mkt&Fin,Others,77.0,Placed,305.7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
False,False,52.0,Sci&Tech_Mkt&HR,Sci&Tech,66.0,Male,Central,52.0,Science,False,...,Average,Not Hired,0,NaN,Mkt&HR,Central,56.0,Not Placed,224.4,0
True,False,52.0,Others_Mkt&HR,Others,68.4,Male,Others,51.0,Science,False,...,Average,Not Hired,0,NaN,Mkt&HR,Others,62.0,Not Placed,232.8,0
False,False,52.0,Others_Mkt&HR,Others,65.0,Female,Others,37.0,Arts,False,...,Average,Not Hired,0,NaN,Mkt&HR,Others,50.0,Not Placed,200.1,0
False,False,50.8,Commerce_Mkt&HR,Commerce,67.0,Male,Central,57.0,Commerce,False,...,Average,Not Hired,0,NaN,Mkt&HR,Central,52.0,Not Placed,227.6,0
True,False,50.0,Commerce_Mkt&HR,Commerce,76.0,Male,Central,47.0,Commerce,False,...,Average,Not Hired,0,NaN,Mkt&HR,Central,62.0,Not Placed,219.0,0

In [131]:
df.nlargest(10, "salary")[["gender", "degree_t", "specialisation", "salary"]]

       gender  degree_t specialisation  salary
False    Male  Commerce        Mkt&Fin  940000
True     Male  Sci&Tech        Mkt&Fin  690000
False  Female  Commerce        Mkt&Fin  650000
False    Male  Sci&Tech        Mkt&Fin  500000
False    Male  Sci&Tech        Mkt&Fin  500000
True     Male  Sci&Tech        Mkt&Fin  500000
False    Male  Sci&Tech         Mkt&HR  450000
True     Male  Commerce        Mkt&Fin  425000
False    Male  Commerce        Mkt&Fin  420000
False    Male  Sci&Tech        Mkt&Fin  411000