# Pandas- Data Manipulation

### Datasets-Matches,deliveries

In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv("matches.csv")
df1

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [3]:
df2=pd.read_csv("deliveries.csv")
df2

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [4]:
df1.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [5]:
df2.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [6]:
#Join matches and deliveries to find total balls bowled per match.
res=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")
total_balls=res.groupby("id")["ball"].count().reset_index()
total_balls

           id  ball
0      335982   225
1      335983   248
2      335984   219
3      335985   246
4      335986   240
...       ...   ...
1090  1426307   247
1091  1426309   208
1092  1426310   241
1093  1426311   251
1094  1426312   184

[1095 rows x 2 columns]

In [7]:
#For each match, get total runs scored by joining matches and deliveries.
new1=df1[["id"]]
new2=df2[["match_id","total_runs"]]
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")
res.groupby("id")["total_runs"].sum().reset_index()

           id  total_runs
0      335982         304
1      335983         447
2      335984         261
3      335985         331
4      335986         222
...       ...         ...
1090  1426307         429
1091  1426309         323
1092  1426310         346
1093  1426311         314
1094  1426312         227

[1095 rows x 2 columns]

In [8]:
#Find the top 10 highest-scoring matches.
res=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")
res.groupby(["id"])["total_runs"].sum().sort_values(ascending=False).head(10)

id
1426268    549
1426280    523
1422126    523
1426281    504
419137     469
1426273    465
1136604    459
1359512    458
1082641    453
1216527    449
Name: total_runs, dtype: int64

In [9]:
#Find the number of wickets per match using join.
res=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")
wickets=res[res["is_wicket"]==1]
wickets.groupby(["id"])["is_wicket"].count()

id
335982     13
335983      9
335984      9
335985     12
335986     15
           ..
1426307    11
1426309    12
1426310    14
1426311    16
1426312    12
Name: is_wicket, Length: 1095, dtype: int64

In [10]:
#List matches where more than 15 wides were bowled.
#df2-extras_type-wides
res=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")
wide=res[res["extras_type"]=="wides"]
wide_count=wide.groupby(["id"])["extras_type"].count()
wide_count[wide_count>15].reset_index()

         id  extras_type
0    336018           18
1    392190           16
2    501221           16
3    548377           19
4    829737           20
5    829811           16
6   1178423           16
7   1216522           18
8   1254069           16
9   1304049           19
10  1304076           19
11  1304084           17
12  1304098           16
13  1359480           16
14  1359516           19
15  1422119           17
16  1422134           18
17  1426268           24
18  1426269           18
19  1426288           18
20  1426305           18

In [11]:
#Find the player with the most deliveries faced across all matches.
deliveries_count=df2.groupby("batter")["ball"].count()
deliveries_count.sort_values(ascending=False).head(1)

batter
V Kohli    6236
Name: ball, dtype: int64

In [12]:
#Find total boundaries (4s &amp; 6s) per match by joining datasets.
def boundaries(df1,df2):
    res=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")

    boundaries=res[res["batsman_runs"]==4 | (res["batsman_runs"]==6)]
    result=boundaries.groupby("id")["batsman_runs"].count()
    return result
boundaries(df1,df2)

id
335982      66
335983      98
335984      80
335985      99
335986      67
          ...
1426307     94
1426309     74
1426310    103
1426311     91
1426312     57
Name: batsman_runs, Length: 1095, dtype: int64

In [13]:
#Combine matches and deliveries to compute strike rate of each batsman
#in each match.
#Strike Rate = (Runs scored / Balls faced) × 100
res=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")
result=res.groupby(["id","batter"]).agg({"batsman_runs":"sum","ball":"count"})
result["strike_rate"]=(result["batsman_runs"]/result["ball"])*100
result

                       batsman_runs  ball  strike_rate
id      batter
335982  AA Noffke                 9    12    75.000000
        B Akhil                   0     2     0.000000
        BB McCullum             158    77   205.194805
        CL White                  6    10    60.000000
        DJ Hussey                12    12   100.000000
...                             ...   ...          ...
1426312 SP Narine                 6     2   300.000000
        SS Iyer                   6     3   200.000000
        Shahbaz Ahmed             8     7   114.285714
        TM Head                   0     1     0.000000
        VR Iyer                  52    27   192.592593

[16515 rows x 3 columns]

In [14]:
#For each season, get total runs scored (join matches → deliveries).
res=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")
res.groupby(["season"])["total_runs"].sum().reset_index()

     season  total_runs
0   2007/08       17937
1      2009       16353
2   2009/10       18883
3      2011       21154
4      2012       22453
5      2013       22602
6      2014       18931
7      2015       18353
8      2016       18862
9      2017       18786
10     2018       19901
11     2019       19434
12  2020/21       19416
13     2021       18637
14     2022       24395
15     2023       25688
16     2024       25971

In [15]:
#For each season, find total wickets taken.
res=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")
wickets=res[res["is_wicket"]==1]
wickets.groupby(["season"])["is_wicket"].sum().reset_index()

     season  is_wicket
0   2007/08        690
1      2009        698
2   2009/10        725
3      2011        813
4      2012        858
5      2013        912
6      2014        674
7      2015        691
8      2016        666
9      2017        711
10     2018        722
11     2019        685
12  2020/21        677
13     2021        717
14     2022        912
15     2023        916
16     2024        883

In [16]:
#Find bowlers who conceded more than 50 runs in a match.
res = pd.merge(df1, df2, left_on="id", right_on="match_id", how="inner")

runs = res.groupby(["id", "bowler"])["total_runs"].sum()

runs[runs > 50]

id       bowler
335982   JH Kallis              52
335983   JR Hopes               54
335989   JDP Oram               53
         P Amarnath             57
335990   MM Patel               55
                                ..
1426297  Simarjeet Singh        60
1426300  Kuldeep Yadav          53
1426302  Naveen-ul-Haq          51
1426306  SN Thakur              62
1426307  Nithish Kumar Reddy    54
Name: total_runs, Length: 283, dtype: int64

In [17]:
# For each match, find the dismissal types that occurred.
df2.groupby("match_id")["dismissal_kind"].unique()

match_id
335982                        [nan, caught, bowled, run out]
335983                            [nan, caught, bowled, lbw]
335984                   [nan, caught, run out, lbw, bowled]
335985     [nan, caught, retired hurt, run out, stumped, ...
335986                   [nan, caught, bowled, run out, lbw]
                                 ...
1426307                       [nan, caught, run out, bowled]
1426309                  [nan, bowled, caught, run out, lbw]
1426310              [nan, caught, bowled, stumped, run out]
1426311                       [nan, caught, bowled, run out]
1426312                           [nan, bowled, caught, lbw]
Name: dismissal_kind, Length: 1095, dtype: object

In [18]:
#Find batsmen who scored more than 30 runs in a single over.
res=df2.groupby(["match_id","over","batter"])["batsman_runs"].sum()
res[res > 30]

match_id  over  batter
501247    2     CH Gayle      36
734047    5     SK Raina      32
1254076   19    RA Jadeja     36
1304060   15    PJ Cummins    34
1422138   19    R Shepherd    32
Name: batsman_runs, dtype: int64

In [19]:
#For each batting team, compute total runs in each match.
res=df2.groupby(["match_id","batting_team"])["total_runs"].sum()
res.reset_index()

      match_id                 batting_team  total_runs
0       335982        Kolkata Knight Riders         222
1       335982  Royal Challengers Bangalore          82
2       335983          Chennai Super Kings         240
3       335983              Kings XI Punjab         207
4       335984             Delhi Daredevils         132
...        ...                          ...         ...
2182   1426310  Royal Challengers Bengaluru         172
2183   1426311             Rajasthan Royals         139
2184   1426311          Sunrisers Hyderabad         175
2185   1426312        Kolkata Knight Riders         114
2186   1426312          Sunrisers Hyderabad         113

[2187 rows x 3 columns]

In [20]:
#For each bowling team, compute total runs conceded in each match.
res=df2.groupby(["match_id","bowling_team"])["total_runs"].sum()
res

match_id  bowling_team
335982    Kolkata Knight Riders           82
          Royal Challengers Bangalore    222
335983    Chennai Super Kings            207
          Kings XI Punjab                240
335984    Delhi Daredevils               129
                                        ...
1426310   Royal Challengers Bengaluru    174
1426311   Rajasthan Royals               175
          Sunrisers Hyderabad            139
1426312   Kolkata Knight Riders          113
          Sunrisers Hyderabad            114
Name: total_runs, Length: 2187, dtype: int64

In [21]:
#Identify matches where the winning team scored more runs in
#powerplay (overs 1–6).
powerplay = df2[df2["over"] <= 5]
res = pd.merge(df1, df2, left_on="id", right_on="match_id", how="inner")

winning_team=res[res["batting_team"]==res["winner"]]
winning_team.groupby(["id"])["total_runs"].sum()

id
335982     222
335983     240
335984     132
335985     166
335986     112
          ...
1426307    215
1426309    164
1426310    174
1426311    175
1426312    114
Name: total_runs, Length: 1090, dtype: int64

In [22]:
#For each match, find the bowler with the most dot balls.
dot_balls=df2[df2["total_runs"]==0]
dot_balls.groupby(["match_id","bowler"])["total_runs"].count().sort_values(ascending=False)

match_id  bowler
392233    MM Patel          19
1304082   Umran Malik       19
1304052   HV Patel          19
392226    A Nehra           19
1359518   Mohammed Shami    19
                            ..
1422138   Lalit Yadav        1
          Mohammad Nabi      1
598062    J Botha            1
548309    BJ Hodge           1
1136580   DJ Hooda           1
Name: total_runs, Length: 12649, dtype: int64

In [23]:
#For each match, find the batsman with the highest strike rate (min 10
#balls).
result = df2.groupby(["match_id", "batter"]).agg({
    "batsman_runs": "sum",
    "ball": "count"
})

result = result[result["ball"] >= 10]

result["strike_rate"] = (result["batsman_runs"] / result["ball"]) * 100

result

                              batsman_runs  ball  strike_rate
match_id batter
335982   AA Noffke                       9    12    75.000000
         BB McCullum                   158    77   205.194805
         CL White                        6    10    60.000000
         DJ Hussey                      12    12   100.000000
         MV Boucher                      7    11    63.636364
...                                    ...   ...          ...
1426312  Nithish Kumar Reddy            13    10   130.000000
         PJ Cummins                     24    19   126.315789
         RA Tripathi                     9    16    56.250000
         Rahmanullah Gurbaz             39    35   111.428571
         VR Iyer                        52    27   192.592593

[9296 rows x 3 columns]

In [24]:
#Calculate the economy of each bowler per season (join deliveries →
#matches).
result=pd.merge(df1,df2,left_on="id",right_on="match_id",how="inner")
result["bowler_runs"]=result["total_runs"]-result["batsman_runs"]
res = result.groupby(["season", "bowler"]).agg({
    "bowler_runs": "sum",
    "ball": "count"
})
res["economy"] = (res["bowler_runs"] / res["ball"]) * 6
res

                           bowler_runs  ball   economy
season  bowler
2007/08 A Kumble                    20   236  0.508475
        A Mishra                     6   123  0.292683
        A Nehra                     21   280  0.450000
        A Nel                        0    18  0.000000
        A Symonds                   12    44  1.636364
...                                ...   ...       ...
2024    Washington Sundar            0    30  0.000000
        YS Chahal                   17   362  0.281768
        Yash Dayal                  38   322  0.708075
        Yash Thakur                 15   225  0.400000
        Yudhvir Singh                0    24  0.000000

[1948 rows x 3 columns]

In [25]:
#Find bowlers who bowled maiden overs in a match.
new=df2[["match_id","inning","bowler","over","total_runs"]]
maiden=new.groupby(["match_id","inning","bowler","over"])["total_runs"].sum()

maiden=maiden[maiden==0]
maiden

match_id  inning  bowler         over
335984    1       GD McGrath     2       0
335986    1       I Sharma       3       0
335991    2       IK Pathan      19      0
335992    1       SK Warne       11      0
335997    1       ST Jayasuriya  13      0
                                        ..
1426292   2       Harshit Rana   16      0
1426293   2       PJ Cummins     3       0
1426300   2       Yash Dayal     19      0
1426312   1       AD Russell     18      0
                  Harshit Rana   14      0
Name: total_runs, Length: 331, dtype: int64

In [26]:
#For each match, find the over with the most runs.
result=df2.groupby(["match_id","over"])["total_runs"].sum()
result=result.groupby("match_id").idxmax()
result

match_id
335982      (335982, 14)
335983      (335983, 19)
335984       (335984, 3)
335985      (335985, 17)
335986      (335986, 16)
               ...
1426307    (1426307, 11)
1426309    (1426309, 13)
1426310     (1426310, 3)
1426311     (1426311, 5)
1426312     (1426312, 5)
Name: total_runs, Length: 1095, dtype: object

In [27]:
#For each match, identify bowlers who took multiple wickets.
res=df2.groupby(['match_id', 'bowler'])['is_wicket'].sum().reset_index()
res=res[res["is_wicket"]>1]
res

       match_id         bowler  is_wicket
1        335982     AB Agarkar          3
2        335982       AB Dinda          2
9        335982     SC Ganguly          3
12       335983      IK Pathan          2
27       335984    MF Maharoof          2
...         ...            ...        ...
12962   1426311  Shahbaz Ahmed          3
12964   1426311       TA Boult          3
12966   1426312     AD Russell          3
12970   1426312   Harshit Rana          2
12972   1426312       MA Starc          2

[3560 rows x 3 columns]

In [28]:
#Get number of balls faced by each batsman in winning matches only.
res = pd.merge(df2, df1, left_on='match_id', right_on='id',how='inner')

result = res[res['batting_team'] == res['winner']]

result.groupby(['batter'])['ball'].count()

batter
A Ashish Reddy     80
A Badoni          194
A Chopra           51
A Flintoff         14
A Kumble            5
                 ...
Yash Dayal          1
Yashpal Singh      20
Yudhvir Singh       1
Yuvraj Singh      887
Z Khan              5
Name: ball, Length: 496, dtype: int64

In [29]:
#Total extras conceded by each team per season.
new1=df1[["id","season"]]
new2=df2[["match_id","bowling_team","extra_runs"]]
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")
res.groupby(["season","bowling_team"])["extra_runs"].sum()

season   bowling_team
2007/08  Chennai Super Kings            160
         Deccan Chargers                145
         Delhi Daredevils               118
         Kings XI Punjab                142
         Kolkata Knight Riders          152
                                       ...
2024     Mumbai Indians                 150
         Punjab Kings                   132
         Rajasthan Royals               133
         Royal Challengers Bengaluru    151
         Sunrisers Hyderabad            146
Name: extra_runs, Length: 146, dtype: int64

In [30]:
#Identify umpires officiating in matches with > 200 total runs.
new1=df1[["id","umpire1","umpire2"]]
new2=df2[["match_id","total_runs"]]
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")
result=res.groupby(["match_id"])["total_runs"].sum()
result = result[result > 200].reset_index()
final=pd.merge(result,new1,left_on="match_id",right_on="id",how="inner")
final[["match_id", "total_runs", "umpire1", "umpire2"]]

      match_id  total_runs                umpire1               umpire2
0       335982         304              Asad Rauf           RE Koertzen
1       335983         447              MR Benson            SL Shastri
2       335984         261              Aleem Dar        GA Pratapkumar
3       335985         331               SJ Davis             DJ Harper
4       335986         222              BF Bowden           K Hariharan
...        ...         ...                    ...                   ...
1050   1426307         429            Nitin Menon             VK Sharma
1051   1426309         323           AK Chaudhary              R Pandit
1052   1426310         346  KN Ananthapadmanabhan  MV Saidharshan Kumar
1053   1426311         314            Nitin Menon             VK Sharma
1054   1426312         227          J Madanagopal           Nitin Menon

[1055 rows x 4 columns]

In [31]:
#Find the batsman who scored the highest runs in matches won by chasing.
new1=df1[["id","winner","result"]]
new2=df2[["match_id","batting_team","batter","batsman_runs"]]
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")
matches_won=res[res["batting_team"]==res["winner"]]
matches_won = matches_won[matches_won["result"] == "wickets"]
runs = matches_won.groupby("batter")["batsman_runs"].sum()
runs.idxmax()

'S Dhawan'

In [32]:
df1["result"].unique()

array(['runs', 'wickets', 'tie', 'no result'], dtype=object)

In [33]:
#For each match, show total runs in 1st innings vs 2nd innings.
res=df2.groupby(["match_id","inning"])["total_runs"].sum()
res

match_id  inning
335982    1         222
          2          82
335983    1         240
          2         207
335984    1         129
                   ...
1426310   2         174
1426311   1         175
          2         139
1426312   1         113
          2         114
Name: total_runs, Length: 2217, dtype: int64

In [34]:
#Identify matches where total 6s > total 4s.
four=df2[df2["batsman_runs"]==4]
six=df2[df2["batsman_runs"]==6]
four_count=four.groupby("match_id")["batsman_runs"].count()
six_count=six.groupby("match_id")["batsman_runs"].count()
six_count[six_count > four_count]

match_id
548314     16
1082598    20
1082632    31
1136565    31
1136584    33
1216496    33
1216531    22
1254116    12
1304049    27
1304115    21
1359498    33
1359507    30
1422121    29
1422126    38
1422128    24
1422133    22
1426280    42
Name: batsman_runs, dtype: int64

In [35]:
#For each match, find the highest scoring batsman in the last 5 overs.
overs=df2[df2["over"]>=15]
res=overs.groupby(["match_id","batter"])["total_runs"].sum()
res = res.reset_index()
max_runs = res.groupby("match_id")["total_runs"].max()
result = res[res["total_runs"] == res["match_id"].map(max_runs)]
result

      match_id       batter  total_runs
0       335982  BB McCullum          59
7       335983   MEK Hussey          42
10      335984   D Salunkhe          18
18      335985   MV Boucher          31
22      335986    DJ Hussey          21
...        ...          ...         ...
8157   1426307    JM Sharma          33
8164   1426309   PJ Cummins          27
8168   1426310    MK Lomror          24
8173   1426311  Dhruv Jurel          33
8182   1426312   PJ Cummins          19

[1124 rows x 3 columns]

In [36]:
#Get bowlers who delivered more than 100 balls in a season.
new1=df1[["id","season"]]
new2=df2[["match_id","bowler","ball"]]
merge=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")
res=merge.groupby(["season","bowler"])["ball"].count()
greater=res[res>100]
greater

season   bowler
2007/08  A Kumble       236
         A Mishra       123
         A Nehra        280
         AB Agarkar     168
         AB Dinda       245
                       ...
2024     UT Yadav       129
         VG Arora       201
         YS Chahal      362
         Yash Dayal     322
         Yash Thakur    225
Name: ball, Length: 962, dtype: int64

In [37]:
#For each team, find wins where they scored more than 180 runs.
new1=df1[["id","winner"]]
new2=df2[["match_id","batting_team","total_runs"]]
merge=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")
winnings=merge[merge["batting_team"]==merge["winner"]]
res=winnings.groupby(["match_id","winner","batting_team"])["total_runs"].sum()
res[res>180]

match_id  winner                       batting_team
335982    Kolkata Knight Riders        Kolkata Knight Riders          222
335983    Chennai Super Kings          Chennai Super Kings            240
335989    Chennai Super Kings          Chennai Super Kings            208
335990    Rajasthan Royals             Rajasthan Royals               217
335991    Kings XI Punjab              Kings XI Punjab                182
                                                                     ...
1426300   Royal Challengers Bengaluru  Royal Challengers Bengaluru    187
1426302   Delhi Capitals               Delhi Capitals                 208
1426305   Lucknow Super Giants         Lucknow Super Giants           214
1426306   Royal Challengers Bengaluru  Royal Challengers Bengaluru    218
1426307   Sunrisers Hyderabad          Sunrisers Hyderabad            215
Name: total_runs, Length: 352, dtype: int64

In [38]:
#For each match, find the bowler who conceded most boundaries.
four=df2[df2["batsman_runs"]==4]
six=df2[df2["batsman_runs"]==6]
four_count = four.groupby(["match_id", "bowler"])["batsman_runs"].count()
six_count = six.groupby(["match_id", "bowler"])["batsman_runs"].count()
total=four_count+six_count
total = four_count.add(six_count, fill_value=0)
total = total.reset_index()
max_boundaries = total.groupby("match_id")["batsman_runs"].max()
max_boundaries

match_id
335982     8.0
335983     8.0
335984     8.0
335985     8.0
335986     5.0
          ...
1426307    8.0
1426309    7.0
1426310    8.0
1426311    6.0
1426312    5.0
Name: batsman_runs, Length: 1095, dtype: float64

In [39]:
#Identify matches where first innings score > 120 but team won.
new1=df1[["id","winner"]]
new2=df2[["match_id","inning","batting_team","total_runs"]]
first_innings=df2[df2["inning"]==1]
score=first_innings.groupby(["match_id","batting_team"])["total_runs"].sum()
score = score.reset_index()
merge=pd.merge(score,new1,left_on="match_id",right_on="id",how="inner")
won=merge[merge["batting_team"]==merge["winner"]]
won[won["total_runs"]>120]

,match_id,batting_team,total_runs,id,winner
0,335982,Kolkata Knight Riders,222,335982,Kolkata Knight Riders
1,335983,Chennai Super Kings,240,335983,Chennai Super Kings
7,335989,Chennai Super Kings,208,335989,Chennai Super Kings
9,335991,Kings XI Punjab,182,335991,Kings XI Punjab
14,335996,Chennai Super Kings,178,335996,Chennai Super Kings
...,...,...,...,...,...
1085,1426300,Royal Challengers Bengaluru,187,1426300,Royal Challengers Bengaluru
1086,1426302,Delhi Capitals,208,1426302,Delhi Capitals
1088,1426305,Lucknow Super Giants,214,1426305,Lucknow Super Giants
1089,1426306,Royal Challengers Bengaluru,218,1426306,Royal Challengers Bengaluru
1093,1426311,Sunrisers Hyderabad,175,1426311,Sunrisers Hyderabad

In [40]:
#For each season, find the total number of matches that went to the last over.
overs=df2[df2["over"]==19]
new1 = df1[["id", "season"]]
merge = pd.merge(overs, new1, left_on="match_id", right_on="id", how="inner")
matches = merge.groupby(["season", "match_id"]).size()
result = matches.groupby("season").count()
result

season
2007/08    51
2009       55
2009/10    59
2011       67
2012       71
2013       75
2014       57
2015       55
2016       57
2017       56
2018       55
2019       58
2020/21    60
2021       59
2022       71
2023       73
2024       68
dtype: int64

In [41]:
#For each match, find total leg-byes conceded.
extras=df2[df2["extras_type"]=="legbyes"]
group=extras.groupby("match_id")["extra_runs"].sum()
group

match_id
335982     12
335983      6
335984      3
335985      6
335986     12
           ..
1426307    11
1426309     9
1426310     3
1426311     2
1426312     4
Name: extra_runs, Length: 1059, dtype: int64

In [42]:
#Find teams that conceded more wides than no-balls.
extras=extras = df2[(df2["extras_type"] == "wides") | (df2["extras_type"] == "noballs")]
wides = extras[extras["extras_type"] == "wides"]
wide_count = wides.groupby("bowling_team")["extras_type"].count()

noballs = extras[extras["extras_type"] == "noballs"]
noball_count = noballs.groupby("bowling_team")["extras_type"].count()

result = wide_count[wide_count > noball_count]
result

bowling_team
Chennai Super Kings             946
Deccan Chargers                 280
Delhi Capitals                  387
Delhi Daredevils                550
Gujarat Lions                    91
Gujarat Titans                  149
Kings XI Punjab                 720
Kochi Tuskers Kerala             52
Kolkata Knight Riders           848
Lucknow Super Giants            193
Mumbai Indians                 1090
Pune Warriors                   120
Punjab Kings                    234
Rajasthan Royals                949
Rising Pune Supergiant           62
Rising Pune Supergiants          56
Royal Challengers Bangalore     951
Royal Challengers Bengaluru      85
Sunrisers Hyderabad             617
Name: extras_type, dtype: int64

In [43]:
#For each batsman, find highest runs against a specific team.
new = df2[["match_id", "batter", "bowling_team", "batsman_runs"]]
team = new[new["bowling_team"] == "Chennai Super Kings"]
runs = team.groupby(["match_id", "batter"])["batsman_runs"].sum()
runs = runs.reset_index()
result = runs.groupby("batter")["batsman_runs"].max()
result

batter
A Ashish Reddy    36
A Badoni          59
A Kumble           2
A Manohar         12
A Mishra          15
                  ..
YS Chahal          8
YV Dhull          13
YV Takawale       19
Yuvraj Singh      62
Z Khan            21
Name: batsman_runs, Length: 416, dtype: int64

In [44]:
#List bowlers taking wicket on the first delivery of an over.
first=df2[df2["over"]==1]
wicket=first[first["is_wicket"]==1]
result=wicket["bowler"].unique()
result

array(['I Sharma', 'SR Watson', 'Z Khan', 'RP Singh', 'S Sreesanth',
       'Mohammad Asif', 'A Nehra', 'IK Pathan', 'Sohail Tanvir',
       'JA Morkel', 'PJ Sangwan', 'MM Patel', 'DJ Bravo', 'MS Gony',
       'YK Pathan', 'M Ntini', 'Anureet Singh', 'Pankaj Singh',
       'SL Malinga', 'VS Malik', 'S Tyagi', 'DS Kulkarni',
       'R Vinay Kumar', 'DP Nannes', 'WPUJC Vaas', 'CK Langeveldt',
       'A Singh', 'T Thushara', 'MF Maharoof', 'DW Steyn', 'Kamran Khan',
       'DE Bollinger', 'MR Marsh', 'RJ Harris', 'P Kumar', 'M Morkel',
       'SB Wagh', 'TG Southee', 'Harbhajan Singh', 'L Balaji', 'BA Bhatt',
       'J Botha', 'JD Unadkat', 'S Aravind', 'R Ashwin', 'JDP Oram',
       'Iqbal Abdulla', 'RE van der Merwe', 'AB Dinda', 'JH Kallis',
       'S Nadeem', 'KMDN Kulasekara', 'P Awana', 'B Lee', 'M de Lange',
       'B Kumar', 'BW Hilfenhaus', 'PP Ojha', 'UT Yadav',
       'Shakib Al Hasan', 'GH Vihari', 'MC Henriques', 'S Kaul',
       'CH Morris', 'Azhar Mahmood', 'MM Sharma', 'BAW Mendis',
       'MG Johnson', 'JO Holder', 'JP Faulkner', 'Bipul Sharma',
       'WD Parnell', 'R Dhawan', 'Mohammed Shami', 'NM Coulter-Nile',
       'IC Pandey', 'Sandeep Sharma', 'MA Starc', 'PJ Cummins',
       'STR Binny', 'YS Chahal', 'JP Duminy', 'BE Hendricks',
       'MJ McClenaghan', 'P Negi', 'JJ Bumrah', 'KW Richardson',
       'SP Narine', 'BB Sran', 'A Choudhary', 'DL Chahar', 'SN Thakur',
       'Mohammed Siraj', 'NB Singh', 'K Rabada', 'Basil Thampi',
       'Mohammad Nabi', 'CJ Jordan', 'PP Chawla', 'CR Woakes',
       'B Stanlake', 'AD Russell', 'Mujeeb Ur Rahman', 'GJ Maxwell',
       'Avesh Khan', 'KM Asif', 'L Ngidi', 'HV Patel', 'TA Boult',
       'BA Stokes', 'LH Ferguson', 'JC Archer', 'Navdeep Saini',
       'M Prasidh Krishna', 'KK Ahmed', 'S Lamichhane', 'S Gopal',
       'JL Pattinson', 'A Nortje', 'Washington Sundar', 'Shivam Mavi',
       'CV Varun', 'KA Jamieson', 'J Yadav', 'DJ Hooda', 'GHS Garton',
       'AF Milne', 'HH Pandya', 'DJ Willey', 'Yash Dayal', 'M Jansen',
       'M Theekshana', 'C Sakariya', 'Harshit Rana', 'PVD Chameera',
       'Simarjeet Singh', 'Arshdeep Singh', 'TU Deshpande', 'C Green',
       'JP Behrendorff', 'Mukesh Kumar', 'KH Pandya', 'Arshad Khan',
       'Akash Madhwal', 'Naveen-ul-Haq', 'VG Arora', 'Mohsin Khan',
       'G Coetzee', 'SH Johnson', 'S Sandeep Warrier'], dtype=object)

In [45]:
#For each match, find the over with the most wides.
wides=df2[df2["extras_type"]=="wides"]
count = wides.groupby(["match_id", "over"])["extras_type"].count()
count = count.reset_index()
max_wides = count.groupby("match_id")["extras_type"].max()
result = count[count["extras_type"] == count["match_id"].map(max_wides)]
result

      match_id  over  extras_type
0       335982     0            2
3       335982     6            2
4       335982     8            2
6       335982    12            2
7       335982    14            2
...        ...   ...          ...
6448   1426309     1            2
6455   1426310    10            3
6461   1426311    14            2
6463   1426311    17            2
6468   1426312     3            5

[2537 rows x 3 columns]

In [46]:
#For each match, find the bowler who bowled the final over.
match=df2.groupby(["match_id"])["over"].max()
result=df2[df2["over"]==df2["match_id"].map(match)]
result[["match_id","over","bowler"]].drop_duplicates()

        match_id  over           bowler
118       335982    19          P Kumar
343       335983    19         JR Hopes
467       335983    19  Joginder Sharma
589       335984    19       GD McGrath
809       335985    19           Z Khan
...          ...   ...              ...
260157   1426309    19       AD Russell
260360   1426310    19   Sandeep Sharma
260605   1426311    19       Avesh Khan
260730   1426311    19      T Natarajan
260850   1426312    18       AD Russell

[1765 rows x 3 columns]

In [47]:
#Identify the match with the most extras conceded by losing team.
new1=df1[["id","winner"]]
new2=df2[["match_id","bowling_team","extra_runs"]]
runs=df2.groupby(["match_id","bowling_team"])["extra_runs"].sum()
runs=runs.reset_index
res=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")
losing=res[res["bowling_team"]!=res["winner"]]
result=losing.loc[losing["extra_runs"].idxmax()]
result

id                        729309
winner          Delhi Daredevils
match_id                  729309
bowling_team      Mumbai Indians
extra_runs                     7
Name: 98231, dtype: object

In [48]:
#For each venue, find the average match score.
new1=df1[["id","venue"]]
new2=df2[["match_id","inning","total_runs"]]
score=new2.groupby(["match_id","inning"])["total_runs"].sum()
score=score.reset_index()
res=pd.merge(score,new1,left_on="match_id",right_on="id",how="inner")
res.groupby(["venue"])["total_runs"].mean()

venue
Arun Jaitley Stadium                                                     151.433333
Arun Jaitley Stadium, Delhi                                              190.343750
Barabati Stadium                                                         162.714286
Barsapara Cricket Stadium, Guwahati                                      169.833333
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    159.037037
Brabourne Stadium                                                        174.050000
Brabourne Stadium, Mumbai                                                171.294118
Buffalo Park                                                             133.166667
De Beers Diamond Oval                                                    149.500000
Dr DY Patil Sports Academy                                               141.470588
Dr DY Patil Sports Academy, Mumbai                                       164.325000
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                      144.076923
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam       200.000000
Dubai International Cricket Stadium                                      144.500000
Eden Gardens                                                             153.623377
Eden Gardens, Kolkata                                                    190.156250
Feroz Shah Kotla                                                         154.798319
Green Park                                                               162.250000
Himachal Pradesh Cricket Association Stadium                             160.944444
Himachal Pradesh Cricket Association Stadium, Dharamsala                 189.375000
Holkar Cricket Stadium                                                   159.555556
JSCA International Stadium Complex                                       146.857143
Kingsmead                                                                145.100000
M Chinnaswamy Stadium                                                    154.679389
M Chinnaswamy Stadium, Bengaluru                                         190.071429
M.Chinnaswamy Stadium                                                    170.900000
MA Chidambaram Stadium                                                   142.388889
MA Chidambaram Stadium, Chepauk                                          155.887755
MA Chidambaram Stadium, Chepauk, Chennai                                 152.862069
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur       167.500000
Maharashtra Cricket Association Stadium                                  159.250000
Maharashtra Cricket Association Stadium, Pune                            158.000000
Narendra Modi Stadium, Ahmedabad                                         169.791667
Nehru Stadium                                                            136.300000
New Wanderers Stadium                                                    143.250000
Newlands                                                                 112.312500
OUTsurance Oval                                                          132.250000
Punjab Cricket Association IS Bindra Stadium                             173.800000
Punjab Cricket Association IS Bindra Stadium, Mohali                     161.136364
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh         185.600000
Punjab Cricket Association Stadium, Mohali                               156.957143
Rajiv Gandhi International Stadium                                       154.366667
Rajiv Gandhi International Stadium, Uppal                                148.880000
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     182.423077
Sardar Patel Stadium, Motera                                             144.884615
Saurashtra Cricket Association Stadium                                   151.500000
Sawai Mansingh Stadium                                                   151.744681
Sawai Mansingh Stadium, Jaipur                                           171.050000
Shaheed Veer Narayan Singh International Stadium                         145.083333
Sharjah Cricket Stadium                                                  153.267857
Sheikh Zayed Stadium                                                     142.854839
St George's Park                                                         145.214286
Subrata Roy Sahara Stadium                                               141.500000
SuperSport Park                                                          152.208333
Vidarbha Cricket Association Stadium, Jamtha                             147.000000
Wankhede Stadium                                                         158.155405
Wankhede Stadium, Mumbai                                                 173.188889
Zayed Cricket Stadium, Abu Dhabi                                         154.687500
Name: total_runs, dtype: float64

In [49]:
#For each match, find the partnership with the most runs.
new2=df2[["match_id","inning","batter","non_striker","total_runs"]]
runs=new2.groupby(["match_id","inning","batter","non_striker"])["total_runs"].sum()
runs=runs.reset_index()
max_runs = runs.groupby("match_id")["total_runs"].max()
result = runs[runs["total_runs"] == runs["match_id"].map(max_runs)]
result

       match_id  inning          batter         non_striker  total_runs
3        335982       1     BB McCullum          SC Ganguly          49
32       335983       1      MEK Hussey         S Badrinath          42
70       335984       2        S Dhawan           G Gambhir          59
93       335985       2      MV Boucher           JH Kallis          39
123      335986       2      SC Ganguly           DJ Hussey          27
...         ...     ...             ...                 ...         ...
27358   1426307       1  P Simran Singh       Atharva Taide          50
27398   1426309       2         SS Iyer             VR Iyer          58
27422   1426310       2      SO Hetmyer             R Parag          26
27439   1426311       1     RA Tripathi             TM Head          37
27484   1426312       2         VR Iyer  Rahmanullah Gurbaz          50

[1141 rows x 5 columns]

In [50]:
#Get number of players dismissed “caught” in each match.
new2=df2[["match_id","dismissal_kind","player_dismissed"]]
dismissal=new2[new2["dismissal_kind"]=="caught"]
dismissal.groupby(["match_id"])["player_dismissed"].count()

match_id
335982      9
335983      6
335984      2
335985      7
335986     11
           ..
1426307     8
1426309     7
1426310    10
1426311    12
1426312     8
Name: player_dismissed, Length: 1094, dtype: int64

In [51]:
#For each match, find overs without any boundaries.
new2 = df2[["match_id", "inning", "over", "batsman_runs"]]
boundaries = new2[
    (new2["batsman_runs"] == 4) | (new2["batsman_runs"] == 6)]
fours = boundaries.groupby(["match_id", "inning", "over"])["batsman_runs"].count()
fours = fours.reset_index()
overs = new2.groupby(["match_id", "inning", "over"])["batsman_runs"].count()

overs = overs.reset_index()
result = overs.merge(
    fours,
    on=["match_id", "inning", "over"],
    how="left",
    suffixes=("_all", "_boundary")
)

result = result[result["batsman_runs_boundary"].isna()]
result

       match_id  inning  over  batsman_runs_all  batsman_runs_boundary
0        335982       1     0                 7                    NaN
5        335982       1     5                 6                    NaN
6        335982       1     6                 6                    NaN
7        335982       1     7                 6                    NaN
8        335982       1     8                 6                    NaN
...         ...     ...   ...               ...                    ...
42195   1426312       1    15                 6                    NaN
42197   1426312       1    17                 6                    NaN
42198   1426312       1    18                 3                    NaN
42208   1426312       2     9                 6                    NaN
42209   1426312       2    10                 3                    NaN

[15317 rows x 5 columns]

In [52]:
#Identify matches with hat-tricks (three wickets in three balls).
new2=df2[["match_id","inning","over","ball","bowler","is_wicket"]]
wicket=new2[new2["is_wicket"]==1]
hat_trick=wicket.groupby(["match_id","inning","bowler","over"])["is_wicket"].count()
hat_trick=hat_trick.reset_index()
result=hat_trick[hat_trick["is_wicket"]>=3]
result

       match_id  inning             bowler  over  is_wicket
214      336002       1           DW Steyn    19          3
337      336013       2           L Balaji    19          3
382      336017       2          LR Shukla    17          3
406      336020       2           A Mishra    19          3
481      336028       2          VRV Singh    19          3
...         ...     ...                ...   ...        ...
10996   1426273       2        T Natarajan    18          3
11028   1426276       1     Sandeep Sharma    19          3
11161   1426289       2           MA Starc    18          3
11169   1426290       1  Vijaykumar Vyshak    19          3
11235   1426296       1           HV Patel    19          3

[120 rows x 5 columns]

In [53]:
#For each team, find matches where they defended &lt;150 successfully.
new1=df1[["id","team1","team2","winner","result"]]
new2=df2[["match_id","inning","batting_team","total_runs"]]
first=new2[new2["inning"]==1]
score=first.groupby(["match_id","batting_team"])["total_runs"].sum()
score=score.reset_index()
res = pd.merge(score, new1, left_on="match_id", right_on="id", how="inner")
won = res[(res["total_runs"] < 150) & (res["batting_team"] == res["winner"])]
won

,match_id,batting_team,total_runs,id,team1,team2,winner,result
28,336010,Kolkata Knight Riders,129,336010,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,runs
35,336017,Kolkata Knight Riders,133,336017,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,runs
47,336029,Royal Challengers Bangalore,126,336029,Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,runs
59,392182,Royal Challengers Bangalore,133,392182,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,runs
70,392195,Kings XI Punjab,139,392195,Kings XI Punjab,Rajasthan Royals,Kings XI Punjab,runs
...,...,...,...,...,...,...,...,...
932,1304103,Gujarat Titans,144,1304103,Gujarat Titans,Lucknow Super Giants,Gujarat Titans,runs
979,1359504,Gujarat Titans,135,1359504,Gujarat Titans,Lucknow Super Giants,Gujarat Titans,runs
983,1359508,Delhi Capitals,144,1359508,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,runs
992,1359517,Royal Challengers Bangalore,126,1359517,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore,runs
993,1359518,Delhi Capitals,130,1359518,Delhi Capitals,Gujarat Titans,Delhi Capitals,runs

In [54]:
#For each match, compare runs scored in odd overs vs even overs.
new=df2[["match_id","over","total_runs"]]
odd=new[new["over"]%2!=0]
even=new[new["over"]%2==0]
res_odd=odd.groupby(["match_id"])["total_runs"].sum().reset_index()
res_even=even.groupby(["match_id"])["total_runs"].sum().reset_index()
res = pd.merge(res_odd, res_even, on="match_id", how="inner", suffixes=("_odd", "_even"))
res["comparison"] = res["total_runs_odd"] - res["total_runs_even"]
res

      match_id  total_runs_odd  total_runs_even  comparison
0       335982             141              163         -22
1       335983             234              213          21
2       335984             138              123          15
3       335985             150              181         -31
4       335986             103              119         -16
...        ...             ...              ...         ...
1090   1426307             235              194          41
1091   1426309             164              159           5
1092   1426310             184              162          22
1093   1426311             146              168         -22
1094   1426312             111              116          -5

[1095 rows x 4 columns]

In [55]:
#Count matches per season.
df1.groupby(["season"])["id"].count()

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
2023       74
2024       71
Name: id, dtype: int64

In [57]:
#Find number of matches each team has won.
df1.groupby(["winner"])["id"].count()

winner
Chennai Super Kings            138
Deccan Chargers                 29
Delhi Capitals                  48
Delhi Daredevils                67
Gujarat Lions                   13
Gujarat Titans                  28
Kings XI Punjab                 88
Kochi Tuskers Kerala             6
Kolkata Knight Riders          131
Lucknow Super Giants            24
Mumbai Indians                 144
Pune Warriors                   12
Punjab Kings                    24
Rajasthan Royals               112
Rising Pune Supergiant          10
Rising Pune Supergiants          5
Royal Challengers Bangalore    116
Royal Challengers Bengaluru      7
Sunrisers Hyderabad             88
Name: id, dtype: int64

In [58]:
#Compute number of toss wins per team.
df1.groupby(["toss_winner"])["id"].count()

toss_winner
Chennai Super Kings            122
Deccan Chargers                 43
Delhi Capitals                  50
Delhi Daredevils                80
Gujarat Lions                   15
Gujarat Titans                  22
Kings XI Punjab                 85
Kochi Tuskers Kerala             8
Kolkata Knight Riders          122
Lucknow Super Giants            19
Mumbai Indians                 143
Pune Warriors                   20
Punjab Kings                    24
Rajasthan Royals               120
Rising Pune Supergiant           6
Rising Pune Supergiants          7
Royal Challengers Bangalore    113
Royal Challengers Bengaluru      8
Sunrisers Hyderabad             88
Name: id, dtype: int64

In [61]:
#Find most frequent “toss_decision” per team.
df1.groupby(["toss_decision","toss_winner"])["id"].count().sort_values(ascending=False)

toss_decision  toss_winner
field          Mumbai Indians                 90
               Kolkata Knight Riders          84
               Royal Challengers Bangalore    80
               Rajasthan Royals               76
               Chennai Super Kings            63
bat            Chennai Super Kings            59
field          Kings XI Punjab                58
               Sunrisers Hyderabad            53
bat            Mumbai Indians                 53
field          Delhi Daredevils               51
bat            Rajasthan Royals               44
field          Delhi Capitals                 38
bat            Kolkata Knight Riders          38
               Sunrisers Hyderabad            35
               Royal Challengers Bangalore    33
               Delhi Daredevils               29
               Kings XI Punjab                27
               Deccan Chargers                24
field          Punjab Kings                   19
               Deccan Chargers                19
               Gujarat Titans                 16
               Gujarat Lions                  14
               Lucknow Super Giants           13
bat            Delhi Capitals                 12
               Pune Warriors                  11
field          Pune Warriors                   9
bat            Gujarat Titans                  6
field          Rising Pune Supergiant          6
               Royal Challengers Bengaluru     6
bat            Lucknow Super Giants            6
field          Kochi Tuskers Kerala            5
bat            Punjab Kings                    5
field          Rising Pune Supergiants         4
bat            Kochi Tuskers Kerala            3
               Rising Pune Supergiants         3
               Royal Challengers Bengaluru     2
               Gujarat Lions                   1
Name: id, dtype: int64

In [62]:
#Identify venues with the most matches.
df1.groupby(["venue"])["id"].count().sort_values(ascending=False)

venue
Eden Gardens                                                             77
Wankhede Stadium                                                         73
M Chinnaswamy Stadium                                                    65
Feroz Shah Kotla                                                         60
Rajiv Gandhi International Stadium, Uppal                                49
MA Chidambaram Stadium, Chepauk                                          48
Sawai Mansingh Stadium                                                   47
Dubai International Cricket Stadium                                      46
Wankhede Stadium, Mumbai                                                 45
Punjab Cricket Association Stadium, Mohali                               35
Sheikh Zayed Stadium                                                     29
Sharjah Cricket Stadium                                                  28
MA Chidambaram Stadium, Chepauk, Chennai                                 28
Narendra Modi Stadium, Ahmedabad                                         24
Maharashtra Cricket Association Stadium                                  22
Dr DY Patil Sports Academy, Mumbai                                       20
Dr DY Patil Sports Academy                                               17
Brabourne Stadium, Mumbai                                                17
Arun Jaitley Stadium, Delhi                                              16
Eden Gardens, Kolkata                                                    16
Subrata Roy Sahara Stadium                                               16
M.Chinnaswamy Stadium                                                    15
Kingsmead                                                                15
Rajiv Gandhi International Stadium                                       15
Arun Jaitley Stadium                                                     14
M Chinnaswamy Stadium, Bengaluru                                         14
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    14
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                      13
Maharashtra Cricket Association Stadium, Pune                            13
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     13
SuperSport Park                                                          12
Sardar Patel Stadium, Motera                                             12
Punjab Cricket Association IS Bindra Stadium, Mohali                     11
Sawai Mansingh Stadium, Jaipur                                           10
Brabourne Stadium                                                        10
Saurashtra Cricket Association Stadium                                   10
Punjab Cricket Association IS Bindra Stadium                             10
MA Chidambaram Stadium                                                    9
Himachal Pradesh Cricket Association Stadium                              9
Holkar Cricket Stadium                                                    9
Zayed Cricket Stadium, Abu Dhabi                                          8
New Wanderers Stadium                                                     8
Newlands                                                                  7
Barabati Stadium                                                          7
JSCA International Stadium Complex                                        7
St George's Park                                                          7
Shaheed Veer Narayan Singh International Stadium                          6
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh          5
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur        5
Nehru Stadium                                                             5
Himachal Pradesh Cricket Association Stadium, Dharamsala                  4
Green Park                                                                4
De Beers Diamond Oval                                                     3
Buffalo Park                                                              3
Vidarbha Cricket Association Stadium, Jamtha                              3
Barsapara Cricket Stadium, Guwahati                                       3
OUTsurance Oval                                                           2
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam        2
Name: id, dtype: int64

In [65]:
#Calculate average margin of victory per season.
victory=df1.groupby(["season"])["result_margin"].mean()
victory

season
2007/08    15.965517
2009       16.857143
2009/10    19.762712
2011       18.930556
2012       16.229730
2013       19.837838
2014       14.728814
2015       17.821429
2016       15.333333
2017       17.103448
2018       14.350000
2019       15.210526
2020/21    22.589286
2021       13.576271
2022       16.972973
2023       19.246575
2024       17.873239
Name: result_margin, dtype: float64

In [66]:
#Count matches decided by runs vs wickets per season.
df1.groupby(["season","result"])["id"].count()

season   result
2007/08  runs         24
         wickets      34
2009     runs         27
         tie           1
         wickets      29
2009/10  runs         31
         tie           1
         wickets      28
2011     no result     1
         runs         33
         wickets      39
2012     runs         34
         wickets      40
2013     runs         37
         tie           2
         wickets      37
2014     runs         22
         tie           1
         wickets      37
2015     no result     2
         runs         32
         tie           1
         wickets      24
2016     runs         21
         wickets      39
2017     runs         26
         tie           1
         wickets      32
2018     runs         28
         wickets      32
2019     no result     1
         runs         22
         tie           2
         wickets      35
2020/21  runs         27
         tie           4
         wickets      29
2021     runs         22
         tie           1
         wickets      37
2022     runs         37
         wickets      37
2023     no result     1
         runs         40
         wickets      33
2024     runs         35
         wickets      36
Name: id, dtype: int64

In [68]:
#Find the team winning the most tosses per season.
df1.groupby(["season","toss_winner"])["id"].count().sort_values(ascending=False)

season  toss_winner
2013    Mumbai Indians           12
2019    Chennai Super Kings      12
2013    Kolkata Knight Riders    12
2018    Chennai Super Kings      11
2017    Mumbai Indians           11
                                 ..
2014    Delhi Daredevils          4
2024    Gujarat Titans            3
        Kolkata Knight Riders     3
2023    Lucknow Super Giants      3
2024    Chennai Super Kings       3
Name: id, Length: 146, dtype: int64

In [71]:
#For each venue, get highest number of wins by a single team.
wins = df1.groupby(["venue", "winner"])["id"].count()
wins = wins.reset_index()
result = wins.groupby("venue")["id"].max()
result

venue
Arun Jaitley Stadium                                                      4
Arun Jaitley Stadium, Delhi                                               6
Barabati Stadium                                                          3
Barsapara Cricket Stadium, Guwahati                                       2
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow     7
Brabourne Stadium                                                         5
Brabourne Stadium, Mumbai                                                 4
Buffalo Park                                                              1
De Beers Diamond Oval                                                     1
Dr DY Patil Sports Academy                                                5
Dr DY Patil Sports Academy, Mumbai                                        3
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                       3
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam        1
Dubai International Cricket Stadium                                       9
Eden Gardens                                                             45
Eden Gardens, Kolkata                                                     7
Feroz Shah Kotla                                                         23
Green Park                                                                2
Himachal Pradesh Cricket Association Stadium                              5
Himachal Pradesh Cricket Association Stadium, Dharamsala                  1
Holkar Cricket Stadium                                                    4
JSCA International Stadium Complex                                        3
Kingsmead                                                                 3
M Chinnaswamy Stadium                                                    29
M Chinnaswamy Stadium, Bengaluru                                          4
M.Chinnaswamy Stadium                                                     8
MA Chidambaram Stadium                                                    7
MA Chidambaram Stadium, Chepauk                                          33
MA Chidambaram Stadium, Chepauk, Chennai                                 10
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur        1
Maharashtra Cricket Association Stadium                                   5
Maharashtra Cricket Association Stadium, Pune                             3
Narendra Modi Stadium, Ahmedabad                                          9
Nehru Stadium                                                             2
New Wanderers Stadium                                                     3
Newlands                                                                  2
OUTsurance Oval                                                           1
Punjab Cricket Association IS Bindra Stadium                              8
Punjab Cricket Association IS Bindra Stadium, Mohali                      4
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh          1
Punjab Cricket Association Stadium, Mohali                               18
Rajiv Gandhi International Stadium                                       10
Rajiv Gandhi International Stadium, Uppal                                20
Rajiv Gandhi International Stadium, Uppal, Hyderabad                      6
Sardar Patel Stadium, Motera                                              7
Saurashtra Cricket Association Stadium                                    3
Sawai Mansingh Stadium                                                   32
Sawai Mansingh Stadium, Jaipur                                            5
Shaheed Veer Narayan Singh International Stadium                          4
Sharjah Cricket Stadium                                                   5
Sheikh Zayed Stadium                                                      6
St George's Park                                                          2
Subrata Roy Sahara Stadium                                                4
SuperSport Park                                                           2
Vidarbha Cricket Association Stadium, Jamtha                              2
Wankhede Stadium                                                         42
Wankhede Stadium, Mumbai                                                 10
Zayed Cricket Stadium, Abu Dhabi                                          2
Name: id, dtype: int64

In [75]:
#Find umpires officiating in the most matches.
ump1=df1.groupby(["umpire1"])["id"].count().reset_index()
ump2=df1.groupby(["umpire2"])["id"].count().reset_index()
combine=pd.merge(ump1,ump2,left_on="umpire1",right_on="umpire2",how="outer")
combine

           umpire1   id_x         umpire2  id_y
0       A Deshmukh    9.0      A Deshmukh   3.0
1   A Nand Kishore   24.0  A Nand Kishore  13.0
2          A Totre   13.0             NaN   NaN
3         AG Wharf    2.0             NaN   NaN
4     AK Chaudhary  115.0    AK Chaudhary  16.0
..             ...    ...             ...   ...
65       UV Gandhe    4.0       UV Gandhe  27.0
66     VA Kulkarni   13.0     VA Kulkarni  44.0
67       VK Sharma    4.0       VK Sharma  61.0
68    Vinod Seshan    3.0    Vinod Seshan  11.0
69        YC Barde    6.0        YC Barde  36.0

[70 rows x 4 columns]

In [80]:
#Count matches with result “tie”.
match=df1[df1["result"]=="tie"]["id"].count()
match

np.int64(14)

In [83]:
#For each team, count matches where they batted first.
innings=df2[df2["inning"]==1]
innings.groupby(["batting_team"])["match_id"].count()

batting_team
Chennai Super Kings            16085
Deccan Chargers                 5280
Delhi Capitals                  5105
Delhi Daredevils                8753
Gujarat Lions                   1726
Gujarat Titans                  2614
Kings XI Punjab                11869
Kochi Tuskers Kerala             876
Kolkata Knight Riders          14719
Lucknow Super Giants            2874
Mumbai Indians                 16675
Pune Warriors                   2448
Punjab Kings                    3882
Rajasthan Royals               12730
Rising Pune Supergiant           994
Rising Pune Supergiants          849
Royal Challengers Bangalore    14761
Royal Challengers Bengaluru     1133
Sunrisers Hyderabad            11645
Name: match_id, dtype: int64

In [87]:
#For each team, count matches where they chased.
innings = df2[df2["inning"] == 2]
innings = innings[["match_id", "batting_team"]]
innings = innings.drop_duplicates()
innings.groupby(["batting_team"])["match_id"].count()

batting_team
Chennai Super Kings            107
Deccan Chargers                 32
Delhi Capitals                  50
Delhi Daredevils                89
Gujarat Lions                   16
Gujarat Titans                  24
Kings XI Punjab                 93
Kochi Tuskers Kerala             7
Kolkata Knight Riders          131
Lucknow Super Giants            21
Mumbai Indians                 127
Pune Warriors                   25
Punjab Kings                    25
Rajasthan Royals               117
Rising Pune Supergiant           8
Rising Pune Supergiants          7
Royal Challengers Bangalore    119
Royal Challengers Bengaluru      6
Sunrisers Hyderabad             88
Name: match_id, dtype: int64

In [90]:
#Identify teams with most wins at a particular venue.
wins=df1.groupby(["venue","winner"])["id"].count().reset_index()
max_wins=wins.groupby("venue")["id"].max()
result=wins[wins["id"]==wins["venue"].map(max_wins)]
result

                                            venue                 winner  id
1                            Arun Jaitley Stadium         Delhi Capitals   4
2                            Arun Jaitley Stadium       Delhi Daredevils   4
8                     Arun Jaitley Stadium, Delhi         Delhi Capitals   6
14                               Barabati Stadium        Deccan Chargers   3
16                               Barabati Stadium  Kolkata Knight Riders   3
..                                            ...                    ...  ..
350  Vidarbha Cricket Association Stadium, Jamtha        Deccan Chargers   2
360                              Wankhede Stadium         Mumbai Indians  42
372                      Wankhede Stadium, Mumbai         Mumbai Indians  10
379              Zayed Cricket Stadium, Abu Dhabi  Kolkata Knight Riders   2
380              Zayed Cricket Stadium, Abu Dhabi         Mumbai Indians   2

[89 rows x 3 columns]

In [91]:
#Find most common man of the match per season.
common=df1.groupby(["season","player_of_match"])["id"].count().reset_index()
res=common.groupby(["season"])["id"].max()
result = common[common["id"] == common["season"].map(res)]
result

      season  player_of_match  id
28   2007/08         SE Marsh   5
80      2009        YK Pathan   3
121  2009/10     SR Tendulkar   4
133     2011         CH Gayle   6
188     2012         CH Gayle   5
253     2013       MEK Hussey   5
285     2014       GJ Maxwell   4
319     2015        DA Warner   4
386     2016          V Kohli   5
392     2017        BA Stokes   3
419     2017  NM Coulter-Nile   3
462     2018      Rashid Khan   4
475     2019       AD Russell   4
515  2020/21   AB de Villiers   3
528  2020/21         KL Rahul   3
542  2020/21       RD Gaikwad   3
554  2020/21         TA Boult   3
592     2021       RD Gaikwad   4
622     2022    Kuldeep Yadav   4
702     2023     Shubman Gill   4
707     2023      YBK Jaiswal   4
709     2024  Abhishek Sharma   3
747     2024        SP Narine   3
755     2024          TM Head   3

In [95]:
#Get count of matches with Duckworth-Lewis method applied.
res=df1[df1["method"]=="D/L"]
res.groupby(["method"])["id"].count()

method
D/L    21
Name: id, dtype: int64

In [98]:
#For each season, find total teams participating.
team1 = df1[["season", "team1"]]
team2 = df1[["season", "team2"]]

team1 = team1.drop_duplicates()
team2 = team2.drop_duplicates()

team1.groupby("season")["team1"].count()

season
2007/08     8
2009        7
2009/10     8
2011       10
2012        9
2013        9
2014        8
2015        8
2016        8
2017        8
2018        8
2019        8
2020/21     8
2021        8
2022       10
2023       10
2024       10
Name: team1, dtype: int64

In [99]:
#For each city, count number of matches played.
df1.groupby(["city"])["id"].count()

city
Abu Dhabi          37
Ahmedabad          36
Bangalore          65
Bengaluru          29
Bloemfontein        2
Cape Town           7
Centurion          12
Chandigarh         61
Chennai            85
Cuttack             7
Delhi              90
Dharamsala         13
Dubai              13
Durban             15
East London         3
Guwahati            3
Hyderabad          77
Indore              9
Jaipur             57
Johannesburg        8
Kanpur              4
Kimberley           3
Kochi               5
Kolkata            93
Lucknow            14
Mohali              5
Mumbai            173
Nagpur              3
Navi Mumbai         9
Port Elizabeth      7
Pune               51
Raipur              6
Rajkot             10
Ranchi              7
Sharjah            10
Visakhapatnam      15
Name: id, dtype: int64

In [106]:
#Using groupby, list top 5 match winners at each venue.
ven=df1.groupby(["venue","winner"])["id"].count().reset_index()
ven=ven.sort_values(["venue","id"],ascending=False)
res=ven.groupby("venue").head(5)
res

                                venue                 winner  id
379  Zayed Cricket Stadium, Abu Dhabi  Kolkata Knight Riders   2
380  Zayed Cricket Stadium, Abu Dhabi         Mumbai Indians   2
377  Zayed Cricket Stadium, Abu Dhabi    Chennai Super Kings   1
378  Zayed Cricket Stadium, Abu Dhabi         Delhi Capitals   1
381  Zayed Cricket Stadium, Abu Dhabi       Rajasthan Royals   1
..                                ...                    ...  ..
1                Arun Jaitley Stadium         Delhi Capitals   4
2                Arun Jaitley Stadium       Delhi Daredevils   4
6                Arun Jaitley Stadium    Sunrisers Hyderabad   2
0                Arun Jaitley Stadium    Chennai Super Kings   1
3                Arun Jaitley Stadium        Kings XI Punjab   1

[260 rows x 3 columns]

In [108]:
#Find total deliveries bowled per bowler.
df2.groupby(["bowler"])["ball"].count()

bowler
A Ashish Reddy     270
A Badoni            25
A Chandila         234
A Choudhary        108
A Dananjaya         25
                  ...
Yash Dayal         615
Yash Thakur        432
Yudhvir Singh       74
Yuvraj Singh       882
Z Khan            2276
Name: ball, Length: 530, dtype: int64

In [110]:
#Find total runs scored by each batsman.
df2.groupby(["batter"])["total_runs"].sum()

batter
A Ashish Reddy     288
A Badoni           688
A Chandila           4
A Chopra            58
A Choudhary         25
                  ...
Yashpal Singh       49
Younis Khan          3
Yudhvir Singh       22
Yuvraj Singh      2884
Z Khan             121
Name: total_runs, Length: 673, dtype: int64

In [111]:
#Compute number of 4s hit by each batsman.
hits=df2[df2["batsman_runs"]==4]
hits.groupby(["batter"])["batsman_runs"].count()

batter
A Ashish Reddy     16
A Badoni           46
A Chopra            7
A Choudhary         1
A Flintoff          5
                 ...
YV Takawale        26
Yashpal Singh       5
Yudhvir Singh       1
Yuvraj Singh      218
Z Khan             11
Name: batsman_runs, Length: 538, dtype: int64

In [112]:
#Compute number of 6s hit by each batsman.
hits=df2[df2["batsman_runs"]==6]
hits.groupby(["batter"])["batsman_runs"].count()

batter
A Ashish Reddy     15
A Badoni           24
A Choudhary         1
A Flintoff          2
A Manohar          10
                 ...
YK Pathan         161
YV Takawale         3
Yudhvir Singh       2
Yuvraj Singh      149
Z Khan              2
Name: batsman_runs, Length: 451, dtype: int64

In [114]:
#Find bowlers with most no-balls.
extras=df2[df2["extras_type"]=="noballs"]
extras.groupby(["bowler"])["extras_type"].count().sort_values(ascending=False)

bowler
JJ Bumrah       33
S Sreesanth     23
I Sharma        23
UT Yadav        23
A Mishra        21
                ..
JE Taylor        1
Pankaj Singh     1
JW Hastings      1
KAJ Roach        1
S Aravind        1
Name: extras_type, Length: 269, dtype: int64

In [117]:
#Find batsmen with most dot balls faced.
runs=df2[df2["batsman_runs"]==0]
runs.groupby(["batter"])["batsman_runs"].count().sort_values(ascending=False)

batter
V Kohli             2198
S Dhawan            2136
RG Sharma           2036
DA Warner           1873
CH Gayle            1636
                    ...
JL Denly               1
Mayank Dagar           1
S Kaushik              1
PM Sarvesh Kumar       1
VS Yeligati            1
Name: batsman_runs, Length: 662, dtype: int64

In [119]:
#For each over, compute total runs scored.
df2.groupby(["match_id","inning","over"])["total_runs"].sum()

match_id  inning  over
335982    1       0        3
                  1       18
                  2        6
                  3       23
                  4       10
                          ..
1426312   2       6       12
                  7        9
                  8       13
                  9        5
                  10       3
Name: total_runs, Length: 42210, dtype: int64

In [120]:
#For each match, total runs in each over.
df2.groupby(["match_id","over"])["total_runs"].sum()

match_id  over
335982    0        7
          1       23
          2        9
          3       27
          4       18
                  ..
1426312   14       0
          15       8
          16      10
          17       5
          18       0
Name: total_runs, Length: 21717, dtype: int64

In [122]:
#Count wickets per bowler.
wicket=df2[df2["is_wicket"]==1]
wicket.groupby(["bowler"])["is_wicket"].sum().sort_values().tail(5)

bowler
R Ashwin     198
SP Narine    200
PP Chawla    201
DJ Bravo     207
YS Chahal    213
Name: is_wicket, dtype: int64

In [124]:
#Count dismissals of type “caught” per fielder.
kind=df2[df2["dismissal_kind"]=="caught"]
kind.groupby(["fielder"])["dismissal_kind"].count().sort_values().tail(5)

fielder
SK Raina          106
V Kohli           114
AB de Villiers    120
KD Karthik        145
MS Dhoni          152
Name: dismissal_kind, dtype: int64

In [127]:
#Find total wides bowled by each bowler.
extra=df2[df2["extras_type"]=="wides"]
extra.groupby(["bowler"])["extras_type"].count()

bowler
A Ashish Reddy     6
A Choudhary        6
A Dananjaya        1
A Kamboj           6
A Kumble          13
                  ..
Yash Dayal        32
Yash Thakur       25
Yudhvir Singh      2
Yuvraj Singh      12
Z Khan            74
Name: extras_type, Length: 443, dtype: int64

In [128]:
#Find total extras conceded by each team.
df2.groupby(["bowling_team"])["extra_runs"].sum()

bowling_team
Chennai Super Kings            1842
Deccan Chargers                 659
Delhi Capitals                  725
Delhi Daredevils               1268
Gujarat Lions                   188
Gujarat Titans                  295
Kings XI Punjab                1571
Kochi Tuskers Kerala            110
Kolkata Knight Riders          1957
Lucknow Super Giants            386
Mumbai Indians                 2295
Pune Warriors                   335
Punjab Kings                    480
Rajasthan Royals               1917
Rising Pune Supergiant          111
Rising Pune Supergiants         108
Royal Challengers Bangalore    2040
Royal Challengers Bengaluru     151
Sunrisers Hyderabad            1254
Name: extra_runs, dtype: int64

In [129]:
#Compute batsman strike rate (runs/balls × 100).
runs = df2.groupby(["batter"])["batsman_runs"].sum()

valid = df2[df2["extras_type"] != "wides"]
balls = valid.groupby(["batter"])["ball"].count()

strike_rate = runs / balls * 100
strike_rate

batter
A Ashish Reddy    145.077720
A Badoni          134.038055
A Chandila         57.142857
A Chopra           74.647887
A Choudhary       125.000000
                     ...
Yashpal Singh      71.212121
Younis Khan        42.857143
Yudhvir Singh     137.500000
Yuvraj Singh      129.783223
Z Khan             82.978723
Length: 673, dtype: float64

In [130]:
#Compute bowler economy rate (runs/overs).
runs = df2.groupby(["bowler"])["total_runs"].sum()

valid = df2[(df2["extras_type"] != "wides") & (df2["extras_type"] != "noballs")]
balls = valid.groupby(["bowler"])["ball"].count()

overs = balls / 6
economy = runs / overs
economy.sort_values()

bowler
AC Gilchrist      0.0
R Ravindra        3.5
NB Singh          4.5
Sachin Baby       4.8
AM Rahane         5.0
                 ...
B Chipli         20.0
LPC Silva        21.0
I Malhotra       23.0
Atharva Taide    24.0
YBK Jaiswal      36.0
Length: 530, dtype: float64

In [133]:
#Count balls faced by each batsman.
extra=df2[df2["extras_type"]!="wides"]
extra.groupby(["batter"])["ball"].count()

batter
A Ashish Reddy     193
A Badoni           473
A Chandila           7
A Chopra            71
A Choudhary         20
                  ...
Yashpal Singh       66
Younis Khan          7
Yudhvir Singh       16
Yuvraj Singh      2122
Z Khan             141
Name: ball, Length: 673, dtype: int64

In [135]:
#Count balls bowled by each bowler.
extra=df2[(df2["extras_type"]!="wides") & (df2["extras_type"]!="noballs")]
extra.groupby(["bowler"])["ball"].count()

bowler
A Ashish Reddy     262
A Badoni            25
A Chandila         234
A Choudhary        101
A Dananjaya         24
                  ...
Yash Dayal         578
Yash Thakur        404
Yudhvir Singh       72
Yuvraj Singh       869
Z Khan            2200
Name: ball, Length: 530, dtype: int64

In [136]:
#Find batsmen scoring most runs in powerplay (1–6 overs).
powerplay = df2[(df2["over"] >= 0) & (df2["over"] <= 5)]
powerplay.groupby(["batter"])["batsman_runs"].sum().sort_values(ascending=False)

batter
S Dhawan       3415
DA Warner      3318
V Kohli        2809
CH Gayle       2405
AM Rahane      2319
               ...
M Rawat           0
SN Thakur         0
JC Archer         0
GD Phillips       0
Z Khan            0
Name: batsman_runs, Length: 362, dtype: int64

In [137]:
#Find batsmen scoring most runs in death overs (16–20).
death=df2[(df2["over"]>=15) & (df2["over"]<=19)]
death.groupby(["batter"])["batsman_runs"].sum().sort_values().tail(5)

batter
RA Jadeja         1680
AB de Villiers    1868
KD Karthik        1904
KA Pollard        2032
MS Dhoni          3292
Name: batsman_runs, dtype: int64

In [138]:
#For each batting team, compute total boundaries.
boundary=df2[(df2["batsman_runs"]==4) | (df2["batsman_runs"]==6)]
boundary.groupby(["batting_team"])["batsman_runs"].count()

batting_team
Chennai Super Kings            4705
Deccan Chargers                1357
Delhi Capitals                 1902
Delhi Daredevils               2957
Gujarat Lions                   615
Gujarat Titans                  962
Kings XI Punjab                3706
Kochi Tuskers Kerala            223
Kolkata Knight Riders          4956
Lucknow Super Giants            909
Mumbai Indians                 5322
Pune Warriors                   721
Punjab Kings                   1235
Rajasthan Royals               4328
Rising Pune Supergiant          286
Rising Pune Supergiants         239
Royal Challengers Bangalore    4637
Royal Challengers Bengaluru     394
Sunrisers Hyderabad            3447
Name: batsman_runs, dtype: int64

In [140]:
#For each bowler, compute wickets per season (requires join with matches).
new1=df1[["id","season"]]
new2=df2[["match_id","bowler","is_wicket"]]
ex=pd.merge(new1,new2,left_on="id",right_on="match_id",how="inner")
wicket=ex[ex["is_wicket"]==1]
wicket.groupby(["season","bowler"])["is_wicket"].count()

season   bowler
2007/08  A Kumble              8
         A Mishra             11
         A Nehra              14
         A Nel                 1
         AA Noffke             1
                              ..
2024     Washington Sundar     1
         YS Chahal            19
         Yash Dayal           16
         Yash Thakur          12
         Yudhvir Singh         1
Name: is_wicket, Length: 1625, dtype: int64

In [141]:
#For each match, compute number of dot balls.
dot=df2[df2["total_runs"]==0]
dot.groupby(["match_id"])["total_runs"].count()

match_id
335982      86
335983      57
335984      85
335985      81
335986     123
          ...
1426307     64
1426309     70
1426310     71
1426311     94
1426312     74
Name: total_runs, Length: 1095, dtype: int64

In [142]:
#For each bowling team, compute wides conceded.
wide=df2[df2["extras_type"]=="wides"]
wide.groupby(["bowling_team"])["extras_type"].count()

bowling_team
Chennai Super Kings             946
Deccan Chargers                 280
Delhi Capitals                  387
Delhi Daredevils                550
Gujarat Lions                    91
Gujarat Titans                  149
Kings XI Punjab                 720
Kochi Tuskers Kerala             52
Kolkata Knight Riders           848
Lucknow Super Giants            193
Mumbai Indians                 1090
Pune Warriors                   120
Punjab Kings                    234
Rajasthan Royals                949
Rising Pune Supergiant           62
Rising Pune Supergiants          56
Royal Challengers Bangalore     951
Royal Challengers Bengaluru      85
Sunrisers Hyderabad             617
Name: extras_type, dtype: int64

In [146]:
#Identify top scorers in each match.
top = df2.groupby(["match_id", "batter"])["batsman_runs"].sum().reset_index()

for i in top["match_id"].unique():
    scores = top[top["match_id"] == i]
    print(scores[scores["batsman_runs"] == scores["batsman_runs"].max()])

   match_id       batter  batsman_runs
2    335982  BB McCullum           158
    match_id      batter  batsman_runs
21    335983  MEK Hussey           116
    match_id     batter  batsman_runs
31    335984  G Gambhir            58
    match_id      batter  batsman_runs
52    335985  RV Uthappa            48
    match_id     batter  batsman_runs
61    335986  DJ Hussey            38
    match_id     batter  batsman_runs
86    335987  SR Watson            76
    match_id    batter  batsman_runs
99    335988  V Sehwag            94
     match_id     batter  batsman_runs
111    335989  ML Hayden            81
     match_id     batter  batsman_runs
119    335990  A Symonds           117
     match_id         batter  batsman_runs
143    335991  KC Sangakkara            94
     match_id     batter  batsman_runs
167    335992  SR Watson            61
     match_id     batter  batsman_runs
177    335993  ML Hayden            70
     match_id        batter  batsman_runs
184    335994  AC Gilchrist           109
     match_id     batter  batsman_runs
205    335995  SM Katich            75
     match_id    batter  batsman_runs
218    335996  MS Dhoni            65
     match_id    batter  batsman_runs
231    335997  DJ Bravo            64
     match_id     batter  batsman_runs
241    335998  G Gambhir            86
     match_id    batter  batsman_runs
265    335999  SE Marsh            84
     match_id       batter  batsman_runs
281    336000  SA Asnodkar            60
     match_id    batter  batsman_runs
300    336001  V Sehwag            71
     match_id    batter  batsman_runs
306    336002  HH Gibbs            47
     match_id     batter  batsman_runs
320    336003  DJ Hussey            71
     match_id    batter  batsman_runs
350    336004  V Sehwag            40
     match_id     batter  batsman_runs
354    336005  JA Morkel            42
     match_id    batter  batsman_runs
378    336006  R Dravid            66
     match_id        batter  batsman_runs
385    336007  AC Gilchrist            54
     match_id       batter  batsman_runs
407    336008  SA Asnodkar            39
     match_id     batter  batsman_runs
417    336009  G Gambhir            80
     match_id      batter  batsman_runs
437    336010  MV Boucher            50
     match_id     batter  batsman_runs
458    336011  YK Pathan            68
     match_id         batter  batsman_runs
469    336012  ST Jayasuriya            54
     match_id       batter  batsman_runs
479    336013  S Badrinath            64
     match_id      batter  batsman_runs
497    336014  SC Ganguly            91
     match_id     batter  batsman_runs
515    336015  SR Watson            74
     match_id    batter  batsman_runs
530    336016  SE Marsh            74
     match_id       batter  batsman_runs
545    336017  Salman Butt            48
     match_id         batter  batsman_runs
560    336018  ST Jayasuriya           114
     match_id    batter  batsman_runs
569    336019  SE Marsh           115
     match_id     batter  batsman_runs
577    336020  G Gambhir            79
     match_id         batter  batsman_runs
602    336021  ST Jayasuriya            48
     match_id    batter  batsman_runs
615    336022  V Sehwag            51
     match_id    batter  batsman_runs
621    336023  GC Smith            75
626    336023  R Dravid            75
     match_id           batter  batsman_runs
647    336024  Y Venugopal Rao            57
     match_id       batter  batsman_runs
656    336025  Salman Butt            73
     match_id      batter  batsman_runs
670    336026  SP Goswami            52
     match_id     batter  batsman_runs
689    336027  YK Pathan            48
     match_id    batter  batsman_runs
701    336028  SE Marsh            81
     match_id    batter  batsman_runs
719    336029  R Dravid            47
     match_id    batter  batsman_runs
736    336031  SE Marsh            60
     match_id         batter  batsman_runs
751    336032  ST Jayasuriya            66
     match_id    batter  batsman_runs
755    336033  GC Smith            91
     match_id     batter  batsman_runs
777    336034  RG Sharma            57
     match_id      batter  batsman_runs
794    336035  SC Ganguly            86
     match_id    batter  batsman_runs
806    336036  NK Patel            40
     match_id    batter  batsman_runs
827    336037  SK Raina            54
     match_id     batter  batsman_runs
846    336038  SR Watson            52
     match_id    batter  batsman_runs
862    336039  SK Raina            55
     match_id     batter  batsman_runs
880    336040  YK Pathan            56
     match_id        batter  batsman_runs
894    392181  SR Tendulkar            59
     match_id    batter  batsman_runs
909    392182  R Dravid            66
     match_id    batter  batsman_runs
921    392183    K Goel            38
924    392183  V Sehwag            38
     match_id    batter  batsman_runs
933    392184  HH Gibbs            43
     match_id     batter  batsman_runs
948    392185  ML Hayden            65
     match_id    batter  batsman_runs
960    392186  CH Gayle            44
     match_id        batter  batsman_runs
970    392188  AC Gilchrist            71
     match_id          batter  batsman_runs
988    392189  AB de Villiers           105
      match_id     batter  batsman_runs
1018    392190  YK Pathan            60
      match_id     batter  batsman_runs
1032    392191  RS Bopara            84
      match_id    batter  batsman_runs
1042    392192  HH Gibbs            58
      match_id      batter  batsman_runs
1066    392194  TM Dilshan            67
      match_id         batter  batsman_runs
1074    392195  KC Sangakkara            60
      match_id    batter  batsman_runs
1088    392196  HH Gibbs            69
      match_id        batter  batsman_runs
1112    392197  SR Tendulkar            68
      match_id     batter  batsman_runs
1131    392198  YK Pathan            62
      match_id      batter  batsman_runs
1140    392199  MN van Wyk            43
1144    392199  SP Goswami            43
      match_id     batter  batsman_runs
1152    392200  JP Duminy            59
      match_id      batter  batsman_runs
1177    392201  TM Dilshan            52
      match_id    batter  batsman_runs
1193    392202  SK Raina            98
      match_id    batter  batsman_runs
1200    392203  BJ Hodge            73
      match_id        batter  batsman_runs
1230    392204  Yuvraj Singh            50
      match_id    batter  batsman_runs
1244    392205  TL Suman            41
      match_id      batter  batsman_runs
1252    392206  KD Karthik            52
      match_id    batter  batsman_runs
1266    392207  BJ Hodge            70
      match_id     batter  batsman_runs
1279    392208  JH Kallis            69
      match_id    batter  batsman_runs
1291    392209  MS Dhoni            58
      match_id    batter  batsman_runs
1303    392210  GC Smith            77
      match_id      batter  batsman_runs
1322    392211  MN van Wyk            74
      match_id     batter  batsman_runs
1333    392212  JP Duminy            52
      match_id   batter  batsman_runs
1348    392213  NV Ojha            52
      match_id     batter  batsman_runs
1361    392214  ML Hayden            89
      match_id          batter  batsman_runs
1368    392215  AB de Villiers            50
      match_id     batter  batsman_runs
1383    392216  A Symonds            60
      match_id       batter  batsman_runs
1406    392217  S Badrinath            59
      match_id     batter  batsman_runs
1413    392218  AM Rahane            62
      match_id      batter  batsman_runs
1435    392219  SC Ganguly            44
      match_id    batter  batsman_runs
1443    392220  DR Smith            47
      match_id       batter  batsman_runs
1460    392221  BB McCullum            84
      match_id    batter  batsman_runs
1472    392222  DJ Bravo            70
      match_id        batter  batsman_runs
1487    392223  AC Gilchrist            64
      match_id     batter  batsman_runs
1511    392224  ML Hayden            60
      match_id     batter  batsman_runs
1534    392225  RJ Quiney            51
      match_id         batter  batsman_runs
1546    392226  KC Sangakkara            43
      match_id     batter  batsman_runs
1561    392227  JP Duminy            62
      match_id    batter  batsman_runs
1572    392228  BJ Hodge            48
      match_id         batter  batsman_runs
1587    392229  KC Sangakkara            56
      match_id          batter  batsman_runs
1600    392230  AB de Villiers            79
      match_id       batter  batsman_runs
1615    392231  BB McCullum            81
      match_id     batter  batsman_runs
1629    392232  JH Kallis            58
      match_id     batter  batsman_runs
1645    392233  LR Shukla            48
      match_id    batter  batsman_runs
1668    392234  PA Patel            32
      match_id     batter  batsman_runs
1682    392235  AM Rahane            56
      match_id     batter  batsman_runs
1701    392236  MK Pandey           114
      match_id        batter  batsman_runs
1713    392237  AC Gilchrist            85
      match_id     batter  batsman_runs
1728    392238  MK Pandey            48
      match_id    batter  batsman_runs
1741    392239  HH Gibbs            53
      match_id      batter  batsman_runs
1758    419106  AD Mathews            65
      match_id     batter  batsman_runs
1786    419107  YK Pathan           100
      match_id     batter  batsman_runs
1789    419108  G Gambhir            72
      match_id     batter  batsman_runs
1808    419109  JH Kallis            65
      match_id     batter  batsman_runs
1819    419110  A Symonds            50
      match_id    batter  batsman_runs
1848    419111  V Sehwag            75
      match_id     batter  batsman_runs
1852    419112  JH Kallis            89
      match_id    batter  batsman_runs
1867    419113  MS Dhoni            66
      match_id        batter  batsman_runs
1887    419114  SR Tendulkar            63
      match_id     batter  batsman_runs
1894    419115  JH Kallis            44
      match_id     batter  batsman_runs
1913    419116  ML Hayden            93
      match_id     batter  batsman_runs
1927    419117  IK Pathan            60
      match_id           batter  batsman_runs
1940    419118  AA Jhunjhunwala            45
      match_id     batter  batsman_runs
1960    419119  JH Kallis            66
      match_id     batter  batsman_runs
1974    419120  DA Warner            57
      match_id    batter  batsman_runs
1999    419121  PA Patel            57
      match_id    batter  batsman_runs
2008    419122  CH Gayle            75
      match_id      batter  batsman_runs
2028    419123  RV Uthappa            68
      match_id    batter  batsman_runs
2032    419124  AC Voges            45
2034    419124  FY Fazal            45
      match_id    batter  batsman_runs
2057    419125  SK Raina            83
      match_id     batter  batsman_runs
2073    419126  YK Pathan            73
      match_id     batter  batsman_runs
2082    419127  MK Tiwary            75
      match_id     batter  batsman_runs
2096    419128  KM Jadhav            50
      match_id   batter  batsman_runs
2114    419129  NV Ojha            80
      match_id        batter  batsman_runs
2137    419130  SR Tendulkar            55
      match_id     batter  batsman_runs
2145    419131  DA Warner           107
      match_id    batter  batsman_runs
2170    419132  SE Marsh            57
      match_id   batter  batsman_runs
2180    419133  M Vijay            78
      match_id      batter  batsman_runs
2194    419134  KD Karthik            69
      match_id      batter  batsman_runs
2217    419135  SC Ganguly            88
      match_id        batter  batsman_runs
2225    419136  KP Pietersen            66
      match_id   batter  batsman_runs
2237    419137  M Vijay           127
      match_id     batter  batsman_runs
2248    419138  AT Rayudu            55
      match_id            batter  batsman_runs
2266    419139  DPMD Jayawardene           110
      match_id          batter  batsman_runs
2284    419140  PD Collingwood            75
      match_id     batter  batsman_runs
2302    419141  RG Sharma            73
      match_id        batter  batsman_runs
2324    419142  SR Tendulkar            45
      match_id   batter  batsman_runs
2330    419143  MJ Lumb            83
      match_id    batter  batsman_runs
2351    419144  V Sehwag            64
      match_id    batter  batsman_runs
2362    419145  TL Suman            78
      match_id         batter  batsman_runs
2371    419146  KC Sangakkara            56
      match_id    batter  batsman_runs
2394    419147  TL Suman            55
      match_id    batter  batsman_runs
2406    419148  R Dravid            52
      match_id            batter  batsman_runs
2416    419149  DPMD Jayawardene            38
      match_id        batter  batsman_runs
2438    419150  SR Tendulkar            89
      match_id     batter  batsman_runs
2457    419151  RG Sharma            51
      match_id      batter  batsman_runs
2470    419152  KA Pollard            45
      match_id    batter  batsman_runs
2488    419153  SK Raina            78
      match_id        batter  batsman_runs
2495    419154  KP Pietersen            62
      match_id     batter  batsman_runs
2507    419155  G Gambhir            57
      match_id            batter  batsman_runs
2524    419156  DPMD Jayawardene            93
      match_id     batter  batsman_runs
2535    419157  AT Rayudu            46
      match_id      batter  batsman_runs
2559    419158  SC Ganguly            75
      match_id    batter  batsman_runs
2572    419159  SE Marsh            88
      match_id     batter  batsman_runs
2577    419160  A Symonds            54
      match_id       batter  batsman_runs
2595    419161  BB McCullum            57
      match_id     batter  batsman_runs
2621    419162  SS Tiwary            52
      match_id       batter  batsman_runs
2639    419163  S Badrinath            37
      match_id         batter  batsman_runs
2644    419164  Anirudh Singh            40
      match_id    batter  batsman_runs
2668    419165  SK Raina            57
      match_id      batter  batsman_runs
2684    501198  S Anirudha            64
      match_id   batter  batsman_runs
2696    501199  J Botha            67
      match_id          batter  batsman_runs
2702    501200  AB de Villiers            54
      match_id        batter  batsman_runs
2725    501201  SR Tendulkar            46
      match_id     batter  batsman_runs
2740    501202  R McLaren            51
      match_id     batter  batsman_runs
2753    501203  JH Kallis            53
      match_id           batter  batsman_runs
2773    501204  Y Venugopal Rao            60
      match_id     batter  batsman_runs
2775    501205  AT Rayudu            63
      match_id       batter  batsman_runs
2788    501206  PC Valthaty           120
      match_id     batter  batsman_runs
2804    501207  RA Jadeja            47
      match_id   batter  batsman_runs
2827    501208  V Kohli            71
      match_id     batter  batsman_runs
2833    501209  JH Kallis            80
      match_id        batter  batsman_runs
2844    501210  SR Tendulkar           100
      match_id      batter  batsman_runs
2853    501211  MEK Hussey            83
      match_id       batter  batsman_runs
2871    501212  PC Valthaty            75
      match_id        batter  batsman_runs
2888    501213  Yuvraj Singh            66
      match_id     batter  batsman_runs
2895    501214  G Gambhir            35
      match_id    batter  batsman_runs
2914    501215  SK Raina            50
      match_id   batter  batsman_runs
2926    501216  S Sohal            62
      match_id      batter  batsman_runs
2940    501218  RV Uthappa            45
      match_id     batter  batsman_runs
2956    501219  MK Tiwary            46
      match_id    batter  batsman_runs
2978    501220  SE Marsh            71
      match_id     batter  batsman_runs
2994    501221  RG Sharma            87
      match_id    batter  batsman_runs
3001    501222  CH Gayle           102
      match_id    batter  batsman_runs
3017    501223  SE Marsh            95
      match_id     batter  batsman_runs
3034    501224  RG Sharma            56
      match_id     batter  batsman_runs
3051    501225  SR Watson            49
      match_id      batter  batsman_runs
3061    501226  MEK Hussey            61
      match_id   batter  batsman_runs
3084    501227  V Kohli            56
      match_id       batter  batsman_runs
3097    501228  S Badrinath            63
      match_id         batter  batsman_runs
3108    501229  KC Sangakkara            65
      match_id     batter  batsman_runs
3129    501230  MK Tiwary            61
      match_id   batter  batsman_runs
3145    501231  J Botha            45
      match_id   batter  batsman_runs
3165    501232  V Kohli            67
      match_id    batter  batsman_runs
3183    501233  V Sehwag            80
      match_id     batter  batsman_runs
3191    501234  G Gambhir            45
      match_id       batter  batsman_runs
3203    501235  LRPL Taylor            47
      match_id    batter  batsman_runs
3227    501236  SK Raina            59
      match_id    batter  batsman_runs
3242    501237  SE Marsh            61
      match_id           batter  batsman_runs
3256    501238  Y Venugopal Rao            40
      match_id    batter  batsman_runs
3267    501239  S Dhawan            54
      match_id      batter  batsman_runs
3276    501240  MEK Hussey            79
      match_id     batter  batsman_runs
3290    501241  MK Pandey            59
      match_id      batter  batsman_runs
3302    501242  EJG Morgan            66
      match_id    batter  batsman_runs
3325    501243  V Sehwag           119
      match_id    batter  batsman_runs
3333    501244  CH Gayle           107
      match_id       batter  batsman_runs
3354    501245  S Badrinath            54
      match_id     batter  batsman_runs
3359    501246  AT Rayudu            59
      match_id      batter  batsman_runs
3384    501247  TM Dilshan            52
      match_id        batter  batsman_runs
3402    501248  Yuvraj Singh            35
      match_id   batter  batsman_runs
3411    501249  M Vijay            53
      match_id     batter  batsman_runs
3427    501250  MK Pandey            49
      match_id    batter  batsman_runs
3449    501251  SE Marsh            43
      match_id    batter  batsman_runs
3456    501252  CH Gayle            70
      match_id    batter  batsman_runs
3471    501253  MS Dhoni            63
      match_id            batter  batsman_runs
3481    501254  DPMD Jayawardene            76
      match_id    batter  batsman_runs
3492    501255  CH Gayle            38
      match_id        batter  batsman_runs
3518    501256  SR Tendulkar            37
      match_id       batter  batsman_runs
3529    501257  PC Valthaty            62
      match_id    batter  batsman_runs
3542    501258  BJ Hodge            33
      match_id    batter  batsman_runs
3562    501259  MR Marsh            37
      match_id        batter  batsman_runs
3571    501260  AC Gilchrist           106
      match_id    batter  batsman_runs
3585    501261  BJ Hodge            51
      match_id     batter  batsman_runs
3599    501262  G Gambhir            54
      match_id     batter  batsman_runs
3618    501263  SR Watson            89
      match_id    batter  batsman_runs
3633    501264  S Dhawan            95
      match_id     batter  batsman_runs
3636    501265  DA Warner            19
      match_id    batter  batsman_runs
3641    501266  CH Gayle            75
      match_id     batter  batsman_runs
3657    501267  JH Kallis            59
      match_id    batter  batsman_runs
3677    501268  SK Raina            73
      match_id            batter  batsman_runs
3690    501269  RN ten Doeschate            70

In [147]:
#Compute average runs per wicket for each bowler.
runs=df2.groupby(["bowler"])["total_runs"].sum()
wicket=df2[df2["is_wicket"]==1]
wick=wicket.groupby(["bowler"])["is_wicket"].count()
average=runs/wick
average

bowler
A Ashish Reddy    21.052632
A Badoni          18.500000
A Chandila        22.272727
A Choudhary       28.800000
A Dananjaya             NaN
                    ...
Yash Dayal        30.096774
Yash Thakur       26.000000
Yudhvir Singh     31.250000
Yuvraj Singh      27.974359
Z Khan            24.033613
Length: 530, dtype: float64

In [148]:
#Compute runs conceded by each bowler to each batsman.
df2.groupby(["bowler","batter"])["total_runs"].sum()

bowler          batter
A Ashish Reddy  AB de Villiers     48
                AC Thomas          10
                AD Mathews          3
                AD Russell          1
                AL Menaria          9
                                   ..
Z Khan          WA Mota             1
                WP Saha            39
                Y Venugopal Rao     9
                YK Pathan          35
                Yuvraj Singh       12
Name: total_runs, Length: 27881, dtype: int64

In [151]:
#For each inning, find cumulative runs over overs.
runs=df2.groupby(["inning","over"])["total_runs"].sum().reset_index()

runs["cumulative_runs"] = runs.groupby("inning")["total_runs"].cumsum()
runs

    inning  over  total_runs  cumulative_runs
0        1     0        6425             6425
1        1     1        7861            14286
2        1     2        8783            23069
3        1     3        8903            31972
4        1     4        9364            41336
5        1     5        9245            50581
6        1     6        7329            57910
7        1     7        7993            65903
8        1     8        8245            74148
9        1     9        8340            82488
10       1    10        8470            90958
11       1    11        8664            99622
12       1    12        8607           108229
13       1    13        9065           117294
14       1    14        9615           126909
15       1    15        9639           136548
16       1    16       10252           146800
17       1    17       10853           157653
18       1    18       11522           169175
19       1    19       12099           181274
20       2     0        6940             6940
21       2     1        8302            15242
22       2     2        9112            24354
23       2     3        9512            33866
24       2     4        9201            43067
25       2     5        9283            52350
26       2     6        7510            59860
27       2     7        7988            67848
28       2     8        8394            76242
29       2     9        8013            84255
30       2    10        8309            92564
31       2    11        8412           100976
32       2    12        8598           109574
33       2    13        8569           118143
34       2    14        8534           126677
35       2    15        8833           135510
36       2    16        8760           144270
37       2    17        8706           152976
38       2    18        7554           160530
39       2    19        5666           166196
40       3     0         137              137
41       4     0         123              123
42       5     0          11               11
43       6     0          15               15

In [154]:
#Find bowlers with most maidens (if maiden can be computed).
run=df2.groupby(["match_id","inning","bowler","over"])["total_runs"].sum().reset_index()
zero=run[run["total_runs"]==0]
zero.groupby(["bowler"])["over"].count().sort_values(ascending=False)

bowler
P Kumar           12
B Kumar           11
IK Pathan          9
TA Boult           9
SL Malinga         8
                  ..
L Ngidi            1
KR Sen             1
K Gowtham          1
JW Hastings        1
MJ McClenaghan     1
Name: over, Length: 157, dtype: int64

In [157]:
#For each match, find batsmen who faced more than 20 balls.
nowide=df2[df2["extras_type"]!="wides"]
balls=nowide.groupby(["match_id","batter"])["ball"].count()
balls[balls>20]

match_id  batter
335982    BB McCullum           73
335983    JR Hopes              33
          KC Sangakkara         33
          MEK Hussey            54
335984    G Gambhir             46
                                ..
1426311   TM Head               28
          YBK Jaiswal           21
1426312   AK Markram            23
          Rahmanullah Gurbaz    32
          VR Iyer               26
Name: ball, Length: 4533, dtype: int64

In [158]:
#For each match, find strike rate of all batsmen.
runs=df2.groupby(["match_id","batter"])["batsman_runs"].sum()
nowide=df2[df2["extras_type"]!="wides"]
balls=nowide.groupby(["match_id","batter"])["ball"].count()
strike=(runs/balls)*100
strike

match_id  batter
335982    AA Noffke         90.000000
          B Akhil            0.000000
          BB McCullum      216.438356
          CL White          60.000000
          DJ Hussey        100.000000
                              ...
1426312   SP Narine        300.000000
          SS Iyer          200.000000
          Shahbaz Ahmed    114.285714
          TM Head            0.000000
          VR Iyer          200.000000
Length: 16515, dtype: float64

In [159]:
#For each match, compute total deliveries that resulted in extra
deliv=df2[df2["extra_runs"]>0]
deliv.groupby(["match_id"])["extra_runs"].count()

match_id
335982     24
335983     16
335984     12
335985     13
335986     24
           ..
1426307    19
1426309    12
1426310    10
1426311    13
1426312    16
Name: extra_runs, Length: 1095, dtype: int64