## Admission dataset

In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("Admission_Predict.csv")
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
1,2,324,107,4,4.0,4.5,8.87,1,1
2,3,316,104,3,3.0,3.5,8.00,1,0
3,4,322,110,3,3.5,2.5,8.67,1,1
4,5,314,103,2,2.0,3.0,8.21,0,0
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
398,399,312,103,3,3.5,4.0,8.78,0,0
399,400,333,117,4,5.0,4.0,9.66,1,1

In [5]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR', 'CGPA', 'Research', 'Chance of Admit'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    int64
dtypes: float64(3), int64(6)
memory usage: 28.3 KB

In [9]:
#Display all rows where GRE Score is greater than 320.
df[df["GRE Score"]>320]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
1,2,324,107,4,4.0,4.5,8.87,1,1
3,4,322,110,3,3.5,2.5,8.67,1,1
5,6,330,115,5,4.5,3.0,9.34,1,1
6,7,321,109,3,3.0,4.0,8.20,1,1
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,1
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
399,400,333,117,4,5.0,4.0,9.66,1,1

In [10]:
#Show applicants whose TOEFL Score is less than 100.
df[df["TOEFL Score"]<100]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
27,28,298,98,2,1.5,2.5,7.50,1,0
28,29,295,93,1,2.0,2.0,7.20,0,0
29,30,310,99,2,1.5,2.0,7.30,0,0
30,31,300,97,2,3.0,3.0,8.10,1,0
50,51,313,98,3,2.5,4.5,8.30,1,1
57,58,298,99,2,4.0,2.0,7.60,0,0
58,59,300,99,1,3.0,2.0,6.80,1,0
77,78,301,99,2,3.0,2.0,8.22,0,0
78,79,296,95,2,3.0,2.0,7.54,1,0
79,80,294,93,1,1.5,2.0,7.36,0,0
91,92,299,97,3,5.0,3.5,7.66,0,0
92,93,298,98,2,4.0,3.0,8.03,0,0
93,94,301,97,2,3.0,3.0,7.88,1,0
94,95,303,99,3,2.0,2.5,7.66,0,0
118,119,296,99,2,3.0,3.5,7.28,0,0
161,162,298,99,1,1.5,3.0,7.46,0,0
168,169,293,97,2,2.0,4.0,7.80,1,0
169,170,311,99,2,2.5,3.0,7.98,0,0
205,206,295,99,2,2.5,3.0,7.65,0,0
206,207,315,99,2,3.5,3.0,7.89,0,0
225,226,296,99,2,2.5,2.5,8.03,0,0
251,252,316,99,2,2.5,3.0,9.00,0,0
256,257,309,99,3,4.0,4.0,8.56,0,1
271,272,299,96,2,1.5,2.0,7.86,0,0
272,273,294,95,1,1.5,1.5,7.64,0,0
273,274,312,99,1,1.0,1.5,8.01,1,0
292,293,302,99,2,1.0,2.0,7.97,0,0
293,294,312,98,1,3.5,3.0,8.18,1,0
317,318,300,99,1,1.0,2.5,8.01,0,0
329,330,297,96,2,2.5,1.5,7.89,0,0
344,345,295,96,2,1.5,2.0,7.34,0,0
345,346,316,98,1,1.5,2.0,7.43,0,0
346,347,304,97,2,1.5,2.0,7.64,0,0
347,348,299,94,1,1.0,1.0,7.34,0,0
348,349,302,99,1,2.0,2.0,7.25,0,0
354,355,297,98,2,2.5,3.0,7.67,0,0
367,368,311,98,1,1.0,2.5,7.46,0,0
368,369,298,92,1,2.0,2.0,7.88,0,0
369,370,301,98,1,2.0,3.0,8.03,1,0
376,377,297,96,2,2.5,2.0,7.43,0,0
378,379,303,98,1,2.0,2.5,7.65,0,0
379,380,311,99,1,2.5,3.0,8.43,1,0
388,389,296,97,2,1.5,2.0,7.80,0,0

In [11]:
#Get records where University Rating equals 5.
df[df["University Rating"]==5]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
5,6,330,115,5,4.5,3.0,9.34,1,1
22,23,328,116,5,5.0,5.0,9.50,1,1
23,24,334,119,5,5.0,4.5,9.70,1,1
24,25,336,119,5,4.0,3.5,9.80,1,1
25,26,340,120,5,4.5,4.5,9.60,1,1
26,27,322,109,5,4.5,3.5,8.80,0,1
33,34,340,114,5,4.0,4.0,9.60,1,1
34,35,331,112,5,4.0,5.0,9.80,1,1
35,36,320,110,5,5.0,5.0,9.20,1,1
44,45,326,113,5,4.5,4.0,9.40,1,1
45,46,322,110,5,5.0,4.0,9.10,1,1
46,47,329,114,5,4.0,5.0,9.30,1,1
47,48,339,119,5,4.5,4.0,9.70,0,1
70,71,332,118,5,5.0,5.0,9.64,1,1
71,72,336,112,5,5.0,5.0,9.76,1,1
72,73,321,111,5,5.0,5.0,9.45,1,1
82,83,320,110,5,5.0,4.5,9.22,1,1
83,84,322,115,5,4.0,4.5,9.36,1,1
84,85,340,115,5,4.5,4.5,9.45,1,1
108,109,331,116,5,5.0,5.0,9.38,1,1
109,110,304,103,5,5.0,4.0,8.64,0,0
110,111,305,108,5,3.0,3.0,8.48,0,0
119,120,327,104,5,3.0,3.5,8.84,1,0
120,121,335,117,5,5.0,5.0,9.56,1,1
121,122,334,119,5,4.5,4.5,9.48,1,1
129,130,333,118,5,5.0,5.0,9.35,1,1
130,131,339,114,5,4.0,4.5,9.76,1,1
131,132,303,105,5,5.0,4.5,8.65,0,1
132,133,309,105,5,3.5,3.5,8.56,0,0
133,134,323,112,5,4.0,4.5,8.78,0,1
134,135,333,113,5,4.0,4.0,9.28,1,1
142,143,331,115,5,4.0,3.5,9.44,1,1
151,152,332,116,5,5.0,5.0,9.28,1,1
152,153,321,112,5,5.0,5.0,9.06,1,1
165,166,322,110,5,4.5,4.0,8.97,0,1
171,172,334,117,5,4.0,4.5,9.07,1,1
187,188,335,118,5,4.5,3.5,9.44,1,1
188,189,331,115,5,4.5,3.5,9.36,1,1
189,190,324,112,5,5.0,5.0,9.08,1,1
190,191,324,111,5,4.5,4.0,9.16,1,1
191,192,323,110,5,4.0,5.0,8.98,1,1
192,193,322,114,5,4.5,4.0,8.94,1,1
193,194,336,118,5,4.5,5.0,9.53,1,1
202,203,340,120,5,4.5,4.5,9.91,1,1
203,204,334,120,5,4.0,5.0,9.87,1,1
213,214,333,119,5,5.0,4.5,9.78,1,1
215,216,330,116,5,5.0,4.5,9.36,1,1
234,235,330,113,5,5.0,4.0,9.31,1,1
235,236,326,111,5,4.5,4.0,9.23,1,1
237,238,329,114,5,4.5,5.0,9.19,1,1
260,261,327,108,5,5.0,3.5,9.13,1,1
276,277,329,113,5,5.0,4.5,9.45,1,1
285,286,331,116,5,4.0,4.0,9.26,1,1
286,287,336,118,5,4.5,4.0,9.19,1,1
287,288,324,114,5,5.0,4.5,9.08,1,1
337,338,332,118,5,5.0,5.0,9.47,1,1
338,339,323,108,5,4.0,4.0,8.74,1,1
339,340,324,107,5,3.5,4.0,8.66,1,1
362,363,338,115,5,4.5,5.0,9.23,1,1
385,386,335,117,5,5.0,5.0,9.82,1,1

In [12]:
#Select all students who have done Research (value 1).
df[df["Research"]==1]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
1,2,324,107,4,4.0,4.5,8.87,1,1
2,3,316,104,3,3.0,3.5,8.00,1,0
3,4,322,110,3,3.5,2.5,8.67,1,1
5,6,330,115,5,4.5,3.0,9.34,1,1
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,1
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
399,400,333,117,4,5.0,4.0,9.66,1,1

In [13]:
#Display students who have not done Research (value 0).
df[df["Research"]!=1]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
4,5,314,103,2,2.0,3.0,8.21,0,0
7,8,308,101,2,3.0,4.0,7.90,0,0
8,9,302,102,1,2.0,1.5,8.00,0,0
9,10,323,108,3,3.5,3.0,8.60,0,0
15,16,314,105,3,3.5,2.5,8.30,0,0
...,...,...,...,...,...,...,...,...,...
388,389,296,97,2,1.5,2.0,7.80,0,0
390,391,314,102,2,2.0,2.5,8.24,0,0
391,392,318,106,3,2.0,3.0,8.65,0,0
393,394,317,104,2,3.0,3.0,8.76,0,1
398,399,312,103,3,3.5,4.0,8.78,0,0

In [14]:
#Find applicants with CGPA greater than 9.0.
df[df["CGPA"]>9.0]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
5,6,330,115,5,4.5,3.0,9.34,1,1
12,13,328,112,4,4.0,4.5,9.10,1,1
22,23,328,116,5,5.0,5.0,9.50,1,1
23,24,334,119,5,5.0,4.5,9.70,1,1
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,1
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
399,400,333,117,4,5.0,4.0,9.66,1,1

In [17]:
#Retrieve records where both GRE Score &gt; 320 and CGPA &gt; 9.0.
df[(df["GRE Score"]>320) & (df["CGPA"]>9.0)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
5,6,330,115,5,4.5,3.0,9.34,1,1
12,13,328,112,4,4.0,4.5,9.10,1,1
22,23,328,116,5,5.0,5.0,9.50,1,1
23,24,334,119,5,5.0,4.5,9.70,1,1
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,1
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
399,400,333,117,4,5.0,4.0,9.66,1,1

In [18]:
#Display records where either SOP or LOR rating is 5.0.
df[(df["SOP"]==5.0) | (df["LOR"]==5.0)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
22,23,328,116,5,5.0,5.0,9.50,1,1
23,24,334,119,5,5.0,4.5,9.70,1,1
34,35,331,112,5,4.0,5.0,9.80,1,1
35,36,320,110,5,5.0,5.0,9.20,1,1
45,46,322,110,5,5.0,4.0,9.10,1,1
46,47,329,114,5,4.0,5.0,9.30,1,1
48,49,321,110,3,3.5,5.0,8.85,1,1
70,71,332,118,5,5.0,5.0,9.64,1,1
71,72,336,112,5,5.0,5.0,9.76,1,1
72,73,321,111,5,5.0,5.0,9.45,1,1
74,75,314,106,3,3.0,5.0,8.90,0,0
81,82,340,120,4,5.0,5.0,9.50,1,1
82,83,320,110,5,5.0,4.5,9.22,1,1
91,92,299,97,3,5.0,3.5,7.66,0,0
98,99,332,119,4,5.0,4.5,9.24,1,1
108,109,331,116,5,5.0,5.0,9.38,1,1
109,110,304,103,5,5.0,4.0,8.64,0,0
120,121,335,117,5,5.0,5.0,9.56,1,1
129,130,333,118,5,5.0,5.0,9.35,1,1
131,132,303,105,5,5.0,4.5,8.65,0,1
136,137,312,103,3,5.0,4.0,8.45,0,1
151,152,332,116,5,5.0,5.0,9.28,1,1
152,153,321,112,5,5.0,5.0,9.06,1,1
166,167,302,102,3,3.5,5.0,8.33,0,0
172,173,322,110,4,4.0,5.0,9.13,1,1
189,190,324,112,5,5.0,5.0,9.08,1,1
191,192,323,110,5,4.0,5.0,8.98,1,1
193,194,336,118,5,4.5,5.0,9.53,1,1
203,204,334,120,5,4.0,5.0,9.87,1,1
211,212,328,110,4,5.0,4.0,9.14,1,1
212,213,338,120,4,5.0,5.0,9.66,1,1
213,214,333,119,5,5.0,4.5,9.78,1,1
214,215,331,117,4,4.5,5.0,9.42,1,1
215,216,330,116,5,5.0,4.5,9.36,1,1
234,235,330,113,5,5.0,4.0,9.31,1,1
237,238,329,114,5,4.5,5.0,9.19,1,1
254,255,321,114,4,4.0,5.0,9.12,0,1
257,258,324,100,3,4.0,5.0,8.64,1,1
258,259,326,102,4,5.0,5.0,8.76,1,1
259,260,331,119,4,5.0,4.5,9.34,1,1
260,261,327,108,5,5.0,3.5,9.13,1,1
268,269,327,113,4,4.5,5.0,9.14,0,1
269,270,308,108,4,4.5,5.0,8.34,0,1
276,277,329,113,5,5.0,4.5,9.45,1,1
284,285,340,112,4,5.0,4.5,9.66,1,1
287,288,324,114,5,5.0,4.5,9.08,1,1
288,289,314,104,4,5.0,5.0,9.02,0,1
337,338,332,118,5,5.0,5.0,9.47,1,1
360,361,322,110,3,4.0,5.0,8.64,1,1
362,363,338,115,5,4.5,5.0,9.23,1,1
384,385,340,113,4,5.0,5.0,9.74,1,1
385,386,335,117,5,5.0,5.0,9.82,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
399,400,333,117,4,5.0,4.0,9.66,1,1

In [19]:
#Get rows where Chance of Admit is above 0.8 and University Rating ≥ 4.
df[(df["Chance of Admit"]>0.8) & (df["University Rating"]>=4)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
1,2,324,107,4,4.0,4.5,8.87,1,1
5,6,330,115,5,4.5,3.0,9.34,1,1
11,12,327,111,4,4.0,4.5,9.00,1,1
12,13,328,112,4,4.0,4.5,9.10,1,1
...,...,...,...,...,...,...,...,...,...
385,386,335,117,5,5.0,5.0,9.82,1,1
392,393,326,112,4,4.0,3.5,9.12,1,1
394,395,329,111,4,4.5,4.0,9.23,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
399,400,333,117,4,5.0,4.0,9.66,1,1

In [20]:
#Find all rows where TOEFL Score is between 100 and 110.
df[(df["TOEFL Score"]>=100) & (df["TOEFL Score"]<=110)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
1,2,324,107,4,4.0,4.5,8.87,1,1
2,3,316,104,3,3.0,3.5,8.00,1,0
3,4,322,110,3,3.5,2.5,8.67,1,1
4,5,314,103,2,2.0,3.0,8.21,0,0
6,7,321,109,3,3.0,4.0,8.20,1,1
...,...,...,...,...,...,...,...,...,...
391,392,318,106,3,2.0,3.0,8.65,0,0
393,394,317,104,2,3.0,3.0,8.76,0,1
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
398,399,312,103,3,3.5,4.0,8.78,0,0

In [21]:
#Display data for students whose GRE Score is not equal to 300.
df[df["GRE Score"]!=300]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
1,2,324,107,4,4.0,4.5,8.87,1,1
2,3,316,104,3,3.0,3.5,8.00,1,0
3,4,322,110,3,3.5,2.5,8.67,1,1
4,5,314,103,2,2.0,3.0,8.21,0,0
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
398,399,312,103,3,3.5,4.0,8.78,0,0
399,400,333,117,4,5.0,4.0,9.66,1,1

In [22]:
#Show all students with CGPA less than 8 and Research = 1.
df[(df["CGPA"]<8) & (df["Research"]==1)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
20,21,312,107,3,3.0,2.0,7.90,1,0
27,28,298,98,2,1.5,2.5,7.50,1,0
51,52,312,100,2,1.5,3.5,7.90,1,0
58,59,300,99,1,3.0,2.0,6.80,1,0
78,79,296,95,2,3.0,2.0,7.54,1,0
90,91,318,106,2,4.0,4.0,7.92,1,0
93,94,301,97,2,3.0,3.0,7.88,1,0
168,169,293,97,2,2.0,4.0,7.80,1,0
357,358,301,104,2,3.5,3.5,7.89,1,0

In [24]:
#Retrieve rows where University Rating &lt; 3 and SOP &gt; 4.
df[(df["University Rating"]<3) & (df["SOP"]>4)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
103,104,317,104,2,4.5,4.0,8.47,0,0
138,139,326,116,2,4.5,3.0,9.08,1,1
141,142,332,118,2,4.5,3.5,9.36,1,1

In [25]:
#Get records of students having TOEFL Score &gt; 105 but GRE Score &lt; 310.
df[(df["TOEFL Score"]>105) & (df["GRE Score"]<310)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
13,14,307,109,3,4.0,3.0,8.00,1,0
36,37,299,106,2,4.0,4.0,8.40,0,0
39,40,307,108,2,4.0,3.5,7.70,0,0
40,41,308,110,3,3.5,3.0,8.00,1,0
110,111,305,108,5,3.0,3.0,8.48,0,0
112,113,301,107,3,3.5,3.5,8.34,1,0
123,124,308,108,3,3.5,3.5,8.22,0,0
124,125,301,106,4,2.5,3.0,8.47,0,0
158,159,306,106,2,2.0,2.5,8.14,0,0
178,179,309,108,3,2.5,3.0,8.12,0,0
181,182,305,107,2,2.5,2.5,8.42,0,0
195,196,307,107,2,3.0,3.5,8.52,1,1
208,209,305,106,2,3.0,3.0,8.16,0,0
223,224,308,109,2,3.0,4.0,8.45,0,0
226,227,306,110,2,3.5,4.0,8.45,0,0
255,256,307,110,4,4.0,4.5,8.37,0,1
269,270,308,108,4,4.5,5.0,8.34,0,1
299,300,305,112,3,3.0,3.5,8.65,0,0
300,301,309,106,2,2.5,2.5,8.00,0,0
309,310,308,110,4,3.5,3.0,8.60,0,0
332,333,308,106,3,3.5,2.5,8.21,1,1
342,343,308,106,3,3.0,3.0,8.24,0,0

In [26]:
#Display records where Chance of Admit &lt; 0.6 or GRE Score &lt; 300.
df[(df["Chance of Admit"]<0.6) | (df["GRE Score"])]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
1,2,324,107,4,4.0,4.5,8.87,1,1
2,3,316,104,3,3.0,3.5,8.00,1,0
3,4,322,110,3,3.5,2.5,8.67,1,1
4,5,314,103,2,2.0,3.0,8.21,0,0
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
398,399,312,103,3,3.5,4.0,8.78,0,0
399,400,333,117,4,5.0,4.0,9.66,1,1

In [28]:
#Find the top 10 students with the highest GRE Score.
df["GRE Score"].sort_values(ascending=False).head(10)

202    340
33     340
84     340
143    340
81     340
284    340
25     340
384    340
47     339
130    339
Name: GRE Score, dtype: int64

In [29]:
#Display applicants who scored exactly 4.5 in LOR.
df[df["LOR"]==4.5]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
1,2,324,107,4,4.0,4.5,8.87,1,1
11,12,327,111,4,4.0,4.5,9.00,1,1
12,13,328,112,4,4.0,4.5,9.10,1,1
23,24,334,119,5,5.0,4.5,9.70,1,1
25,26,340,120,5,4.5,4.5,9.60,1,1
32,33,338,118,4,3.0,4.5,9.40,1,1
50,51,313,98,3,2.5,4.5,8.30,1,1
82,83,320,110,5,5.0,4.5,9.22,1,1
83,84,322,115,5,4.0,4.5,9.36,1,1
84,85,340,115,5,4.5,4.5,9.45,1,1
98,99,332,119,4,5.0,4.5,9.24,1,1
105,106,316,110,3,4.0,4.5,8.78,1,0
106,107,329,111,4,4.5,4.5,9.18,1,1
107,108,338,117,4,3.5,4.5,9.46,1,1
115,116,310,106,4,4.5,4.5,9.04,1,0
121,122,334,119,5,4.5,4.5,9.48,1,1
130,131,339,114,5,4.0,4.5,9.76,1,1
131,132,303,105,5,5.0,4.5,8.65,0,1
133,134,323,112,5,4.0,4.5,8.78,0,1
171,172,334,117,5,4.0,4.5,9.07,1,1
173,174,323,113,4,4.0,4.5,9.23,1,1
176,177,329,119,4,4.5,4.5,9.16,1,1
185,186,327,113,4,4.5,4.5,9.11,1,1
198,199,311,104,3,4.5,4.5,8.43,0,0
199,200,313,107,3,4.0,4.5,8.69,0,0
202,203,340,120,5,4.5,4.5,9.91,1,1
213,214,333,119,5,5.0,4.5,9.78,1,1
215,216,330,116,5,5.0,4.5,9.36,1,1
216,217,322,112,4,4.5,4.5,9.26,1,1
230,231,313,104,3,4.0,4.5,8.65,0,0
236,237,325,112,4,4.0,4.5,9.17,1,1
253,254,335,115,4,4.5,4.5,9.68,1,1
255,256,307,110,4,4.0,4.5,8.37,0,1
259,260,331,119,4,5.0,4.5,9.34,1,1
276,277,329,113,5,5.0,4.5,9.45,1,1
281,282,317,110,3,4.0,4.5,9.11,1,1
284,285,340,112,4,5.0,4.5,9.66,1,1
287,288,324,114,5,5.0,4.5,9.08,1,1
297,298,320,120,3,4.0,4.5,9.11,0,1
298,299,330,114,3,4.5,4.5,9.24,1,1
312,313,311,107,4,4.5,4.5,9.00,1,1
335,336,325,111,4,4.0,4.5,9.11,1,1
366,367,320,104,3,3.5,4.5,8.34,1,0
397,398,330,116,4,5.0,4.5,9.45,1,1

In [33]:
#Select students whose SOP rating lies between 3 and 4 (inclusive).
df[(df["SOP"]>=3) & (df["SOP"]<=4)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
1,2,324,107,4,4.0,4.5,8.87,1,1
2,3,316,104,3,3.0,3.5,8.00,1,0
3,4,322,110,3,3.5,2.5,8.67,1,1
6,7,321,109,3,3.0,4.0,8.20,1,1
7,8,308,101,2,3.0,4.0,7.90,0,0
...,...,...,...,...,...,...,...,...,...
392,393,326,112,4,4.0,3.5,9.12,1,1
393,394,317,104,2,3.0,3.0,8.76,0,1
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
398,399,312,103,3,3.5,4.0,8.78,0,0

In [34]:
#Display all students whose University Rating is either 2 or 3.
df[(df["University Rating"]==2) | (df["University Rating"]==3)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
2,3,316,104,3,3.0,3.5,8.00,1,0
3,4,322,110,3,3.5,2.5,8.67,1,1
4,5,314,103,2,2.0,3.0,8.21,0,0
6,7,321,109,3,3.0,4.0,8.20,1,1
7,8,308,101,2,3.0,4.0,7.90,0,0
...,...,...,...,...,...,...,...,...,...
391,392,318,106,3,2.0,3.0,8.65,0,0
393,394,317,104,2,3.0,3.0,8.76,0,1
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
398,399,312,103,3,3.5,4.0,8.78,0,0

In [35]:
#Filter rows where CGPA is an integer value (e.g., 8.0, 9.0).
df[df["CGPA"] % 1 == 0]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
2,3,316,104,3,3.0,3.5,8.0,1,0
8,9,302,102,1,2.0,1.5,8.0,0,0
11,12,327,111,4,4.0,4.5,9.0,1,1
13,14,307,109,3,4.0,3.0,8.0,1,0
17,18,319,106,3,4.0,3.0,8.0,1,0
40,41,308,110,3,3.5,3.0,8.0,1,0
52,53,334,116,4,4.0,3.0,8.0,1,1
54,55,322,110,3,3.0,3.5,8.0,0,0
96,97,306,100,2,3.0,3.0,8.0,0,0
251,252,316,99,2,2.5,3.0,9.0,0,0
289,290,313,109,3,4.0,3.5,9.0,0,1
300,301,309,106,2,2.5,2.5,8.0,0,0
307,308,325,112,4,4.0,4.0,9.0,1,1
312,313,311,107,4,4.5,4.5,9.0,1,1

In [38]:
#Retrieve records where Chance of Admit is between 0.5 and 0.7.
df[(df["Chance of Admit"]>=0.5) & (df["Chance of Admit"]<=0.7)]

Empty DataFrame
Columns: [Serial No., GRE Score, TOEFL Score, University Rating, SOP, LOR, CGPA, Research, Chance of Admit]
Index: []

In [39]:
#Select students who scored below average GRE Score.
df[df["GRE Score"] < df["GRE Score"].mean()]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
2,3,316,104,3,3.0,3.5,8.00,1,0
4,5,314,103,2,2.0,3.0,8.21,0,0
7,8,308,101,2,3.0,4.0,7.90,0,0
8,9,302,102,1,2.0,1.5,8.00,0,0
13,14,307,109,3,4.0,3.0,8.00,1,0
...,...,...,...,...,...,...,...,...,...
386,387,302,101,2,2.5,3.5,7.96,0,0
387,388,307,105,2,2.0,3.5,8.10,0,0
388,389,296,97,2,1.5,2.0,7.80,0,0
390,391,314,102,2,2.0,2.5,8.24,0,0
398,399,312,103,3,3.5,4.0,8.78,0,0

In [43]:
#Show all records where TOEFL Score equals the dataset’s maximum
#TOEFL Score.
df[df["TOEFL Score"]==df["TOEFL Score"].max()]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
25,26,340,120,5,4.5,4.5,9.60,1,1
81,82,340,120,4,5.0,5.0,9.50,1,1
97,98,331,120,3,4.0,4.0,8.96,1,1
143,144,340,120,4,4.5,4.0,9.92,1,1
202,203,340,120,5,4.5,4.5,9.91,1,1
203,204,334,120,5,4.0,5.0,9.87,1,1
212,213,338,120,4,5.0,5.0,9.66,1,1
297,298,320,120,3,4.0,4.5,9.11,0,1

In [44]:
#Filter students who have both LOR and SOP less than 3.
df[(df["LOR"]<3) & (df["SOP"]<3)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
8,9,302,102,1,2.0,1.5,8.00,0,0
27,28,298,98,2,1.5,2.5,7.50,1,0
28,29,295,93,1,2.0,2.0,7.20,0,0
29,30,310,99,2,1.5,2.0,7.30,0,0
37,38,300,105,1,1.0,2.0,7.80,0,0
...,...,...,...,...,...,...,...,...,...
376,377,297,96,2,2.5,2.0,7.43,0,0
377,378,290,100,1,1.5,2.0,7.56,0,0
378,379,303,98,1,2.0,2.5,7.65,0,0
388,389,296,97,2,1.5,2.0,7.80,0,0
390,391,314,102,2,2.0,2.5,8.24,0,0

In [49]:
#Retrieve students who have GRE Score divisible by 5.  Add a new
#column named GRE_to_TOEFL_Ratio = GRE Score / TOEFL Score.
gre=df[df["GRE Score"]%5==0]
df["GRE_to_TOEFL_RATIO"]=df["GRE Score"]/df["TOEFL Score"]
df["GRE_to_TOEFL_RATIO"]

0      2.855932
1      3.028037
2      3.038462
3      2.927273
4      3.048544
         ...
395    2.945455
396    3.037383
397    2.844828
398    3.029126
399    2.846154
Name: GRE_to_TOEFL_RATIO, Length: 400, dtype: float64

In [51]:
#Create a new column Admission_Chance_% = Chance of Admit × 100.
df["Admission_Chance_%"]=df["Chance of Admit"]*100
df["Admission_Chance_%"]

0      100
1      100
2        0
3      100
4        0
      ...
395    100
396    100
397    100
398      0
399    100
Name: Admission_Chance_%, Length: 400, dtype: int64

In [53]:
#Rename the column Chance of Admit to Admit_Probability.
df=df.rename(columns={"Chance of Admit":"Admit_Probability"})
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR', 'CGPA', 'Research', 'Admit_Probability', 'GRE_to_TOEFL_RATIO',
       'Admission_Chance_%'],
      dtype='object')

In [55]:
#Change all column names to lowercase.
df.columns = df.columns.str.lower()

In [65]:
df.columns

Index(['gre score', 'toefl score', 'university rating', 'sop', 'lor', 'cgpa',
       'research', 'admit_probability', 'gre_to_toefl_ratio',
       'admission_chance_%'],
      dtype='object')

In [59]:
#Drop the column Serial No..
df.drop(columns=["serial no."],inplace=True)

In [62]:
#Round all values in CGPA to one decimal place.
df["cgpa"] = df["cgpa"].round(1)

In [70]:
#Replace all University Rating values of 5 with 10.
df["university rating"]=df["university rating"].replace(5,10)

In [71]:
df["university rating"].unique()

array([ 4,  3,  2, 10,  1])

In [72]:
#Convert Research column values from 0/1 to “No”/“Yes”.
df["research"]=df["research"].apply(lambda x: "Yes" if x==1 else "No")

In [73]:
#Create a new column GRE_Level = “High” if GRE ≥ 320 else “Low”.
df["GRE_Level"]=df["gre score"].apply(lambda x: "High" if x>=320 else "Low")

normalized value=x-min(x)/max(x)-min(x)

In [74]:
#Normalize CGPA column to range 0–1 using min-max scaling (without
#sklearn).
df["cgpa_normalized"]=(df["cgpa"]-df["cgpa"].min())/(df["cgpa"].max()-df["cgpa"].min())

In [75]:
#Increase all TOEFL Score values by 2 points.
df["toefl score"]=df["toefl score"]+2

In [76]:
#Add a column Weighted_Score = GRE Score * 0.3 + TOEFL Score * 0.2 +
#CGPA * 0.5.
df["weighted score"]=(df["gre score"]*0.3)+(df["toefl score"]*0.2)+(df["cgpa"]*0.5)

In [78]:
df=df.rename(columns={"GRE_Level":"gre level"})

In [80]:
df.columns

Index(['gre score', 'toefl score', 'university rating', 'sop', 'lor', 'cgpa',
       'research', 'admit_probability', 'gre_to_toefl_ratio',
       'admission_chance_%', 'gre level', 'cgpa_normalized', 'weighted score'],
      dtype='object')

In [83]:
#Replace all SOP values less than 2 with the mean SOP.
df.loc[df["sop"]<2,"sop"]=df["sop"].mean()
#loc-select a particular row or column

In [85]:
#Create a new column combining University Rating and Research (e.g.,
#Rating-Research).
df["rating research"] = df["university rating"].astype(str) + "-" + df["research"].astype(str)

In [89]:
#Convert Chance of Admit to categorical bins: “Low”, “Medium”, “High”.
df["admission_chance_%"]=df["admission_chance_%"].apply(bins)

In [88]:
def bins(x):
    if x==100:
        return "High"
    elif x==0:
        return "Low"
    else:
        return "Medium"

In [90]:
df["admission_chance_%"].unique()

array(['High', 'Low'], dtype=object)

In [91]:
#Add a constant column Country with value “India”.
df["country"] = "India"

In [93]:
#Reorder columns so that Chance of Admit comes first.
df = df[["admission_chance_%"] + [col for col in df.columns if col != "admission_chance_%"]]

In [99]:
#Replace values in LOR column where rating is 5 with 4.9.
df["lor"]=df["lor"].replace(5,4.9)

In [100]:
df["lor"].unique()

array([4.5, 3.5, 2.5, 3. , 4. , 1.5, 2. , 4.9, 1. ])

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   admission_chance_%  400 non-null    object
 1   gre score           400 non-null    int64
 2   toefl score         400 non-null    int64
 3   university rating   400 non-null    int64
 4   sop                 400 non-null    float64
 5   lor                 400 non-null    float64
 6   cgpa                400 non-null    float64
 7   research            400 non-null    object
 8   admit_probability   400 non-null    int64
 9   gre_to_toefl_ratio  400 non-null    float64
 10  gre level           400 non-null    object
 11  cgpa_normalized     400 non-null    float64
 12  weighted score      400 non-null    float64
 13  rating research     400 non-null    object
 14  country             400 non-null    object
dtypes: float64(6), int64(4), object(5)
memory usage: 47.0+ KB

In [116]:
##Convert all float columns to integers (after rounding).
df["sop"]=df["sop"].astype(int)
df["lor"]=df["lor"].astype(int)
df["cgpa"]=df["cgpa"].astype(int)
df["gre_to_toefl_ratio"]=df["gre_to_toefl_ratio"].astype(int)
df["cgpa_normalized"]=df["cgpa_normalized"].astype(int)
df["weighted score"]=df["weighted score"].astype(int)

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   admission_chance_%  400 non-null    object
 1   gre score           400 non-null    int64
 2   toefl score         400 non-null    int64
 3   university rating   400 non-null    int64
 4   sop                 400 non-null    int64
 5   lor                 400 non-null    int64
 6   cgpa                400 non-null    int64
 7   research            400 non-null    object
 8   admit_probability   400 non-null    int64
 9   gre_to_toefl_ratio  400 non-null    int64
 10  gre level           400 non-null    object
 11  cgpa_normalized     400 non-null    int64
 12  weighted score      400 non-null    int64
 13  rating research     400 non-null    object
 14  country             400 non-null    object
dtypes: int64(10), object(5)
memory usage: 47.0+ KB

In [118]:
#Replace CGPA values above 9.5 with 9.5.
df["cgpa"] = df["cgpa"].astype(float)
df.loc[df["cgpa"]>9.5,"cgpa"]=9.5

In [119]:
#Apply a lambda function to square all SOP values.
df["sop"]=df["sop"].apply(lambda x: x**2)

In [125]:
#Add a column GRE_Category = “Below Avg”, “Avg”, “Above Avg” based
#on mean GRE.
mean_gre = df["gre score"].mean()

def gre_category(x):
    if x < mean_gre:
        return "Below Avg"
    elif x > mean_gre:
        return "Above Avg"
    else:
        return "Avg"

df["gre category"] = df["gre score"].apply(gre_category)

In [126]:
df["gre category"].unique()

array(['Above Avg', 'Below Avg'], dtype=object)

In [127]:
#Standardize column names to snake_case (lowercase, replace spaces
#with _).
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [128]:
df.columns

Index(['admission_chance_%', 'gre_score', 'toefl_score', 'university_rating',
       'sop', 'lor', 'cgpa', 'research', 'admit_probability',
       'gre_to_toefl_ratio', 'gre_level', 'cgpa_normalized', 'weighted_score',
       'rating_research', 'country', 'gre_category'],
      dtype='object')

In [129]:
#Create a new column showing difference between TOEFL Score and GRE
#Score/4.
df["score_difference"] = df["toefl_score"] - df["gre_score"] / 4

In [130]:
#Find the average GRE Score for each University Rating.
df.groupby("university_rating")["gre_score"].mean()

university_rating
1     303.153846
2     309.177570
3     315.954887
4     324.824324
10    328.333333
Name: gre_score, dtype: float64

In [131]:
#Get the mean CGPA for students with and without research.
df.groupby("research")["cgpa"].mean()

research
No     7.81768
Yes    8.47032
Name: cgpa, dtype: float64

In [132]:
#Count how many applicants have each University Rating.
df.groupby("university_rating")["university_rating"].count()

university_rating
1      26
2     107
3     133
4      74
10     60
Name: university_rating, dtype: int64

In [133]:
# Find the total number of students in each Research category.
df.groupby(["research"])["research"].count()

research
No     181
Yes    219
Name: research, dtype: int64

In [136]:
#Group by University Rating and show average TOEFL Score.
df.groupby(["university_rating"])["toefl_score"].mean()

university_rating
1     101.076923
2     105.523364
3     108.887218
4     113.824324
10    115.666667
Name: toefl_score, dtype: float64

In [137]:
#Get the maximum Chance of Admit for each Research group.
df.groupby(["research"])["admission_chance_%"].max()

research
No     Low
Yes    Low
Name: admission_chance_%, dtype: object

In [139]:
#Find minimum SOP value per University Rating.
df.groupby(["university_rating"])["sop"].min()

university_rating
1     4
2     4
3     4
4     4
10    9
Name: sop, dtype: int64

In [141]:
#Count number of students with GRE Score ≥ 320 for each University
#Rating.
gre=df[df["gre_score"]>=320]
gre.groupby(["university_rating"])["gre_score"].count()

university_rating
2     11
3     49
4     59
10    56
Name: gre_score, dtype: int64

In [143]:
#Calculate median CGPA grouped by Research.
df.groupby(["research"])["cgpa"].median()

research
No     8.0
Yes    9.0
Name: cgpa, dtype: float64

In [147]:
#Get the number of students per combination of University Rating and
#Research.
df.groupby(["university_rating"])["research"].size()

university_rating
1      26
2     107
3     133
4      74
10     60
Name: research, dtype: int64

In [149]:
#Find the mean GRE Score grouped by both Research and SOP.
df.groupby(["research","sop"])["gre_score"].mean()

research  sop
No        4      308.050000
          9      307.446429
          16     313.100000
          25     306.400000
Yes       4      313.650000
          9      315.941176
          16     324.233083
          25     330.218750
Name: gre_score, dtype: float64

In [151]:
#For each University Rating, find both min and max TOEFL Score.
mini=df.groupby(["university_rating"])["toefl_score"].min()
maxi=df.groupby(["university_rating"])["toefl_score"].max()

In [152]:
mini

university_rating
1      94
2      97
3      99
4     102
10    105
Name: toefl_score, dtype: int64

In [153]:
maxi

university_rating
1     111
2     120
3     122
4     122
10    122
Name: toefl_score, dtype: int64

In [161]:
#Display number of unique GRE Score values per University Rating.
df.groupby(["university_rating"])["gre_score"].nunique()

university_rating
1     17
2     33
3     30
4     32
10    23
Name: gre_score, dtype: int64

In [159]:
#Find the average of all numeric columns grouped by Research.
df.groupby("research").agg({"gre_score":"mean",
                              "toefl_score":"mean",
                              "university_rating":"mean",
                              "sop":"mean",
                              "lor":"mean",
                              "cgpa":"mean",
                              "admit_probability":"mean"})

,gre_score,toefl_score,university_rating,sop,lor,cgpa,admit_probability
research,,,,,,,
No,309.491713,106.143646,2.745856,10.104972,3.071823,7.81768,0.165746
Yes,322.853881,112.109589,4.739726,15.132420,3.757991,8.47032,0.684932

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   admission_chance_%  400 non-null    object
 1   gre_score           400 non-null    int64
 2   toefl_score         400 non-null    int64
 3   university_rating   400 non-null    int64
 4   sop                 400 non-null    int64
 5   lor                 400 non-null    int64
 6   cgpa                400 non-null    float64
 7   research            400 non-null    object
 8   admit_probability   400 non-null    int64
 9   gre_to_toefl_ratio  400 non-null    int64
 10  gre_level           400 non-null    object
 11  cgpa_normalized     400 non-null    int64
 12  weighted_score      400 non-null    int64
 13  rating_research     400 non-null    object
 14  country             400 non-null    object
 15  gre_category        400 non-null    object
 16  score_difference    400 non-null    float64
dtypes: float64(2), int64(9), object(6)
memory usage: 53.3+ KB

In [160]:
#Get the count of applicants having CGPA &gt; 9 grouped by Research.
applicants=df[df["cgpa"]>9]
applicants.groupby(["research"])["cgpa"].count()

Series([], Name: cgpa, dtype: int64)

In [162]:
#For each SOP rating, find mean Chance of Admit.
df.groupby(["sop"])["admit_probability"].mean()

sop
4     0.087500
9     0.188889
16    0.626943
25    0.945946
Name: admit_probability, dtype: float64

In [163]:
#Calculate mean and std deviation of GRE Score per University Rating.
meu=df.groupby(["university_rating"])["gre_score"].mean()
sigma=df.groupby(["university_rating"])["gre_score"].std()

In [164]:
meu

university_rating
1     303.153846
2     309.177570
3     315.954887
4     324.824324
10    328.333333
Name: gre_score, dtype: float64

In [165]:
sigma

university_rating
1     7.918042
2     8.503954
3     7.748768
4     9.917962
10    8.524475
Name: gre_score, dtype: float64

In [169]:
#Get total number of students whose Chance of Admit &gt; 0.8 per
#Research.
ap=df[df["admit_probability"]>0.8]
ap.groupby(["research"])["admit_probability"].count()

research
No      30
Yes    150
Name: admit_probability, dtype: int64

In [170]:
#Find number of records for each distinct combination of University
#Rating, SOP, and LOR.
df.groupby(["university_rating", "sop", "lor"]).size()

university_rating  sop  lor
1                  4    2       6
                        3       3
                   9    1       1
                        2      13
                        3       1
                   16   3       1
                        4       1
2                  4    2      23
                        3      12
                        4      15
                   9    2      16
                        3       9
                        4      11
                   16   2       2
                        3       9
                        4      10
3                  4    2       8
                        3       9
                        4       2
                   9    2       4
                        3      10
                        4      15
                        5       1
                   16   2       6
                        3      23
                        4      49
                        5       4
                   25   4       2
4                  4    2       1
                        3       1
                   9    2       3
                        3       1
                        4       3
                   16   2       2
                        3       4
                        4      43
                        5       5
                   25   4       6
                        5       5
10                 9    3       1
                        4       1
                   16   3       1
                        4      26
                        5       7
                   25   4      11
                        5      13
dtype: int64

In [175]:
#Get the highest GRE Score among students with Research = 0.
res=df[df["research"]=="No"]
res.groupby(["research"])["gre_score"].max()

research
No    339
Name: gre_score, dtype: int64

In [182]:
#Find how many students in each Research category have CGPA &gt; 9.
mark=df[df["cgpa"]>=9]
mark.groupby(["research"])["cgpa"].count()

research
No      12
Yes    113
Name: cgpa, dtype: int64

In [183]:
#Calculate total GRE Score for each University Rating.
df.groupby(["university_rating"])["gre_score"].sum()

university_rating
1      7882
2     33082
3     42022
4     24037
10    19700
Name: gre_score, dtype: int64

In [186]:
#Find mean Chance of Admit for each unique LOR score.
df.groupby(["lor"])["admit_probability"].mean()

lor
1    0.000000
2    0.107143
3    0.258824
4    0.594872
5    0.942857
Name: admit_probability, dtype: float64

In [187]:
#Get number of students with same TOEFL Score grouped by that score.
df.groupby("toefl_score").size()

toefl_score
94      1
95      2
96      1
97      2
98      4
99      6
100     9
101    18
102    19
103    11
104    17
105    16
106    25
107    28
108    24
109    26
110    17
111    17
112    37
113    17
114    21
115    14
116    15
117     9
118    11
119     7
120     9
121     9
122     8
dtype: int64

In [188]:
#Find the group with the maximum average Chance of Admit.
res = df.groupby("research")["admit_probability"].mean()
res.idxmax()

'Yes'

In [191]:
#Sort dataset by GRE Score in descending order.
df.sort_values(by="gre_score", ascending=False)

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
202,High,340,122,10,16,4,9.0,Yes,1,2,High,1,131,10-Yes,India,Above Avg,37.00
33,High,340,116,10,16,4,9.0,Yes,1,2,High,0,130,10-Yes,India,Above Avg,31.00
84,High,340,117,10,16,4,9.0,Yes,1,2,High,0,130,10-Yes,India,Above Avg,32.00
143,High,340,122,4,16,4,9.0,Yes,1,2,High,1,131,4-Yes,India,Above Avg,37.00
81,High,340,122,4,25,5,9.0,Yes,1,2,High,0,131,4-Yes,India,Above Avg,37.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Low,294,95,1,9,2,7.0,No,0,3,Low,0,110,1-No,India,Below Avg,21.50
272,Low,294,97,1,9,2,7.0,No,0,3,Low,0,111,1-No,India,Below Avg,23.50
168,Low,293,99,2,4,4,7.0,Yes,0,3,Low,0,111,2-Yes,India,Below Avg,25.75
377,Low,290,102,1,9,2,7.0,No,0,2,Low,0,111,1-No,India,Below Avg,29.50
117,Low,290,106,4,4,2,7.0,No,0,2,Low,0,111,4-No,India,Below Avg,33.50

In [190]:
#Sort by University Rating, then CGPA.
df.sort_values(
    by=["university_rating", "cgpa"],
    ascending=[True, True]
)

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
58,Low,300,101,1,9,2,6.0,Yes,0,3,Low,0,113,1-Yes,India,Below Avg,26.00
28,Low,295,95,1,4,2,7.0,No,0,3,Low,0,111,1-No,India,Below Avg,21.25
37,Low,300,107,1,9,2,7.0,No,0,2,Low,0,115,1-No,India,Below Avg,32.00
38,Low,304,107,1,9,2,7.0,No,0,2,Low,0,116,1-No,India,Below Avg,31.00
79,Low,294,95,1,9,2,7.0,No,0,3,Low,0,110,1-No,India,Below Avg,21.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,High,336,120,10,16,4,9.0,Yes,1,2,High,0,129,10-Yes,India,Above Avg,36.00
287,High,324,116,10,25,4,9.0,Yes,1,2,High,0,124,10-Yes,India,Above Avg,35.00
337,High,332,120,10,25,5,9.0,Yes,1,2,High,0,128,10-Yes,India,Above Avg,37.00
362,High,338,117,10,16,5,9.0,Yes,1,2,High,0,129,10-Yes,India,Above Avg,32.50
385,High,335,119,10,25,5,9.0,Yes,1,2,High,0,129,10-Yes,India,Above Avg,35.25

In [194]:
#Display top 5 rows with highest Chance of Admit.
df.sort_values(
    by="admit_probability",
    ascending=False
).head(5)

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
0,High,337,120,4,16,4,9.0,Yes,1,2,High,0,129,4-Yes,India,Above Avg,35.75
213,High,333,121,10,25,4,9.0,Yes,1,2,High,0,129,10-Yes,India,Above Avg,37.75
188,High,331,117,10,16,4,9.0,Yes,1,2,High,0,127,10-Yes,India,Above Avg,34.25
189,High,324,114,10,25,5,9.0,Yes,1,2,High,0,124,10-Yes,India,Above Avg,33.00
190,High,324,113,10,16,4,9.0,Yes,1,2,High,0,124,10-Yes,India,Above Avg,32.00

In [195]:
#Sort values by TOEFL Score ascending.
df.sort_values(
    by="toefl_score",
    ascending=True
)

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
368,Low,298,94,1,4,2,7.0,No,0,3,Low,0,112,1-No,India,Below Avg,19.50
79,Low,294,95,1,9,2,7.0,No,0,3,Low,0,110,1-No,India,Below Avg,21.50
28,Low,295,95,1,4,2,7.0,No,0,3,Low,0,111,1-No,India,Below Avg,21.25
347,Low,299,96,1,9,1,7.0,No,0,3,Low,0,112,1-No,India,Below Avg,21.25
272,Low,294,97,1,9,2,7.0,No,0,3,Low,0,111,1-No,India,Below Avg,23.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,High,334,122,10,16,5,9.0,Yes,1,2,High,1,129,10-Yes,India,Above Avg,38.50
202,High,340,122,10,16,4,9.0,Yes,1,2,High,1,131,10-Yes,India,Above Avg,37.00
143,High,340,122,4,16,4,9.0,Yes,1,2,High,1,131,4-Yes,India,Above Avg,37.00
81,High,340,122,4,25,5,9.0,Yes,1,2,High,0,131,4-Yes,India,Above Avg,37.00
297,High,320,122,3,16,4,9.0,No,1,2,High,0,124,3-No,India,Above Avg,42.00

In [196]:
#Sort dataset by multiple columns: Research and Chance of Admit.
df.sort_values(
    by=["research","admit_probability"],
    ascending=[True,True]
)

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
4,Low,314,105,2,4,3,8.0,No,0,3,Low,0,119,2-No,India,Below Avg,26.50
7,Low,308,103,2,9,4,7.0,No,0,3,Low,0,116,2-No,India,Below Avg,26.00
8,Low,302,104,1,4,2,8.0,No,0,2,Low,0,115,1-No,India,Below Avg,28.50
9,Low,323,110,3,16,3,8.0,No,0,2,High,0,123,3-No,India,Above Avg,29.25
15,Low,314,107,3,16,2,8.0,No,0,2,Low,0,119,3-No,India,Below Avg,28.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,High,329,113,4,16,4,9.0,Yes,1,2,High,0,125,4-Yes,India,Above Avg,30.75
395,High,324,112,3,16,4,9.0,Yes,1,2,High,0,124,3-Yes,India,Above Avg,31.00
396,High,325,109,3,9,4,9.0,Yes,1,3,High,0,123,3-Yes,India,Above Avg,27.75
397,High,330,118,4,25,4,9.0,Yes,1,2,High,0,127,4-Yes,India,Above Avg,35.50
399,High,333,119,4,25,4,9.0,Yes,1,2,High,0,128,4-Yes,India,Above Avg,35.75

In [197]:
#Sort all applicants by CGPA then GRE Score descending.
df.sort_values(
    by=["cgpa","gre_score"],
    ascending=[False,False]
)

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
25,High,340,122,10,16,4,9.0,Yes,1,2,High,0,131,10-Yes,India,Above Avg,37.00
33,High,340,116,10,16,4,9.0,Yes,1,2,High,0,130,10-Yes,India,Above Avg,31.00
81,High,340,122,4,25,5,9.0,Yes,1,2,High,0,131,4-Yes,India,Above Avg,37.00
84,High,340,117,10,16,4,9.0,Yes,1,2,High,0,130,10-Yes,India,Above Avg,32.00
143,High,340,122,4,16,4,9.0,Yes,1,2,High,1,131,4-Yes,India,Above Avg,37.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,Low,294,97,1,9,2,7.0,No,0,3,Low,0,111,1-No,India,Below Avg,23.50
168,Low,293,99,2,4,4,7.0,Yes,0,3,Low,0,111,2-Yes,India,Below Avg,25.75
117,Low,290,106,4,4,2,7.0,No,0,2,Low,0,111,4-No,India,Below Avg,33.50
377,Low,290,102,1,9,2,7.0,No,0,2,Low,0,111,1-No,India,Below Avg,29.50
58,Low,300,101,1,9,2,6.0,Yes,0,3,Low,0,113,1-Yes,India,Below Avg,26.00

In [198]:
#Retrieve bottom 10 rows after sorting by GRE Score.
df.sort_values(
    by="gre_score",
    ascending=True
).tail(10)

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
47,High,339,121,10,16,4,9.0,No,1,2,High,0,130,10-No,India,Above Avg,36.25
130,High,339,116,10,16,4,9.0,Yes,1,2,High,0,129,10-Yes,India,Above Avg,31.25
81,High,340,122,4,25,5,9.0,Yes,1,2,High,0,131,4-Yes,India,Above Avg,37.00
33,High,340,116,10,16,4,9.0,Yes,1,2,High,0,130,10-Yes,India,Above Avg,31.00
84,High,340,117,10,16,4,9.0,Yes,1,2,High,0,130,10-Yes,India,Above Avg,32.00
25,High,340,122,10,16,4,9.0,Yes,1,2,High,0,131,10-Yes,India,Above Avg,37.00
202,High,340,122,10,16,4,9.0,Yes,1,2,High,1,131,10-Yes,India,Above Avg,37.00
384,High,340,115,4,25,5,9.0,Yes,1,3,High,0,129,4-Yes,India,Above Avg,30.00
143,High,340,122,4,16,4,9.0,Yes,1,2,High,1,131,4-Yes,India,Above Avg,37.00
284,High,340,114,4,25,4,9.0,Yes,1,3,High,0,129,4-Yes,India,Above Avg,29.00

In [199]:
#Use .nlargest() to get top 5 CGPA values.
df["cgpa"].nlargest()

0     9.0
5     9.0
11    9.0
12    9.0
22    9.0
Name: cgpa, dtype: float64

In [200]:
#Use .nsmallest() to get lowest 5 TOEFL Score values.
df["toefl_score"].nsmallest()

368    94
28     95
79     95
347    96
78     97
Name: toefl_score, dtype: int64

In [205]:
#Add a new DataFrame containing only students with Research = 1 and
#merge it with main dataset.
research_students = df[df["research"] == "Yes"]
research_students

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
0,High,337,120,4,16,4,9.0,Yes,1,2,High,0,129,4-Yes,India,Above Avg,35.75
1,High,324,109,4,16,4,8.0,Yes,1,3,High,0,123,4-Yes,India,Above Avg,28.00
2,Low,316,106,3,9,4,8.0,Yes,0,3,Low,0,120,3-Yes,India,Below Avg,27.00
3,High,322,112,3,16,2,8.0,Yes,1,2,High,0,123,3-Yes,India,Above Avg,31.50
5,High,330,117,10,16,3,9.0,Yes,1,2,High,0,127,10-Yes,India,Above Avg,34.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,High,329,113,4,16,4,9.0,Yes,1,2,High,0,125,4-Yes,India,Above Avg,30.75
395,High,324,112,3,16,4,9.0,Yes,1,2,High,0,124,3-Yes,India,Above Avg,31.00
396,High,325,109,3,9,4,9.0,Yes,1,3,High,0,123,3-Yes,India,Above Avg,27.75
397,High,330,118,4,25,4,9.0,Yes,1,2,High,0,127,4-Yes,India,Above Avg,35.50
399,High,333,119,4,25,4,9.0,Yes,1,2,High,0,128,4-Yes,India,Above Avg,35.75

In [208]:
#Create two DataFrames — one for Research = 0, another for Research =
#1 — and concatenate them.
no_research=df[df["research"]=="No"]
yes_research=df[df["research"] == "Yes"]
research_done=pd.concat([no_research,yes_research])
research_done

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
4,Low,314,105,2,4,3,8.0,No,0,3,Low,0,119,2-No,India,Below Avg,26.50
7,Low,308,103,2,9,4,7.0,No,0,3,Low,0,116,2-No,India,Below Avg,26.00
8,Low,302,104,1,4,2,8.0,No,0,2,Low,0,115,1-No,India,Below Avg,28.50
9,Low,323,110,3,16,3,8.0,No,0,2,High,0,123,3-No,India,Above Avg,29.25
15,Low,314,107,3,16,2,8.0,No,0,2,Low,0,119,3-No,India,Below Avg,28.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,High,329,113,4,16,4,9.0,Yes,1,2,High,0,125,4-Yes,India,Above Avg,30.75
395,High,324,112,3,16,4,9.0,Yes,1,2,High,0,124,3-Yes,India,Above Avg,31.00
396,High,325,109,3,9,4,9.0,Yes,1,3,High,0,123,3-Yes,India,Above Avg,27.75
397,High,330,118,4,25,4,9.0,Yes,1,2,High,0,127,4-Yes,India,Above Avg,35.50
399,High,333,119,4,25,4,9.0,Yes,1,2,High,0,128,4-Yes,India,Above Avg,35.75

In [209]:
#Use .loc[] to select students with index from 10 to 20.
df.loc[10:20]

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
10,Low,325,108,3,16,4,8.0,Yes,0,3,High,0,123,3-Yes,India,Above Avg,26.75
11,High,327,113,4,16,4,9.0,Yes,1,2,High,0,125,4-Yes,India,Above Avg,31.25
12,High,328,114,4,16,4,9.0,Yes,1,2,High,0,125,4-Yes,India,Above Avg,32.00
13,Low,307,111,3,16,3,8.0,Yes,0,2,Low,0,118,3-Yes,India,Below Avg,34.25
14,Low,311,106,3,16,2,8.0,Yes,0,2,Low,0,118,3-Yes,India,Below Avg,28.25
15,Low,314,107,3,16,2,8.0,No,0,2,Low,0,119,3-No,India,Below Avg,28.50
16,Low,317,109,3,16,3,8.0,No,0,2,Low,0,121,3-No,India,Above Avg,29.75
17,Low,319,108,3,16,3,8.0,Yes,0,3,Low,0,121,3-Yes,India,Above Avg,28.25
18,Low,318,112,3,16,3,8.0,No,0,2,Low,0,122,3-No,India,Above Avg,32.50
19,Low,303,104,3,16,3,8.0,No,0,2,Low,0,115,3-No,India,Below Avg,28.25
20,Low,312,109,3,9,2,7.0,Yes,0,2,Low,0,119,3-Yes,India,Below Avg,31.00

In [210]:
#Use .iloc[] to select the first 5 rows and first 3 columns.
df.iloc[:5,:3]

  admission_chance_%  gre_score  toefl_score
0               High        337          120
1               High        324          109
2                Low        316          106
3               High        322          112
4                Low        314          105

In [212]:
#Select only GRE Score, TOEFL Score, and CGPA columns.
df.loc[:,["gre_score","toefl_score","cgpa"]]

     gre_score  toefl_score  cgpa
0          337          120   9.0
1          324          109   8.0
2          316          106   8.0
3          322          112   8.0
4          314          105   8.0
..         ...          ...   ...
395        324          112   9.0
396        325          109   9.0
397        330          118   9.0
398        312          105   8.0
399        333          119   9.0

[400 rows x 3 columns]

In [213]:
#Sort all rows in reverse alphabetical order of index.
df.sort_index(ascending=False)

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
399,High,333,119,4,25,4,9.0,Yes,1,2,High,0,128,4-Yes,India,Above Avg,35.75
398,Low,312,105,3,16,4,8.0,No,0,3,Low,0,119,3-No,India,Below Avg,27.00
397,High,330,118,4,25,4,9.0,Yes,1,2,High,0,127,4-Yes,India,Above Avg,35.50
396,High,325,109,3,9,4,9.0,Yes,1,3,High,0,123,3-Yes,India,Above Avg,27.75
395,High,324,112,3,16,4,9.0,Yes,1,2,High,0,124,3-Yes,India,Above Avg,31.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,Low,314,105,2,4,3,8.0,No,0,3,Low,0,119,2-No,India,Below Avg,26.50
3,High,322,112,3,16,2,8.0,Yes,1,2,High,0,123,3-Yes,India,Above Avg,31.50
2,Low,316,106,3,9,4,8.0,Yes,0,3,Low,0,120,3-Yes,India,Below Avg,27.00
1,High,324,109,4,16,4,8.0,Yes,1,3,High,0,123,4-Yes,India,Above Avg,28.00
0,High,337,120,4,16,4,9.0,Yes,1,2,High,0,129,4-Yes,India,Above Avg,35.75

In [215]:
#Extract rows with even index numbers only.
df[df.index%2==0]

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
0,High,337,120,4,16,4,9.0,Yes,1,2,High,0,129,4-Yes,India,Above Avg,35.75
2,Low,316,106,3,9,4,8.0,Yes,0,3,Low,0,120,3-Yes,India,Below Avg,27.00
4,Low,314,105,2,4,3,8.0,No,0,3,Low,0,119,2-No,India,Below Avg,26.50
6,High,321,111,3,9,4,8.0,Yes,1,2,High,0,122,3-Yes,India,Above Avg,30.75
8,Low,302,104,1,4,2,8.0,No,0,2,Low,0,115,1-No,India,Below Avg,28.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,Low,314,104,2,4,2,8.0,No,0,3,Low,0,119,2-No,India,Below Avg,25.50
392,High,326,114,4,16,4,9.0,Yes,1,2,High,0,125,4-Yes,India,Above Avg,32.50
394,High,329,113,4,16,4,9.0,Yes,1,2,High,0,125,4-Yes,India,Above Avg,30.75
396,High,325,109,3,9,4,9.0,Yes,1,3,High,0,123,3-Yes,India,Above Avg,27.75
398,Low,312,105,3,16,4,8.0,No,0,3,Low,0,119,3-No,India,Below Avg,27.00

In [217]:
#Display first and last 3 rows of dataset together.
pd.concat([df.head(3), df.tail(3)])

,admission_chance_%,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,admit_probability,gre_to_toefl_ratio,gre_level,cgpa_normalized,weighted_score,rating_research,country,gre_category,score_difference
0,High,337,120,4,16,4,9.0,Yes,1,2,High,0,129,4-Yes,India,Above Avg,35.75
1,High,324,109,4,16,4,8.0,Yes,1,3,High,0,123,4-Yes,India,Above Avg,28.00
2,Low,316,106,3,9,4,8.0,Yes,0,3,Low,0,120,3-Yes,India,Below Avg,27.00
397,High,330,118,4,25,4,9.0,Yes,1,2,High,0,127,4-Yes,India,Above Avg,35.50
398,Low,312,105,3,16,4,8.0,No,0,3,Low,0,119,3-No,India,Below Avg,27.00
399,High,333,119,4,25,4,9.0,Yes,1,2,High,0,128,4-Yes,India,Above Avg,35.75

In [218]:
#Rearrange columns alphabetically.
df = df[sorted(df.columns)]

In [219]:
df

,admission_chance_%,admit_probability,cgpa,cgpa_normalized,country,gre_category,gre_level,gre_score,gre_to_toefl_ratio,lor,rating_research,research,score_difference,sop,toefl_score,university_rating,weighted_score
0,High,1,9.0,0,India,Above Avg,High,337,2,4,4-Yes,Yes,35.75,16,120,4,129
1,High,1,8.0,0,India,Above Avg,High,324,3,4,4-Yes,Yes,28.00,16,109,4,123
2,Low,0,8.0,0,India,Below Avg,Low,316,3,4,3-Yes,Yes,27.00,9,106,3,120
3,High,1,8.0,0,India,Above Avg,High,322,2,2,3-Yes,Yes,31.50,16,112,3,123
4,Low,0,8.0,0,India,Below Avg,Low,314,3,3,2-No,No,26.50,4,105,2,119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,High,1,9.0,0,India,Above Avg,High,324,2,4,3-Yes,Yes,31.00,16,112,3,124
396,High,1,9.0,0,India,Above Avg,High,325,3,4,3-Yes,Yes,27.75,9,109,3,123
397,High,1,9.0,0,India,Above Avg,High,330,2,4,4-Yes,Yes,35.50,25,118,4,127
398,Low,0,8.0,0,India,Below Avg,Low,312,3,4,3-No,No,27.00,16,105,3,119
399,High,1,9.0,0,India,Above Avg,High,333,2,4,4-Yes,Yes,35.75,25,119,4,128