# Pandas

### Data Cleaning

Data cleaning: Gathering data from different resources

1.Data is not a proper structure
2.There might be a missing values
3.There can be outliers etc
pandas+python is used.

1.dataset-laptop price prediction dataset
Based on the features-->predict the price of a laptop

Model understands only numbers...so we need to convert the data into numbers form.

#### 1.Dataset-laptop price prediction dataset

In [69]:
df=pd.read_csv("laptop_data.csv")
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [70]:
df.columns

Index(['Unnamed: 0', 'Company', 'TypeName', 'Inches', 'ScreenResolution',
       'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

In [71]:
df.shape

(1303, 12)

In [72]:
df.ndim

2

In [73]:
df.shape[0] #row

1303

In [74]:
df.shape[1] #column

12

In [75]:
df.head(5) #starting 5

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [76]:
df.tail(2) #end

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
1301,1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.92
1302,1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.32

In [77]:
df.sample() #random

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
1140,1140,Lenovo,2 in 1 Convertible,14.0,IPS Panel Touchscreen 2560x1440,Intel Core i7 6600U 2.6GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,2.8kg,130003.2

In [78]:
df.isnull() #boolean results whether there is null value

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,False,False,False,False,False,False,False,False,False,False,False,False
1299,False,False,False,False,False,False,False,False,False,False,False,False
1300,False,False,False,False,False,False,False,False,False,False,False,False
1301,False,False,False,False,False,False,False,False,False,False,False,False
1302,False,False,False,False,False,False,False,False,False,False,False,False

In [79]:
df.isnull().sum() #total number of null values column wise

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [80]:
df.duplicated() #gives duplicated rows in boolean

0       False
1       False
2       False
3       False
4       False
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Length: 1303, dtype: bool

In [81]:
df.duplicated().sum()

np.int64(0)

In [82]:
df.info() #information about columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1303 non-null   int64
 1   Company           1303 non-null   object
 2   TypeName          1303 non-null   object
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   object
 5   Cpu               1303 non-null   object
 6   Ram               1303 non-null   object
 7   Memory            1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price             1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

In [83]:
#drop column 
df.drop(columns=["Unnamed: 0"],inplace=True)

In [84]:
df #inplace removes the column in the original data

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [85]:
df["Ram"].unique

<bound method Series.unique of 0        8GB
1        8GB
2        8GB
3       16GB
4        8GB
        ...
1298     4GB
1299    16GB
1300     2GB
1301     6GB
1302     4GB
Name: Ram, Length: 1303, dtype: object>

In [86]:
df["Weight"].unique

<bound method Series.unique of 0       1.37kg
1       1.34kg
2       1.86kg
3       1.83kg
4       1.37kg
         ...
1298     1.8kg
1299     1.3kg
1300     1.5kg
1301    2.19kg
1302     2.2kg
Name: Weight, Length: 1303, dtype: object>

In [87]:
#replace ram gp to space, weight to kg to space
df["Ram"]=df["Ram"].str.replace("GB","")
df["Weight"]=df["Weight"].str.replace("kg","")

In [88]:
df["Ram"]=df["Ram"].astype("int") #changing ram to int from object
df["Weight"]=df["Weight"].astype("float") #changing weight to float from object

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   int64
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   float64
 10  Price             1303 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 112.1+ KB

In [90]:
df["ScreenResolution"].value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
4K Ultra HD 3840x2160                              7
Touchscreen 2560x1440                              7
IPS Panel 1366x768                                 7
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Retina Display 2560x1600                 6
IPS Panel Retina Display 2304x1440                 6
Touchscreen 2256x1504                              6
IPS Panel Touchscreen 2560x1440                    5
IPS Panel Retina Display 2880x1800                 4
IPS Panel Touchscreen 1920x1200                    4
1440x900                                           4
IPS Panel 2560x1440                                4
IPS Panel Quad HD+ 2560x1440                       3
Quad HD+ 3200x1800                                 3
1920x1080                                          3
Touchscreen 2400x1600                              3
2560x1440                                          3
IPS Panel Touchscreen 1366x768                     3
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Full HD 2160x1440                        2
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 1920x1200                        1
IPS Panel Full HD 2560x1440                        1
IPS Panel Full HD 1366x768                         1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / Quad HD+ 3200x1800                   1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [91]:
#we are diving the whole column into based on ips and touch screen. 
#Using lambda
df["IPS"]=df["ScreenResolution"].apply(lambda x: 1 if "IPS" in x else 0)

In [92]:
df["IPS"].unique()

array([1, 0])

In [93]:
df["Touchscreen"]=df["ScreenResolution"].apply(lambda x: 1 if "Touchscreen" in x else 0)

In [94]:
df["Touchscreen"].unique()

array([0, 1])

In [95]:
#another 2 columns for the numbers 2400x1600 where first value is x-resolution, 2nd is y-resolution
import re
new=df["ScreenResolution"].str.split("x",n=1,expand=True) #n is how many splits want to do. as x is one n=1, expand converts into column
df["x_resolution"]=new[0]
df["y-resolution"]=new[1]

In [96]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,IPS,Touchscreen,x_resolution,y-resolution
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,1,0,IPS Panel Retina Display 2560,1600
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232,0,0,1440,900
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000,0,0,Full HD 1920,1080
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360,1,0,IPS Panel Retina Display 2880,1800
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080,1,0,IPS Panel Retina Display 2560,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400,1,1,IPS Panel Full HD / Touchscreen 1920,1080
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200,1,1,IPS Panel Quad HD+ / Touchscreen 3200,1800
1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2,64GB Flash Storage,Intel HD Graphics,Windows 10,1.50,12201.1200,0,0,1366,768
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200,0,0,1366,768
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,Windows 10,2.20,19660.3200,0,0,1366,768

In [97]:
#now get x_resolution values
def convert(x):
    res=""
    for i in x:
        if i.isdigit():
            res+=i
    return res

In [98]:
df["x_resolution"]=df["x_resolution"].apply(convert)

In [99]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,IPS,Touchscreen,x_resolution,y-resolution
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,1,0,2560,1600
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232,0,0,1440,900
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000,0,0,1920,1080
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360,1,0,2880,1800
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080,1,0,2560,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400,1,1,1920,1080
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200,1,1,3200,1800
1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2,64GB Flash Storage,Intel HD Graphics,Windows 10,1.50,12201.1200,0,0,1366,768
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200,0,0,1366,768
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,Windows 10,2.20,19660.3200,0,0,1366,768

In [100]:
#as they are string need to convert to int
df["x_resolution"]=df["x_resolution"].astype("int")
df["y-resolution"]=df["y-resolution"].astype("int")

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   int64
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   float64
 10  Price             1303 non-null   float64
 11  IPS               1303 non-null   int64
 12  Touchscreen       1303 non-null   int64
 13  x_resolution      1303 non-null   int64
 14  y-resolution      1303 non-null   int64
dtypes: float64(3), int64(5), object(7)
memory usage: 152.8+ KB

In [102]:
#after creating 2 different columns IPS, Touchscreen we will drop the original table.
df.drop(columns=["ScreenResolution"],inplace=True)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company       1303 non-null   object
 1   TypeName      1303 non-null   object
 2   Inches        1303 non-null   float64
 3   Cpu           1303 non-null   object
 4   Ram           1303 non-null   int64
 5   Memory        1303 non-null   object
 6   Gpu           1303 non-null   object
 7   OpSys         1303 non-null   object
 8   Weight        1303 non-null   float64
 9   Price         1303 non-null   float64
 10  IPS           1303 non-null   int64
 11  Touchscreen   1303 non-null   int64
 12  x_resolution  1303 non-null   int64
 13  y-resolution  1303 non-null   int64
dtypes: float64(3), int64(5), object(6)
memory usage: 142.6+ KB

cpu column--
Intel/Intel I3/5/7 keep Intel 
SAMSUNG
AMD

In [104]:
df["Cpu"].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz       190
Intel Core i7 7700HQ 2.8GHz      146
Intel Core i7 7500U 2.7GHz       134
Intel Core i7 8550U 1.8GHz        73
Intel Core i5 8250U 1.6GHz        72
                                ...
Intel Core M M3-6Y30 0.9GHz        1
AMD A9-Series 9420 2.9GHz          1
Intel Core i3 6006U 2.2GHz         1
AMD A6-Series 7310 2GHz            1
Intel Xeon E3-1535M v6 3.1GHz      1
Name: count, Length: 118, dtype: int64

In [105]:
def convert_processor(x):
    if "Intel" in x:
        return "Intel"
    elif "Samsung" in x:
        return "Samsung"
    else:
        return "AMD"
x="AMD A9-Series 9420 2.9GHz"
convert_processor(x)

'AMD'

In [106]:
df["cpu_new"]=df["Cpu"].apply(convert_processor)

In [107]:
df["cpu_new"].unique()

array(['Intel', 'AMD', 'Samsung'], dtype=object)

Intel-0
AMD-1
samsung-2

In [108]:
def value(x):
    if "Intel" in x:
        return 0
    elif "AMD" in x:
        return 1
    else:
        return 2

In [109]:
df["cat_Cpu"]=df["cpu_new"].apply(value)

In [110]:
df["cat_Cpu"].unique()

array([0, 1, 2])

In [111]:
df.drop(columns=["Cpu","cpu_new"],inplace=True)

In [112]:
df

,Company,TypeName,Inches,Ram,Memory,Gpu,OpSys,Weight,Price,IPS,Touchscreen,x_resolution,y-resolution,cat_Cpu
0,Apple,Ultrabook,13.3,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,1,0,2560,1600,0
1,Apple,Ultrabook,13.3,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232,0,0,1440,900,0
2,HP,Notebook,15.6,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000,0,0,1920,1080,0
3,Apple,Ultrabook,15.4,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360,1,0,2880,1800,0
4,Apple,Ultrabook,13.3,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080,1,0,2560,1600,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400,1,1,1920,1080,0
1299,Lenovo,2 in 1 Convertible,13.3,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200,1,1,3200,1800,0
1300,Lenovo,Notebook,14.0,2,64GB Flash Storage,Intel HD Graphics,Windows 10,1.50,12201.1200,0,0,1366,768,0
1301,HP,Notebook,15.6,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200,0,0,1366,768,0
1302,Asus,Notebook,15.6,4,500GB HDD,Intel HD Graphics,Windows 10,2.20,19660.3200,0,0,1366,768,0

gpu
Intel
Nividia
AMD
ARM

In [113]:
df["Gpu"].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
AMD Radeon R5 520            1
AMD Radeon R7                1
Intel HD Graphics 540        1
AMD Radeon 540               1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [114]:
def convert(x):
    if "Intel" in x:
        return "Intel"
    elif "Nvidia" in x:
        return "Nvidia"
    elif "AMD" in x:
        return "AMD"
    else:
        return "ARM"

In [115]:
df["Gpu_new"]=df["Gpu"].apply(convert)

In [116]:
df["Gpu_new"].unique()

array(['Intel', 'AMD', 'Nvidia', 'ARM'], dtype=object)

In [117]:
def value(x):
    if "Intel" in x:
        return 0
    elif "Nvidia" in x:
        return 1
    elif "AMD" in x:
        return 2
    else:
        return 3

In [118]:
df["cat_Gpu"]=df["Gpu_new"].apply(value)

In [119]:
df["cat_Gpu"].unique()

array([0, 2, 1, 3])

In [120]:
#delete gpu
df.drop(columns=["Gpu","Gpu_new"],inplace=True)

In [121]:
df

,Company,TypeName,Inches,Ram,Memory,OpSys,Weight,Price,IPS,Touchscreen,x_resolution,y-resolution,cat_Cpu,cat_Gpu
0,Apple,Ultrabook,13.3,8,128GB SSD,macOS,1.37,71378.6832,1,0,2560,1600,0,0
1,Apple,Ultrabook,13.3,8,128GB Flash Storage,macOS,1.34,47895.5232,0,0,1440,900,0,0
2,HP,Notebook,15.6,8,256GB SSD,No OS,1.86,30636.0000,0,0,1920,1080,0,0
3,Apple,Ultrabook,15.4,16,512GB SSD,macOS,1.83,135195.3360,1,0,2880,1800,0,2
4,Apple,Ultrabook,13.3,8,256GB SSD,macOS,1.37,96095.8080,1,0,2560,1600,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,4,128GB SSD,Windows 10,1.80,33992.6400,1,1,1920,1080,0,0
1299,Lenovo,2 in 1 Convertible,13.3,16,512GB SSD,Windows 10,1.30,79866.7200,1,1,3200,1800,0,0
1300,Lenovo,Notebook,14.0,2,64GB Flash Storage,Windows 10,1.50,12201.1200,0,0,1366,768,0,0
1301,HP,Notebook,15.6,6,1TB HDD,Windows 10,2.19,40705.9200,0,0,1366,768,0,2
1302,Asus,Notebook,15.6,4,500GB HDD,Windows 10,2.20,19660.3200,0,0,1366,768,0,0

OpSys
windows
mac
others

windows-1
mac-2
others-3

In [122]:
df["OpSys"].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         27
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [123]:
df["OpSys"].unique()

array(['macOS', 'No OS', 'Windows 10', 'Mac OS X', 'Linux', 'Android',
       'Windows 10 S', 'Chrome OS', 'Windows 7'], dtype=object)

In [124]:
def convert(s):
    if "Windows" in s:
        return "Windows"
    elif "Mac" in s:
        return "Mac"
    else:
        return "Others"

In [125]:
df["operating_sys"]=df["OpSys"].apply(convert)

In [126]:
df["operating_sys"].unique()

array(['Others', 'Windows', 'Mac'], dtype=object)

In [127]:
def value(s):
    if "Windows" in s:
        return 0
    elif "Mac" in s:
        return 1
    else:
        return 2

In [128]:
df["operating_sys"]=df["OpSys"].apply(value)

In [129]:
df["operating_sys"].unique()

array([2, 0, 1])

In [130]:
df.drop(columns=["OpSys"],inplace=True)

In [131]:
df

,Company,TypeName,Inches,Ram,Memory,Weight,Price,IPS,Touchscreen,x_resolution,y-resolution,cat_Cpu,cat_Gpu,operating_sys
0,Apple,Ultrabook,13.3,8,128GB SSD,1.37,71378.6832,1,0,2560,1600,0,0,2
1,Apple,Ultrabook,13.3,8,128GB Flash Storage,1.34,47895.5232,0,0,1440,900,0,0,2
2,HP,Notebook,15.6,8,256GB SSD,1.86,30636.0000,0,0,1920,1080,0,0,2
3,Apple,Ultrabook,15.4,16,512GB SSD,1.83,135195.3360,1,0,2880,1800,0,2,2
4,Apple,Ultrabook,13.3,8,256GB SSD,1.37,96095.8080,1,0,2560,1600,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,4,128GB SSD,1.80,33992.6400,1,1,1920,1080,0,0,0
1299,Lenovo,2 in 1 Convertible,13.3,16,512GB SSD,1.30,79866.7200,1,1,3200,1800,0,0,0
1300,Lenovo,Notebook,14.0,2,64GB Flash Storage,1.50,12201.1200,0,0,1366,768,0,0,0
1301,HP,Notebook,15.6,6,1TB HDD,2.19,40705.9200,0,0,1366,768,0,2,0
1302,Asus,Notebook,15.6,4,500GB HDD,2.20,19660.3200,0,0,1366,768,0,0,0

Memory-
need to create 4 columns
1.HDD 2.SSD 3. Flash 4. Hybrid

In [135]:
df["Memory"].value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [140]:
df["Memory"].unique()

array(['128 SSD', '128 Flash Storage', '256 SSD', '512 SSD', '500 HDD',
       '256 Flash Storage', '1000 HDD', '32 Flash Storage',
       '128 SSD +  1000 HDD', '256 SSD +  256 SSD', '64 Flash Storage',
       '256 SSD +  1000 HDD', '256 SSD +  2000 HDD', '32 SSD', '2000 HDD',
       '64 SSD', '1000 Hybrid', '512 SSD +  1000 HDD', '1000 SSD',
       '256 SSD +  500 HDD', '128 SSD +  2000 HDD', '512 SSD +  512 SSD',
       '16 SSD', '16 Flash Storage', '512 SSD +  256 SSD',
       '512 SSD +  2000 HDD', '64 Flash Storage +  1000 HDD', '180 SSD',
       '1000 HDD +  1000 HDD', '32 HDD', '1000 SSD +  1000 HDD',
       '512 Flash Storage', '128 HDD', '240 SSD', '8 SSD', '508 Hybrid',
       '512 SSD +  1000 Hybrid', '256 SSD +  1000 Hybrid'], dtype=object)

remove ".0"

In [137]:
df["Memory"]=df["Memory"].str.replace(".0","")

GB-with blank
TB-000
Entire date is in the GB

In [139]:
df["Memory"]=df["Memory"].str.replace("GB","")
df["Memory"]=df["Memory"].str.replace("TB","000")

Now need to split into 2 columns

In [142]:
new=df["Memory"].str.split("+",n=1,expand=True)

In [143]:
new

                      0     1
0               128 SSD  None
1     128 Flash Storage  None
2               256 SSD  None
3               512 SSD  None
4               256 SSD  None
...                 ...   ...
1298            128 SSD  None
1299            512 SSD  None
1300   64 Flash Storage  None
1301           1000 HDD  None
1302            500 HDD  None

[1303 rows x 2 columns]

In [144]:
new[0].unique()

array(['128 SSD', '128 Flash Storage', '256 SSD', '512 SSD', '500 HDD',
       '256 Flash Storage', '1000 HDD', '32 Flash Storage', '128 SSD ',
       '256 SSD ', '64 Flash Storage', '32 SSD', '2000 HDD', '64 SSD',
       '1000 Hybrid', '512 SSD ', '1000 SSD', '16 SSD',
       '16 Flash Storage', '64 Flash Storage ', '180 SSD', '1000 HDD ',
       '32 HDD', '1000 SSD ', '512 Flash Storage', '128 HDD', '240 SSD',
       '8 SSD', '508 Hybrid'], dtype=object)

In [145]:
new[1].unique()

array([None, '  1000 HDD', '  256 SSD', '  2000 HDD', '  500 HDD',
       '  512 SSD', '  1000 Hybrid'], dtype=object)

Creating dummy columns to assign new[0] and new[1]

In [147]:
df["dc1"]=new[0]
df["dc2"]=new[1]

In [148]:
df.columns

Index(['Company', 'TypeName', 'Inches', 'Ram', 'Memory', 'Weight', 'Price',
       'IPS', 'Touchscreen', 'x_resolution', 'y-resolution', 'cat_Cpu',
       'cat_Gpu', 'operating_sys', 'dc1', 'dc2'],
      dtype='object')

Create 4 columns for each dc- HDD1,HDD2,SSD1...etc

In [150]:
#for dc1
df["HDD1"]=df["dc1"].apply(lambda x: 1 if "HDD" in x else 0)
df["SSD1"]=df["dc1"].apply(lambda x: 1 if "SSD" in x else 0)
df["Hybrid1"]=df["dc1"].apply(lambda x: 1 if "Hybrid" in x else 0)
df["Flash1"]=df["dc1"].apply(lambda x: 1 if "Flash" in x else 0)

In [151]:
df["HDD1"].unique()

array([0, 1])

In [152]:
df["SSD1"].unique()

array([1, 0])

In [153]:
df["Hybrid1"].unique()

array([0, 1])

In [154]:
df["Flash1"].unique()

array([0, 1])

as they are none values we need to fill none with 0

In [155]:
df["dc2"]=df["dc2"].fillna("0")

In [157]:
#dc2
df["HDD2"]=df["dc2"].apply(lambda x: 1 if "HDD" in x else 0)
df["SSD2"]=df["dc2"].apply(lambda x: 1 if "SSD" in x else 0)
df["Hybrid2"]=df["dc2"].apply(lambda x: 1 if "Hybrid" in x else 0)
df["Flash2"]=df["dc2"].apply(lambda x: 1 if "Flash" in x else 0)

In [158]:
df["HDD2"].unique()

array([0, 1])

In [159]:
df["SSD2"].unique()

array([0, 1])

In [160]:
df["Hybrid2"].unique()

array([0, 1])

In [161]:
df["Flash2"].unique()

array([0])

By using 4,4 columns need to create an original column, like HDD, SSD, Hybrid, Flash 
To get the original column-
HDD= HDD1*dc1+HDD2*dc2 -but dc1 and dc2 has string too value

In [163]:
df["dc1"]=df["dc1"].str.replace(r"\D","",regex="True") #\D- gives alphabets opposite of \d (digits)

In [164]:
df["dc1"].unique()

array(['128', '256', '512', '500', '1000', '32', '64', '2000', '16',
       '180', '240', '8', '508'], dtype=object)

In [166]:
df["dc2"]=df["dc2"].str.replace(r"\D","",regex="True")

In [167]:
df["dc2"].unique()

array(['0', '1000', '256', '2000', '500', '512'], dtype=object)

In [169]:
df["dc1"]=df["dc1"].astype("int")

In [170]:
df["dc2"]=df["dc2"].astype("int")

In [171]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company        1303 non-null   object
 1   TypeName       1303 non-null   object
 2   Inches         1303 non-null   float64
 3   Ram            1303 non-null   int64
 4   Memory         1303 non-null   object
 5   Weight         1303 non-null   float64
 6   Price          1303 non-null   float64
 7   IPS            1303 non-null   int64
 8   Touchscreen    1303 non-null   int64
 9   x_resolution   1303 non-null   int64
 10  y-resolution   1303 non-null   int64
 11  cat_Cpu        1303 non-null   int64
 12  cat_Gpu        1303 non-null   int64
 13  operating_sys  1303 non-null   int64
 14  dc1            1303 non-null   int64
 15  dc2            1303 non-null   int64
 16  HDD1           1303 non-null   int64
 17  SSD1           1303 non-null   int64
 18  Hybrid1        1303 non-null   int64
 19  Flash1         1303 non-null   int64
 20  HDD2           1303 non-null   int64
 21  SSD2           1303 non-null   int64
 22  Hybrid2        1303 non-null   int64
 23  Flash2         1303 non-null   int64
dtypes: float64(3), int64(18), object(3)
memory usage: 244.4+ KB

In [173]:
df["HDD"]=(df["HDD1"]*df["dc1"])+(df["HDD2"]*df["dc2"])

In [174]:
df["SSD"]=(df["SSD1"]*df["dc1"])+(df["SSD2"]*df["dc2"])

In [175]:
df["Flash"]=(df["Flash1"]*df["dc1"])+(df["Flash2"]*df["dc2"])

In [176]:
df["Hybrid"]=(df["Hybrid1"]*df["dc1"])+(df["Hybrid2"]*df["dc2"])

In [178]:
df["HDD"].unique()

array([   0,  500, 1000, 2000,   32,  128])

In [179]:
df["SSD"].unique()

array([ 128,    0,  256,  512,   32,   64, 1000, 1024,   16,  768,  180,
        240,    8])

In [180]:
df["Flash"].unique()

array([  0, 128, 256,  32,  64,  16, 512])

In [181]:
df["Hybrid"].unique()

array([   0, 1000,  508])

In [183]:
df.drop(columns=["HDD1","SSD1","Hybrid1","Flash1","HDD2","SSD2","Hybrid2","Flash2","dc1","dc2"],inplace=True)

In [255]:
df.columns

Index(['Company', 'TypeName', 'Inches', 'Ram', 'Memory', 'Weight', 'Price',
       'IPS', 'Touchscreen', 'x_resolution', 'y-resolution', 'cat_Cpu',
       'cat_Gpu', 'operating_sys', 'HDD', 'SSD', 'Flash', 'Hybrid'],
      dtype='object')

#### 2.Dataset- Bengaluru_House_Data

In [300]:
df1=pd.read_csv("Bengaluru_House_Data.csv")
df1

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [301]:
df1.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [302]:
df1.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [303]:
df.duplicated().sum()

np.int64(31)

In [304]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

area_type column-
give numbers to unique--and delete the old column

In [305]:
df1["area_type"].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [306]:
def convert(x):
    if "Super built-up  Area" in x:
        return 0
    elif "Plot  Area" in x:
        return 1
    elif "Built-up  Area" in x:
        return 2
    else:
        return 3

In [307]:
df1["new_area"]=df1["area_type"].apply(convert)

In [308]:
df1["new_area"].unique()

array([0, 1, 2, 3])

In [309]:
df1.drop(columns=["area_type"],inplace=True)

In [310]:
df1

,availability,location,size,society,total_sqft,bath,balcony,price,new_area
0,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,0
1,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,1
2,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,2
3,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,0
4,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,0
...,...,...,...,...,...,...,...,...,...
13315,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,2
13316,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,0
13317,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2
13318,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,0
13319,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,0

availabilty-
new_availability column:-
ready to move
immediate possesion 
date- available in future..

In [311]:
df1["availability"].unique()

array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
       '17-Oct', '21-Dec', '19-Sep', '20-Sep', '18-Mar', '20-Feb',
       '18-Apr', '20-Aug', '18-Oct', '19-Mar', '17-Sep', '18-Dec',
       '17-Aug', '19-Apr', '18-Jun', '22-Dec', '22-Jan', '18-Aug',
       '19-Jan', '17-Jul', '18-Jul', '21-Jun', '20-May', '19-Aug',
       '18-Sep', '17-May', '17-Jun', '21-May', '18-Jan', '20-Mar',
       '17-Dec', '16-Mar', '19-Jun', '22-Jun', '19-Jul', '21-Feb',
       'Immediate Possession', '19-May', '17-Nov', '20-Oct', '20-Jun',
       '19-Feb', '21-Oct', '21-Jan', '17-Mar', '17-Apr', '22-May',
       '19-Oct', '21-Jul', '21-Nov', '21-Mar', '16-Dec', '22-Mar',
       '20-Jan', '21-Sep', '21-Aug', '14-Nov', '19-Nov', '15-Nov',
       '16-Jul', '15-Jun', '17-Feb', '20-Nov', '20-Jul', '16-Sep',
       '15-Oct', '15-Dec', '16-Oct', '22-Nov', '15-Aug', '17-Jan',
       '16-Nov', '20-Apr', '16-Jan', '14-Jul'], dtype=object)

In [312]:
def convert_avail(x):
    if x=="Ready To Move":
        return "Ready To Move"
    elif x=="Immediate Possession":
        return "Immediate Possession"
    else:
        return "Available in future"

In [313]:
df1["new_availability"]=df1["availability"].apply(convert_avail)

In [314]:
df1["new_availability"].unique()

array(['Available in future', 'Ready To Move', 'Immediate Possession'],
      dtype=object)

In [315]:
def value(x):
    if "Available in future" in x:
        return 0
    elif "Ready To Move" in x:
        return 1
    else:
        return 2

In [316]:
df1["cat_availabilty"]=df1["new_availability"].apply(value)

In [317]:
df1["cat_availabilty"].unique()

array([0, 1, 2])

In [318]:
df1.drop(columns=["new_availability","availability"],inplace=True)

In [319]:
df1

,location,size,society,total_sqft,bath,balcony,price,new_area,cat_availabilty
0,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,0,0
1,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,1,1
2,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,2,1
3,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,0,1
4,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,0,1
...,...,...,...,...,...,...,...,...,...
13315,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,2,1
13316,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,0,1
13317,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,1
13318,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,0,0
13319,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,0,1

location-
every value into 3-4 words

In [320]:
df1["location"].unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], shape=(1306,), dtype=object)

In [321]:
df1["location"].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [322]:
def conversion(x):
    x=str(x)
    lst=x.split()
    first_three=lst[:3]
    return " ".join(first_three)

In [323]:
df1["new_location"]=df1["location"].apply(conversion)

In [324]:
df1["new_location"].unique()

array(['Electronic City Phase', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas', 'Havanur extension', 'Abshot Layout'],
      shape=(1288,), dtype=object)

In [325]:
df1.drop(columns=["location"],inplace=True)

size- need to do
bedroom- to BHK 
BHK- Blank

In [372]:
df1["size"].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [348]:
df1["new_size"]=df1["size"].str.replace("BHK","")

In [355]:
df1["new_size"]=df1["new_size"].str.replace("Bedroom","")

In [370]:
df1["new_size"]=df1["new_size"].str.replace("RK","")

In [371]:
df1["new_size"].unique()

array(['2 ', '4 ', '3 ', '6 ', '1 ', '8 ', '7 ', '5 ', '11 ', '9 ', nan,
       '27 ', '10 ', '19 ', '16 ', '43 ', '14 ', '12 ', '13 ', '18 '],
      dtype=object)

Society -
Just null values

In [283]:
df1["society"].value_counts()

society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: count, Length: 2688, dtype: int64

In [285]:
df1["society"].isnull().sum()

np.int64(5502)

In [286]:
df1["society"]=df1["society"].fillna("unknown")

In [290]:
df1["society"].unique()

array(['Coomee ', 'Theanmp', 'unknown', ..., 'SJovest', 'ThhtsV ',
       'RSntsAp'], shape=(2689,), dtype=object)

total_sqft
prblms-
range
yards
sq.meter
acres etc
1234-4567---> (1234-4567)/2

In [289]:
df1["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [337]:
import numpy as np
def convert_squarefeet(x):
    try:
        if "-" in x:
            var=x.split("-")
            return ((float(var[0]))+(float(var[1])))/2
        return float(x)
    except:
        return np.nan

In [338]:
df1["new_sq_feet"]=df1["total_sqft"].apply(convert_squarefeet)

In [339]:
df1["new_sq_feet"].isnull().sum()

np.int64(46)

In [340]:
df1["new_sq_feet"]=df1["new_sq_feet"].fillna(np.mean(df1["new_sq_feet"]))

In [341]:
df1["new_sq_feet"].isnull().sum()

np.int64(0)

In [342]:
df1.drop(columns=["total_sqft"],inplace=True)

In [343]:
df1

,size,society,bath,balcony,price,new_area,cat_availabilty,new_location,new_size,new_sq_feet
0,2 BHK,Coomee,2.0,1.0,39.07,0,0,Electronic City Phase,2,1056.0
1,4 Bedroom,Theanmp,5.0,3.0,120.00,1,1,Chikka Tirupathi,4 Bedroom,2600.0
2,3 BHK,NaN,2.0,3.0,62.00,2,1,Uttarahalli,3,1440.0
3,3 BHK,Soiewre,3.0,1.0,95.00,0,1,Lingadheeranahalli,3,1521.0
4,2 BHK,NaN,2.0,1.0,51.00,0,1,Kothanur,2,1200.0
...,...,...,...,...,...,...,...,...,...,...
13315,5 Bedroom,ArsiaEx,4.0,0.0,231.00,2,1,Whitefield,5 Bedroom,3453.0
13316,4 BHK,NaN,5.0,NaN,400.00,0,1,Richards Town,4,3600.0
13317,2 BHK,Mahla T,2.0,1.0,60.00,2,1,Raja Rajeshwari Nagar,2,1141.0
13318,4 BHK,SollyCl,4.0,1.0,488.00,0,0,Padmanabhanagar,4,4689.0
13319,1 BHK,NaN,1.0,1.0,17.00,0,1,Doddathoguru,1,550.0

Bath

replace empty with 2
convet to int

In [352]:
df1["bath"].value_counts()

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64

In [354]:
df1["bath"].isnull().sum()

np.int64(73)

In [357]:
df1["bath"]=df1["bath"].fillna("2")

In [358]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   size             13304 non-null  object
 1   society          7818 non-null   object
 2   bath             13320 non-null  object
 3   balcony          12711 non-null  float64
 4   price            13320 non-null  float64
 5   new_area         13320 non-null  int64
 6   cat_availabilty  13320 non-null  int64
 7   new_location     13320 non-null  object
 8   new_size         13304 non-null  object
 9   new_sq_feet      13320 non-null  float64
dtypes: float64(3), int64(2), object(5)
memory usage: 1.0+ MB

In [359]:
df1["bath"]=df1["bath"].astype("int")

In [360]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   size             13304 non-null  object
 1   society          7818 non-null   object
 2   bath             13320 non-null  int64
 3   balcony          12711 non-null  float64
 4   price            13320 non-null  float64
 5   new_area         13320 non-null  int64
 6   cat_availabilty  13320 non-null  int64
 7   new_location     13320 non-null  object
 8   new_size         13304 non-null  object
 9   new_sq_feet      13320 non-null  float64
dtypes: float64(3), int64(3), object(4)
memory usage: 1.0+ MB

Balcony
as majority is 2 replace null values to 2

In [361]:
df1["balcony"].unique()

array([ 1.,  3., nan,  2.,  0.])

In [362]:
df1["balcony"].value_counts()

balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64

In [363]:
df1["balcony"].isnull().sum()

np.int64(609)

In [364]:
df1["balcony"]=df1["balcony"].fillna("2")

In [366]:
df1["balcony"]=df1["balcony"].astype("int")

In [367]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   size             13304 non-null  object
 1   society          7818 non-null   object
 2   bath             13320 non-null  int64
 3   balcony          13320 non-null  int64
 4   price            13320 non-null  float64
 5   new_area         13320 non-null  int64
 6   cat_availabilty  13320 non-null  int64
 7   new_location     13320 non-null  object
 8   new_size         13304 non-null  object
 9   new_sq_feet      13320 non-null  float64
dtypes: float64(2), int64(4), object(4)
memory usage: 1.0+ MB

In [369]:
df1["price"].unique()

array([ 39.07, 120.  ,  62.  , ...,  40.14, 231.  , 488.  ], shape=(1994,))

#### 3.Dataset-train.csv

3)New data-train.csv(data cleaning)
need to predict whether a passenger will survived or not

In [374]:
df2=pd.read_csv("train.csv")

In [375]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [377]:
df2.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Remove passenger id...as it doesnt effect anything

In [379]:
df2.drop(columns=["PassengerId"],inplace=True)

In [380]:
df2

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [382]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB

survived:
doesnt have any nulls or any problem

In [384]:
df2["Survived"].isnull().sum()

np.int64(0)

pc class:
doesnt have any problem

In [385]:
df2["Pclass"].isnull().sum()

np.int64(0)

Name :
it has large one..so we need to keep 2 words which has family name and members in it.

In [ ]:
def convert(x):
    x=str(x)
    lst=x.split(",")
    first_word=lst[0]
    return str(first_word)

In [386]:
df2["new_Name"]=df2["Name"].apply(convert)

In [389]:
df2

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_Name
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3

In [390]:
df2.drop(columns=["Name"],inplace=True)

sex- 
No problem

In [392]:
df2["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

Age-

In [394]:
df2["Age"].isnull().sum()

np.int64(177)

In [395]:
df2["Age"].value_counts()

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [396]:
df2["Age"]=df2["Age"].fillna(np.mean(df2["Age"]))

In [398]:
df2["Age"].isnull().sum()

np.int64(0)

SibSp-
Create a new column family 
add sibsp and parch in one as both are members of family

In [399]:
df2["SibSp"].isnull().sum()

np.int64(0)

In [400]:
df2["family"]=df2["SibSp"]+df2["Parch"]

In [401]:
df2.drop(columns=["SibSp","Parch"],inplace=True)

In [403]:
df2

,Survived,Pclass,Sex,Age,Ticket,Fare,Cabin,Embarked,new_Name,family
0,0,3,male,22.000000,A/5 21171,7.2500,NaN,S,3,1
1,1,1,female,38.000000,PC 17599,71.2833,C85,C,3,1
2,1,3,female,26.000000,STON/O2. 3101282,7.9250,NaN,S,3,0
3,1,1,female,35.000000,113803,53.1000,C123,S,3,1
4,0,3,male,35.000000,373450,8.0500,NaN,S,3,0
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,211536,13.0000,NaN,S,3,0
887,1,1,female,19.000000,112053,30.0000,B42,S,3,0
888,0,3,female,29.699118,W./C. 6607,23.4500,NaN,S,3,3
889,1,1,male,26.000000,111369,30.0000,C148,C,3,0
890,0,3,male,32.000000,370376,7.7500,NaN,Q,3,0

Ticket-
Ntg to change

In [404]:
df2.drop(columns=["Ticket"],inplace=True)

Fare-

In [406]:
df2["Fare"].isnull().sum()

np.int64(0)

Cabin-

In [407]:
df2["Cabin"].isnull().sum()

np.int64(687)

In [419]:
df2["Cabin"]=df2["Cabin"].ffill()

In [420]:
df2["Cabin"]=df2["Cabin"].bfill()

In [421]:
df2

,Survived,Pclass,Sex,Age,Fare,Cabin,Embarked,new_Name,family
0,0,3,male,22.000000,7.2500,C85,S,3,1
1,1,1,female,38.000000,71.2833,C85,C,3,1
2,1,3,female,26.000000,7.9250,C85,S,3,0
3,1,1,female,35.000000,53.1000,C123,S,3,1
4,0,3,male,35.000000,8.0500,C123,S,3,0
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,13.0000,C50,S,3,0
887,1,1,female,19.000000,30.0000,B42,S,3,0
888,0,3,female,29.699118,23.4500,B42,S,3,3
889,1,1,male,26.000000,30.0000,C148,C,3,0
890,0,3,male,32.000000,7.7500,C148,Q,3,0

eg- to use ffill- forward fill
bfill- back fill

In [414]:
data={
    "name":["abc","pqr","xyz","mnp"],
    "salary":[10000,None,20000,None],
    "city":[None,"mumbai",None,"pune"]
}
data=pd.DataFrame(data)
data

  name   salary    city
0  abc  10000.0    None
1  pqr      NaN  mumbai
2  xyz  20000.0    None
3  mnp      NaN    pune

In [415]:
data["salary"]=data["salary"].ffill()

In [416]:
data

  name   salary    city
0  abc  10000.0    None
1  pqr  10000.0  mumbai
2  xyz  20000.0    None
3  mnp  20000.0    pune

In [417]:
data["city"]=data["city"].bfill()

In [418]:
data

  name   salary    city
0  abc  10000.0  mumbai
1  pqr  10000.0  mumbai
2  xyz  20000.0    pune
3  mnp  20000.0    pune

Embarked:
Repalce null with S

In [423]:
df2["Embarked"].isnull().sum()

np.int64(2)

In [424]:
df2["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [425]:
df2["Embarked"]=df2["Embarked"].fillna("S")

In [426]:
df2

,Survived,Pclass,Sex,Age,Fare,Cabin,Embarked,new_Name,family
0,0,3,male,22.000000,7.2500,C85,S,3,1
1,1,1,female,38.000000,71.2833,C85,C,3,1
2,1,3,female,26.000000,7.9250,C85,S,3,0
3,1,1,female,35.000000,53.1000,C123,S,3,1
4,0,3,male,35.000000,8.0500,C123,S,3,0
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,13.0000,C50,S,3,0
887,1,1,female,19.000000,30.0000,B42,S,3,0
888,0,3,female,29.699118,23.4500,B42,S,3,3
889,1,1,male,26.000000,30.0000,C148,C,3,0
890,0,3,male,32.000000,7.7500,C148,Q,3,0

#### 4.Data set-quikr_car.csv

In [428]:
df3=pd.read_csv("quikr_car.csv")

In [429]:
df3

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

name-

In [432]:
def removing_first_word(x):
    x=str(x)
    lst=x.split()
    exclude_first=lst[1:]
    return " ".join(exclude_first)

In [433]:
df3["new_name"]=df3["name"].apply(removing_first_word)

In [434]:
df3["new_name"]

0        Santro Xing XO eRLX Euro III
1                      Jeep CL550 MDI
2                 Suzuki Alto 800 Vxi
3      Grand i10 Magna 1.2 Kappa VTVT
4         EcoSport Titanium 1.5L TDCi
                    ...
887
888                    Zest XM Diesel
889                         Quanto C8
890                Amaze 1.2 E i VTEC
891                   Sail 1.2 LT ABS
Name: new_name, Length: 892, dtype: object

In [436]:
df3.drop(columns=["name"],inplace=True)

company-
no change

year-

In [438]:
df3["year"].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [440]:
update=df3[df3["year"].str.isdigit()]
update #new data set

,company,year,Price,kms_driven,fuel_type,new_name
0,Hyundai,2007,"80,000","45,000 kms",Petrol,Santro Xing XO eRLX Euro III
1,Mahindra,2006,"4,25,000",40 kms,Diesel,Jeep CL550 MDI
2,Maruti,2018,Ask For Price,"22,000 kms",Petrol,Suzuki Alto 800 Vxi
3,Hyundai,2014,"3,25,000","28,000 kms",Petrol,Grand i10 Magna 1.2 Kappa VTVT
4,Ford,2014,"5,75,000","36,000 kms",Diesel,EcoSport Titanium 1.5L TDCi
...,...,...,...,...,...,...
886,Toyota,2009,"3,00,000","1,32,000 kms",Petrol,Corolla Altis
888,Tata,2018,"2,60,000","27,000 kms",Diesel,Zest XM Diesel
889,Mahindra,2013,"3,90,000","40,000 kms",Diesel,Quanto C8
890,Honda,2014,"1,80,000",Petrol,NaN,Amaze 1.2 E i VTEC
891,Chevrolet,2014,"1,60,000",Petrol,NaN,Sail 1.2 LT ABS

In [443]:
update["year"].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '2003', '2004', '1995', '2002', '2001'], dtype=object)

Price-
Remove ,- with nothing
Remove Ask For Price

In [444]:
df3["Price"].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [445]:
df3["Price"].isnull().sum()

np.int64(0)

In [451]:
def commas(x):
    x=str(x)
    x=x.replace(",","")
    return x

In [453]:
df3["Price"]=df3["Price"].apply(commas)

In [455]:
update = df3[df3["Price"].str.isdigit()]
update

,company,year,Price,kms_driven,fuel_type,new_name
0,Hyundai,2007,80000,"45,000 kms",Petrol,Santro Xing XO eRLX Euro III
1,Mahindra,2006,425000,40 kms,Diesel,Jeep CL550 MDI
3,Hyundai,2014,325000,"28,000 kms",Petrol,Grand i10 Magna 1.2 Kappa VTVT
4,Ford,2014,575000,"36,000 kms",Diesel,EcoSport Titanium 1.5L TDCi
6,Ford,2012,175000,"41,000 kms",Diesel,Figo
...,...,...,...,...,...,...
887,Tara,zest,310000,NaN,NaN,
888,Tata,2018,260000,"27,000 kms",Diesel,Zest XM Diesel
889,Mahindra,2013,390000,"40,000 kms",Diesel,Quanto C8
890,Honda,2014,180000,Petrol,NaN,Amaze 1.2 E i VTEC
891,Chevrolet,2014,160000,Petrol,NaN,Sail 1.2 LT ABS

kms_driven:
remove commas
remove kms and keep numbers only 
petrol- keep is digit

In [458]:
df3["kms_driven"]=df3["kms_driven"].str.replace(",","")

In [459]:
df3["kms_driven"]

0      45000 kms
1         40 kms
2      22000 kms
3      28000 kms
4      36000 kms
         ...
887          NaN
888    27000 kms
889    40000 kms
890       Petrol
891       Petrol
Name: kms_driven, Length: 892, dtype: object

In [466]:
df3["kms_driven"]=df3["kms_driven"].str.replace("kms","")

In [467]:
df3["kms_driven"].isnull().sum()

np.int64(0)

In [468]:
df3["kms_driven"].value_counts()

kms_driven
45000      52
45000      30
35000      30
55000      25
50000      23
           ..
103553      1
29685       1
30874       1
49800       1
69900       1
Name: count, Length: 259, dtype: int64

In [471]:
df3["kms_driven"]=df3["kms_driven"].fillna("45000")

In [472]:
update=df3[df3["kms_driven"].str.isdigit()]
update

,company,year,Price,kms_driven,fuel_type,new_name
69,I,2017,Ask For Price,45000,NaN,want to sell my car Tata Zest
85,I,2017,Ask For Price,45000,NaN,want to sell my car Tata Zest
185,Commercial,...,Ask For Price,45000,NaN,", DZire LDI, 2016, for sale"
195,Tata,150k,150000,45000,NaN,"indigo ecs LX, 201"
206,MARUTI,TOUR,400000,45000,NaN,SUZUKI DESI
286,Commercial,...,Ask For Price,45000,NaN,", DZire LDI, 2016, for sale"
294,Yamaha,r 15,55000,45000,NaN,
360,selling,Zest,Ask For Price,45000,NaN,car Ta
368,Tata,/-Rs,Ask For Price,45000,NaN,Zest 90
385,Maruti,sale,300000,45000,NaN,Suzuki Swift Dzire car
395,Maruti,ara),300000,45000,NaN,Suzuki Swift Dzire Tour (Gat
401,URJENT,SELL,180000,45000,NaN,
414,Swift,tion,370000,45000,NaN,Dzire Tour 27 Dec 2016 Regis
432,Tata,odel,320000,45000,NaN,zest x
433,Mahindra,2 bs,350000,45000,NaN,xyl
441,Used,arry,150000,45000,NaN,Commercial Maruti Omn
560,Hyundai,Eon,Ask For Price,45000,NaN,
593,Commercial,o...,225000,45000,NaN,Chevrolet Sail Hatchback ca
599,Commercial,Zest,371500,45000,NaN,Car Ta
608,tata,sale,130000,45000,NaN,Indica
614,Used,Zest,255000,45000,NaN,bt new conditions ta
616,Sale,ture,100000,45000,NaN,tata
624,Tata,emi,170000,45000,NaN,indigo 2017 top model..
635,Tata,car,150000,45000,NaN,indigo
643,very,able,200000,45000,NaN,good condition tata bolts are av
645,Sale,no.,Ask For Price,45000,NaN,Hyundai xcent commerc
723,I,o...,475000,45000,NaN,want to sell my commercial car due t
725,i,d...,320000,45000,NaN,want sale my car.no emi....uber atta
728,Tata,car,370000,45000,NaN,ZEST 6 month old
758,MARUTI,SALE,650000,45000,NaN,SUZUKI ERTIGA F
764,Tata,digo,Ask For Price,45000,NaN,
792,2012,sell,250000,45000,NaN,Tata Sumo Gold f
795,Well,d Ex,380000,45000,NaN,mentained Tata Sumo
796,all,n...,145000,45000,NaN,paper updated tata indica v2 and u
797,Maruti,e...,480000,45000,NaN,Ertiga showroom condition with
798,7,D...,Ask For Price,45000,NaN,SEATER MAHINDRA BOLERO IN VERY GOOD
799,9,", Ac",Ask For Price,45000,NaN,SEATER MAHINDRA BOL
800,scratch,go .,140000,45000,NaN,less Tata I
801,Maruti,d...,360000,45000,NaN,Suzuki swift dzire for sale in
802,Commercial,k...,180000,45000,NaN,Chevrolet beat for sale in
803,urgent,o c4,350000,45000,NaN,sell my Mahindra qu
805,sell,zire,300000,45000,NaN,my car Maruti Suzuki Swif
806,Maruti,o...,310000,45000,NaN,Suzuki Swift Dzire good car fo
807,Hyundai,cent,Ask For Price,45000,NaN,
808,Commercial,...,Ask For Price,45000,NaN,Maruti Suzuki Alto Lxi 800
809,urgent,Sumo,220000,45000,NaN,sale Ta
810,Maruti,cab,95000,45000,NaN,Suzuki Alto vxi t
811,tata,t xe,Ask For Price,45000,NaN,
812,TATA,EV2,110000,45000,NaN,INDI
845,Any,r...,170000,45000,NaN,type car avaiabel hare...comercica
884,tata,sale,450000,45000,NaN,zest 2017 f
887,Tara,zest,310000,45000,NaN,

In [474]:
df3["kms_driven"].value_counts()

kms_driven
45000      52
45000      30
35000      30
55000      25
50000      23
           ..
103553      1
29685       1
30874       1
49800       1
69900       1
Name: count, Length: 259, dtype: int64

fuel_type-
nan replace with the majority

In [476]:
df3["fuel_type"].isnull().sum()

np.int64(55)

In [477]:
df3["fuel_type"].value_counts()

fuel_type
Petrol    440
Diesel    395
LPG         2
Name: count, dtype: int64

In [478]:
df3["fuel_type"]=df3["fuel_type"].fillna("Petrol")

In [479]:
df3

,company,year,Price,kms_driven,fuel_type,new_name
0,Hyundai,2007,80000,45000,Petrol,Santro Xing XO eRLX Euro III
1,Mahindra,2006,425000,40,Diesel,Jeep CL550 MDI
2,Maruti,2018,Ask For Price,22000,Petrol,Suzuki Alto 800 Vxi
3,Hyundai,2014,325000,28000,Petrol,Grand i10 Magna 1.2 Kappa VTVT
4,Ford,2014,575000,36000,Diesel,EcoSport Titanium 1.5L TDCi
...,...,...,...,...,...,...
887,Tara,zest,310000,45000,Petrol,
888,Tata,2018,260000,27000,Diesel,Zest XM Diesel
889,Mahindra,2013,390000,40000,Diesel,Quanto C8
890,Honda,2014,180000,Petrol,Petrol,Amaze 1.2 E i VTEC
891,Chevrolet,2014,160000,Petrol,Petrol,Sail 1.2 LT ABS

In [1]:
#### 4.Dataset- loan.csv

In [81]:
import pandas as pd
import numpy as np

In [38]:
df4=pd.read_csv("loan.csv")

In [39]:
df4

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [40]:
df4.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

drop loan id column

In [41]:
df4.drop(columns=["Loan_ID"],inplace=True)

In [42]:
df4

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

Gender:
Having nan so majority fill na

In [43]:
df4["Gender"].unique()

array(['Male', 'Female', nan], dtype=object)

In [44]:
df4["Gender"].value_counts()

Gender
Male      489
Female    112
Name: count, dtype: int64

In [45]:
df4.shape

(614, 12)

In [46]:
df4["Gender"]=df4["Gender"].fillna("Male")

In [47]:
df4["Gender"].unique()

array(['Male', 'Female'], dtype=object)

Make male-0 female 1

In [48]:
df4["Gender"]=df4["Gender"].apply(lambda x: 1 if x=="Male" else 0)

In [49]:
df4["Gender"].unique()

array([1, 0])

Married:
Nan is avaialble so fillna with majority
convert into 0 and 1

In [50]:
df4["Married"].unique()

array(['No', 'Yes', nan], dtype=object)

In [51]:
df4["Married"].value_counts()

Married
Yes    398
No     213
Name: count, dtype: int64

In [52]:
df4["Married"]=df4["Married"].fillna("Yes")

In [53]:
df4["Married"].unique()

array(['No', 'Yes'], dtype=object)

In [54]:
df4["Married"]=df4["Married"].apply(lambda x: 1 if x=="Yes" else 0)

In [55]:
df4["Married"].unique()

array([0, 1])

Dependents:
3+- convert to 3
fillna with majotity 
change type to int

In [56]:
df4["Dependents"].unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [57]:
df4["Dependents"]=df4["Dependents"].replace("3+","3")

In [58]:
df4["Dependents"].unique()

array(['0', '1', '2', '3', nan], dtype=object)

In [59]:
df4["Dependents"].value_counts()

Dependents
0    345
1    102
2    101
3     51
Name: count, dtype: int64

In [60]:
df4["Dependents"]=df4["Dependents"].fillna("0")

In [61]:
df4["Dependents"]=df4["Dependents"].astype("int")

In [63]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             614 non-null    int64
 1   Married            614 non-null    int64
 2   Dependents         614 non-null    int64
 3   Education          614 non-null    object
 4   Self_Employed      582 non-null    object
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object
 11  Loan_Status        614 non-null    object
dtypes: float64(4), int64(4), object(4)
memory usage: 57.7+ KB

Education:
Graduate-0
not graduate-1

In [65]:
df4["Education"].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [66]:
df4["Education"]=df4["Education"].apply(lambda x: 1 if x=="Graduate" else 0)

In [67]:
df4["Education"].unique()

array([1, 0])

Self_Employed:
nan- fillna with majority
yes-1
no-0

In [69]:
df4["Self_Employed"].unique()

array(['No', 'Yes', nan], dtype=object)

In [70]:
df4["Self_Employed"].value_counts()

Self_Employed
No     500
Yes     82
Name: count, dtype: int64

In [71]:
df4["Self_Employed"]=df4["Self_Employed"].fillna("No")

In [72]:
df4["Self_Employed"].unique()

array(['No', 'Yes'], dtype=object)

In [73]:
df4["Self_Employed"]=df4["Self_Employed"].apply(lambda x: 1 if x== "Yes" else 0)

In [74]:
df4["Self_Employed"].unique()

array([0, 1])

ApplicantIncome :
Nothing changed

In [76]:
df4["ApplicantIncome"].unique()

array([ 5849,  4583,  3000,  2583,  6000,  5417,  2333,  3036,  4006,
       12841,  3200,  2500,  3073,  1853,  1299,  4950,  3596,  3510,
        4887,  2600,  7660,  5955,  3365,  3717,  9560,  2799,  4226,
        1442,  3750,  4166,  3167,  4692,  3500, 12500,  2275,  1828,
        3667,  3748,  3600,  1800,  2400,  3941,  4695,  3410,  5649,
        5821,  2645,  4000,  1928,  3086,  4230,  4616, 11500,  2708,
        2132,  3366,  8080,  3357,  3029,  2609,  4945,  5726, 10750,
        7100,  4300,  3208,  1875,  4755,  5266,  1000,  3333,  3846,
        2395,  1378,  3988,  2366,  8566,  5695,  2958,  6250,  3273,
        4133,  3620,  6782,  2484,  1977,  4188,  1759,  4288,  4843,
       13650,  4652,  3816,  3052, 11417,  7333,  3800,  2071,  5316,
        2929,  3572,  7451,  5050, 14583,  2214,  5568, 10408,  5667,
        2137,  2957,  3692, 23803,  3865, 10513,  6080, 20166,  2014,
        2718,  3459,  4895,  3316, 14999,  4200,  5042,  6950,  2698,
       11757,  2330, 14866,  1538, 10000,  4860,  6277,  2577,  9166,
        2281,  3254, 39999,  9538,  2980,  1863,  7933,  3089,  4167,
        9323,  3707,  2439,  2237,  8000,  1820, 51763,  3522,  5708,
        4344,  3497,  2045,  5516,  6400,  1916,  4600, 33846,  3625,
       39147,  2178,  2383,   674,  9328,  4885, 12000,  6033,  3858,
        4191,  3125,  8333,  1907,  3416, 11000,  4923,  3992,  3917,
        4408,  3244,  3975,  2479,  3418,  3430,  7787,  5703,  3173,
        3850,   150,  3727,  5000,  4283,  2221,  4009,  2971,  7578,
        3250,  4735,  4758,  2491,  3716,  3189,  3155,  5500,  5746,
        3463,  3812,  3315,  5819,  2510,  2965,  3406,  6050,  9703,
        6608,  2882,  1809,  1668,  3427,  2661, 16250,  3083,  6045,
        5250, 14683,  4931,  6083,  2060,  3481,  7200,  5166,  4095,
        4708,  4333,  2876,  3237, 11146,  2833,  2620,  3900,  2750,
        3993,  3103,  4100,  4053,  3927,  2301,  1811, 20667,  3158,
        3704,  4124,  9508,  3075,  4400,  3153,  4416,  6875,  4666,
        2875,  1625,  2000,  3762, 20233,  7667,  2917,  2927,  2507,
        2473,  3399,  2058,  3541,  4342,  3601,  3166, 15000,  8666,
        4917,  5818,  4384,  2935, 63337,  9833,  5503,  1830,  4160,
        2647,  2378,  4554,  2499,  3523,  6333,  2625,  9083,  8750,
        2666,  2423,  3813,  3875,  5167,  4723,  4750,  3013,  6822,
        6216,  5124,  6325, 19730, 15759,  5185,  3062,  2764,  4817,
        4310,  3069,  5391,  5941,  7167,  4566,  2346,  3010,  5488,
        9167,  9504,  1993,  3100,  3276,  3180,  3033,  3902,  1500,
        2889,  2755,  1963,  7441,  4547,  2167,  2213,  8300, 81000,
        3867,  6256,  6096,  2253,  2149,  2995,  1600,  1025,  3246,
        5829,  2720,  7250, 14880,  4606,  5935,  2920,  2717,  8624,
        6500, 12876,  2425, 10047,  1926, 10416,  7142,  3660,  7901,
        4707, 37719,  3466,  3539,  3340,  2769,  2309,  1958,  3948,
        2483,  7085,  3859,  4301,  3708,  4354,  8334,  2083,  7740,
        3015,  5191,  2947, 16692,   210,  3450,  2653,  4691,  5532,
       16525,  6700,  2873, 16667,  4350,  3095, 10833,  3547, 18333,
        2435,  2699,  5333,  3691, 17263,  3597,  3326,  4625,  2895,
        6283,   645,  3159,  4865,  4050,  3814, 20833,  3583, 13262,
        3598,  6065,  3283,  2130,  5815,  2031,  3074,  4683,  3400,
        2192,  5677,  7948,  4680, 17500,  3775,  5285,  2679,  6783,
        4281,  3588, 11250, 18165,  2550,  6133,  3617,  6417,  4608,
        2138,  3652,  2239,  3017,  2768,  3358,  2526,  2785,  6633,
        2492,  2454,  3593,  5468,  2667, 10139,  3887,  4180,  3675,
       19484,  5923,  5800,  8799,  4467,  3417,  5116, 16666,  6125,
        6406,  3087,  3229,  1782,  3182,  6540,  1836,  1880,  2787,
        2297,  2165,  2726,  9357, 16120,  3833,  6383,  2987,  9963,
        5780,   416,  2894,  3676,  3987,  3232,  2900,  4106,  8072,
        7583])

CoapplicantIncome:
NO change

In [77]:
df4["CoapplicantIncome"].unique()

array([0.00000000e+00, 1.50800000e+03, 2.35800000e+03, 4.19600000e+03,
       1.51600000e+03, 2.50400000e+03, 1.52600000e+03, 1.09680000e+04,
       7.00000000e+02, 1.84000000e+03, 8.10600000e+03, 2.84000000e+03,
       1.08600000e+03, 3.50000000e+03, 5.62500000e+03, 1.91100000e+03,
       1.91700000e+03, 2.92500000e+03, 2.25300000e+03, 1.04000000e+03,
       2.08300000e+03, 3.36900000e+03, 1.66700000e+03, 3.00000000e+03,
       2.06700000e+03, 1.33000000e+03, 1.45900000e+03, 7.21000000e+03,
       1.66800000e+03, 1.21300000e+03, 2.33600000e+03, 3.44000000e+03,
       2.27500000e+03, 1.64400000e+03, 1.16700000e+03, 1.59100000e+03,
       2.20000000e+03, 2.25000000e+03, 2.85900000e+03, 3.79600000e+03,
       3.44900000e+03, 4.59500000e+03, 2.25400000e+03, 3.06600000e+03,
       1.87500000e+03, 1.77400000e+03, 4.75000000e+03, 3.02200000e+03,
       4.00000000e+03, 2.16600000e+03, 1.88100000e+03, 2.53100000e+03,
       2.00000000e+03, 2.11800000e+03, 4.16700000e+03, 2.90000000e+03,
       5.65400000e+03, 1.82000000e+03, 2.30200000e+03, 9.97000000e+02,
       3.54100000e+03, 3.26300000e+03, 3.80600000e+03, 3.58300000e+03,
       7.54000000e+02, 1.03000000e+03, 1.12600000e+03, 3.60000000e+03,
       2.33300000e+03, 4.11400000e+03, 2.28300000e+03, 1.39800000e+03,
       2.14200000e+03, 2.66700000e+03, 8.98000000e+03, 2.01400000e+03,
       1.64000000e+03, 3.85000000e+03, 2.56900000e+03, 1.92900000e+03,
       7.75000000e+03, 1.43000000e+03, 2.03400000e+03, 4.48600000e+03,
       1.42500000e+03, 1.66600000e+03, 8.30000000e+02, 3.75000000e+03,
       1.04100000e+03, 1.28000000e+03, 1.44700000e+03, 3.16600000e+03,
       3.33300000e+03, 1.76900000e+03, 7.36000000e+02, 1.96400000e+03,
       1.61900000e+03, 1.13000000e+04, 1.45100000e+03, 7.25000000e+03,
       5.06300000e+03, 2.13800000e+03, 5.29600000e+03, 2.58300000e+03,
       2.36500000e+03, 2.81600000e+03, 2.50000000e+03, 1.08300000e+03,
       1.25000000e+03, 3.02100000e+03, 9.83000000e+02, 1.80000000e+03,
       1.77500000e+03, 2.38300000e+03, 1.71700000e+03, 2.79100000e+03,
       1.01000000e+03, 1.69500000e+03, 2.05400000e+03, 2.59800000e+03,
       1.77900000e+03, 1.26000000e+03, 5.00000000e+03, 1.98300000e+03,
       5.70100000e+03, 1.30000000e+03, 4.41700000e+03, 4.33300000e+03,
       1.84300000e+03, 1.86800000e+03, 3.89000000e+03, 2.16700000e+03,
       7.10100000e+03, 2.10000000e+03, 4.25000000e+03, 2.20900000e+03,
       3.44700000e+03, 1.38700000e+03, 1.81100000e+03, 1.56000000e+03,
       1.85700000e+03, 2.22300000e+03, 1.84200000e+03, 3.27400000e+03,
       2.42600000e+03, 8.00000000e+02, 9.85799988e+02, 3.05300000e+03,
       2.41600000e+03, 3.33400000e+03, 2.54100000e+03, 2.93400000e+03,
       1.75000000e+03, 1.80300000e+03, 1.86300000e+03, 2.40500000e+03,
       2.13400000e+03, 1.89000000e+02, 1.59000000e+03, 2.98500000e+03,
       4.98300000e+03, 2.16000000e+03, 2.45100000e+03, 1.79300000e+03,
       1.83300000e+03, 4.49000000e+03, 6.88000000e+02, 4.60000000e+03,
       1.58700000e+03, 1.22900000e+03, 2.33000000e+03, 2.45800000e+03,
       3.23000000e+03, 2.16800000e+03, 4.58300000e+03, 6.25000000e+03,
       5.05000000e+02, 3.16700000e+03, 3.66700000e+03, 3.03300000e+03,
       5.26600000e+03, 7.87300000e+03, 1.98700000e+03, 9.23000000e+02,
       4.99600000e+03, 4.23200000e+03, 1.60000000e+03, 3.13600000e+03,
       2.41700000e+03, 2.11500000e+03, 1.62500000e+03, 1.40000000e+03,
       4.84000000e+02, 2.00000000e+04, 2.40000000e+03, 2.03300000e+03,
       3.23700000e+03, 2.77300000e+03, 1.41700000e+03, 1.71900000e+03,
       4.30000000e+03, 1.61200008e+01, 2.34000000e+03, 1.85100000e+03,
       1.12500000e+03, 5.06400000e+03, 1.99300000e+03, 8.33300000e+03,
       1.21000000e+03, 1.37600000e+03, 1.71000000e+03, 1.54200000e+03,
       1.25500000e+03, 1.45600000e+03, 1.73300000e+03, 2.46600000e+03,
       4.08300000e+03, 2.18800000e+03, 1.66400000e+03, 2.91700000e+03,
       2.07900000e+03, 1.50000000e+03, 4.64800000e+03, 1.01400000e+03,
       1.87200000e+03, 1.60300000e+03, 3.15000000e+03, 2.43600000e+03,
       2.78500000e+03, 1.13100000e+03, 2.15700000e+03, 9.13000000e+02,
       1.70000000e+03, 2.85700000e+03, 4.41600000e+03, 3.68300000e+03,
       5.62400000e+03, 5.30200000e+03, 1.48300000e+03, 6.66700000e+03,
       3.01300000e+03, 1.28700000e+03, 2.00400000e+03, 2.03500000e+03,
       6.66600000e+03, 3.66600000e+03, 3.42800000e+03, 1.63200000e+03,
       1.91500000e+03, 1.74200000e+03, 1.42400000e+03, 7.16600000e+03,
       2.08700000e+03, 1.30200000e+03, 5.50000000e+03, 2.04200000e+03,
       3.90600000e+03, 5.36000000e+02, 2.84500000e+03, 2.52400000e+03,
       6.63000000e+02, 1.95000000e+03, 1.78300000e+03, 2.01600000e+03,
       2.37500000e+03, 3.25000000e+03, 4.26600000e+03, 1.03200000e+03,
       2.66900000e+03, 2.30600000e+03, 2.42000000e+02, 2.06400000e+03,
       4.61000000e+02, 2.21000000e+03, 2.73900000e+03, 2.23200000e+03,
       3.38370000e+04, 1.52200000e+03, 3.41600000e+03, 3.30000000e+03,
       1.00000000e+03, 4.16670000e+04, 2.79200000e+03, 4.30100000e+03,
       3.80000000e+03, 1.41100000e+03, 2.40000000e+02])

LoanAmount:
Fillna with mean

In [78]:
df4["LoanAmount"].unique()

array([ nan, 128.,  66., 120., 141., 267.,  95., 158., 168., 349.,  70.,
       109., 200., 114.,  17., 125., 100.,  76., 133., 115., 104., 315.,
       116., 112., 151., 191., 122., 110.,  35., 201.,  74., 106., 320.,
       144., 184.,  80.,  47.,  75., 134.,  96.,  88.,  44., 286.,  97.,
       135., 180.,  99., 165., 258., 126., 312., 136., 172.,  81., 187.,
       113., 176., 130., 111., 167., 265.,  50., 210., 175., 131., 188.,
        25., 137., 160., 225., 216.,  94., 139., 152., 118., 185., 154.,
        85., 259., 194.,  93., 370., 182., 650., 102., 290.,  84., 242.,
       129.,  30., 244., 600., 255.,  98., 275., 121.,  63., 700.,  87.,
       101., 495.,  67.,  73., 260., 108.,  58.,  48., 164., 170.,  83.,
        90., 166., 124.,  55.,  59., 127., 214., 240.,  72.,  60., 138.,
        42., 280., 140., 155., 123., 279., 192., 304., 330., 150., 207.,
       436.,  78.,  54.,  89., 143., 105., 132., 480.,  56., 159., 300.,
       376., 117.,  71., 490., 173.,  46., 228., 308., 236., 570., 380.,
       296., 156., 103.,  45.,  65.,  53., 360.,  62., 218., 178., 239.,
       405., 148., 190., 149., 153., 162., 230.,  86., 234., 246., 500.,
       186., 119., 107., 209., 208., 243.,  40., 250., 311., 400., 161.,
       196., 324., 157., 145., 181.,  26., 211.,   9., 205.,  36.,  61.,
       146., 292., 142., 350., 496., 253.])

In [79]:
df4["LoanAmount"].isnull().sum()

np.int64(22)

In [82]:
df4["LoanAmount"]=df4["LoanAmount"].fillna(np.mean(df4["LoanAmount"]))

In [83]:
df4["LoanAmount"].isnull().sum()

np.int64(0)

Loan_Amount_Term:
ffill
bfill

In [84]:
df4["Loan_Amount_Term"].unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  36.,  84.,  12.])

In [85]:
df4["Loan_Amount_Term"].value_counts()

Loan_Amount_Term
360.0    512
180.0     44
480.0     15
300.0     13
240.0      4
84.0       4
120.0      3
60.0       2
36.0       2
12.0       1
Name: count, dtype: int64

In [86]:
df4["Loan_Amount_Term"]=df4["Loan_Amount_Term"].ffill()

In [87]:
df4["Loan_Amount_Term"]=df4["Loan_Amount_Term"].bfill()

In [88]:
df4["Loan_Amount_Term"].unique()

array([360., 120., 240., 180.,  60., 300., 480.,  36.,  84.,  12.])

Credit_History:
fillna with 1.0

In [89]:
df4["Credit_History"].unique()

array([ 1.,  0., nan])

In [98]:
df4["Credit_History"]=df4["Credit_History"].fillna("1.0")

In [99]:
df4["Credit_History"].unique()

array([1.0, 0.0, '1'], dtype=object)

Property_Area:
urban-0
rurual-1
semiurban-2

In [100]:
df4["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [101]:
def fun(x):
    if x=="Urban":
        return 0
    elif x=="Rural":
        return 1
    else:
        return 2

In [102]:
df4["Property_Area"]=df4["Property_Area"].apply(fun)

In [104]:
df4["Property_Area"].unique()

array([0, 1, 2])

#### 5. Dataset- breast-cancer.csv

In [108]:
df5=pd.read_csv("breast-cancer.csv")

In [109]:
df5

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

id- remove

In [111]:
df5.drop(columns="id",inplace=True)

diagnosis:
m=1
b=0

In [113]:
df5["diagnosis"].unique()

array(['M', 'B'], dtype=object)

In [114]:
df5["diagnosis"]=df5["diagnosis"].apply(lambda x: 1 if x=="M" else 0)

In [115]:
df5["diagnosis"].unique()

array([1, 0])

radius_mean:

In [117]:
df5["radius_mean"].unique()

array([17.99 , 20.57 , 19.69 , 11.42 , 20.29 , 12.45 , 18.25 , 13.71 ,
       13.   , 12.46 , 16.02 , 15.78 , 19.17 , 15.85 , 13.73 , 14.54 ,
       14.68 , 16.13 , 19.81 , 13.54 , 13.08 ,  9.504, 15.34 , 21.16 ,
       16.65 , 17.14 , 14.58 , 18.61 , 15.3  , 17.57 , 18.63 , 11.84 ,
       17.02 , 19.27 , 16.74 , 14.25 , 13.03 , 14.99 , 13.48 , 13.44 ,
       10.95 , 19.07 , 13.28 , 13.17 , 18.65 ,  8.196, 12.05 , 13.49 ,
       11.76 , 13.64 , 11.94 , 18.22 , 15.1  , 11.52 , 19.21 , 14.71 ,
       13.05 ,  8.618, 10.17 ,  8.598,  9.173, 12.68 , 14.78 ,  9.465,
       11.31 ,  9.029, 12.78 , 18.94 ,  8.888, 17.2  , 13.8  , 12.31 ,
       16.07 , 13.53 , 18.05 , 20.18 , 12.86 , 11.45 , 13.34 , 25.22 ,
       19.1  , 12.   , 18.46 , 14.48 , 19.02 , 12.36 , 14.64 , 14.62 ,
       15.37 , 13.27 , 13.45 , 15.06 , 20.26 , 12.18 ,  9.787, 11.6  ,
       14.42 , 13.61 ,  6.981,  9.876, 10.49 , 13.11 , 11.64 , 22.27 ,
       11.34 ,  9.777, 12.63 , 14.26 , 10.51 ,  8.726, 11.93 ,  8.95 ,
       14.87 , 17.95 , 11.41 , 18.66 , 24.25 , 14.5  , 13.37 , 13.85 ,
       19.   , 19.79 , 12.19 , 15.46 , 16.16 , 15.71 , 18.45 , 12.77 ,
       11.71 , 11.43 , 14.95 , 11.28 ,  9.738, 16.11 , 12.9  , 10.75 ,
       11.9  , 11.8  , 14.44 , 13.74 ,  8.219,  9.731, 11.15 , 13.15 ,
       12.25 , 17.68 , 16.84 , 12.06 , 10.9  , 11.75 , 19.19 , 19.59 ,
       12.34 , 23.27 , 14.97 , 10.8  , 16.78 , 17.47 , 12.32 , 13.43 ,
       11.08 , 10.66 ,  8.671,  9.904, 16.46 , 13.01 , 12.81 , 27.22 ,
       21.09 , 15.7  , 15.28 , 10.08 , 18.31 , 11.81 , 12.3  , 14.22 ,
        9.72 , 14.86 , 12.91 , 13.77 , 18.08 , 19.18 , 14.45 , 12.23 ,
       17.54 , 23.29 , 13.81 , 12.47 , 15.12 , 17.01 , 15.27 , 20.58 ,
       28.11 , 17.42 , 14.19 , 13.86 , 11.89 , 10.2  , 19.8  , 19.53 ,
       13.65 , 13.56 , 10.18 , 15.75 , 14.34 , 10.44 , 15.   , 12.62 ,
       12.83 , 17.05 , 11.32 , 11.22 , 20.51 ,  9.567, 14.03 , 23.21 ,
       20.48 , 17.46 , 12.42 , 11.3  , 13.75 , 19.4  , 10.48 , 13.2  ,
       12.89 , 10.65 , 20.94 , 11.5  , 19.73 , 17.3  , 19.45 , 13.96 ,
       19.55 , 15.32 , 15.66 , 15.53 , 20.31 , 17.35 , 17.29 , 15.61 ,
       17.19 , 20.73 , 10.6  , 13.59 , 12.87 , 10.71 , 14.29 , 11.29 ,
       21.75 ,  9.742, 17.93 , 11.33 , 18.81 , 19.16 , 11.74 , 16.24 ,
       12.58 , 11.26 , 11.37 , 14.41 , 14.96 , 12.95 , 11.85 , 12.72 ,
       10.91 , 20.09 , 11.46 ,  9.   , 13.5  , 11.7  , 14.61 , 12.76 ,
       11.54 ,  8.597, 12.49 ,  9.042, 12.43 , 10.25 , 20.16 , 20.34 ,
       12.2  , 12.67 , 14.11 , 12.03 , 16.27 , 16.26 , 16.03 , 12.98 ,
       11.25 , 17.06 , 12.99 , 18.77 , 10.05 , 23.51 ,  9.606, 11.06 ,
       19.68 , 10.26 , 14.76 , 11.47 , 11.95 , 11.66 , 25.73 , 15.08 ,
       11.14 , 12.56 , 13.87 ,  8.878,  9.436, 12.54 , 13.3  , 16.5  ,
       13.4  , 20.44 , 20.2  , 12.21 , 21.71 , 22.01 , 16.35 , 15.19 ,
       21.37 , 20.64 , 13.69 , 16.17 , 10.57 , 13.46 , 13.66 , 11.27 ,
       11.04 , 12.39 , 14.6  , 13.88 ,  8.734, 15.49 , 21.61 , 12.1  ,
       14.06 , 13.51 , 12.8  , 17.91 , 12.96 , 12.94 , 10.94 , 16.14 ,
       12.85 , 12.27 , 11.36 ,  9.397, 15.13 ,  9.405, 15.5  , 12.7  ,
       11.16 , 11.57 , 14.69 , 11.61 , 10.03 , 11.13 , 14.9  , 12.4  ,
       18.82 , 13.98 , 14.04 , 14.02 , 10.97 , 17.27 , 13.78 , 18.03 ,
       11.99 , 17.75 , 14.8  , 14.53 , 21.1  , 11.87 , 13.38 , 11.63 ,
       13.21 ,  9.755, 17.08 , 27.42 , 14.4  , 13.24 , 13.14 ,  9.668,
       17.6  , 11.62 ,  9.667, 12.04 , 14.92 , 10.88 , 14.2  , 13.9  ,
       11.49 , 16.25 , 12.16 , 13.47 , 13.7  , 15.73 , 19.44 , 11.68 ,
       16.69 , 17.85 , 18.01 , 13.16 , 12.65 , 18.49 , 20.59 , 15.04 ,
       13.82 , 23.09 ,  9.268,  9.676, 12.22 , 16.3  , 14.81 , 15.05 ,
       19.89 , 12.88 , 12.75 ,  9.295, 24.63 ,  9.847,  8.571, 13.94 ,
       12.07 , 11.67 , 13.68 , 20.47 , 10.96 , 20.55 , 14.27 , 11.69 ,
        7.729,  7.691, 14.47 , 14.74 , 13.62 , 10.32 ,  9.683, 10.82 ,
       10.86 ,  9.333, 10.29 , 10.16 ,  9.423, 14.59 , 11.51 , 14.05 ,
       11.2  , 15.22 , 20.92 , 21.56 , 20.13 , 16.6  , 20.6  ,  7.76 ])

texture_mean:

In [119]:
df5["texture_mean"].unique()

array([10.38, 17.77, 21.25, 20.38, 14.34, 15.7 , 19.98, 20.83, 21.82,
       24.04, 23.24, 17.89, 24.8 , 23.95, 22.61, 27.54, 20.13, 20.68,
       22.15, 14.36, 15.71, 12.44, 14.26, 23.04, 21.38, 16.4 , 21.53,
       20.25, 25.27, 15.05, 25.11, 18.7 , 23.98, 26.47, 17.88, 21.59,
       21.72, 18.42, 25.2 , 20.82, 21.58, 21.35, 24.81, 20.28, 21.81,
       17.6 , 16.84, 18.66, 14.63, 22.3 , 21.6 , 16.34, 18.24, 22.02,
       18.75, 18.57, 19.31, 11.79, 14.88, 20.98, 13.86, 23.84, 23.94,
       21.01, 19.04, 17.33, 16.49, 21.31, 14.64, 24.52, 15.79, 16.52,
       19.65, 10.94, 16.15, 23.97, 18.  , 20.97, 15.86, 24.91, 26.29,
       15.65, 18.52, 21.46, 24.59, 21.8 , 15.24, 24.02, 22.76, 14.76,
       18.3 , 19.83, 23.03, 17.84, 19.94, 12.84, 19.77, 24.98, 13.43,
       20.52, 19.4 , 19.29, 15.56, 18.33, 18.54, 19.67, 21.26, 16.99,
       20.76, 20.19, 15.83, 15.76, 16.67, 22.91, 20.01, 10.82, 17.12,
       20.2 , 10.89, 16.39, 17.21, 24.69, 18.91, 25.12, 13.29, 19.48,
       21.54, 13.93, 21.91, 22.47, 15.39, 17.57, 13.39, 11.97, 18.05,
       17.31, 15.92, 14.97, 14.65, 16.58, 18.77, 15.18, 17.91, 20.78,
       20.7 , 15.34, 13.08, 17.94, 20.74, 19.46, 12.74, 12.96, 20.18,
       15.94, 18.15, 22.22, 22.04, 19.76,  9.71, 18.8 , 24.68, 16.95,
       12.39, 19.63, 11.89, 14.71, 15.15, 14.45, 18.06, 20.11, 13.06,
       21.87, 26.57, 20.31, 14.92, 22.41, 15.11, 18.58, 17.19, 17.39,
       15.9 , 23.12, 21.41, 18.22, 26.86, 23.21, 16.33, 22.29, 21.84,
       22.49, 20.22, 19.56, 19.32, 26.67, 23.75, 18.6 , 16.68, 17.27,
       20.26, 22.54, 12.91, 22.14, 18.94, 18.47, 25.56, 23.81, 16.93,
       18.35, 17.48, 21.56, 32.47, 13.16, 13.9 , 17.53, 17.02, 13.47,
       15.46, 15.51, 22.33, 19.08, 27.08, 33.81, 27.81, 15.91, 26.97,
       27.85, 39.28, 15.6 , 15.04, 18.19, 23.77, 23.5 , 19.86, 17.43,
       14.11, 25.22, 14.93, 23.56, 18.45, 19.82, 17.08, 19.33, 17.05,
       28.77, 23.2 , 33.56, 27.06, 23.06, 22.13, 19.38, 22.07, 31.12,
       18.95, 16.21, 20.39, 16.82, 13.04, 20.99, 15.67, 24.48, 17.36,
       14.16, 26.6 , 14.02, 18.18, 18.4 , 13.12, 19.96, 18.89, 19.73,
       19.1 , 16.02, 17.46, 13.78, 13.27, 12.35, 18.14, 18.17, 23.09,
       18.9 , 19.89, 23.86, 18.61, 18.16, 24.49, 15.82, 14.4 , 12.71,
       13.84, 19.11, 15.69, 13.37, 10.72, 16.85, 14.08, 18.87, 17.  ,
       16.18, 19.66, 13.32, 21.51, 15.21, 17.3 , 12.88, 17.93, 20.71,
       21.88, 19.35, 14.78, 19.02, 21.  , 14.23, 21.43, 24.27, 16.54,
       14.96, 21.68, 15.45, 14.74, 16.03, 17.07, 19.22, 25.74, 14.07,
       19.07, 18.59, 15.49, 18.32, 18.07, 21.57, 18.84, 18.29, 21.78,
       26.83, 18.02, 17.25, 21.9 , 23.29, 13.21, 15.1 , 17.35, 16.07,
       28.21, 18.83, 22.72, 13.72, 14.09, 16.16, 15.5 , 12.22, 19.97,
       22.28, 17.72, 17.18, 14.83, 17.26, 21.02, 10.91, 16.17, 14.95,
       14.86, 21.37, 20.66, 17.92, 16.83, 22.11, 29.81, 21.17, 21.7 ,
       21.08, 12.17, 13.98, 19.13, 19.12, 21.28, 14.98, 21.98, 16.62,
       17.67, 22.53, 17.68, 19.54, 21.97, 16.94, 19.62, 15.98, 19.6 ,
       15.66, 17.2 , 25.42, 24.89, 28.03, 17.66, 19.34, 25.  , 28.23,
       17.15, 30.72, 29.29, 25.25, 25.13, 28.2 , 27.15, 26.27, 26.99,
       18.36, 18.1 , 23.33, 18.49, 28.14, 29.97, 15.62, 15.73, 20.53,
       14.59, 19.51, 18.03, 19.24, 14.06, 17.64, 11.28, 16.41, 18.82,
       22.44, 13.23, 20.56, 12.83, 20.54, 20.21, 17.52, 21.24, 16.74,
       16.32, 12.87, 13.14, 20.04, 14.69, 14.7 , 13.66, 20.58, 16.7 ,
       18.68, 15.68, 13.1 , 12.27, 13.17, 13.44, 17.56, 20.02, 20.67,
       17.62, 20.86, 22.55, 24.44, 25.49, 25.44, 14.44, 24.99, 28.06,
       23.23, 16.35, 24.21, 21.48, 29.43, 21.94, 28.92, 27.61, 19.59,
       27.88, 22.68, 23.93, 29.37, 30.62, 25.09, 22.39, 28.25, 28.08,
       29.33, 24.54])

In [120]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    int64
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

#### 6.Dataset-stroke-data.csv

In [165]:
df6=pd.read_csv("stroke-data.csv")

In [166]:
df6

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [167]:
df6.drop(columns="id",inplace=True)

gender:

In [168]:
df6["gender"].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [169]:
#data percentage of male and percentage of female
male_stroke=df6[(df6["gender"]=="Male") & (df6["stroke"]==1)]
(male_stroke.shape[0]/2115)*100

5.106382978723404

In [170]:
#female stroke
female_strock=df6[(df6["gender"]=="Female") & (df6["stroke"]==1)]
(female_strock.shape[0]/2994)*100

4.709418837675351

In [171]:
def func(x):
    if x=="Male":
        return 0
    else:
        return 1

In [172]:
df6["gender"]=df6["gender"].apply(func)

In [164]:
df6["gender"].unique()

array([0, 1])

age:

In [137]:
df6["age"].unique()

array([6.70e+01, 6.10e+01, 8.00e+01, 4.90e+01, 7.90e+01, 8.10e+01,
       7.40e+01, 6.90e+01, 5.90e+01, 7.80e+01, 5.40e+01, 5.00e+01,
       6.40e+01, 7.50e+01, 6.00e+01, 5.70e+01, 7.10e+01, 5.20e+01,
       8.20e+01, 6.50e+01, 5.80e+01, 4.20e+01, 4.80e+01, 7.20e+01,
       6.30e+01, 7.60e+01, 3.90e+01, 7.70e+01, 7.30e+01, 5.60e+01,
       4.50e+01, 7.00e+01, 6.60e+01, 5.10e+01, 4.30e+01, 6.80e+01,
       4.70e+01, 5.30e+01, 3.80e+01, 5.50e+01, 1.32e+00, 4.60e+01,
       3.20e+01, 1.40e+01, 3.00e+00, 8.00e+00, 3.70e+01, 4.00e+01,
       3.50e+01, 2.00e+01, 4.40e+01, 2.50e+01, 2.70e+01, 2.30e+01,
       1.70e+01, 1.30e+01, 4.00e+00, 1.60e+01, 2.20e+01, 3.00e+01,
       2.90e+01, 1.10e+01, 2.10e+01, 1.80e+01, 3.30e+01, 2.40e+01,
       3.40e+01, 3.60e+01, 6.40e-01, 4.10e+01, 8.80e-01, 5.00e+00,
       2.60e+01, 3.10e+01, 7.00e+00, 1.20e+01, 6.20e+01, 2.00e+00,
       9.00e+00, 1.50e+01, 2.80e+01, 1.00e+01, 1.80e+00, 3.20e-01,
       1.08e+00, 1.90e+01, 6.00e+00, 1.16e+00, 1.00e+00, 1.40e+00,
       1.72e+00, 2.40e-01, 1.64e+00, 1.56e+00, 7.20e-01, 1.88e+00,
       1.24e+00, 8.00e-01, 4.00e-01, 8.00e-02, 1.48e+00, 5.60e-01,
       4.80e-01, 1.60e-01])

hypertension:

In [173]:
df6["hypertension"].unique()

array([0, 1])

heart_disease:

In [174]:
df6["heart_disease"].unique()

array([1, 0])

ever_married:

In [175]:
df6["ever_married"].unique()

array(['Yes', 'No'], dtype=object)

bmi:
nan

In [176]:
df6["bmi"].unique()

array([36.6,  nan, 32.5, 34.4, 24. , 29. , 27.4, 22.8, 24.2, 29.7, 36.8,
       27.3, 28.2, 30.9, 37.5, 25.8, 37.8, 22.4, 48.9, 26.6, 27.2, 23.5,
       28.3, 44.2, 25.4, 22.2, 30.5, 26.5, 33.7, 23.1, 32. , 29.9, 23.9,
       28.5, 26.4, 20.2, 33.6, 38.6, 39.2, 27.7, 31.4, 36.5, 33.2, 32.8,
       40.4, 25.3, 30.2, 47.5, 20.3, 30. , 28.9, 28.1, 31.1, 21.7, 27. ,
       24.1, 45.9, 44.1, 22.9, 29.1, 32.3, 41.1, 25.6, 29.8, 26.3, 26.2,
       29.4, 24.4, 28. , 28.8, 34.6, 19.4, 30.3, 41.5, 22.6, 56.6, 27.1,
       31.3, 31. , 31.7, 35.8, 28.4, 20.1, 26.7, 38.7, 34.9, 25. , 23.8,
       21.8, 27.5, 24.6, 32.9, 26.1, 31.9, 34.1, 36.9, 37.3, 45.7, 34.2,
       23.6, 22.3, 37.1, 45. , 25.5, 30.8, 37.4, 34.5, 27.9, 29.5, 46. ,
       42.5, 35.5, 26.9, 45.5, 31.5, 33. , 23.4, 30.7, 20.5, 21.5, 40. ,
       28.6, 42.2, 29.6, 35.4, 16.9, 26.8, 39.3, 32.6, 35.9, 21.2, 42.4,
       40.5, 36.7, 29.3, 19.6, 18. , 17.6, 19.1, 50.1, 17.7, 54.6, 35. ,
       22. , 39.4, 19.7, 22.5, 25.2, 41.8, 60.9, 23.7, 24.5, 31.2, 16. ,
       31.6, 25.1, 24.8, 18.3, 20. , 19.5, 36. , 35.3, 40.1, 43.1, 21.4,
       34.3, 27.6, 16.5, 24.3, 25.7, 21.9, 38.4, 25.9, 54.7, 18.6, 24.9,
       48.2, 20.7, 39.5, 23.3, 64.8, 35.1, 43.6, 21. , 47.3, 16.6, 21.6,
       15.5, 35.6, 16.7, 41.9, 16.4, 17.1, 29.2, 37.9, 44.6, 39.6, 40.3,
       41.6, 39. , 23.2, 18.9, 36.1, 36.3, 46.5, 16.8, 46.6, 35.2, 20.9,
       13.8, 31.8, 15.3, 38.2, 45.2, 17. , 49.8, 27.8, 60.2, 23. , 22.1,
       26. , 44.3, 51. , 39.7, 34.7, 21.3, 41.2, 34.8, 19.2, 35.7, 40.8,
       24.7, 19. , 32.4, 34. , 28.7, 32.1, 51.5, 20.4, 30.6, 71.9, 19.3,
       40.9, 17.2, 16.1, 16.2, 40.6, 18.4, 21.1, 42.3, 32.2, 50.2, 17.5,
       18.7, 42.1, 47.8, 20.8, 30.1, 17.3, 36.4, 12. , 36.2, 55.7, 14.4,
       43. , 41.7, 33.8, 43.9, 22.7, 57.5, 37. , 38.5, 16.3, 44. , 32.7,
       54.2, 40.2, 33.3, 17.4, 41.3, 52.3, 14.6, 17.8, 46.1, 33.1, 18.1,
       43.8, 50.3, 38.9, 43.7, 39.9, 15.9, 19.8, 12.3, 78. , 38.3, 41. ,
       42.6, 43.4, 15.1, 20.6, 33.5, 43.2, 30.4, 38. , 33.4, 44.9, 44.7,
       37.6, 39.8, 53.4, 55.2, 42. , 37.2, 42.8, 18.8, 42.9, 14.3, 37.7,
       48.4, 50.6, 46.2, 49.5, 43.3, 33.9, 18.5, 44.5, 45.4, 55. , 54.8,
       19.9, 17.9, 15.6, 52.8, 15.2, 66.8, 55.1, 18.2, 48.5, 55.9, 57.3,
       10.3, 14.1, 15.7, 56. , 44.8, 13.4, 51.8, 38.1, 57.7, 44.4, 38.8,
       49.3, 39.1, 54. , 56.1, 97.6, 53.9, 13.7, 11.5, 41.4, 14.2, 49.4,
       15.4, 45.1, 49.2, 48.7, 53.8, 42.7, 48.8, 52.7, 53.5, 50.5, 15.8,
       45.3, 14.8, 51.9, 63.3, 40.7, 61.2, 48. , 46.8, 48.3, 58.1, 50.4,
       11.3, 12.8, 13.5, 14.5, 15. , 59.7, 47.4, 52.5, 13.2, 52.9, 61.6,
       49.9, 54.3, 47.9, 13. , 13.9, 50.9, 57.2, 64.4, 92. , 50.8, 57.9,
       45.8, 47.6, 14. , 46.4, 46.9, 47.1, 13.3, 48.1, 51.7, 46.3, 54.1,
       14.9])

In [177]:
df6["bmi"]=df6["bmi"].ffill()

In [178]:
df6["bmi"]=df6["bmi"].bfill()

In [179]:
df6["bmi"].unique()

array([36.6, 32.5, 34.4, 24. , 29. , 27.4, 22.8, 24.2, 29.7, 36.8, 27.3,
       28.2, 30.9, 37.5, 25.8, 37.8, 22.4, 48.9, 26.6, 27.2, 23.5, 28.3,
       44.2, 25.4, 22.2, 30.5, 26.5, 33.7, 23.1, 32. , 29.9, 23.9, 28.5,
       26.4, 20.2, 33.6, 38.6, 39.2, 27.7, 31.4, 36.5, 33.2, 32.8, 40.4,
       25.3, 30.2, 47.5, 20.3, 30. , 28.9, 28.1, 31.1, 21.7, 27. , 24.1,
       45.9, 44.1, 22.9, 29.1, 32.3, 41.1, 25.6, 29.8, 26.3, 26.2, 29.4,
       24.4, 28. , 28.8, 34.6, 19.4, 30.3, 41.5, 22.6, 56.6, 27.1, 31.3,
       31. , 31.7, 35.8, 28.4, 20.1, 26.7, 38.7, 34.9, 25. , 23.8, 21.8,
       27.5, 24.6, 32.9, 26.1, 31.9, 34.1, 36.9, 37.3, 45.7, 34.2, 23.6,
       22.3, 37.1, 45. , 25.5, 30.8, 37.4, 34.5, 27.9, 29.5, 46. , 42.5,
       35.5, 26.9, 45.5, 31.5, 33. , 23.4, 30.7, 20.5, 21.5, 40. , 28.6,
       42.2, 29.6, 35.4, 16.9, 26.8, 39.3, 32.6, 35.9, 21.2, 42.4, 40.5,
       36.7, 29.3, 19.6, 18. , 17.6, 19.1, 50.1, 17.7, 54.6, 35. , 22. ,
       39.4, 19.7, 22.5, 25.2, 41.8, 60.9, 23.7, 24.5, 31.2, 16. , 31.6,
       25.1, 24.8, 18.3, 20. , 19.5, 36. , 35.3, 40.1, 43.1, 21.4, 34.3,
       27.6, 16.5, 24.3, 25.7, 21.9, 38.4, 25.9, 54.7, 18.6, 24.9, 48.2,
       20.7, 39.5, 23.3, 64.8, 35.1, 43.6, 21. , 47.3, 16.6, 21.6, 15.5,
       35.6, 16.7, 41.9, 16.4, 17.1, 29.2, 37.9, 44.6, 39.6, 40.3, 41.6,
       39. , 23.2, 18.9, 36.1, 36.3, 46.5, 16.8, 46.6, 35.2, 20.9, 13.8,
       31.8, 15.3, 38.2, 45.2, 17. , 49.8, 27.8, 60.2, 23. , 22.1, 26. ,
       44.3, 51. , 39.7, 34.7, 21.3, 41.2, 34.8, 19.2, 35.7, 40.8, 24.7,
       19. , 32.4, 34. , 28.7, 32.1, 51.5, 20.4, 30.6, 71.9, 19.3, 40.9,
       17.2, 16.1, 16.2, 40.6, 18.4, 21.1, 42.3, 32.2, 50.2, 17.5, 18.7,
       42.1, 47.8, 20.8, 30.1, 17.3, 36.4, 12. , 36.2, 55.7, 14.4, 43. ,
       41.7, 33.8, 43.9, 22.7, 57.5, 37. , 38.5, 16.3, 44. , 32.7, 54.2,
       40.2, 33.3, 17.4, 41.3, 52.3, 14.6, 17.8, 46.1, 33.1, 18.1, 43.8,
       50.3, 38.9, 43.7, 39.9, 15.9, 19.8, 12.3, 78. , 38.3, 41. , 42.6,
       43.4, 15.1, 20.6, 33.5, 43.2, 30.4, 38. , 33.4, 44.9, 44.7, 37.6,
       39.8, 53.4, 55.2, 42. , 37.2, 42.8, 18.8, 42.9, 14.3, 37.7, 48.4,
       50.6, 46.2, 49.5, 43.3, 33.9, 18.5, 44.5, 45.4, 55. , 54.8, 19.9,
       17.9, 15.6, 52.8, 15.2, 66.8, 55.1, 18.2, 48.5, 55.9, 57.3, 10.3,
       14.1, 15.7, 56. , 44.8, 13.4, 51.8, 38.1, 57.7, 44.4, 38.8, 49.3,
       39.1, 54. , 56.1, 97.6, 53.9, 13.7, 11.5, 41.4, 14.2, 49.4, 15.4,
       45.1, 49.2, 48.7, 53.8, 42.7, 48.8, 52.7, 53.5, 50.5, 15.8, 45.3,
       14.8, 51.9, 63.3, 40.7, 61.2, 48. , 46.8, 48.3, 58.1, 50.4, 11.3,
       12.8, 13.5, 14.5, 15. , 59.7, 47.4, 52.5, 13.2, 52.9, 61.6, 49.9,
       54.3, 47.9, 13. , 13.9, 50.9, 57.2, 64.4, 92. , 50.8, 57.9, 45.8,
       47.6, 14. , 46.4, 46.9, 47.1, 13.3, 48.1, 51.7, 46.3, 54.1, 14.9])

In [180]:
df6.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

smoking_status:

In [182]:
df6["smoking_status"].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],
      dtype=object)